"""Editor property contracts; authoring validation still belongs to ProjectService."""

def inspector_schema():
    return {'schema_version':'legaia.inspector-schema.v1','components':{
        'Transform':{'label':'Transform','units':'Scene units','layout':'layered-number',
            'layers':['imported','authored','effective'],
            'properties':[{'id':axis,'label':axis.upper(),'path':['position',axis],
                'type':'number','nullable':True,'authoring':{'minimum':-32767,'maximum':32767,'step':'any','set_command':'set_transform','clear_command':'clear_transform'},
                'retail_status':'unresolved' if axis=='y' else 'imported',
                'build':{'supported':axis!='y',**({'minimum':64,'maximum':16384,'step':64} if axis!='y' else {}),
                         'note':'Project-only height; clear before Build' if axis=='y' else 'Build requires a representable64-unit retail placement'}} for axis in ('x','y','z')],
            'notes':['Empty authored fields inherit imported values. Authoring bounds and Build encoding bounds are separate.',
                     'Unknown heights use source terrain for preview when available, otherwise the ground plane. Display axes use the SDK conversion.']},
        'ActorAppearance':{'label':'Actor appearance','units':'Model + animation pair','layout':'layered-properties',
            'actions':[{'id':'choose-appearance','label':'Choose donor appearance…','capability':'actor_appearance','requires_edit':True},{'id':'clear-appearance','label':'Clear appearance override','capability':'actor_appearance','requires_edit':True,'when':['authored','donor_entity_id']},{'id':'preview-appearance','label':'Preview authored appearance','capability':'actor_appearance','when':['authored','donor_entity_id']}],
            'layers':[{'id':'imported','label':'Imported'},{'id':'authored','label':'Authored override'},{'id':'effective','label':'Effective'}],
            'properties':[{'id':'asset_id','label':'Model','path':['asset_id'],'type':'asset-reference','layers':['imported','effective'],'state':'read-only-reference'},
                          {'id':'animation_id','label':'Animation ID','path':['animation_id'],'type':'integer','layers':['imported','effective'],'state':'read-only-reference'},
                          {'id':'donor_entity_id','label':'Donor actor','path':['donor_entity_id'],'type':'entity-reference','layers':['authored'],'empty_label':'None · inherit imported appearance','state':'authored-through-donor-review'}],
            'notes':['Assign a verified donor pair to this existing actor. Script behavior and gameplay compatibility are not established by a matching model and animation.']},
        'RuntimeCorrelation':{'label':'Runtime observation','units':'Read only · sampled','layout':'read-only-properties',
            'properties':[{'id':'status','label':'Correlation','path':['status'],'fallback_paths':[['state']],'empty_label':'Unresolved','type':'string','state':'live-observed'},
                          {'id':'binding_confirmed','label':'Binding confirmed','path':['binding_confirmed'],'type':'boolean','state':'live-observed'}],
            'notes':['Candidate associations preserve ambiguity. They do not replace imported or authored values.'],
            'details':[{'label':'Epoch, candidates and evidence','path':[]}]},
        'RetailMetadata':{'label':'Retail metadata','units':'Read only','layout':'read-only-properties',
            'properties':[{'id':'source','label':'Source','path':['source_record','prot_entry_name'],'fallback_paths':[['source_record','scene'],['source_record','kind']],'empty_label':'Imported record','type':'string','state':'read-only-retail'}],
            'details':[{'label':'Source, evidence and unresolved fields','path':[]}]},
        'ModelRenderer':{'label':'Model renderer','layout':'read-only-properties',
            'actions':[{'id':'inspect-model','label':'Inspect model objects','capability':'model_preview','when':['asset_id']}],
            'properties':[{'id':'asset_id','label':'Asset','path':['asset_id'],'type':'asset-reference','state':'read-only-retail'},
                          {'id':'resolution_status','label':'Resolution','path':['resolution_status'],'type':'string','state':'derived'}]},
        'Dialogue':{'label':'Script and dialogue','units':'Inspect source','layout':'read-only-properties','properties':[],
            'notes':['Inspect decoded dialogue and supported instruction paths; source capacity and unknown instructions remain explicit.'],
            'actions':[{'id':'inspect-script','label':'Inspect script and dialogue','capability':'actor_script_preview'},{'id':'inspect-actor-candidate','label':'Inspect NPC creation candidate','capability':'actor_candidate_inspection'}]},
        'Animation':{'label':'Animation','layout':'read-only-properties',
            'properties':[{'id':'imported_id','label':'Imported ID','path':['imported_id'],'type':'integer','state':'read-only-retail'}],
            'notes':['Timing, live animation state and retargeting are not inferred from an imported association.']}
    },'unknown_component_policy':'read-only-details','live_writes':False}
