"""Separate bounded source-scene, authored-NPC and derived terrain allowances."""
MAX_SOURCE_ENTITIES = 512
MAX_DRAFT_ENTITIES = 128
MAX_TERRAIN_ENTITIES = 1
MAX_PREVIEW_ENTITIES = MAX_SOURCE_ENTITIES + MAX_DRAFT_ENTITIES + MAX_TERRAIN_ENTITIES
