const integer=(v,a,b)=>Number.isSafeInteger(v)&&v>=a&&v<=b,exact=(v,keys)=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
export function validateRigBinding(binding){
 if(Object.hasOwn(binding??{},'external_skin_index')&&(!integer(binding.external_skin_index,0,63)||!Array.isArray(binding.external_object_nodes)))throw Error('Joint motion requires a skin index (0–63) and explicit native-object node mapping.');
}
export function validateRigReview(report,binding){
 validateRigBinding(binding);if(!Object.hasOwn(binding,'external_skin_index')){if(Object.hasOwn(report??{},'external_rig')||Object.hasOwn(report??{},'external_skin_index'))throw Error('Review contains an unrequested joint rig.');return;}
 const r=report?.external_rig,keys=['skin_index','joint_nodes','mapped_joint_nodes','common_root_node','skin_mesh_nodes','inverse_bind_accessor','inverse_bind_count','mesh_skinning_applied','scope','ignored_channels'],nodes=list=>Array.isArray(list)&&list.length>0&&list.length<=4096&&list.every(n=>integer(n,0,4095))&&new Set(list).size===list.length;
 if(report.external_skin_index!==binding.external_skin_index||!exact(r,keys)||r.skin_index!==binding.external_skin_index||r.mesh_skinning_applied!==false||r.scope!=='rigid-joint-motion-only'||!nodes(r.joint_nodes)||!nodes(r.skin_mesh_nodes)||JSON.stringify(r.mapped_joint_nodes)!==JSON.stringify(binding.external_object_nodes)||!r.mapped_joint_nodes.every(n=>r.joint_nodes.includes(n))||r.skin_mesh_nodes.some(n=>r.mapped_joint_nodes.includes(n))||!integer(r.common_root_node,0,4095)||!(r.inverse_bind_accessor===null?r.inverse_bind_count===0:integer(r.inverse_bind_accessor,0,16383)&&integer(r.inverse_bind_count,r.joint_nodes.length,4096))||!Array.isArray(r.ignored_channels)||r.ignored_channels.length>256)throw Error('Review joint rig differs from the explicit source mapping.');
 const seen=new Set();for(const c of r.ignored_channels){const key=c?.node_index+':'+c?.path;if(!exact(c,['node_index','path'])||!integer(c.node_index,0,4095)||r.mapped_joint_nodes.includes(c.node_index)||!['translation','rotation','scale'].includes(c.path)||(!r.joint_nodes.includes(c.node_index)&&c.path!=='scale')||seen.has(key))throw Error('Invalid ignored rig channel evidence.');seen.add(key);}
}
