import {openAudioWaveform} from './audio-waveform.js';
// Source bank tables, independent of scene playback and sequence coverage.
const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),exact=(v,keys)=>object(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k)),integer=(v,a,b)=>Number.isSafeInteger(v)&&v>=a&&v<=b,hash=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const programKeys=['slot','offset','tone_count','volume','priority','mode','pan','attributes','source_sha256'];
const toneKeys=['page','index','offset','priority','mode','volume','pan','center','shift','minimum_key','maximum_key','pitch_bend_down','pitch_bend_up','adsr1','adsr2','program_operand','sample_operand','sample_index','source_sha256'];
export function decodeAudioBank(value,context){
 if(!exact(value,['schema_version','asset_id','scene_id','source_key','read_only','project_changed','runtime_state','source_record','reference_commit','header','bank_sha256','bank_size_bytes','sections','programs','tones','samples','sample_table_spacer','sample_table_unused_nonzero','used_program_slots','declared_program_count_matches_used_slots','consumed_sample_end','remaining_bank_bytes','limitations'])||!/^audio:\/\/legaia\/prot\/[0-9]{4}$/.test(context.assetId)||value.schema_version!=='legaia.audio-bank-inspection.v1'||value.asset_id!==context.assetId||value.scene_id!==context.sceneId||value.source_key!==context.sourceKey||!hash(context.sourceKey)||value.read_only!==true||value.project_changed!==false||value.runtime_state!=='not_observed'||!hash(value.bank_sha256)||value.bank_sha256!==context.bankHash||!integer(value.bank_size_bytes,32,4194304)||!/^[a-f0-9]{40}$/.test(value.reference_commit??''))throw new Error('Bank report differs from its reviewed source.');
 const source=value.source_record;if(!exact(source,['disc_sha256','iso_file','prot_entry_index','entry_sha256','entry_byte_offset','entry_size_bytes','carrier','pieces'])||!hash(source.disc_sha256)||source.iso_file!=='PROT.DAT'||source.prot_entry_index!==Number(context.assetId.split('/').at(-1))||!hash(source.entry_sha256)||source.entry_sha256!==context.entryHash||!integer(source.entry_byte_offset,0,2**40)||!integer(source.entry_size_bytes,32,4194304)||!['standalone-vab','leading-contiguous-vab-chunk','split-vab-header-samples'].includes(source.carrier)||!Array.isArray(source.pieces)||source.pieces.length!==(source.carrier==='split-vab-header-samples'?2:1)||source.pieces[0]?.entry_offset!==(source.carrier==='standalone-vab'?0:4))throw new Error('Invalid bank carrier provenance.');
 let end=0,entryEnd=0;for(const piece of source.pieces){if(!exact(piece,['bank_offset','entry_offset','size_bytes'])||piece.bank_offset!==end||!integer(piece.size_bytes,1,value.bank_size_bytes-end)||!integer(piece.entry_offset,entryEnd,source.entry_size_bytes-piece.size_bytes)||(piece.bank_offset>0&&piece.entry_offset!==entryEnd+4))throw new Error('Invalid bank source piece range.');end+=piece.size_bytes;entryEnd=piece.entry_offset+piece.size_bytes;}if(end!==value.bank_size_bytes)throw new Error('Bank pieces do not cover its declared extent.');
 const h=value.header,s=value.sections;if(!exact(h,['version','bank_id','declared_size','program_count','tone_count','sample_count'])||!integer(h.version,0,10)||!integer(h.bank_id,0,4294967295)||h.declared_size!==value.bank_size_bytes||!integer(h.program_count,1,128)||!integer(h.tone_count,0,2048)||!integer(h.sample_count,1,255)||!exact(s,['program_offset','tone_offset','sample_table_offset','sample_offset'])||s.program_offset!==32||s.tone_offset!==2080||s.sample_table_offset!==2080+h.program_count*512||s.sample_offset!==s.sample_table_offset+512||s.sample_offset>value.bank_size_bytes)throw new Error('Invalid bank fixed sections.');
 if(!Array.isArray(value.programs)||value.programs.length!==128||!Array.isArray(value.tones)||value.tones.length!==h.program_count*16||!Array.isArray(value.samples)||value.samples.length!==h.sample_count)throw new Error('Invalid bank table counts.');
 const used=[];for(const [slot,row] of value.programs.entries()){if(!exact(row,programKeys)||row.slot!==slot||row.offset!==32+slot*16||!integer(row.tone_count,0,16)||['volume','priority','mode','pan'].some(k=>!integer(row[k],0,255))||!integer(row.attributes,0,65535)||!hash(row.source_sha256))throw new Error('Invalid source program row.');if(row.tone_count)used.push(slot);}
 for(const [index,row] of value.tones.entries()){if(!exact(row,toneKeys)||row.page!==Math.floor(index/16)||row.index!==index%16||row.offset!==2080+index*32||['priority','mode','volume','pan','center','shift','minimum_key','maximum_key','pitch_bend_down','pitch_bend_up'].some(k=>!integer(row[k],0,255))||!integer(row.adsr1,0,65535)||!integer(row.adsr2,0,65535)||!integer(row.program_operand,-32768,32767)||!integer(row.sample_operand,-32768,32767)||row.sample_index!==(row.sample_operand>=1&&row.sample_operand<=h.sample_count?row.sample_operand-1:null)||!hash(row.source_sha256))throw new Error('Invalid packed tone row or source sample operand.');}
 let cursor=s.sample_offset;for(const [index,row] of value.samples.entries()){if(!exact(row,['index','table_index','size_units','offset','size_bytes','block_aligned','source_sha256'])||row.index!==index||row.table_index!==index+1||!integer(row.size_units,0,65535)||row.size_bytes!==row.size_units*8||row.offset!==cursor||cursor+row.size_bytes>value.bank_size_bytes||row.block_aligned!==(row.size_bytes%16===0)||!hash(row.source_sha256))throw new Error('Invalid source sample span.');cursor+=row.size_bytes;}
 if(!integer(value.sample_table_spacer,0,65535)||!integer(value.sample_table_unused_nonzero,0,255-h.sample_count)||JSON.stringify(value.used_program_slots)!==JSON.stringify(used)||value.declared_program_count_matches_used_slots!==(used.length===h.program_count)||value.consumed_sample_end!==cursor||value.remaining_bank_bytes!==value.bank_size_bytes-cursor||!Array.isArray(value.limitations)||value.limitations.length>32||value.limitations.some(v=>typeof v!=='string'||v.length>8192))throw new Error('Bank summary differs from its source tables.');return structuredClone(value);
}
export function openAudioBank({record,getContext,busy,request=fetch,onError=()=>{}}){
 const expected=structuredClone(getContext()),same=()=>JSON.stringify(getContext())===JSON.stringify(expected),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},dialog=el('dialog');dialog.id='audio-bank-dialog';Object.assign(dialog.style,{width:'min(1080px,calc(100vw - 32px))',maxWidth:'calc(100vw - 32px)',maxHeight:'calc(100vh - 32px)',overflow:'auto'});
 const heading=el('div'),close=el('button','Close');heading.className='dialog-heading';close.onclick=()=>dialog.close();heading.append(el('h2','Source VAB bank tables'),close);const status=el('p','Verifying bank source…'),summary=el('p'),limits=el('p'),toolbar=el('div'),view=el('select'),used=el('input'),usedLabel=el('label','Used program slots only'),pageFilter=el('select'),search=el('input'),prev=el('button','Previous rows'),next=el('button','Next rows'),pageLabel=el('span'),download=el('button','Save bank evidence…'),wrap=el('div'),table=el('table'),thead=el('thead'),tbody=el('tbody');status.setAttribute('role','status');view.setAttribute('aria-label','Bank table');pageFilter.setAttribute('aria-label','Packed tone page');used.type='checkbox';used.checked=true;used.setAttribute('aria-label','Used program slots only');Object.assign(used.style,{width:'auto',margin:'0 6px'});usedLabel.append(used);Object.assign(usedLabel.style,{display:'flex',alignItems:'center'});search.type='search';search.setAttribute('aria-label','Filter bank rows');search.placeholder='Filter source rows';Object.assign(toolbar.style,{display:'flex',flexWrap:'wrap',gap:'8px'});Object.assign(wrap.style,{overflowX:'auto'});Object.assign(table.style,{width:'100%',minWidth:'820px',borderCollapse:'collapse',fontSize:'12px'});table.append(thead,tbody);wrap.append(table);toolbar.append(view,usedLabel,pageFilter,search,prev,next,pageLabel,download);dialog.append(heading,el('p',record.label+' · '+record.id),status,summary,limits,toolbar,wrap);document.body.append(dialog);
 for(const [value,label] of [['programs','Program slots'],['tones','Packed tone pages'],['samples','Source sample spans']]){const option=el('option',label);option.value=value;view.append(option);}view.value='programs';const all=el('option','All packed pages');all.value='all';pageFilter.append(all);pageFilter.value='all';
 let report=null,disposed=false,stale=false,page=0,sampleIndex=null;const controller=new AbortController(),controls=[view,used,pageFilter,search,prev,next,download];controls.forEach(n=>n.disabled=true);
 const invalidate=()=>{stale=true;report=null;thead.replaceChildren();tbody.replaceChildren();summary.textContent='';status.textContent='Project sources changed. Reopen this bank inspector.';controls.forEach(n=>n.disabled=true);};
 const fresh=()=>{if(disposed||stale)return false;if(!same()){invalidate();return false;}return true;};
 const render=()=>{if(!report||!fresh())return;usedLabel.hidden=view.value!=='programs';pageFilter.hidden=view.value!=='tones';const query=search.value.trim().toLowerCase();let rows=report[view.value].filter(row=>(view.value!=='programs'||!used.checked||row.tone_count>0)&&(view.value!=='tones'||pageFilter.value==='all'||String(row.page)===pageFilter.value)&&(view.value!=='samples'||sampleIndex===null||row.index===sampleIndex)&&JSON.stringify(row).toLowerCase().includes(query));page=Math.min(page,Math.max(0,Math.ceil(rows.length/128)-1));thead.replaceChildren();tbody.replaceChildren();const columns=view.value==='programs'?['Slot','Source byte','Tones','Volume / pan','Priority / mode','Attributes']:view.value==='tones'?['Page / row','Source byte','Program operand','Sample operand','Key range / center / shift','Volume / pan','ADSR']:['Index / table slot','Source byte','Encoded size units','Bytes','16-byte aligned','Source SHA-256'];const hr=el('tr');for(const label of columns){const cell=el('th',label);Object.assign(cell.style,{padding:'5px',whiteSpace:'nowrap',textAlign:'left'});hr.append(cell);}thead.append(hr);
 for(const row of rows.slice(page*128,(page+1)*128)){const values=view.value==='programs'?[row.slot,'0x'+row.offset.toString(16),row.tone_count,row.volume+' / '+row.pan,row.priority+' / '+row.mode,row.attributes]:view.value==='tones'?[row.page+' / '+row.index,'0x'+row.offset.toString(16),row.program_operand,row.sample_operand,row.minimum_key+'–'+row.maximum_key+' / '+row.center+' / '+row.shift,row.volume+' / '+row.pan,row.adsr1+' / '+row.adsr2]:[row.index+' / '+row.table_index,'0x'+row.offset.toString(16),row.size_units,row.size_bytes,String(row.block_aligned),row.source_sha256];const tr=el('tr');for(const [index,text] of values.entries()){const td=el('td');Object.assign(td.style,{padding:'5px',borderBottom:'1px solid #33494a'});if(view.value==='tones'&&index===3&&row.sample_index!==null){const button=el('button','Source sample '+row.sample_operand);button.onclick=()=>{if(!fresh())return;sampleIndex=row.sample_index;view.value='samples';page=0;search.value='';render();};td.append(button);}else if(view.value==='samples'&&index===0){const button=el('button','Inspect waveform '+(row.index+1));button.onclick=()=>{if(fresh()&&!busy())openAudioWaveform({bank:report,sample:row,getContext,request,onError});};td.append(el('span',String(text)+' '),button);}else td.textContent=String(text);tr.append(td);}tbody.append(tr);}pageLabel.textContent=`${rows.length} matching · page ${page+1} / ${Math.max(1,Math.ceil(rows.length/128))}`;prev.disabled=page===0;next.disabled=(page+1)*128>=rows.length;};
 view.onchange=()=>{page=0;sampleIndex=null;render();};used.onchange=pageFilter.onchange=search.oninput=()=>{page=0;sampleIndex=null;render();};prev.onclick=()=>{if(fresh()){page--;render();}};next.onclick=()=>{if(fresh()){page++;render();}};download.onclick=()=>{if(!report||!fresh()||busy())return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)+'\n'],{type:'application/json'})),a=el('a');a.href=url;a.download=record.id.split('/').at(-1)+'-bank-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0);};
 const timer=setInterval(()=>{if(!disposed)fresh();},300);dialog.addEventListener('close',()=>{disposed=true;controller.abort();clearInterval(timer);dialog.remove();},{once:true});dialog.showModal();
 const ready=(async()=>{try{const response=await request('/api/audio-bank',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:expected.assetId,expected_source_key:expected.sourceKey,expected_entry_sha256:expected.entryHash}),signal:controller.signal}),raw=await response.text();if(new TextEncoder().encode(raw).length>12*1024*1024)throw new Error('Bank metadata exceeds the display budget.');const value=JSON.parse(raw);if(!fresh())return;if(!response.ok||value.error)throw new Error(value.error??'Bank inspection failed.');report=decodeAudioBank(value,expected);controls.forEach(n=>n.disabled=false);for(let i=0;i<report.header.program_count;i++){const o=el('option','Packed page '+i);o.value=String(i);pageFilter.append(o);}status.textContent='Source bank tables verified.';summary.textContent=`${report.used_program_slots.length} used source slots · ${report.header.program_count} packed tone pages · ${report.samples.length} sample spans · bank SHA-256 ${report.bank_sha256}`;limits.textContent=report.limitations.join(' ');render();}catch(error){if(!controller.signal.aborted&&fresh()){status.textContent=error.message;onError(error);}}})();return {dialog,ready,dispose:()=>dialog.close()};
}
