const hash=value=>typeof value==='string'&&/^[0-9a-f]{64}$/.test(value);
const count=value=>Number.isSafeInteger(value)&&value>=0;
export function modelCoordinateReview(change){
  if(change?.coordinate_changes===undefined)return null;
  const rows=change.coordinate_changes;
  if(change.field!=='model.shape'||!hash(change.before)||!hash(change.after)||!Array.isArray(rows)||rows.length>2*1024*1024)throw new Error('Invalid model native audit.');
  const coordinates=[],offsets=new Set();
  for(const row of rows){
    if(!row||typeof row!=='object'||Array.isArray(row)||typeof row.kind!=='string'||!row.kind||row.kind.length>128)throw new Error('Invalid model audit record.');
    if(!['vertex','normal'].includes(row.kind))continue;
    if(!count(row.object_index)||!count(row.vector_index)||!['x','y','z'].includes(row.axis)||!count(row.byte_offset)||row.byte_offset>4*1024*1024-2||row.byte_offset%2||offsets.has(row.byte_offset)||['before_value','after_value'].some(key=>!Number.isSafeInteger(row[key])||row[key]<-32768||row[key]>32767)||row.before_value===row.after_value)throw new Error('Invalid model coordinate audit.');
    offsets.add(row.byte_offset);coordinates.push(Object.fromEntries(['object_index','kind','vector_index','axis','byte_offset','before_value','after_value'].map(key=>[key,row[key]])));
  }
  return {coordinates,other_change_count:rows.length-coordinates.length,total_change_count:rows.length};
}
export function modelCoordinatePage(review,page=0){
  const pages=Math.max(1,Math.ceil(review.coordinates.length/128));
  if(!count(page)||page>=pages)throw new Error('Choose an existing model coordinate page.');
  return {page,pages,total:review.coordinates.length,rows:structuredClone(review.coordinates.slice(page*128,(page+1)*128))};
}
export function validResourceRelocation(value){
  return value===undefined||!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===3&&count(value.package_bytes)&&value.package_bytes>0&&value.package_bytes<=256*1024*1024&&count(value.archive_growth_bytes)&&value.archive_growth_bytes<=256*1024*1024&&count(value.texture_pack_count)&&value.texture_pack_count<=32;
}
export function decodeBuildReview(value,key){
  const npc=value?.schema_version==='legaia.build-review.v2';
  if(!['legaia.build-review.v1','legaia.build-review.v2'].includes(value?.schema_version)||value.source_key!==key||!hash(key)||value.read_only!==true||!['blocked','ready_for_build'].includes(value.status)||typeof value.normal_build_ready!=='boolean'||!Array.isArray(value.blockers)||value.blockers.length>512||value.normal_build_ready!==(value.blockers.length===0)||value.status!==(value.normal_build_ready?'ready_for_build':'blocked')||!count(value.excluded_npc_draft_count)||value.assessment_scope!==(npc?'all_supported_authored_content_including_source_qualified_npc_drafts':'existing_imported_content_and_supported_overrides_excluding_npc_drafts'))throw new Error('Invalid or stale Build review. Review again.');
  if(npc&&(value.excluded_npc_draft_count!==0||!count(value.included_npc_draft_count)||value.included_npc_draft_count>8192||value.npc_build_scope!=='qualified_man_source_candidates'||value.npc_gameplay_verified!==false))throw new Error('Invalid NPC source candidate coverage or gameplay claim.');
  for(const row of value.blockers)if(!['npc_draft','serialization'].includes(row.kind)||row.owner_id!==null&&(typeof row.owner_id!=='string'||!row.owner_id||row.owner_id.length>1024)||typeof row.message!=='string'||row.message.length>8192)throw new Error('Invalid Build blocker.');
  if(!npc&&value.excluded_npc_draft_count!==value.blockers.filter(row=>row.kind==='npc_draft').length||!Array.isArray(value.limitations)||value.limitations.length>64||value.limitations.some(row=>typeof row!=='string'||row.length>8192))throw new Error('Invalid Build review coverage.');
  const a=value.assessment;if(a!==null){const r=a?.report;if(a.output_written!==false||a.archive_packing!=='not_run'||a.runtime_status!=='not_run'||!hash(a.audit_sha256)||!hash(a.manifest_sha256)||!hash(a.source_disc_sha256)||!count(a.overlay_count)||!['authored','retail'].includes(a.build_kind)||!Array.isArray(a.change_kinds)||a.change_kinds.some(row=>typeof row!=='string')||r?.schema_version!=='legaia.build-report.v1'||!validResourceRelocation(r.resource_relocation)||!count(r.change_count)||!count(r.scene_count)||!count(r.overlay_bytes)||!Array.isArray(r.changes)||r.changes.length!==r.change_count||r.changes.length>100000||r.validation?.retail_provenance!=='fresh_import_match'||r.validation?.live_runtime!=='not_run'||r.validation?.unchanged_opaque_bytes!==true)throw new Error('Invalid Build serialization assessment.');
    for(const row of r.changes){if(typeof row.owner_id!=='string'||row.owner_id.length>1024||typeof row.field!=='string'||row.field.length>1024||typeof row.scope!=='string'||row.scope.length>1024)throw new Error('Invalid reviewed change.');modelCoordinateReview(row);if(npc&&row.composition_changes!==undefined&&(!Array.isArray(row.composition_changes)||row.composition_changes.length>4096))throw new Error('Invalid source candidate composition coverage.');}
  }else if(!value.blockers.some(row=>row.kind==='serialization'))throw new Error('Missing serialization assessment.');
  return structuredClone(value);
}
export function mountBuildReview({after,getState,busy,setBusy,onBuild,onError}){
  const button=document.createElement('button');button.id='build-review-button';button.textContent='Review Build…';button.disabled=true;after.after(button);
  button.onclick=()=>{
    const state=getState();if(busy()||!state.capabilities?.build_review)return;const key=state.build_review_source_key,dialog=document.createElement('dialog'),controller=new AbortController();dialog.id='build-review-dialog';dialog.className='project-dialog';
    const title=document.createElement('h2');title.textContent='Review normal Build';const status=document.createElement('p');status.setAttribute('role','status');status.textContent='Verifying sources and serializing current authored inputs…';const content=document.createElement('div'),build=document.createElement('button');build.textContent='Build reviewed inputs';build.id='build-reviewed-inputs';build.disabled=true;const close=document.createElement('button');close.textContent='Close';close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{controller.abort();dialog.remove();});dialog.append(title,status,content,build,close);document.body.append(dialog);dialog.showModal();setBusy(true);
    const current=()=>dialog.open&&getState().build_review_source_key===key&&getState().capabilities?.build_review===true;
    (async()=>{try{
      const response=await fetch('/api/build-review',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',signal:controller.signal}),raw=await response.json();if(controller.signal.aborted||!dialog.open)return;if(!response.ok||raw.error)throw new Error(raw.error||'Build review failed');if(!current())throw new Error('Authored inputs changed. Review Build again.');const result=decodeBuildReview(raw,key);
      const npc=result.schema_version==='legaia.build-review.v2';
      status.textContent=result.normal_build_ready?(npc?'Source candidates passed serialization and package-fit review. Package not created; gameplay unverified.':'Existing content passed serialization review. Package not created; gameplay unverified.'):`Normal Build blocked · ${result.blockers.length} blocker(s). NPC drafts retained.`;
      if(npc){const summary=document.createElement('p');summary.textContent=`Source serialization assessment includes ${result.included_npc_draft_count} NPC candidate(s).${result.assessment?'':' These requested candidates have not passed serialization assessment.'}`;content.append(summary);const note=document.createElement('p');note.className='field-note';note.textContent='Source package candidates only. The retail actor-pool lower bound is checked. Scenery and two later setup allocations share the pool; scripts can run between allocations, so remaining slots are not a safe NPC budget. Native allocation, spawning, scheduling and opaque script coverage remain unverified; package fit does not establish gameplay acceptance.';content.append(note);}
      for(const row of result.blockers){const p=document.createElement('p');p.className='dialog-error';p.textContent=`${row.owner_id?row.owner_id+' · ':''}${row.message}`;content.append(p);}
      if(result.assessment){const report=result.assessment.report,summary=document.createElement('p');summary.textContent=npc?`${report.change_count} audited source changes · ${report.scene_count} changed scenes · ${result.assessment.overlay_count} overlays · ${report.overlay_bytes} bytes.`:`Existing content assessment excludes ${result.excluded_npc_draft_count} NPC draft(s): ${report.change_count} audited changes · ${report.scene_count} changed scenes · ${result.assessment.overlay_count} overlays · ${report.overlay_bytes} bytes.`;content.append(summary);
        if(report.resource_relocation){const r=report.resource_relocation,p=document.createElement('p');p.textContent=`Resource relocation: ${r.package_bytes.toLocaleString()} package bytes, ${r.archive_growth_bytes.toLocaleString()} PROT growth bytes, ${r.texture_pack_count} rebuilt texture pack(s). Fixed-span edits are composed before relocation.`;content.append(p);}
        const table=document.createElement('table'),head=document.createElement('tr');table.style.width='100%';table.style.tableLayout='fixed';for(const label of ['Owner / field','Before','After']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const row of report.changes.slice(0,256)){const tr=document.createElement('tr');for(const text of [`${row.owner_id} · ${row.field}`,JSON.stringify(row.before),JSON.stringify(row.after)]){const td=document.createElement('td');td.style.overflowWrap='anywhere';td.textContent=text;tr.append(td);}table.append(tr);
          const native=modelCoordinateReview(row);if(native){const detailRow=document.createElement('tr'),cell=document.createElement('td'),details=document.createElement('details'),label=document.createElement('summary');cell.colSpan=3;details.dataset.modelCoordinateReview=row.owner_id;label.textContent=`Native coordinate audit: ${native.coordinates.length} coordinates · ${native.other_change_count} other records`;details.append(label);cell.append(details);detailRow.append(cell);table.append(detailRow);
            let page=0,loaded=false;const pane=document.createElement('div');details.append(pane);const draw=()=>{pane.replaceChildren();const slice=modelCoordinatePage(native,page),note=document.createElement('p');note.textContent=`Page ${page+1}/${slice.pages} · showing ${slice.rows.length} of ${slice.total} recorded coordinate changes. ${native.other_change_count} primitive/allocation/other records remain in the full audit. Recorded model offsets; package not created, gameplay unverified.`;pane.append(note);
              const words=document.createElement('table');words.style.width='100%';words.style.tableLayout='fixed';const head=document.createElement('tr');for(const text of ['Object / vector / axis','Model byte','Before','After']){const th=document.createElement('th');th.textContent=text;head.append(th);}words.append(head);for(const word of slice.rows){const tr=document.createElement('tr');tr.dataset.coordinateOffset=String(word.byte_offset);for(const text of [`${word.object_index} / ${word.kind} ${word.vector_index} / ${word.axis.toUpperCase()}`,String(word.byte_offset),String(word.before_value),String(word.after_value)]){const td=document.createElement('td');td.textContent=text;td.style.overflowWrap='anywhere';tr.append(td);}words.append(tr);}pane.append(words);
              const actions=document.createElement('div');actions.className='dialog-actions';actions.style.flexWrap='wrap';for(const [text,delta] of [['Previous coordinates',-1],['Next coordinates',1]]){const button=document.createElement('button');button.textContent=text;button.disabled=page+delta<0||page+delta>=slice.pages;button.onclick=()=>{if(busy())return;if(!current()){status.textContent='Authored inputs changed. Reopen Build review.';return;}page+=delta;draw();};actions.append(button);}pane.append(actions);};details.ontoggle=()=>{if(details.open&&!loaded){loaded=true;draw();}};
          }
        }content.append(table);if(report.change_count>256){const p=document.createElement('p');p.textContent=`First256 rows shown of ${report.change_count}; serialization assessment covers every reported change.`;content.append(p);}
        const details=document.createElement('details'),label=document.createElement('summary'),pre=document.createElement('pre');label.textContent='Serialization provenance';pre.className='diagnostic-detail';pre.textContent=JSON.stringify({audit_sha256:result.assessment.audit_sha256,manifest_sha256:result.assessment.manifest_sha256,source_disc_sha256:result.assessment.source_disc_sha256,validation:report.validation,change_kinds:result.assessment.change_kinds},null,2);details.append(label,pre);content.append(details);
      }
      const list=document.createElement('ul');for(const text of result.limitations){const row=document.createElement('li');row.textContent=text;list.append(row);}content.append(list);build.disabled=!result.normal_build_ready||getState().project?.mode!=='edit';build.onclick=async()=>{if(busy())return;if(!current()||getState().project?.mode!=='edit'){status.textContent='Authored inputs or mode changed. Review Build again.';return;}dialog.close();try{await onBuild(key);}catch(error){onError(error);}};
    }catch(error){if(error.name!=='AbortError'&&dialog.open)status.textContent=error.message;}finally{setBusy(false);}})();
  };return button;
}
