const hash=value=>typeof value==='string'&&/^[0-9a-f]{64}$/.test(value);
const count=value=>Number.isSafeInteger(value)&&value>=0;
export function decodeBuildReview(value,key){
  if(value?.schema_version!=='legaia.build-review.v1'||value.source_key!==key||!hash(key)||value.read_only!==true||!['blocked','ready_for_build'].includes(value.status)||typeof value.normal_build_ready!=='boolean'||!Array.isArray(value.blockers)||value.blockers.length>512||value.normal_build_ready!==(value.blockers.length===0)||value.status!==(value.normal_build_ready?'ready_for_build':'blocked')||!count(value.excluded_npc_draft_count)||value.assessment_scope!=='existing_imported_content_and_supported_overrides_excluding_npc_drafts')throw new Error('Invalid or stale Build review. Review again.');
  for(const row of value.blockers)if(!['npc_draft','serialization'].includes(row.kind)||row.owner_id!==null&&(typeof row.owner_id!=='string'||!row.owner_id||row.owner_id.length>1024)||typeof row.message!=='string'||row.message.length>8192)throw new Error('Invalid Build blocker.');
  if(value.excluded_npc_draft_count!==value.blockers.filter(row=>row.kind==='npc_draft').length||!Array.isArray(value.limitations)||value.limitations.length>64||value.limitations.some(row=>typeof row!=='string'||row.length>8192))throw new Error('Invalid Build review coverage.');
  const a=value.assessment;if(a!==null){const r=a?.report;if(a.output_written!==false||a.archive_packing!=='not_run'||a.runtime_status!=='not_run'||!hash(a.audit_sha256)||!hash(a.manifest_sha256)||!hash(a.source_disc_sha256)||!count(a.overlay_count)||!['authored','retail'].includes(a.build_kind)||!Array.isArray(a.change_kinds)||a.change_kinds.some(row=>typeof row!=='string')||r?.schema_version!=='legaia.build-report.v1'||!count(r.change_count)||!count(r.scene_count)||!count(r.overlay_bytes)||!Array.isArray(r.changes)||r.changes.length!==r.change_count||r.changes.length>100000||r.validation?.retail_provenance!=='fresh_import_match'||r.validation?.live_runtime!=='not_run'||r.validation?.unchanged_opaque_bytes!==true)throw new Error('Invalid Build serialization assessment.');
    for(const row of r.changes)if(typeof row.owner_id!=='string'||row.owner_id.length>1024||typeof row.field!=='string'||row.field.length>1024||typeof row.scope!=='string'||row.scope.length>1024)throw new Error('Invalid reviewed change.');
  }else if(!value.blockers.some(row=>row.kind==='serialization'))throw new Error('Missing serialization assessment.');
  return structuredClone(value);
}
export function mountBuildReview({after,getState,busy,setBusy,onBuild,onError}){
  const button=document.createElement('button');button.id='build-review-button';button.textContent='Review Build…';button.disabled=true;after.after(button);
  button.onclick=()=>{
    const state=getState();if(busy()||!state.capabilities?.build_review)return;const key=state.build_review_source_key,dialog=document.createElement('dialog'),controller=new AbortController();dialog.id='build-review-dialog';dialog.className='project-dialog';
    const title=document.createElement('h2');title.textContent='Review normal Build';const status=document.createElement('p');status.setAttribute('role','status');status.textContent='Verifying sources and serializing current existing overrides…';const content=document.createElement('div'),build=document.createElement('button');build.textContent='Build reviewed inputs';build.id='build-reviewed-inputs';build.disabled=true;const close=document.createElement('button');close.textContent='Close';close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{controller.abort();dialog.remove();});dialog.append(title,status,content,build,close);document.body.append(dialog);dialog.showModal();setBusy(true);
    const current=()=>dialog.open&&getState().build_review_source_key===key&&getState().capabilities?.build_review===true;
    (async()=>{try{
      const response=await fetch('/api/build-review',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',signal:controller.signal}),raw=await response.json();if(controller.signal.aborted||!dialog.open)return;if(!response.ok||raw.error)throw new Error(raw.error||'Build review failed');if(!current())throw new Error('Authored inputs changed. Review Build again.');const result=decodeBuildReview(raw,key);
      status.textContent=result.normal_build_ready?'Existing content passed serialization review. Package not created; gameplay unverified.':`Normal Build blocked · ${result.blockers.length} blocker(s). NPC drafts retained.`;
      for(const row of result.blockers){const p=document.createElement('p');p.className='dialog-error';p.textContent=`${row.owner_id?row.owner_id+' · ':''}${row.message}`;content.append(p);}
      if(result.assessment){const report=result.assessment.report,summary=document.createElement('p');summary.textContent=`Existing content assessment excludes ${result.excluded_npc_draft_count} NPC draft(s): ${report.change_count} audited changes · ${report.scene_count} changed scenes · ${result.assessment.overlay_count} overlays · ${report.overlay_bytes} bytes.`;content.append(summary);
        const table=document.createElement('table'),head=document.createElement('tr');for(const label of ['Owner / field','Before','After']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const row of report.changes.slice(0,256)){const tr=document.createElement('tr');for(const text of [`${row.owner_id} · ${row.field}`,JSON.stringify(row.before),JSON.stringify(row.after)]){const td=document.createElement('td');td.textContent=text;tr.append(td);}table.append(tr);}content.append(table);if(report.change_count>256){const p=document.createElement('p');p.textContent=`First256 rows shown of ${report.change_count}; serialization assessment covers every reported change.`;content.append(p);}
        const details=document.createElement('details'),label=document.createElement('summary'),pre=document.createElement('pre');label.textContent='Serialization provenance';pre.className='diagnostic-detail';pre.textContent=JSON.stringify({audit_sha256:result.assessment.audit_sha256,manifest_sha256:result.assessment.manifest_sha256,source_disc_sha256:result.assessment.source_disc_sha256,validation:report.validation,change_kinds:result.assessment.change_kinds},null,2);details.append(label,pre);content.append(details);
      }
      const list=document.createElement('ul');for(const text of result.limitations){const row=document.createElement('li');row.textContent=text;list.append(row);}content.append(list);build.disabled=!result.normal_build_ready||getState().project?.mode!=='edit';build.onclick=async()=>{if(busy())return;if(!current()||getState().project?.mode!=='edit'){status.textContent='Authored inputs or mode changed. Review Build again.';return;}dialog.close();try{await onBuild(key);}catch(error){onError(error);}};
    }catch(error){if(error.name!=='AbortError'&&dialog.open)status.textContent=error.message;}finally{setBusy(false);}})();
  };return button;
}
