const integer=(v,min,max)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
const hash=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
export function floorHeights(values){if(!Array.isArray(values)||values.length!==16||values.some(v=>!integer(v,-32768,32767)))throw Error('Floor heights require sixteen signed integer MAN values.');return [...values];}
export function decodeFloorHeights(value,key,scene,asked){
 const proposed=floorHeights(asked),retail=floorHeights(value?.retail),current=floorHeights(value?.current),record=value?.source_record;
 if(!value||value.schema_version!=='legaia.floor-height-review.v1'||value.project_source_key!==key||value.scene_id!==scene||!hash(value.source_sha256)||!hash(value.review_key)||JSON.stringify(floorHeights(value.proposed))!==JSON.stringify(proposed)||value.scope!=='MAN-floor-height-table-only'||value.gameplay_verified!==false||typeof value.project_change!=='boolean'||value.effective_change_count!==current.filter((v,i)=>v!==proposed[i]).length||!Array.isArray(value.limitations)||value.limitations.some(v=>typeof v!=='string')||!record||!hash(record.disc_sha256)||record.payload_sha256!==value.source_sha256||!['descriptor_man','raw_streaming_man'].includes(record.source_kind)||record.compression!==(record.source_kind==='descriptor_man'?'lzs':'none')||!integer(record.entry_index,0,65535)||!integer(record.payload_offset,0,Number.MAX_SAFE_INTEGER)||!integer(record.decoded_size,43,64*1024*1024)||!integer(record.encoded_size,1,64*1024*1024)||(record.source_kind==='raw_streaming_man'?(!integer(record.chunk_header_offset,0,Number.MAX_SAFE_INTEGER)||record.encoded_size!==record.decoded_size):record.chunk_header_offset!==null))throw Error('Height Review differs from the selected source context.');
 const edits=proposed.flatMap((height,tier)=>height===retail[tier]?[]:[{tier,height}]);if(!value.value||Object.keys(value.value).sort().join(',')!=='edits,source_sha256'||value.value.source_sha256!==value.source_sha256||JSON.stringify(value.value.edits)!==JSON.stringify(edits)||!Array.isArray(value.audit)||value.audit.length!==edits.length)throw Error('Height Review authored values or audit differ.');
 value.audit.forEach((row,i)=>{const e=edits[i];if(!row||Object.keys(row).sort().join(',')!=='after_value,before_value,byte_length,decoded_byte_offset,field,record_index,scope,semantic_id,tier'||row.tier!==e.tier||row.decoded_byte_offset!==2+2*e.tier||row.byte_length!==2||row.before_value!==retail[e.tier]||row.after_value!==e.height||row.field!=='floor_height'||row.record_index!==0||row.semantic_id!==scene||row.scope!=='MAN-floor-height-table-only')throw Error('Height Review contains an unqualified MAN span.');});return structuredClone(value);
}
export function mountFloorHeights({host,getState,busy,setBusy,api,sourceCurrent,onScene,onRestore=()=>{}}){
 const launch=document.createElement('button');launch.type='button';launch.textContent='Edit floor heights…';host.append(launch);let dialog=null,binding=null,reviewed=null,controller=null,generation=0,retained=false;
 const current=()=>!!binding&&sourceCurrent()&&getState().project_copy_source_key===binding.key&&getState().scene?.id===binding.scene&&getState().project?.mode==='edit';
 function withdraw(){generation++;if(controller){controller.abort();controller=null;setBusy(false);}reviewed=null;}
 function restore(){binding=null;withdraw();onRestore();if(dialog){const old=dialog;dialog=null;retained=false;if(old.open)old.close();old.remove();}refresh();}
 function request(){return floorHeights([...dialog.querySelectorAll('[data-height-tier]')].map(input=>input.value.trim()===''?NaN:Number(input.value)));}
 function refresh(){launch.disabled=busy()||!sourceCurrent()||getState().project?.mode!=='edit';if(binding&&!current()){restore();return;}if(!dialog)return;for(const control of dialog.querySelectorAll('input,[data-review],[data-reset]'))control.disabled=busy();let valid=false;try{request();valid=true;}catch{}dialog.querySelector('[data-review]').disabled=busy()||!current()||!valid;dialog.querySelector('[data-apply]').disabled=busy()||!current()||!reviewed?.project_change;dialog.querySelector('[data-scene]').disabled=busy()||!current()||!reviewed;}
 async function open(){if(busy()||!sourceCurrent())return;restore();const state=getState();binding={key:state.project_copy_source_key,scene:state.scene.id};const context=binding;dialog=document.createElement('dialog');dialog.id='floor-height-dialog';dialog.className='project-dialog';dialog.style.width='min(900px,92vw)';dialog.style.maxHeight='90vh';dialog.style.overflowY='auto';const active=dialog;
  const heading=document.createElement('h2');heading.textContent='Scene floor height table';const description=document.createElement('p');description.textContent='These sixteen MAN values are shared by floor corners and placed/decorative objects throughout this scene. Reference Y is the negated MAN value. Selectors, native ramps and runtime overrides are separate; gameplay remains unverified.';const form=document.createElement('form'),rows=document.createElement('div');rows.style.overflowX='auto';const table=document.createElement('table');table.style.width='100%';rows.append(table);form.append(rows);const header=document.createElement('tr');for(const label of ['Tier','Retail MAN','Current MAN','Draft MAN','Draft reference Y']){const th=document.createElement('th');th.textContent=label;header.append(th);}table.append(header);
  const review=document.createElement('button');review.dataset.review='';review.textContent='Review floor heights';form.append(review);const resets=document.createElement('div');const status=document.createElement('p');status.setAttribute('role','status');status.textContent='Loading source-qualified Current heights…';const actions=document.createElement('div');actions.className='dialog-actions';const inspect=document.createElement('button');inspect.type='button';inspect.dataset.scene='';inspect.textContent='Inspect proposed height scene';const apply=document.createElement('button');apply.type='button';apply.dataset.apply='';apply.textContent='Apply floor heights';const close=document.createElement('button');close.type='button';close.textContent='Cancel';close.onclick=()=>active.close();actions.append(inspect,apply,close);active.append(heading,description,form,resets,status,actions);document.body.append(active);active.addEventListener('close',()=>{if(retained){retained=false;return;}if(dialog===active)restore();});active.showModal();
  let baseline=null;const updateY=()=>{for(const input of active.querySelectorAll('[data-height-tier]')){const v=input.value.trim()===''?NaN:Number(input.value);input.closest('tr').querySelector('[data-reference-y]').textContent=integer(v,-32768,32767)?String(-v):'Invalid';}};
  form.oninput=()=>{withdraw();updateY();status.textContent='Height draft changed; fresh Review required.';refresh();};
  for(const [label,layer] of [['Restore retail heights','retail'],['Discard height draft','current']]){const button=document.createElement('button');button.type='button';button.dataset.reset='';button.textContent=label;resets.append(button);button.onclick=()=>{if(busy()||!current()||!baseline)return;withdraw();for(const input of active.querySelectorAll('[data-height-tier]'))input.value=baseline[layer][Number(input.dataset.heightTier)];updateY();status.textContent='Height draft reset; fresh Review required.';refresh();};}
  async function read(route,body,asked,initial=false){withdraw();const token=++generation,owned=new AbortController();controller=owned;setBusy(true);refresh();try{const response=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:owned.signal}),value=await response.json();if(!response.ok||value.error)throw Error(value.error||'Height Review failed');if(dialog!==active||!active.open||generation!==token||!current()||!initial&&JSON.stringify(request())!==JSON.stringify(asked))return;const report=decodeFloorHeights(value,context.key,context.scene,initial?value.current:asked);
    if(initial){baseline=report;for(let tier=0;tier<16;tier++){const tr=document.createElement('tr');for(const v of [tier,report.retail[tier],report.current[tier]]){const td=document.createElement('td');td.textContent=v;tr.append(td);}const cell=document.createElement('td'),input=document.createElement('input');input.type='number';input.required=true;input.min=-32768;input.max=32767;input.step=1;input.value=report.current[tier];input.dataset.heightTier=tier;input.style.width='105px';input.setAttribute('aria-label',`MAN height tier ${tier}`);cell.append(input);tr.append(cell);const y=document.createElement('td');y.dataset.referenceY='';tr.append(y);table.append(tr);}updateY();status.textContent='Current source heights loaded. Edit the draft, then Review; nothing applied.';}else{reviewed=report;status.textContent=`${report.effective_change_count} Current tier changes · ${report.value.edits.length} total authored heights. Scene-wide reference heights; nothing applied.`;}
   }catch(e){if(e.name!=='AbortError'&&dialog===active&&generation===token)status.textContent=e.message;}finally{if(controller===owned){controller=null;setBusy(false);}refresh();}}
  form.onsubmit=event=>{event.preventDefault();if(busy()||!current()||!form.reportValidity())return;let asked;try{asked=request();}catch(e){status.textContent=e.message;return;}read('/api/floor-height-review',{entity_id:context.scene,heights:asked},asked);};
  inspect.onclick=async()=>{if(busy()||!current()||!reviewed)return;const report=reviewed,token=++generation,owned=new AbortController();controller=owned;setBusy(true);refresh();const valid=()=>dialog===active&&binding===context&&current()&&reviewed===report&&generation===token;try{await onScene({entity_id:context.scene,heights:report.proposed,review_key:report.review_key},report,{signal:owned.signal,isCurrent:valid,returnToEditor:()=>{if(valid()&&!active.open)active.showModal();refresh();}});if(!valid())return;retained=true;active.close();}catch(e){if(e.name!=='AbortError'&&dialog===active&&generation===token)status.textContent=e.message;}finally{if(controller===owned){controller=null;setBusy(false);}refresh();}};
  apply.onclick=async()=>{if(busy()||!current()||!reviewed?.project_change)return;const report=reviewed;if(await api('/api/command',{type:'apply_floor_heights',entity_id:context.scene,heights:report.proposed,review_key:report.review_key}))restore();else{withdraw();status.textContent='Height Apply rejected; fresh Review required.';refresh();}};
  await read('/api/floor-height-context',{entity_id:context.scene},null,true);
 }
 launch.onclick=()=>open();refresh();return {open,restore,refresh};
}
