const canonical=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x),equal=(a,b)=>canonical(a)===canonical(b);
const valid=v=>v&&Object.keys(v).join()==='duration_ticks'&&Number.isInteger(v.duration_ticks)&&v.duration_ticks>=0&&v.duration_ticks<=32767;
export function decodeNpcWaitSource(value,id,state){
 const draft=state.actor_drafts?.[id],options=value?.options;
 if(!draft||draft.scene_id!==state.scene?.id||value?.schema_version!=='legaia.npc-waits-source.v1'||value.entity_id!==id||value.scene_id!==draft.scene_id||value.project_source_key!==state.project_copy_source_key||!equal(value.draft,draft)||value.gameplay_verified!==false||value.runtime_scheduling!=='not_asserted'||!Array.isArray(options?.targets)||options.targets.length>1024||options.supported!==!!options.targets.length)throw new Error('NPC wait source changed.');
 const seen=new Set();for(const row of options.targets){if(row.owner_id!==draft.donor_entity_id||row.semantic_id!==`script://${draft.donor_entity_id.slice(8)}/wait/${row.pc.toString(16).padStart(4,'0')}`||!Number.isInteger(row.pc)||row.pc<0||row.pc>65535||seen.has(row.semantic_id)||row.mnemonic!=='WAIT_FRAMES'||!valid(row.values)||!equal(row.authored_values,draft.waits?.entries?.[row.semantic_id]??null)||!equal(row.effective_values,row.authored_values??row.values)||!/^[a-f0-9]{64}$/.test(row.source_record_sha256??''))throw new Error('NPC wait target differs from its source or owner.');seen.add(row.semantic_id);}return structuredClone(value);
}
export function decodeNpcWaitReview(value,request,source,state){
 const draft=state.actor_drafts?.[request.entity_id],proposed=structuredClone(draft);
 for(const [id,fields] of Object.entries(request.entries))if(!valid(fields)||!source.options.targets.some(r=>r.semantic_id===id))throw new Error('NPC wait requires a qualified integer target.');
 if(Object.keys(request.entries).length)proposed.waits={donor_entity_id:draft.donor_entity_id,entries:structuredClone(request.entries)};else delete proposed.waits;
 if(value?.schema_version!=='legaia.npc-waits-review.v1'||value.entity_id!==request.entity_id||value.project_source_key!==state.project_copy_source_key||value.project_source_key!==source.project_source_key||!equal(value.request,request)||!equal(value.current,draft)||!equal(value.proposed,proposed)||!/^[a-f0-9]{64}$/.test(value.review_key??'')||value.gameplay_verified!==false||value.runtime_scheduling!=='not_asserted')throw new Error('NPC wait review differs from the requested edit.');return structuredClone(value);
}
export function openNpcWaits({entityId,getState,isBusy,canEdit,api,focusPc,onReturn,onApplied}){
  if(isBusy()||!canEdit())return;const state=getState(),key=state.project_copy_source_key,dialog=document.createElement('dialog');dialog.id='npc-waits-dialog';dialog.innerHTML='<h2>Edit NPC waits</h2><p class="field-note">Wait targets belong to this NPC only. Retail donor operands stay unchanged. Ticks are encoded targets, not seconds; runtime scheduling remains unverified.</p><p data-status role="status">Verifying donor wait targets...</p><form><div data-runs></div><div class="dialog-actions"><button data-review>Review NPC waits</button><button type="button" data-apply>Apply NPC waits</button><button type="button" data-close>Close NPC waits</button></div></form>';dialog.querySelector('.dialog-actions').style.flexWrap='wrap';document.body.append(dialog);dialog.showModal();let source=null,proposal=null,pending=true,generation=0,controller=new AbortController();
  const current=()=>dialog.open&&canEdit()&&getState().project_copy_source_key===key;
  const update=()=>{for(const c of dialog.querySelectorAll('input,button'))if(!c.matches('[data-close]'))c.disabled=pending||isBusy()||!current();dialog.querySelector('[data-review]').disabled=isBusy()||pending||!current()||!source;dialog.querySelector('[data-apply]').disabled=isBusy()||pending||!current()||!proposal||equal(proposal.current,proposal.proposed);};
  if(typeof onReturn==='function'){const back=document.createElement('button');back.type='button';back.textContent='Return to Current NPC script';back.onclick=()=>{if(pending||isBusy()||!current()||!source)return;dialog.close();onReturn();};dialog.querySelector('.dialog-actions').append(back);}
  const timer=setInterval(update,300);
  dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{generation++;controller.abort();clearInterval(timer);dialog.remove();});update();
  const post=async(route,body)=>{const r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal}),v=await r.json();if(!r.ok)throw new Error(v.error??'NPC waits rejected.');return v;};
  const ready=(async()=>{try{const value=await post('/api/npc-waits-source',{entity_id:entityId});if(!current())return;source=decodeNpcWaitSource(value,entityId,getState());for(const run of source.options.targets){const section=document.createElement('section'),label=document.createElement('label'),input=document.createElement('input'),toggle=document.createElement('input'),retail=document.createElement('p');label.textContent=`Own wait at 0x${run.pc.toString(16)} (ticks 0..32767)`;input.type='number';input.min='0';input.max='32767';input.step='1';input.value=String(run.effective_values.duration_ticks);input.dataset.run=run.semantic_id;input.setAttribute('aria-label',`NPC wait ticks at 0x${run.pc.toString(16)}`);toggle.type='checkbox';toggle.checked=run.authored_values!==null;toggle.dataset.enable=run.semantic_id;toggle.style.width='auto';label.append(toggle,input);retail.className='field-note';retail.textContent='Retail target: '+run.values.duration_ticks;section.dataset.npcOperandPc=run.pc;section.append(label,retail);if(run.pc===focusPc){section.tabIndex=-1;section.style.outline='2px solid currentColor';}dialog.querySelector('[data-runs]').append(section);for(const control of [input,toggle])control.oninput=()=>{proposal=null;dialog.querySelector('[data-status]').textContent='Review the edited targets before Apply.';update();};}dialog.querySelector('[data-status]').textContent=source.options.supported?`${source.options.targets.length} supported donor wait targets. Check Own wait to override; uncheck to restore the retail operand.`:source.options.reason??'No supported wait targets.';}catch(e){if(dialog.open&&!controller.signal.aborted)dialog.querySelector('[data-status]').textContent=e.message;}finally{pending=false;if(dialog.open){update();if(Number.isSafeInteger(focusPc))dialog.querySelector('[data-npc-operand-pc="'+focusPc+'"]')?.focus();}}})();
  dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(isBusy()||!source||!current()||pending)return;const entries={};for(const input of dialog.querySelectorAll('[data-run]'))if([...dialog.querySelectorAll('[data-enable]')].find(c=>c.dataset.enable===input.dataset.run).checked)entries[input.dataset.run]={duration_ticks:input.value.trim()===''?NaN:Number(input.value)};const request={entity_id:entityId,entries},token=++generation;pending=true;proposal=null;update();try{const value=await post('/api/npc-waits-review',request);if(token!==generation||!current())return;proposal=decodeNpcWaitReview(value,request,source,getState());dialog.querySelector('[data-status]').textContent='Reviewed fixed-width NPC wait targets. Apply makes one Undo step; Save persists it and normal Build serializes the NPC record.';}catch(e){if(dialog.open)dialog.querySelector('[data-status]').textContent=e.message;}finally{if(token===generation){pending=false;if(dialog.open)update();}}};
  dialog.querySelector('[data-apply]').onclick=async()=>{if(isBusy()||!proposal||!current()||pending)return;const accepted=proposal;pending=true;update();if(await api('/api/command',{type:'set_actor_draft_waits',entity_id:entityId,entries:accepted.proposed.waits?.entries??{},review_key:accepted.review_key},{success:'NPC waits updated. Undo restores the previous targets.'})){dialog.close();if(typeof onApplied==='function')onApplied();}else{proposal=null;pending=false;dialog.querySelector('[data-status]').textContent='Apply rejected. Review again.';update();}};return {dialog,ready};
}
