const hash=value=>typeof value==='string'&&/^[0-9a-f]{64}$/.test(value);
const validRow=row=>row&&typeof row.section==='string'&&row.section.length>0&&(row.owner_id===null||typeof row.owner_id==='string')&&hash(row.record_key)&&typeof row.saved_present==='boolean'&&typeof row.current_present==='boolean'&&(row.saved_present||row.current_present)&&row.change===(row.saved_present&&row.current_present?'modified':row.current_present?'added':'removed');
export function decodeProjectChanges(value){
  if(value?.schema_version!=='legaia.project-changes.v1'||value.read_only!==true||!hash(value.source_key)||!hash(value.current_document_sha256)||typeof value.saved_snapshot_present!=='boolean'||(value.saved_snapshot_present?!hash(value.saved_document_sha256):value.saved_document_sha256!==null)||typeof value.dirty!=='boolean'||value.page_size!==50||!Number.isSafeInteger(value.total)||value.total<0||value.total>16384||!Number.isSafeInteger(value.offset)||value.offset<0||value.offset>value.total||!Array.isArray(value.records)||value.records.length!==Math.min(50,value.total-value.offset)||value.next_offset!==(value.offset+value.records.length<value.total?value.offset+value.records.length:null))throw new Error('Invalid saved/current project review');
  if(value.dirty!==(value.saved_document_sha256!==value.current_document_sha256)||(value.total>0)!==value.dirty)throw new Error('Project change summary contradicts its document identities');
  const seen=new Set();for(const row of value.records){const id=JSON.stringify([row.section,row.owner_id]);if(!validRow(row)||seen.has(id))throw new Error('Invalid project change record');seen.add(id);}return structuredClone(value);
}
export function decodeProjectChange(value,report,row){
  if(value?.schema_version!=='legaia.project-change-record.v1'||value.read_only!==true||value.source_key!==report.source_key||!validRow(value)||['section','owner_id','record_key','change','saved_present','current_present'].some(k=>value[k]!==row[k])||!Object.hasOwn(value,'saved')||!Object.hasOwn(value,'current')||!value.saved_present&&value.saved!==null||!value.current_present&&value.current!==null)throw new Error('Invalid or stale saved/current metadata detail');return structuredClone(value);
}
export function openProjectChanges({save}){
  const dialog=document.createElement('dialog');dialog.id='project-changes-dialog';dialog.style.width='min(900px, calc(100vw - 32px))';dialog.style.maxHeight='92vh';
  const title=document.createElement('h2');title.textContent='Review Unsaved Project Changes';
  const note=document.createElement('p');note.textContent='Compare project metadata with this session’s last Save/Open snapshot. Imported payloads and runtime state are not compared. Save reviewed changes saves all current project metadata, including changes on other pages.';
  const actions=document.createElement('div');actions.className='dialog-actions';actions.style.flexWrap='wrap';const status=document.createElement('p'),error=document.createElement('p'),list=document.createElement('div'),details=document.createElement('div');error.className='dialog-error';error.setAttribute('role','alert');list.style.cssText='max-height:22vh;overflow:auto';details.style.cssText='display:flex;flex-wrap:wrap;gap:12px';
  let report=null,pending=false,generation=0;
  const button=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;actions.append(b);return b;};
  const request=async(path,body)=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||result.error)throw new Error(typeof result.error==='string'?result.error:'Project change review failed');return result;};
  const run=async fn=>{if(pending)return;pending=true;const token=++generation;for(const b of [...actions.querySelectorAll('button'),...list.querySelectorAll('button')])b.disabled=true;error.textContent='';try{await fn(token);}catch(exc){if(dialog.open&&token===generation){error.textContent=exc.message;details.replaceChildren();}}finally{pending=false;if(dialog.open&&token===generation){refresh.disabled=false;close.disabled=false;previous.disabled=!report||report.offset===0;next.disabled=!report||report.next_offset===null;saveButton.disabled=!report?.dirty;for(const b of list.querySelectorAll('button'))b.disabled=false;}}};
  const load=offset=>run(async token=>{const value=decodeProjectChanges(await request('/api/project/change-review',{offset}));if(!dialog.open||token!==generation)return;report=value;list.replaceChildren();details.replaceChildren();status.textContent=`${value.total} changed metadata records; showing ${value.records.length?value.offset+1:0}–${value.offset+value.records.length}. ${value.saved_snapshot_present?'Compared with last Save/Open.':'No saved snapshot yet.'}`;
    for(const row of value.records){const b=document.createElement('button');b.style.cssText='display:block;width:100%;text-align:left;margin:4px 0;overflow-wrap:anywhere;white-space:normal';b.textContent=`${row.change[0].toUpperCase()+row.change.slice(1)} · ${row.section}${row.owner_id===null?'':' · '+row.owner_id}`;b.onclick=()=>run(async detailToken=>{const value=decodeProjectChange(await request('/api/project/change-inspect',{source_key:report.source_key,section:row.section,owner_id:row.owner_id,record_key:row.record_key}),report,row);if(!dialog.open||detailToken!==generation)return;details.replaceChildren();for(const side of ['saved','current']){const section=document.createElement('section');section.dataset.side=side;section.style.cssText='flex:1 1 240px;min-width:0';const heading=document.createElement('h3');heading.textContent=`${side==='saved'?'Saved':'Current'} · ${value[side+'_present']?'Present':'Missing'}`;const pre=document.createElement('pre');pre.style.cssText='max-height:26vh;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere';pre.textContent=value[side+'_present']?JSON.stringify(value[side],null,2):'No value';section.append(heading,pre);details.append(section);}});list.append(b);}
  });
  const refresh=button('Refresh',()=>load(0)),previous=button('Previous page',()=>load(Math.max(0,report.offset-50))),next=button('Next page',()=>load(report.next_offset)),saveButton=button('Save reviewed changes',()=>run(async()=>{if(report?.dirty)await save(report.source_key,dialog);})),close=button('Close',()=>dialog.close());
  dialog.append(title,note,actions,status,error,list,details);dialog.addEventListener('close',()=>{generation++;dialog.remove();},{once:true});document.body.append(dialog);dialog.showModal();load(0);
}
