const hash=value=>typeof value==='string'&&/^[0-9a-f]{64}$/.test(value);
function inventory(value){
  if(!Array.isArray(value)||!value.length||value.length>512)throw new Error('Invalid project input inventory');
  const seen=new Set();let total=0;
  for(const row of value){if(!row||typeof row.path!=='string'||!(/^(project\.legaia\.json|Imported\/[0-9a-f]{64}\.json|Authored\/Textures\/[0-9a-f]{64}\.tim|Authored\/Models\/[0-9a-f]{64}\.tmd)$/.test(row.path))||seen.has(row.path)||!hash(row.sha256)||!Number.isSafeInteger(row.byte_length)||row.byte_length<0||row.byte_length>64*1024*1024)throw new Error('Invalid copied input identity');seen.add(row.path);total+=row.byte_length;}
  if(!seen.has('project.legaia.json')||total>256*1024*1024)throw new Error('Copied input inventory exceeds limit');return total;
}
export function decodeCopyReview(value,key,path){
  if(value?.schema_version!=='legaia.project-copy-review.v1'||value.project_source_key!==key||!hash(key)||!hash(value.review_key)||value.source_project!==path||typeof value.source_name!=='string'||typeof value.source_dirty!=='boolean'||!hash(value.source_authored_state_key)||!Number.isSafeInteger(value.imported_scene_count)||value.imported_scene_count<0||value.imported_scene_count>64||value.includes_unsaved_metadata!==true||value.retail_disc_included!==false||value.undo_history_included!==false||value.generated_outputs_included!==false||value.live_state_included!==false||value.file_count!==value.files?.length||value.byte_length!==inventory(value.files))throw new Error('Invalid or stale project copy review');return structuredClone(value);
}
export function copyRequest(review,name){
  if(typeof name!=='string'||/[\x00-\x1f\x7f\ud800-\udfff]/u.test(name)||Array.from(name.trim()).length<1||Array.from(name.trim()).length>120||!hash(review?.review_key))throw new Error('Copy name requires 1–120 valid Unicode characters without controls');return {name:name.trim(),review_key:review.review_key};
}
export function decodeCreatedCopy(value,key,path){
  const prefix=path.replaceAll('\\','/')+'/ProjectCopies/project-',destination=value?.copied_project?.replaceAll('\\','/');
  if(value?.schema_version!=='legaia.project-copy.v1'||!hash(key)||value.project_source_key!==key||value.source_project!==path||!hash(value.source_review_key)||!hash(value.source_authored_state_key)||typeof value.source_dirty!=='boolean'||!destination?.startsWith(prefix)||!/^[0-9a-f]{32}$/.test(destination.slice(prefix.length))||value.readback_verified!==true||value.reopened_metadata_verified!==true||value.retail_disc_included!==false||value.undo_history_included!==false||value.generated_outputs_included!==false||value.live_state_included!==false)throw new Error('Invalid project copy result');copyRequest({review_key:value.source_review_key},value.name);inventory(value.files);return structuredClone(value);
}
export function mountProjectCopy({after,getState,busy,setBusy,api}){
  const button=document.createElement('button');button.id='project-copy-button';button.textContent='Copy project…';button.disabled=true;after.after(button);
  button.onclick=async()=>{
    const initial=getState();if(busy()||!initial.capabilities?.project_copy)return;const root=initial.project.path,key=initial.project_copy_source_key,dialog=document.createElement('dialog');dialog.id='project-copy-dialog';dialog.className='project-dialog';
    const title=document.createElement('h2');title.textContent='Create editable project copy';const status=document.createElement('p');status.setAttribute('role','status');status.textContent='Capturing current inputs for review…';const summary=document.createElement('div'),form=document.createElement('form');form.hidden=true;
    const label=document.createElement('label');label.textContent='Copy name';const name=document.createElement('input');name.setAttribute('aria-label','Copy name');name.required=true;name.maxLength=240;name.value=Array.from(initial.project.name).slice(0,115).join('')+' copy';label.append(name);const create=document.createElement('button');create.type='submit';create.textContent='Create editable copy';form.append(label,create);
    const open=document.createElement('button');open.textContent='Open copy';open.hidden=true;const path=document.createElement('pre');path.style.overflowWrap='anywhere';path.style.whiteSpace='pre-wrap';const close=document.createElement('button');close.textContent='Close';close.onclick=()=>dialog.close();const controller=new AbortController();dialog.addEventListener('close',()=>{controller.abort();dialog.remove();});dialog.append(title,status,summary,form,path,open,close);document.body.append(dialog);dialog.showModal();let reviewed=null,created=null;
    const rootCurrent=()=>dialog.open&&getState().project.path===root&&getState().project.mode==='edit',current=()=>rootCurrent()&&getState().project_copy_source_key===key;
    const request=async(route,body)=>{if(!current())throw new Error('Source project changed. Reopen Copy project.');const response=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});const value=await response.json();if(!response.ok)throw new Error(value.error||'Project copy failed');if(!current())throw new Error('Source project changed. Reopen Copy project.');return value;};
    form.onsubmit=async event=>{event.preventDefault();if(busy()||!reviewed||created)return;setBusy(true);create.disabled=true;try{created=decodeCreatedCopy(await request('/api/project/copy',copyRequest(reviewed,name.value)),key,root);status.textContent='Editable copy created and reopened for validation. The original project remains active; its files, dirty state and undo history are preserved.';path.textContent=created.copied_project;form.hidden=true;open.hidden=false;}catch(error){if(dialog.open)status.textContent=`Copy failed: ${error.message}`;}finally{setBusy(false);create.disabled=false;}};
    open.onclick=async()=>{if(busy()||!created)return;if(!rootCurrent()){status.textContent='The active project changed. Use Open project with the saved copy path.';return;}if(getState().project.dirty){status.textContent='Save or Undo changes in the current project before opening the copy. The saved copy retains the captured inputs.';return;}if(await api('/api/project/open',{path:created.copied_project}))dialog.close();};
    setBusy(true);try{reviewed=decodeCopyReview(await request('/api/project/copy-review',{}),key,root);status.textContent=`${reviewed.file_count} captured input files · ${reviewed.byte_length.toLocaleString()} bytes${reviewed.source_dirty?' · includes unsaved metadata':''}`;const note=document.createElement('p');note.textContent='Copies imported evidence, authored changes, drafts, templates, saved views/selections and referenced authored model/texture files. Retail disc, generated outputs, live state and undo history are excluded. The original stays open.';summary.append(note);form.hidden=false;}catch(error){if(dialog.open)status.textContent=`Could not review inputs: ${error.message}`;}finally{setBusy(false);}
  };
}
