const finite=v=>typeof v==='number'&&Number.isFinite(v);
const xyz=p=>p&&['x','y','z'].every(a=>finite(p[a]));
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
/** Snap only to a corner of the depth-tested visible triangle, within CSS pixels. */
export function nearestSceneVertex(hit,vertices,triangle,matrix,project,click,radius=24){
 if(!hit||typeof hit.entity_id!=='string'||typeof hit.geometry_key!=='string'||!Number.isSafeInteger(hit.triangle_index)||hit.triangle_index<0||!Array.isArray(vertices)||vertices.length>100000||!Array.isArray(triangle)||triangle.length!==3||triangle.some(i=>!Number.isSafeInteger(i)||i<0||i>=vertices.length)||!Array.isArray(matrix)||matrix.length!==16||!matrix.every(finite)||!same(matrix.slice(12),[0,0,0,1])||!xyz({...click,z:0})||!finite(radius)||radius<=0||radius>64)throw Error('Invalid scene vertex measurement source.');
 let best=null;
 for(const index of [...new Set(triangle)].sort((a,b)=>a-b)){
  const row=vertices[index];if(!Array.isArray(row)||row.length!==3||!row.every(finite))throw Error('Invalid decoded vertex.');
  const position={x:matrix[0]*row[0]+matrix[1]*row[1]+matrix[2]*row[2]+matrix[3],y:matrix[4]*row[0]+matrix[5]*row[1]+matrix[6]*row[2]+matrix[7],z:matrix[8]*row[0]+matrix[9]*row[1]+matrix[10]*row[2]+matrix[11]};if(!xyz(position))throw Error('Nonfinite scene measurement point.');
  const screen=project(position);if(!screen)continue;const d=Math.hypot(screen.x-click.x,screen.y-click.y);if(!finite(d)||d>radius||best&&d>=best.pixel_distance)continue;
  best={...hit,vertex_index:index,decoded_model_position:[...row],display_position:position,model_to_display:[...matrix],pixel_distance:d,snap_radius_pixels:radius};
 }return best;
}
export function sceneMeasurement(context,a,b){
 if(!context||typeof context.project_path!=='string'||!context.project_path||typeof context.scene_id!=='string'||!context.scene_id.startsWith('scene://')||!/^([0-9a-f]{64})$/.test(context.source_key)||!a||!b||!xyz(a.display_position)||!xyz(b.display_position))throw Error('Measurement needs two Current scene vertices.');
 const delta=Object.fromEntries(['x','y','z'].map(axis=>[axis,b.display_position[axis]-a.display_position[axis]])),distance=Math.hypot(delta.x,delta.y,delta.z);if(!xyz(delta)||!finite(distance))throw Error('Measurement exceeds finite coordinates.');
 return structuredClone({schema_version:'legaia.scene-vertex-measurement.v1',read_only:true,context,endpoints:{a,b},display_delta_b_minus_a:delta,distance_display_units:distance,limitations:['Decoded model vertices and editor display coordinates; not raw guest memory or confirmed runtime actor coordinates.','Snap selects the nearest projected corner of the visible triangle within 24 CSS pixels.','The line is an editor overlay and can appear through scenery; distance is straight-line, not path or collision distance.','Instance transforms can contain derived preview heights or poses; native actor height remains unknown when absent.','No real-world unit scale or gameplay identity is inferred.']});
}
export function mountSceneRuler({after,getContext,available,busy,pickVertex,onDraw,notify}){
 const document=after.ownerDocument,button=document.createElement('button');button.id='scene-ruler-button';button.textContent='Measure mesh vertices';after.after(button);
 const bar=document.createElement('div');bar.id='scene-ruler-tools';bar.className='scene-ruler-tools';bar.hidden=true;after.parentElement.after(bar);
 bar.innerHTML='<strong>Scene vertex ruler · display only</strong><p>Pick two corners on visible Current geometry, within 24 screen pixels. Coordinates are decoded model and editor display space; runtime positions remain separate.</p><div class="ruler-actions"><button type="button" data-ruler-a>Pick A</button><button type="button" data-ruler-b>Pick B</button><button type="button" data-ruler-cancel>Cancel pick</button><button type="button" data-ruler-clear>Clear points</button><button type="button" data-ruler-download>Download measurement</button><button type="button" data-ruler-close>Close ruler</button></div><p data-ruler-status role="status"></p><pre data-ruler-report></pre>';
 let context=null,points={a:null,b:null},pending=null,loading=false,generation=0,rejectedContext=null;
 const key=()=>JSON.stringify(getContext()),status=bar.querySelector('[data-ruler-status]'),report=bar.querySelector('[data-ruler-report]');
 function clear(){generation++;points={a:null,b:null};pending=null;report.textContent='';}
 function update(){const current=key();if(context!==current){clear();context=current;rejectedContext=null;}button.disabled=loading||busy()||!available()||rejectedContext===current;if(button.disabled){pending=null;if(!available())clear();}button.classList.toggle('active',!bar.hidden);for(const action of ['a','b'])bar.querySelector('[data-ruler-'+action+']').disabled=button.disabled;bar.querySelector('[data-ruler-cancel]').disabled=!pending;bar.querySelector('[data-ruler-download]').disabled=button.disabled||!points.a||!points.b;status.textContent=rejectedContext===current?'Source changed. Refresh the Current scene before measuring.':pending?'Click a visible triangle near its vertex for '+pending.toUpperCase()+'. Drag to orbit; a drag does not pick.':points.a&&points.b?'Two source-qualified vertices. Distance uses editor display units.':points.a?'A captured. Pick B to measure.':points.b?'B captured. Pick A to measure.':'Pick A and B to measure; no project command is created.';if(points.a||points.b){const data=points.a&&points.b?sceneMeasurement(getContext(),points.a,points.b):null;if(data&&!pending)status.textContent='Distance '+Number(data.distance_display_units.toFixed(6))+' display units · B − A: '+Object.values(data.display_delta_b_minus_a).map(v=>Number(v.toFixed(6))).join(', ');report.textContent=['A','B'].filter(name=>points[name.toLowerCase()]).map(name=>{const row=points[name.toLowerCase()];return name+' · '+row.entity_id+' · decoded vertex '+row.vertex_index+'\nModel XYZ: '+row.decoded_model_position.join(', ')+'\nDisplay XYZ: '+['x','y','z'].map(a=>row.display_position[a]).join(', ');}).join('\n\n')+(data?'\n\nB − A: '+Object.values(data.display_delta_b_minus_a).join(', ')+'\nDistance: '+data.distance_display_units:'');}}
 button.onclick=()=>{update();if(button.disabled)return;bar.hidden=!bar.hidden;if(bar.hidden)clear();update();onDraw();};
 for(const name of ['a','b'])bar.querySelector('[data-ruler-'+name+']').onclick=()=>{update();if(button.disabled)return;pending=name;update();onDraw();};
 for(const action of ['clear','cancel','close'])bar.querySelector('[data-ruler-'+action+']').onclick=()=>{if(action==='cancel')pending=null;else clear();if(action==='close')bar.hidden=true;update();onDraw();};
 bar.querySelector('[data-ruler-download]').onclick=async()=>{update();if(bar.querySelector('[data-ruler-download]').disabled)return;const owned=key(),revision=generation,data=sceneMeasurement(getContext(),points.a,points.b);loading=true;update();try{const response=await fetch('/api/state'),state=await response.json();if(revision!==generation||owned!==key()||bar.hidden)return;if(!response.ok||state.error)throw Error(state.error||'Unable to verify Current measurement source.');if(state.project?.path!==data.context.project_path||state.scene?.id!==data.context.scene_id||state.scene_preview_source_key!==data.context.source_key){rejectedContext=owned;clear();throw Error('Measurement source changed. Refresh the Current scene before measuring.');}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='scene-vertex-measurement.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){if(revision===generation||rejectedContext===owned)notify(error.message,true);}finally{loading=false;update();}};
 document.addEventListener('keydown',event=>{if(event.key==='Escape'&&pending){pending=null;update();onDraw();}});
 return {bar,update,picking:()=>pending!==null,contextKey:key,pick(point,expectedContext){update();if(!pending||button.disabled||context!==expectedContext)return false;const hit=pickVertex(point);if(!hit){notify('No visible triangle corner within 24 pixels. Zoom in or choose a nearer vertex.');return false;}points[pending]=structuredClone(hit);generation++;pending=null;update();return true;},draw(ctx,project){update();if(bar.hidden)return;ctx.save();ctx.strokeStyle='#ffdb79';ctx.fillStyle='#ffdb79';ctx.lineWidth=2;const a=points.a&&project(points.a.display_position),b=points.b&&project(points.b.display_position);if(a&&b){ctx.setLineDash([6,4]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}for(const [name,p] of [['A',a],['B',b]])if(p){ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill();ctx.fillText(name,p.x+9,p.y-7);}ctx.restore();}};
}
