// Native allocation review; source context and every authoring choice stay bound.
const hash=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v);
const integer=(v,lo,hi)=>Number.isInteger(v)&&v>=lo&&v<=hi;
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const fail=message=>{throw new Error(message);};
const layoutKeys=['bpp','x','y','width','height','width_words'];
function layout(v){
  if(!exact(v,layoutKeys)||![4,8,16,24].includes(v.bpp)||!integer(v.x,0,1023)||!integer(v.y,0,511)||!integer(v.width,1,4096)||!integer(v.width_words,1,1024)||!integer(v.height,1,512)||v.width*v.bpp!==v.width_words*16||v.x+v.width_words>1024||v.y+v.height>512)fail('Texture allocation has invalid native dimensions or VRAM bounds.');
  return v;
}
const sameLayout=(a,b)=>layoutKeys.every(k=>a[k]===b[k]);
const area=(a,b)=>Math.max(0,Math.min(a.x+a.width_words,b.x+b.width_words)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));

export function decodeResizeSource(v,assetId,context){
  if(!exact(v,['schema_version','asset_id','project_source_key','retail_sha256','effective_sha256','current_layout','byte_length','palette_count','read_only','project_changed'])||v.schema_version!=='legaia.texture-resize-source.v1'||v.asset_id!==assetId||v.project_source_key!==context.sourceKey||!hash(v.retail_sha256)||!hash(v.effective_sha256)||!integer(v.byte_length,20,1048576)||!integer(v.palette_count,0,32768)||v.read_only!==true||v.project_changed!==false)fail('Resize source differs from the selected texture or current scene.');
  layout(v.current_layout);
  if(v.byte_length<20+v.current_layout.width_words*v.current_layout.height*2||![4,8].includes(v.current_layout.bpp)&&v.palette_count!==0)fail('Resize source length or palette count differs from its layout.');
  return structuredClone(v);
}

export function decodeResizeReview(v,request,source,applied=false){
  const keys=['schema_version','asset_id','project_source_key','retail_sha256','effective_sha256','proposed_sha256','width','height','fill_value','resize_mode','current_layout','proposed_layout','allocation','footprint','accept_potential_overlap','can_apply','project_changed','gameplay_verified','review_key'];
  if(!exact(v,keys)||v.schema_version!=='legaia.texture-resize-review.v1'||v.asset_id!==request.asset_id||v.project_source_key!==request.source_key||v.retail_sha256!==source.retail_sha256||v.effective_sha256!==request.expected_sha256||v.effective_sha256!==source.effective_sha256||!hash(v.proposed_sha256)||!hash(v.review_key)||v.width!==request.width||v.height!==request.height||v.fill_value!==request.fill_value||v.resize_mode!==(request.resize_mode??'crop-fill')||!['crop-fill','nearest'].includes(v.resize_mode)||v.resize_mode==='nearest'&&v.fill_value!==0||v.accept_potential_overlap!==request.accept_potential_overlap||typeof v.accept_potential_overlap!=='boolean'||v.project_changed!==applied||v.gameplay_verified!==false)fail('Resize review differs from the current source or authoring choices.');
  const before=layout(v.current_layout),after=layout(v.proposed_layout),a=v.allocation;
  if(!sameLayout(before,source.current_layout)||after.width!==v.width||after.height!==v.height||after.bpp!==before.bpp||after.x!==before.x||after.y!==before.y||!integer(v.fill_value,0,2**before.bpp-1))fail('Resize review changed mode, origin or current dimensions.');
  const changed=!sameLayout(before,after),delta=2*(after.width_words*after.height-before.width_words*before.height);
  if(!exact(a,['source_sha256','proposed_sha256','source_byte_length','proposed_byte_length','before','after','bpp','image_origin','changed','layout_changed','scope','gameplay_verified'])||a.source_sha256!==v.effective_sha256||a.proposed_sha256!==v.proposed_sha256||a.source_byte_length!==source.byte_length||a.proposed_byte_length!==source.byte_length+delta||!integer(a.proposed_byte_length,20,1048576)||a.bpp!==before.bpp||!exact(a.image_origin,['x','y'])||a.image_origin.x!==before.x||a.image_origin.y!==before.y||a.changed!==changed||a.layout_changed!==changed||a.scope!=='TIM-image-allocation-fixed-mode-and-VRAM-origin'||a.gameplay_verified!==false||(v.proposed_sha256===v.effective_sha256)!==!changed)fail('Resize allocation evidence contradicts its layouts or hashes.');
  for(const [row,want] of [[a.before,before],[a.after,after]])if(!exact(row,['width','height','width_words'])||['width','height','width_words'].some(k=>row[k]!==want[k]))fail('Resize allocation dimensions differ from the review.');
  const f=v.footprint;
  if(!exact(f,['schema_version','examined_upload_count','potential_overlap_count','rows','rows_truncated','coverage','runtime_residency_verified'])||f.schema_version!=='legaia.texture-footprint.v1'||!integer(f.examined_upload_count,0,65536)||!integer(f.potential_overlap_count,0,f.examined_upload_count)||!Array.isArray(f.rows)||f.rows.length!==Math.min(f.potential_overlap_count,64)||f.rows_truncated!==(f.potential_overlap_count>64)||f.coverage!=='known-static-scene-and-boot-uploads'||f.runtime_residency_verified!==false)fail('Resize footprint census has invalid coverage or counts.');
  const shared={...before,width_words:Math.min(before.width_words,after.width_words),height:Math.min(before.height,after.height)},seen=new Set();
  for(const row of f.rows){
    if(!exact(row,['asset_id','kind','boot_upload_index','rectangle','added_overlap_words'])||!['image','flattened-clut','boot-upload'].includes(row.kind)||!(row.kind==='boot-upload'?row.asset_id===null&&integer(row.boot_upload_index,0,65535):typeof row.asset_id==='string'&&row.asset_id.startsWith('texture://')&&row.asset_id.length<=512&&row.boot_upload_index===null)||!exact(row.rectangle,['x','y','width_words','height']))fail('Resize overlap identity differs from its upload kind.');
    const r=row.rectangle,key=JSON.stringify([row.asset_id,row.kind,row.boot_upload_index]);
    if(seen.has(key)||!integer(r.x,0,1023)||!integer(r.y,0,511)||!integer(r.width_words,1,524288)||!integer(r.height,1,512)||!integer(row.added_overlap_words,1,524288)||row.added_overlap_words!==area(after,r)-area(shared,r))fail('Resize overlap evidence contradicts its rectangles.');
    seen.add(key);
  }
  if(v.can_apply!==(changed&&(f.potential_overlap_count===0||v.accept_potential_overlap)))fail('Resize Apply status contradicts its allocation or overlap choice.');
  return structuredClone(v);
}

function png(value,want){
  if(typeof value!=='string'||value.length>11184812||value.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(value))fail('Resize preview has invalid bounded PNG bytes.');
  const bytes=Uint8Array.from(atob(value),c=>c.charCodeAt(0));
  if(bytes.length<33||bytes.length>8388608||![137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))fail('Resize preview is not a bounded PNG.');
  const view=new DataView(bytes.buffer);if(view.getUint32(8)!==13||view.getUint32(12)!==0x49484452||view.getUint32(16)!==want.width||view.getUint32(20)!==want.height)fail('Resize preview PNG dimensions differ from the reviewed layout.');
  return `data:image/png;base64,${value}`;
}
export function decodeResizePixels(v,review,request,source,paletteIndex){
  if(!exact(v,['report','palette_index','current_png_base64','proposed_png_base64'])||v.palette_index!==paletteIndex)fail('Resize pixel preview differs from the selected palette.');
  const qualified=decodeResizeReview(v.report,request,source);
  if(JSON.stringify(qualified)!==JSON.stringify(review))fail('Resize pixel preview differs from the reviewed proposal.');
  return {current:png(v.current_png_base64,review.current_layout),proposed:png(v.proposed_png_base64,review.proposed_layout)};
}

const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const button=text=>{const n=node('button',text);n.type='button';return n;};

export async function openTextureResizeEditor({assetId,paletteIndex,getContext,busy,setBusy,onApplied,onError=()=>{},canPreviewScene=()=>false,onScenePreview=null}){
  const context=structuredClone(getContext()),contextKey=JSON.stringify(context);
  if(context.mode!=='edit'||!hash(context.sourceKey)||typeof assetId!=='string'||!assetId.startsWith('texture://')||assetId.length>512||!integer(paletteIndex,0,32767))fail('Resize editing requires the selected texture in the current Edit scene.');
  const dialog=node('dialog');dialog.id='texture-resize-dialog';dialog.className='project-dialog';Object.assign(dialog.style,{width:'min(820px,94vw)',maxHeight:'92vh',overflowY:'auto',boxSizing:'border-box'});
  const heading=node('div');heading.className='dialog-heading';const close=button('×');close.setAttribute('aria-label','Close texture resize');heading.append(node('h2','Resize texture image'),close);
  const help=node('p','Choose crop and fill or nearest-neighbor scaling. Scaling copies encoded pixels without palette conversion. Pixel mode, palette layout and VRAM origin stay fixed. UVs remain unchanged.');
  const form=node('div');form.className='dialog-actions';Object.assign(form.style,{justifyContent:'flex-start',gap:'16px',marginTop:'16px'});const inputs={};
  for(const [key,label] of [['width','Width in pixels'],['height','Height in pixels'],['fill_value','Encoded fill value']]){const wrapper=node('label',label),input=node('input');input.type='number';input.step='1';input.min=key==='fill_value'?'0':'1';input.setAttribute('aria-label',label);Object.assign(wrapper.style,{flex:'1',minWidth:'0'});input.style.width='100%';wrapper.append(input);form.append(wrapper);inputs[key]=input;}
  const method=node('select');method.setAttribute('aria-label','Resize method');for(const [value,label] of [['crop-fill','Crop and fill'],['nearest','Scale with nearest neighbor']]){const option=node('option',label);option.value=value;method.append(option);}method.value='crop-fill';const methodLabel=node('label','Resize method');methodLabel.append(method);
  const overlap=node('input');overlap.type='checkbox';overlap.setAttribute('aria-label','Accept listed potential overlap');const choice=node('label','Accept the listed potential overlap for this edit');Object.assign(choice.style,{display:'flex',flexDirection:'row',alignItems:'center',justifyContent:'flex-start',gap:'8px',margin:'16px 0'});Object.assign(overlap.style,{width:'auto',margin:'0'});choice.prepend(overlap);
  const reviewButton=button('Review resize'),pixelButton=button('Inspect resized pixels'),sceneButton=button('Inspect resize in scene'),applyButton=button('Apply reviewed resize');const actions=node('div');actions.className='dialog-actions';actions.append(reviewButton,pixelButton,sceneButton,applyButton);
  const status=node('p','Verifying the current native texture…'),summary=node('section'),error=node('p');status.className='field-note';error.className='dialog-error';error.setAttribute('role','alert');
  dialog.append(heading,help,methodLabel,form,choice,actions,status,summary,error);document.body.append(dialog);
  let source=null,review=null,pending=null,controller=null,generation=0,owner=null,closed=false,suspended=false,pixelDialog=null;
  const contextCurrent=()=>!closed&&contextKey===JSON.stringify(getContext());
  const values=()=>Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value.trim()===''?NaN:Number(v.value)]));
  const request=()=>({asset_id:assetId,expected_sha256:source?.effective_sha256,source_key:context.sourceKey,...values(),resize_mode:method.value,accept_potential_overlap:overlap.checked});
  const requestValid=()=>{if(!source)return false;const v=values(),l=source.current_layout;return integer(v.width,1,4096)&&integer(v.height,1,512)&&integer(v.fill_value,0,2**l.bpp-1)&&integer(v.width*l.bpp/16,1,1024-l.x)&&v.height+l.y<=512;};
  const reviewedCurrent=()=>contextCurrent()&&review&&JSON.stringify(review.request)===JSON.stringify(request());
  function controls(){if(!closed&&!contextCurrent()){review=null;summary.replaceChildren();status.textContent='Project, scene, mode or source changed. Reopen resize editing.';}const blocked=!contextCurrent()||pending!==null||busy();for(const input of Object.values(inputs))input.disabled=blocked;method.disabled=blocked;inputs.fill_value.disabled=blocked||method.value==='nearest';overlap.disabled=blocked;reviewButton.disabled=blocked||!requestValid();pixelButton.disabled=blocked||!reviewedCurrent();sceneButton.disabled=blocked||!reviewedCurrent()||!onScenePreview||!canPreviewScene();applyButton.disabled=blocked||!reviewedCurrent()||!review.report.can_apply;close.disabled=pending==='apply';}
  function release(token){if(token&&owner===token){owner=null;setBusy(false);}}
  function invalidate(){generation++;controller?.abort();controller=null;pending=null;release(owner);review=null;summary.replaceChildren();if(pixelDialog?.open)pixelDialog.close();controls();}
  function dispose(){if(closed)return;closed=true;invalidate();pixelDialog?.remove();dialog.remove();}
  for(const input of [...Object.values(inputs),overlap])input.oninput=()=>{invalidate();status.textContent='Choices changed. Review the resize again before inspection or Apply.';error.textContent='';};
  method.onchange=()=>{if(method.value==='nearest')inputs.fill_value.value=0;invalidate();status.textContent='Resize method changed. Review again before inspection or Apply.';error.textContent='';};
  async function post(route,body,signal,maximum=1048576){const response=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});const text=await response.text();if(new TextEncoder().encode(text).length>maximum)fail('Resize response exceeds its inspection budget.');const result=JSON.parse(text);if(!response.ok||result.error)fail(result.error||'Texture resize request failed.');return result;}
  async function run(kind,work){if(!contextCurrent()||!dialog.open||pending||busy())return false;const token={},ticket=++generation;owner=token;pending=kind;controller=new AbortController();const signal=controller.signal;setBusy(true);error.textContent='';controls();const valid=()=>contextCurrent()&&generation===ticket&&!signal.aborted;try{return await work(signal,valid);}catch(e){if(valid()&&e.name!=='AbortError'){review=null;summary.replaceChildren();error.textContent=e.message;onError(e);}return false;}finally{release(token);if(generation===ticket){pending=null;controller=null;controls();}}}
  function showReview(report){summary.replaceChildren();const old=report.current_layout,next=report.proposed_layout,shared=Math.min(old.width,next.width)*Math.min(old.height,next.height),f=report.footprint;
    summary.append(node('h3','Reviewed resize · not applied'),node('p',report.resize_mode==='nearest'?'Nearest-neighbor scaling · encoded source pixels copied at destination pixel centers':'Crop and fill · top-left overlap retained'),node('p',`${old.width} × ${old.height} → ${next.width} × ${next.height} pixels · ${old.bpp} bpp · ${next.width*next.height-shared} added · ${old.width*old.height-shared} removed`),node('p',`${report.allocation.source_byte_length} → ${report.allocation.proposed_byte_length} native bytes · VRAM origin (${old.x}, ${old.y}) unchanged`),node('p',`${f.potential_overlap_count} potential overlaps added across ${f.examined_upload_count} known uploads. Runtime residency and upload order are unverified.`));
    if(f.rows.length){const details=node('details'),pre=node('pre');details.append(node('summary','Known added overlaps'));pre.style.overflowWrap='anywhere';pre.textContent=f.rows.map(r=>`${r.asset_id??`Boot upload ${r.boot_upload_index}`} · ${r.kind} · ${r.added_overlap_words} added VRAM words`).join('\n')+(f.rows_truncated?'\nDetail limited to 64 overlaps; counts are complete.':'');details.append(pre);summary.append(details);}
    const details=node('details'),pre=node('pre',JSON.stringify({retail:report.retail_sha256,current:report.effective_sha256,proposed:report.proposed_sha256,review:report.review_key},null,2));pre.style.overflowWrap='anywhere';details.append(node('summary','Source hashes and review'),pre);summary.append(details);
    status.textContent=report.can_apply?'Review complete. Inspect the proposal or explicitly Apply, then Save project.':report.allocation.changed?'The new footprint overlaps known uploads. Accept that choice and review again to enable Apply.':'No change to the current image dimensions.';
  }
  reviewButton.onclick=()=>{if(reviewButton.disabled)return;review=null;summary.replaceChildren();const body=request();return run('review',async(signal,valid)=>{const result=await post('/api/texture-resize-preview',body,signal);if(!valid()||JSON.stringify(body)!==JSON.stringify(request()))return false;review={request:body,report:decodeResizeReview(result,body,source)};showReview(review.report);return true;});};
  pixelButton.onclick=()=>{if(pixelButton.disabled)return;const accepted=review;return run('pixels',async(signal,valid)=>{const result=await post('/api/texture-resize-pixels-preview',{...accepted.request,review_key:accepted.report.review_key,palette_index:paletteIndex},signal,24*1024*1024);if(!valid()||review!==accepted)return false;const images=decodeResizePixels(result,accepted.report,accepted.request,source,paletteIndex);pixelDialog=node('dialog');pixelDialog.id='texture-resize-pixels-dialog';Object.assign(pixelDialog.style,{width:'min(1100px,94vw)',maxHeight:'92vh',overflowY:'auto'});const grid=node('div');Object.assign(grid.style,{display:'flex',gap:'20px',flexWrap:'wrap'});for(const [kind,label] of [['current','Current'],['proposed','Proposed · not applied']]){const l=accepted.report[kind==='current'?'current_layout':'proposed_layout'],figure=node('figure'),img=node('img');figure.style.flex='1 1 280px';figure.style.margin='0';figure.append(node('figcaption',`${label} · ${l.width} × ${l.height}`));img.src=images[kind];img.alt=`${label} resized texture pixels`;img.style.maxWidth='100%';img.style.imageRendering='pixelated';figure.append(img);grid.append(figure);}const back=button('Return to resize review');back.onclick=()=>pixelDialog.close();pixelDialog.append(node('h2','Resize pixel comparison'),node('p','Palette selection is for inspection. Transparent-zero alpha is shown; PSX STP blending and runtime appearance remain unverified.'),grid,back);document.body.append(pixelDialog);pixelDialog.onclose=()=>{pixelDialog.remove();pixelDialog=null;};pixelDialog.showModal();return true;});};
  sceneButton.onclick=()=>{if(sceneButton.disabled)return;const accepted=review;return run('scene',async(signal,valid)=>{const returnToEditor=()=>{if(!contextCurrent()||review!==accepted||!reviewedCurrent())return false;suspended=false;if(!dialog.open)dialog.showModal();controls();return true;};await onScenePreview({...accepted.request,review_key:accepted.report.review_key},accepted.report,{returnToEditor,isCurrent:()=>valid()&&review===accepted,signal});if(!valid()||review!==accepted)return false;suspended=true;dialog.close();return true;});};
  applyButton.onclick=()=>{if(applyButton.disabled)return;const accepted=review;return run('apply',async(signal,valid)=>{const next=await post('/api/texture-resize',{...accepted.request,review_key:accepted.report.review_key},signal,16*1024*1024);if(!valid()||review!==accepted)return false;const report=decodeResizeReview(next.resize_report,accepted.request,source,true);if(report.review_key!==accepted.report.review_key||next.project?.path!==context.projectPath||next.project?.mode!=='edit'||next.scene?.id!==context.sceneId)fail('Resize Apply returned another project, scene or review.');await onApplied(next);dispose();return true;});};
  close.onclick=()=>{if(pending!=='apply')dispose();};dialog.oncancel=e=>{e.preventDefault();if(pending!=='apply')dispose();};dialog.onclose=()=>{if(!suspended)dispose();};dialog.showModal();controls();
  await run('source',async(signal,valid)=>{const result=await post('/api/texture-resize-source',{asset_id:assetId,source_key:context.sourceKey},signal);if(!valid())return false;source=decodeResizeSource(result,assetId,context);const l=source.current_layout;inputs.width.value=l.width;inputs.height.value=l.height;inputs.fill_value.value=0;inputs.width.max=Math.floor((1024-l.x)*16/l.bpp);inputs.height.max=512-l.y;inputs.fill_value.max=2**l.bpp-1;status.textContent=`Current image ${l.width} × ${l.height} · ${l.bpp} bpp. ${l.bpp<=8?'Fill is an existing palette index.':l.bpp===16?'Fill is an encoded PSX16 word.':'Fill is encoded RGB24 (R in the low byte).'} Width must contain whole native words.`;return true;});
  return {dialog,dispose,update:controls};
}
