const hash=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v);
const integer=(v,a,b)=>Number.isInteger(v)&&v>=a&&v<=b;
const fail=m=>{throw new Error(m);};
const authored=v=>typeof v==='string'&&/^texture-new:\/\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v);
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));

export function decodeSlotReview(v,request,file,applied=false){
  const keys=['schema_version','project_source_key','source_scene_id','anchor_asset_id','source_pack_sha256','source_slot_count','pack_entry_index','pack_descriptor_index','slot_index','proposed_sha256','byte_length','label','image_layout','allocation','footprint','accept_potential_overlap','can_apply','project_changed','gameplay_verified','palette_count','review_key'];
  if(applied)keys.push('asset_id');
  if(!exact(v,keys)||v.schema_version!=='legaia.texture-slot-review.v1'||v.project_source_key!==request.source_key||v.anchor_asset_id!==request.anchor_asset_id||!hash(v.source_pack_sha256)||!hash(v.review_key)||v.proposed_sha256!==file.sha256||v.byte_length!==file.size||v.label!==request.label||v.accept_potential_overlap!==request.accept_potential_overlap||typeof v.accept_potential_overlap!=='boolean'||v.project_changed!==applied||v.gameplay_verified!==false||!integer(v.source_slot_count,1,1023)||!integer(v.slot_index,v.source_slot_count,1023)||!integer(v.pack_entry_index,0,65535)||!integer(v.pack_descriptor_index,-1,1023)||!integer(v.palette_count,0,32768)||applied&&!authored(v.asset_id))fail('New texture review differs from the file, source or choices.');
  const l=v.image_layout,a=v.allocation,f=v.footprint;
  if(!exact(l,['bpp','x','y','width','height','width_words'])||![4,8,16,24].includes(l.bpp)||!integer(l.x,0,1023)||!integer(l.y,0,511)||!integer(l.width,1,4096)||!integer(l.width_words,1,1024)||!integer(l.height,1,512)||l.width*l.bpp!==l.width_words*16||l.x+l.width_words>1024||l.y+l.height>512||![4,8].includes(l.bpp)&&v.palette_count!==0||v.byte_length<20+l.width_words*l.height*2)fail('New texture review has invalid native dimensions or palette count.');
  if(!a||a.schema_version!=='legaia.texture-pack-slot-allocation.v1'||a.source_sha256!==v.source_pack_sha256||a.source_slot_count!==v.source_slot_count||a.slot_count!==v.slot_index+1||a.standalone!==(v.pack_descriptor_index===-1)||a.native_members_verified!==true||a.opaque_tails_preserved!==true||a.gameplay_verified!==false||!hash(a.proposed_sha256)||!integer(a.proposed_byte_length,1,8388608)||!Array.isArray(a.added_slot_indices)||JSON.stringify(a.added_slot_indices)!==JSON.stringify(Array.from({length:v.slot_index-v.source_slot_count+1},(_,i)=>v.source_slot_count+i))||!Array.isArray(a.members)||a.members.length!==a.slot_count)fail('New texture allocation contradicts its slot identity.');
  const last=a.members.at(-1);if(last.slot_index!==v.slot_index||last.added!==true||last.tim_sha256!==file.sha256||last.tim_byte_length!==file.size)fail('New texture allocation differs from the selected complete TIM.');
  if(!exact(f,['potential_overlap_count','rows','rows_truncated','coverage','runtime_residency_verified'])||!integer(f.potential_overlap_count,0,65536)||!Array.isArray(f.rows)||f.rows.length!==Math.min(f.potential_overlap_count,64)||f.rows_truncated!==(f.potential_overlap_count>64)||f.coverage!=='known-static-scene-authored-and-boot-uploads'||f.runtime_residency_verified!==false)fail('New texture overlap census is malformed.');
  for(const r of f.rows){const t=r.rectangle;if(!exact(r,['asset_id','kind','proposed_kind','overlap_words','rectangle'])||!(r.asset_id===null||typeof r.asset_id==='string'&&(r.asset_id.startsWith('texture://')||authored(r.asset_id)))||!['image','flattened-clut','boot-upload','proposed-clut'].includes(r.kind)||!['image','flattened-clut'].includes(r.proposed_kind)||!integer(r.overlap_words,1,524288)||!exact(t,['x','y','width_words','height'])||!integer(t.x,0,1023)||!integer(t.y,0,511)||!integer(t.width_words,1,524288)||!integer(t.height,1,512))fail('New texture overlap row is malformed.');}
  if(v.can_apply!==(f.potential_overlap_count===0||v.accept_potential_overlap))fail('New texture Apply status contradicts the overlap choice.');
  return structuredClone(v);
}

export function decodeSlotPixels(v,review,request,file,paletteIndex){
  if(!exact(v,['report','palette_index','proposed_png_base64'])||v.palette_index!==paletteIndex||!integer(paletteIndex,0,Math.max(1,review.palette_count)-1))fail('New texture pixels differ from the selected palette.');
  const qualified=decodeSlotReview(v.report,request,file);if(JSON.stringify(qualified)!==JSON.stringify(review))fail('New texture pixels differ from the reviewed proposal.');
  const encoded=v.proposed_png_base64;if(typeof encoded!=='string'||encoded.length>11184812||encoded.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))fail('New texture PNG is malformed or exceeds its budget.');
  const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),view=new DataView(bytes.buffer);
  if(bytes.length<33||bytes.length>8388608||![137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n)||view.getUint32(8)!==13||view.getUint32(12)!==0x49484452||view.getUint32(16)!==review.image_layout.width||view.getUint32(20)!==review.image_layout.height)fail('New texture PNG dimensions differ from the reviewed TIM.');
  return `data:image/png;base64,${encoded}`;
}

const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const button=text=>{const n=node('button',text);n.type='button';return n;};
export function openTextureSlotEditor({assetId,getContext,busy,setBusy,onApplied,onError=()=>{}}){
  const context=structuredClone(getContext()),contextKey=JSON.stringify(context);
  if(context.mode!=='edit'||!hash(context.sourceKey)||typeof assetId!=='string'||!assetId.startsWith('texture://'))fail('New texture import requires a selected Retail pack in Edit mode.');
  const dialog=node('dialog');dialog.id='texture-slot-dialog';dialog.className='project-dialog';Object.assign(dialog.style,{width:'min(820px,94vw)',maxHeight:'92vh',overflowY:'auto',boxSizing:'border-box'});
  const heading=node('div');heading.className='dialog-heading';const close=button('×');close.setAttribute('aria-label','Close new texture import');heading.append(node('h2','Import new texture slot'),close);
  const help=node('p','Append a complete TIM to the selected texture pack. Its native image and palette coordinates determine placement. Existing slots keep their indices. Review placement and Proposed pixels before Apply.');
  const file=node('input');file.type='file';file.accept='.tim';file.setAttribute('aria-label','New texture TIM file');const fileLabel=node('label','Complete TIM · up to 1 MiB');fileLabel.append(file);
  const label=node('input');label.type='text';label.maxLength=128;label.setAttribute('aria-label','New texture name');const nameLabel=node('label','Texture name');nameLabel.append(label);
  const palette=node('input');palette.type='number';palette.min='0';palette.max='32767';palette.step='1';palette.value='0';palette.setAttribute('aria-label','New texture inspection palette');const paletteLabel=node('label','Inspection palette');paletteLabel.append(palette);
  const overlap=node('input');overlap.type='checkbox';overlap.setAttribute('aria-label','Accept new texture potential overlaps');const choice=node('label','Accept the listed potential overlaps for this import');Object.assign(choice.style,{display:'flex',flexDirection:'row',gap:'8px',alignItems:'center',margin:'16px 0'});overlap.style.width='auto';choice.prepend(overlap);
  const reviewButton=button('Review new texture'),pixelsButton=button('Inspect proposed texture pixels'),applyButton=button('Apply reviewed new texture');const actions=node('div');actions.className='dialog-actions';actions.append(reviewButton,pixelsButton,applyButton);
  const status=node('p','Choose a complete TIM. Review and pixel inspection do not change the project.'),summary=node('section'),error=node('p');error.className='dialog-error';error.setAttribute('role','alert');
  dialog.append(heading,help,fileLabel,nameLabel,paletteLabel,choice,actions,status,summary,error);document.body.append(dialog);
  let content=null,review=null,pending=null,controller=null,owner=null,generation=0,closed=false,pixelDialog=null;
  const current=()=>!closed&&JSON.stringify(getContext())===contextKey;
  const request=()=>({anchor_asset_id:assetId,source_key:context.sourceKey,label:label.value,accept_potential_overlap:overlap.checked,content_base64:content?.base64});
  const reviewed=()=>current()&&review&&JSON.stringify(review.request)===JSON.stringify(request());
  function controls(){if(!closed&&!current()){review=null;summary.replaceChildren();status.textContent='Project, scene, mode or source changed. Reopen new texture import.';}const blocked=!current()||pending!==null||busy();for(const input of [file,label,overlap,palette])input.disabled=blocked;reviewButton.disabled=blocked||!content||!label.value.trim();pixelsButton.disabled=blocked||!reviewed()||!integer(Number(palette.value),0,Math.max(1,review?.report.palette_count??0)-1)||palette.value.trim()==='';applyButton.disabled=blocked||!reviewed()||!review.report.can_apply;close.disabled=pending==='apply';}
  function release(token){if(token&&owner===token){owner=null;setBusy(false);}}
  function invalidate(){generation++;controller?.abort();controller=null;pending=null;release(owner);review=null;summary.replaceChildren();pixelDialog?.close();controls();}
  function dispose(){if(closed)return;closed=true;invalidate();pixelDialog?.remove();dialog.remove();}
  async function run(kind,work){if(!current()||pending||busy()||!dialog.open)return;const token={},ticket=++generation;owner=token;pending=kind;controller=new AbortController();const signal=controller.signal;setBusy(true);error.textContent='';controls();const valid=()=>current()&&generation===ticket&&!signal.aborted;try{await work(signal,valid);}catch(e){if(valid()&&e.name!=='AbortError'){review=null;summary.replaceChildren();error.textContent=e.message;onError(e);}}finally{release(token);if(ticket===generation){pending=null;controller=null;controls();}}}
  async function post(route,body,signal,max=1048576){const response=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal}),text=await response.text();if(new TextEncoder().encode(text).length>max)fail('New texture response exceeds its inspection budget.');const result=JSON.parse(text);if(!response.ok||result.error)fail(result.error||'New texture request failed.');return result;}
  for(const input of [label,overlap])input.oninput=()=>{invalidate();status.textContent='Choices changed. Review again before inspection or Apply.';};
  palette.oninput=()=>{pixelDialog?.close();controls();};
  file.onchange=()=>{invalidate();content=null;controls();const selected=file.files?.[0];if(!selected)return;return run('file',async(signal,valid)=>{if(selected.size<20||selected.size>1048576)fail('Choose a complete TIM up to 1 MiB.');const bytes=new Uint8Array(await selected.arrayBuffer()),sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(!valid())return;let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));content={sha256,size:bytes.length,base64:btoa(binary)};if(!label.value.trim())label.value=selected.name.replace(/\.tim$/i,'').slice(0,128);status.textContent=`${selected.name} · ${bytes.length} bytes. Review the native allocation.`;});};
  reviewButton.onclick=()=>{if(reviewButton.disabled)return;review=null;summary.replaceChildren();const body=request(),selected=content;return run('review',async(signal,valid)=>{const result=await post('/api/texture-slot-review',body,signal);if(!valid()||selected!==content||JSON.stringify(body)!==JSON.stringify(request()))return;const report=decodeSlotReview(result,body,selected);if(report.source_scene_id!==context.sceneId)fail('New texture review belongs to another scene.');review={request:body,report};palette.max=String(Math.max(1,report.palette_count)-1);const l=report.image_layout;summary.append(node('h3','Proposed · not applied'),node('p',`Native slot ${report.slot_index} · ${l.width} × ${l.height} pixels · ${l.bpp} bpp · VRAM (${l.x}, ${l.y}) · ${report.palette_count} palettes`),node('p',`${report.footprint.potential_overlap_count} potential overlaps. Runtime residency and upload order remain unverified.`));const details=node('details'),pre=node('pre',JSON.stringify({overlaps:report.footprint,source_pack:report.source_pack_sha256,proposed:report.proposed_sha256,review:report.review_key},null,2));pre.style.overflowWrap='anywhere';details.append(node('summary','Placement evidence and hashes'),pre);summary.append(details);status.textContent=report.can_apply?'Review complete. Inspect Proposed pixels or Apply, then Save project.':'Overlaps found. Accept that choice and review again to enable Apply.';});};
  pixelsButton.onclick=()=>{if(pixelsButton.disabled)return;const accepted=review,index=Number(palette.value),selected=content;return run('pixels',async(signal,valid)=>{const result=await post('/api/texture-slot-pixels',{...accepted.request,review_key:accepted.report.review_key,palette_index:index},signal,16*1024*1024);if(!valid()||review!==accepted)return;const image=decodeSlotPixels(result,accepted.report,accepted.request,selected,index);pixelDialog=node('dialog');pixelDialog.id='texture-slot-pixels-dialog';Object.assign(pixelDialog.style,{width:'min(1000px,94vw)',maxHeight:'92vh',overflowY:'auto'});const img=node('img');img.src=image;img.alt='Proposed new texture pixels';img.style.maxWidth='100%';img.style.width=`${Math.min(768,Math.max(256,accepted.report.image_layout.width))}px`;img.style.height='auto';img.style.display='block';img.style.margin='16px 0';img.style.background='repeating-conic-gradient(#253239 0% 25%,#182328 0% 50%) 0 0 / 16px 16px';img.style.imageRendering='pixelated';const back=button('Return to new texture review');back.onclick=()=>pixelDialog.close();pixelDialog.append(node('h2','Proposed texture · not applied'),node('p',`Palette ${index}. Transparent-zero alpha is shown; runtime STP blending is unverified.`),img,back);document.body.append(pixelDialog);pixelDialog.onclose=()=>{pixelDialog.remove();pixelDialog=null;};pixelDialog.showModal();});};
  applyButton.onclick=()=>{if(applyButton.disabled)return;const accepted=review,selected=content;return run('apply',async(signal,valid)=>{const next=await post('/api/texture-slot-apply',{...accepted.request,review_key:accepted.report.review_key},signal,16*1024*1024);if(!valid()||review!==accepted)return;const report=decodeSlotReview(next.texture_slot_report,accepted.request,selected,true);if(report.review_key!==accepted.report.review_key||next.project?.path!==context.projectPath||next.project?.mode!=='edit'||next.scene?.id!==context.sceneId)fail('New texture Apply returned another project, scene or review.');await onApplied(next);dispose();});};
  close.onclick=()=>{if(pending!=='apply')dispose();};dialog.oncancel=e=>{e.preventDefault();if(pending!=='apply')dispose();};dialog.onclose=dispose;dialog.showModal();controls();return {dialog,dispose,update:controls};
}
