// Reviewed PNG interchange keeps the source TIM layout and its separate STP bit.
const MAX_PNG=8*1024*1024,MAX_BINDING=128*1024,MAX_METADATA=16*1024*1024,MAX_ENVELOPE=24*1024*1024,MAX_PIXELS=2097152,MAX_TIM=1024*1024;
const object=value=>value!==null&&typeof value==='object'&&!Array.isArray(value)&&[Object.prototype,null].includes(Object.getPrototypeOf(value));
const exact=(value,keys)=>object(value)&&Object.keys(value).length===keys.length&&keys.every(key=>Object.hasOwn(value,key));
const integer=(value,min,max)=>Number.isSafeInteger(value)&&value>=min&&value<=max;
const hash=value=>typeof value==='string'&&/^[0-9a-f]{64}$/.test(value);
const text=(value,max=8192)=>typeof value==='string'&&value.length>0&&value.length<=max;
const clone=value=>structuredClone(value),fail=message=>{throw new Error(message);};
const canonical=value=>Array.isArray(value)?value.map(canonical):object(value)?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])])):value;
const same=(a,b)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
const size=value=>new TextEncoder().encode(JSON.stringify(value)).byteLength;
const textureId=value=>typeof value==='string'&&/^texture:\/\/[A-Za-z0-9_./-]{1,512}$/.test(value);
function metadata(value,budget){let nodes=0;function visit(item,depth){if(++nodes>200000||depth>24)fail('Texture PNG metadata exceeds its bounded structure.');if(item===null||typeof item==='boolean'||typeof item==='number'&&Number.isFinite(item)||typeof item==='string'&&item.length<=32768)return;if(Array.isArray(item)&&item.length<=65536){for(const child of item)visit(child,depth+1);return;}if(object(item)){for(const [key,child] of Object.entries(item)){if(!text(key,512))fail('Texture PNG metadata has an invalid key.');visit(child,depth+1);}return;}fail('Texture PNG metadata must contain finite JSON values.');}visit(value,0);if(size(value)>budget)fail('Texture PNG metadata exceeds its byte budget.');}
function frozen(value){const result=clone(value);function freeze(item){if(item&&typeof item==='object'){for(const child of Object.values(item))freeze(child);Object.freeze(item);}}freeze(result);return result;}

export function decodeTextureGlbImages(value,glbHash){
  metadata(value,128*1024);if(!exact(value,['schema_version','glb_sha256','image_count','images','excluded_image_indices','read_only','project_changed'])||value.schema_version!=='legaia.texture-glb-images.v1'||!hash(glbHash)||value.glb_sha256!==glbHash||!integer(value.image_count,1,64)||!Array.isArray(value.images)||value.images.length>64||!Array.isArray(value.excluded_image_indices)||value.read_only!==true||value.project_changed!==false)fail('GLB PNG inventory differs from the selected file.');
  const ids=[];for(const row of value.images){if(!exact(row,['image_index','name','byte_length','png_sha256','width','height'])||!integer(row.image_index,0,value.image_count-1)||!(row.name===null||typeof row.name==='string'&&row.name.length<=256&&!/[\x00-\x1f]/.test(row.name))||!integer(row.byte_length,33,MAX_PNG)||!hash(row.png_sha256)||!integer(row.width,1,MAX_PIXELS)||!integer(row.height,1,MAX_PIXELS)||row.width*row.height>MAX_PIXELS||ids.length&&row.image_index<=ids.at(-1))fail('Invalid embedded GLB PNG identity or dimensions.');ids.push(row.image_index);}
  if(value.excluded_image_indices.some((n,i)=>!integer(n,0,value.image_count-1)||ids.includes(n)||i&&n<=value.excluded_image_indices[i-1])||new Set([...ids,...value.excluded_image_indices]).size!==value.image_count)fail('GLB image coverage differs from its qualified/excluded slots.');return clone(value);
}
export async function decodeTextureGlbImage(value,catalog,imageIndex){
  catalog=decodeTextureGlbImages(catalog,catalog.glb_sha256);const row=catalog.images.find(row=>row.image_index===imageIndex);
  if(!row||!exact(value,['schema_version','glb_sha256','image','png_base64','read_only','project_changed'])||value.schema_version!=='legaia.texture-glb-image.v1'||value.glb_sha256!==catalog.glb_sha256||!same(value.image,row)||value.read_only!==true||value.project_changed!==false)fail('Extracted GLB PNG differs from the inspected selection.');
  const bytes=pngBytes(value.png_base64,row);if(bytes.length!==row.byte_length||await byteHash(bytes)!==row.png_sha256)fail('Embedded PNG bytes differ from their source hash.');return bytes;
}

export function texturePngContext(value){if(!exact(value,['projectPath','sceneId','mode','sourceKey'])||!text(value.projectPath,32768)||!/^scene:\/\/[A-Za-z0-9_-]{1,128}$/.test(value.sceneId)||value.mode!=='edit'||!hash(value.sourceKey))fail('Texture PNG editing requires the current editable scene and source key.');return clone(value);}
export function decodeTexturePngBinding(value,assetId,paletteIndex,context){
  context=texturePngContext(context);metadata(value,MAX_BINDING);
  if(!textureId(assetId)||!integer(paletteIndex,0,32767)||!exact(value,['schema_version','asset_id','scene_id','source_sha256','effective_sha256','project_source_key','profile'])||value.schema_version!=='legaia.texture-png-binding.v1'||value.asset_id!==assetId||value.scene_id!==context.sceneId||!hash(value.source_sha256)||!hash(value.effective_sha256)||value.project_source_key!==context.sourceKey||!object(value.profile))fail('The binding differs from this texture or current source. Export a fresh binding.');
  const p=value.profile,indexed=[4,8].includes(p.bpp);
  if(p.schema_version!=='legaia.texture-png-profile.v1'||![4,8,16,24].includes(p.bpp)||!integer(p.width,1,MAX_PIXELS)||!integer(p.height,1,MAX_PIXELS)||p.width*p.height>MAX_PIXELS||p.palette_index!==paletteIndex||!(indexed?integer(p.palette_count,1,32768)&&paletteIndex<p.palette_count&&p.entry_count===2**p.bpp:p.palette_count===0&&p.entry_count===0&&paletteIndex===0))fail('Texture PNG profile differs from the selected source palette or dimensions.');
  return clone(value);
}
function changes(value,p){
  if(!exact(value,['palette_words_changed','pixel_indices_changed','image_bytes_changed','total_change_count','changes','changes_truncated'])||!integer(value.palette_words_changed,0,p.palette_count*p.entry_count)||!integer(value.image_bytes_changed,0,MAX_TIM)||!integer(value.total_change_count,0,MAX_PIXELS+MAX_TIM)||!Array.isArray(value.changes)||value.changes.length!==Math.min(value.total_change_count,256)||value.changes_truncated!==(value.total_change_count>256))fail('Texture PNG audit counts or truncation differ from their source details.');
  const indexed=[4,8].includes(p.bpp),pixels=p.width*p.height;
  if(indexed?!integer(value.pixel_indices_changed,0,pixels):value.pixel_indices_changed!==null)fail('Texture PNG index counts conflict with the source mode.');
  if(value.total_change_count!==value.palette_words_changed+(indexed?value.pixel_indices_changed:value.image_bytes_changed)||indexed&&(value.image_bytes_changed<Math.ceil(value.pixel_indices_changed/(8/p.bpp))||value.image_bytes_changed>value.pixel_indices_changed))fail('Texture PNG audit totals differ from the changed source payload.');
  const identities=new Set(),count={palette_word:0,pixel_index:0,image_byte:0};
  for(const row of value.changes){let key,max;
    if(row?.kind==='palette_word'){if(!exact(row,['kind','word_index','before','after'])||!integer(row.word_index,0,p.palette_count*p.entry_count-1))fail('Invalid texture palette-word source detail.');key='word:'+row.word_index;max=65535;}
    else if(row?.kind==='pixel_index'){if(!indexed||!exact(row,['kind','x','y','before','after'])||!integer(row.x,0,p.width-1)||!integer(row.y,0,p.height-1))fail('Invalid texture pixel-index source detail.');key='pixel:'+row.x+','+row.y;max=p.entry_count-1;}
    else if(row?.kind==='image_byte'){if(indexed||!exact(row,['kind','image_byte_index','before','after'])||!integer(row.image_byte_index,0,MAX_TIM-1))fail('Invalid texture image-byte source detail.');key='image:'+row.image_byte_index;max=255;}
    else fail('Texture PNG audit contains an unsupported source field.');
    if(!integer(row.before,0,max)||!integer(row.after,0,max)||row.before===row.after||identities.has(key))fail('Texture PNG audit has duplicated or invalid changed values.');identities.add(key);count[row.kind]++;
  }
  for(const [kind,total] of [['palette_word',value.palette_words_changed],['pixel_index',value.pixel_indices_changed??0],['image_byte',indexed?0:value.image_bytes_changed]])if(count[kind]>total||!value.changes_truncated&&count[kind]!==total)fail('Texture PNG source details contradict their complete counts.');
}
export function decodeTexturePngReview(value,binding,assetId,paletteIndex,context,pngHash,stpHash,paletteMode){
  binding=decodeTexturePngBinding(binding,assetId,paletteIndex,context);metadata(value,MAX_METADATA);
  const keys=['schema_version','asset_id','scene_id','source_sha256','effective_sha256','proposed_sha256','png_sha256','stp_png_sha256','project_source_key','palette_mode','palette_index','width','height','bpp','palette_count','changes','pending_changes','quantization','limitations','review_key','project_changed','gameplay_verified'],p=binding.profile;
  if(!object(value)||!keys.every(key=>Object.hasOwn(value,key))||value.schema_version!=='legaia.texture-png-review.v1'||value.asset_id!==assetId||value.scene_id!==context.sceneId||value.source_sha256!==binding.source_sha256||value.effective_sha256!==binding.effective_sha256||value.project_source_key!==context.sourceKey||!hash(value.proposed_sha256)||!hash(value.review_key)||value.png_sha256!==pngHash||!hash(pngHash)||value.stp_png_sha256!==stpHash||!(stpHash===null||hash(stpHash))||value.palette_mode!==paletteMode||!['existing','rebuild'].includes(paletteMode)||![4,8].includes(p.bpp)&&paletteMode!=='existing'||['palette_index','width','height','bpp','palette_count'].some(key=>value[key]!==p[key])||value.project_changed!==false||value.gameplay_verified!==false||!Array.isArray(value.limitations)||value.limitations.length>256||value.limitations.some(line=>!text(line)))fail('Texture PNG review differs from the selected files, mode or current source. Review again.');
  changes(value.changes,p);changes(value.pending_changes,p);
  if(paletteMode==='existing'&&value.pending_changes.palette_words_changed!==0||paletteMode==='rebuild'&&value.pending_changes.palette_words_changed>p.entry_count||value.pending_changes.changes.some(row=>row.kind==='palette_word'&&(row.word_index<paletteIndex*p.entry_count||row.word_index>=(paletteIndex+1)*p.entry_count)))fail('Texture PNG review changed palette words outside the selected palette mode.');
  if((value.pending_changes.total_change_count===0)!==(value.proposed_sha256===value.effective_sha256)||(value.changes.total_change_count===0)!==(value.proposed_sha256===value.source_sha256))fail('Texture PNG audit totals contradict the source and current hashes.');
  const q=value.quantization,qkeys=['color_max_error','color_rms_error','quantized_pixel_count','distinct_requested_words','output_palette_size','stp_changed_pixels','forced_black_stp_pixels','forced_transparent_stp_pixels'],pixels=p.width*p.height;
  if(!exact(q,qkeys)||['color_max_error','color_rms_error'].some(key=>typeof q[key]!=='number'||!Number.isFinite(q[key])||q[key]<0||q[key]>255)||qkeys.slice(2).some(key=>!integer(q[key],0,key==='output_palette_size'?p.entry_count:pixels))||q.forced_black_stp_pixels+q.forced_transparent_stp_pixels>pixels)fail('Texture PNG quantization or STP counts are invalid.');
  return clone(value);
}

export function texturePngDimensions(bytes){if(!(bytes instanceof Uint8Array)||!integer(bytes.length,33,MAX_PNG)||![137,80,78,71,13,10,26,10].every((value,index)=>bytes[index]===value))fail('Choose a PNG up to 8 MiB.');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),width=view.getUint32(16),height=view.getUint32(20);if(view.getUint32(8)!==13||view.getUint32(12)!==0x49484452||!integer(width,1,MAX_PIXELS)||!integer(height,1,MAX_PIXELS)||width*height>MAX_PIXELS)fail('PNG dimensions exceed the source pixel budget.');return {width,height};}
function encode(bytes){let raw='';for(let at=0;at<bytes.length;at+=32768)raw+=String.fromCharCode(...bytes.subarray(at,at+32768));return btoa(raw);}
function pngBytes(value,p){if(!text(value,Math.ceil(MAX_PNG/3)*4)||value.length%4!==0||!/^[A-Za-z0-9+/]*={0,2}$/.test(value))fail('Texture preview has invalid bounded PNG bytes.');const bytes=Uint8Array.from(atob(value),char=>char.charCodeAt(0));if(encode(bytes)!==value||!same(texturePngDimensions(bytes),{width:p.width,height:p.height}))fail('PNG dimensions differ from the fixed source image.');return bytes;}
async function byteHash(bytes){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),value=>value.toString(16).padStart(2,'0')).join('');}
export function decodeTexturePngPixels(value,review,binding,assetId,paletteIndex,context,pngHash,stpHash,paletteMode){if(!exact(value,['report','current_png_base64','proposed_png_base64','width','height'])||size(value)>MAX_ENVELOPE||value.width!==binding.profile.width||value.height!==binding.profile.height)fail('Pixel preview differs from the fixed source dimensions or envelope budget.');const report=decodeTexturePngReview(value.report,binding,assetId,paletteIndex,context,pngHash,stpHash,paletteMode);if(!same(report,review))fail('Pixel preview differs from the reviewed proposal.');pngBytes(value.current_png_base64,binding.profile);pngBytes(value.proposed_png_base64,binding.profile);return clone(value);}
function element(tag,label){const node=document.createElement(tag);if(label!==undefined)node.textContent=label;return node;}
function button(label,action){const node=element('button',label);node.type='button';node.dataset.action=action;return node;}
function filename(value,fallback){return typeof value==='string'&&value.length>0&&value.length<=160&&!/[\\/\x00-\x1f]/.test(value)?value:fallback;}
function download(value,type,name){let url,link;try{url=URL.createObjectURL(new Blob([value],{type}));link=element('a');link.href=url;link.download=name;document.body.append(link);link.click();}finally{link?.remove();if(url)URL.revokeObjectURL(url);}}

export async function openTexturePngEditor({assetId,paletteIndex,getContext,busy,setBusy,onError=()=>{},onApplied,onScenePreview=null,canPreviewScene=()=>false}){
  if([getContext,busy,setBusy,onError,onApplied,canPreviewScene].some(callback=>typeof callback!=='function')||onScenePreview!==null&&typeof onScenePreview!=='function')fail('Texture PNG editor requires source, state and preview callbacks.');const context=texturePngContext(getContext());if(!textureId(assetId)||!integer(paletteIndex,0,32767))fail('Choose an imported texture and source palette.');
  const dialog=element('dialog');dialog.id='texture-png-dialog';dialog.className='project-dialog';dialog.dataset.texturePng='';Object.assign(dialog.style,{width:'min(540px,94vw)',maxHeight:'92vh',overflowY:'auto',boxSizing:'border-box'});
  const heading=element('div');heading.className='dialog-heading';const close=button('×','close');close.setAttribute('aria-label','Close texture PNG');heading.append(element('h2','Edit texture through PNG'),close);
  const help=element('p','Keep the exact image dimensions. PNG alpha must be 0 or 255; partial alpha is unsupported. PSX STP is a separate bit, supplied by an optional opaque black/white PNG. Without it, current STP is retained except transparent pixels and opaque black require specific source words.');help.className='field-note';
  const exportActions=element('div');exportActions.className='dialog-actions';exportActions.style.flexWrap='wrap';const prepare=button('Prepare PNG export','export'),getPng=button('Download PNG','download-png'),getBinding=button('Download binding JSON','download-binding'),getStp=button('Download STP plane','download-stp');exportActions.append(prepare,getPng,getBinding,getStp);
  const png=element('input'),bindingInput=element('input'),stp=element('input');for(const [field,label,accept] of [[png,'Edited texture PNG','.png,image/png'],[bindingInput,'Source binding JSON','.json,application/json'],[stp,'Optional STP PNG','.png,image/png']]){field.type='file';field.accept=accept;field.setAttribute('aria-label',label);Object.assign(field.style,{width:'100%',minWidth:'0'});}
  const files=element('section');files.append(element('h3','Review edited files'));for(const [label,field] of [['Edited PNG · maximum 8 MiB',png],['Binding JSON from the export · maximum 128 KiB',bindingInput],['Optional STP plane · maximum 8 MiB',stp]]){const row=element('label',label);row.append(field);files.append(row);}const clearStp=button('Clear optional STP file','clear-stp');files.append(clearStp);
  const glb=element('input');glb.type='file';glb.accept='.glb';glb.setAttribute('aria-label','GLB PNG source');const glbLabel=element('label','Optional embedded PNG source · GLB maximum 32 MiB');glbLabel.append(glb);
  const imageChoice=element('select');imageChoice.setAttribute('aria-label','Embedded GLB PNG');const imageLabel=element('label','Embedded PNG image');imageLabel.append(imageChoice);const extractPng=button('Use embedded PNG','glb-image'),origin=element('p');origin.style.overflowWrap='anywhere';files.append(glbLabel,imageLabel,extractPng,element('p','Embedded PNG bytes only. GLB materials, UV assignments, samplers and color factors are not imported. Native texture dimensions and bindings remain.'),origin);
  const mode=element('select');mode.setAttribute('aria-label','Palette mode');for(const [value,label] of [['existing','Use existing palette'],['rebuild','Rebuild selected palette']]){const option=element('option',label);option.value=value;mode.append(option);}mode.value='existing';const modeLabel=element('label','Palette mode');modeLabel.append(mode);files.append(modeLabel);const modeHelp=element('p','Existing mode keeps palette words. Rebuild changes only the selected palette; image indices are shared by every source palette. Direct-color modes use existing mode.');modeHelp.className='field-note';files.append(modeHelp);
  const actions=element('div');actions.className='dialog-actions';actions.style.flexWrap='wrap';const inspect=button('Review selected files','review'),pixels=button('Inspect proposed pixels','pixels'),scene=button('Inspect in scene','scene'),apply=button('Apply reviewed texture','apply');scene.hidden=onScenePreview===null;actions.append(inspect,pixels,scene,apply);const status=element('p','Choose the edited PNG and binding JSON to review.');status.setAttribute('role','status');const error=element('p');error.className='dialog-error';error.setAttribute('role','alert');const summary=element('section');summary.hidden=true;dialog.append(heading,help,exportActions,files,actions,status,error,summary);document.body.append(dialog);
  let closed=false,stale=false,pending=null,generation=0,revision=0,controller=null,busyOwner=null,candidate=null,review=null,exportData=null,paletteMode='existing',retainedClose=false,pixelDialog=null,glbSource=null,glbCatalog=null;
  const contextCurrent=()=>{try{return !closed&&!stale&&same(context,texturePngContext(getContext()));}catch{return false;}};
  const filesCurrent=value=>value!==null&&value.revision===revision&&value.paletteMode===paletteMode&&mode.value===paletteMode&&png.files?.[0]===value.pngFile&&bindingInput.files?.[0]===value.bindingFile&&(stp.files?.[0]??null)===value.stpFile;
  const acceptedCurrent=value=>contextCurrent()&&value!==null&&value===review&&value.candidate===candidate&&filesCurrent(candidate);
  const release=token=>{if(busyOwner===token){busyOwner=null;setBusy(false);}};
  function removePixels(){const value=pixelDialog;pixelDialog=null;if(value){value.onclose=null;value.remove();}}
  function abort(){generation++;controller?.abort();controller=null;pending=null;if(busyOwner)release(busyOwner);}
  function invalidate(){abort();review=null;summary.hidden=true;summary.replaceChildren();removePixels();}
  function showError(value){error.textContent=value?.message??String(value);onError(value instanceof Error?value:new Error(String(value)));}
  function sceneAllowed(){try{return onScenePreview!==null&&canPreviewScene()===true;}catch{return false;}}
  function updateState(){if(!closed&&!stale&&!contextCurrent()){invalidate();stale=true;candidate=exportData=null;status.textContent='Project, scene, mode or texture source changed. Reopen PNG editing.';}if(candidate&&!filesCurrent(candidate)){invalidate();candidate=null;mode.value=paletteMode;status.textContent='Files or palette mode changed. Read both files and review again.';}const current=contextCurrent(),blocked=!current||pending!==null||busy()!==false,p=candidate?.binding.profile??exportData?.binding.profile;glb.disabled=blocked;imageChoice.disabled=blocked||!glbCatalog?.images.length;extractPng.disabled=blocked||!glbSource||!glbCatalog?.images.some(row=>String(row.image_index)===imageChoice.value);prepare.disabled=blocked;getPng.disabled=getBinding.disabled=blocked||!exportData;getStp.disabled=blocked||!exportData?.stpBytes;png.disabled=bindingInput.disabled=stp.disabled=!current||pending==='apply'||busy()!==false&&pending===null;clearStp.disabled=blocked||!(stp.files?.length);mode.disabled=blocked||!p||![4,8].includes(p.bpp);mode.children[1].disabled=!p||![4,8].includes(p.bpp);inspect.disabled=blocked||!filesCurrent(candidate);pixels.disabled=blocked||!acceptedCurrent(review);scene.disabled=blocked||!acceptedCurrent(review)||!sceneAllowed();apply.disabled=blocked||!acceptedCurrent(review)||review?.report.pending_changes.total_change_count===0;close.disabled=pending==='apply';}
  function dispose(){if(closed)return;closed=true;invalidate();candidate=exportData=glbSource=glbCatalog=null;if(dialog.open)dialog.close();dialog.remove();}
  async function run(kind,work){if(!contextCurrent()||pending!==null||busy()!==false)return false;const token={},ticket=++generation;controller=new AbortController();const signal=controller.signal;pending=kind;busyOwner=token;setBusy(true);error.textContent='';updateState();const valid=()=>contextCurrent()&&generation===ticket&&!signal.aborted;try{return await work(signal,valid);}catch(value){if(valid()&&value?.name!=='AbortError')showError(value);return false;}finally{release(token);if(generation===ticket){controller=null;pending=null;updateState();}}}
  async function post(route,body,signal,envelope=MAX_METADATA){const response=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});const raw=await response.text();if(new TextEncoder().encode(raw).byteLength>envelope)fail('Texture PNG response exceeds its bounded envelope.');const value=JSON.parse(raw);if(!response.ok||value?.error)fail(value?.error??'Texture PNG request failed.');return value;}
  const request=value=>({asset_id:assetId,png_base64:value.png_base64,stp_png_base64:value.stp_png_base64,binding:clone(value.binding),palette_mode:value.paletteMode});
  const decodeReview=(value,accepted)=>decodeTexturePngReview(value,accepted.binding,assetId,paletteIndex,context,accepted.pngHash,accepted.stpHash,accepted.paletteMode);
  function appendReview(report){summary.replaceChildren();summary.hidden=false;const p=report.pending_changes,q=report.quantization;summary.append(element('h3','Reviewed · not applied'),element('p',`${report.width} × ${report.height} pixels · ${report.bpp} bpp · palette ${report.palette_index} of ${report.palette_count||'direct color'}`),element('p',`${p.total_change_count} current-to-proposed source changes · ${p.palette_words_changed} palette words · ${p.pixel_indices_changed??'not indexed'} pixel indices · ${p.image_bytes_changed} image bytes`),element('p',`${report.changes.total_change_count} total changes from retail source`),element('p',`RGB rounding error · maximum ${Number(q.color_max_error.toPrecision(6))} · RMS ${Number(q.color_rms_error.toPrecision(6))} · ${q.quantized_pixel_count} quantized pixels`),element('p',`${q.distinct_requested_words} requested words · ${q.output_palette_size} output palette entries · ${q.stp_changed_pixels} changed STP pixels`),element('p',`Forced STP rules · ${q.forced_black_stp_pixels} opaque-black pixels · ${q.forced_transparent_stp_pixels} transparent pixels`));if([4,8].includes(report.bpp))summary.append(element('p','Changed image indices affect every palette sharing this source index plane. Only the selected palette can be rebuilt.'));
    for(const [label,key] of [['Retail source','source_sha256'],['Current texture','effective_sha256'],['Proposed texture','proposed_sha256']]){const row=element('p',`${label} SHA-256 · ${report[key]}`);row.style.overflowWrap='anywhere';summary.append(row);}const table=element('table');table.className='operand-review-table';const header=element('tr');for(const label of ['Source field','Current','Proposed'])header.append(element('th',label));table.append(header);for(const row of p.changes.slice(0,100)){const tr=element('tr'),label=row.kind==='palette_word'?'Palette word '+row.word_index:row.kind==='pixel_index'?`Pixel ${row.x},${row.y}`:'Image byte '+row.image_byte_index;for(const value of [label,String(row.before),String(row.after)])tr.append(element('td',value));table.append(tr);}const scroll=element('div');scroll.style.overflowX='auto';scroll.append(table);summary.append(scroll);if(p.total_change_count>Math.min(p.changes.length,100))summary.append(element('p',`Showing ${Math.min(p.changes.length,100)} of ${p.total_change_count} changed source fields; complete counts remain visible.`));for(const line of report.limitations){const row=element('p',line);row.className='field-note';summary.append(row);}const details=element('details');details.append(element('summary','Source/current audit and complete counts'));const audit=element('pre',JSON.stringify({changes:report.changes,pending_changes:p,quantization:q},null,2));audit.className='diagnostic-detail';Object.assign(audit.style,{maxHeight:'240px',overflow:'auto'});details.append(audit);summary.append(details);}
  async function readFiles(){if(!contextCurrent()||pending==='apply'||busy()!==false&&busyOwner===null)return false;revision++;invalidate();candidate=null;error.textContent='';status.textContent='Choose the edited PNG and binding JSON to review.';updateState();const pngFile=png.files?.[0],bindingFile=bindingInput.files?.[0],stpFile=stp.files?.[0]??null,fileRevision=revision;if(!pngFile||!bindingFile)return false;return run('files',async(_signal,valid)=>{for(const file of [pngFile,stpFile].filter(Boolean))if(!integer(file.size,33,MAX_PNG)||!file.name?.toLowerCase().endsWith('.png'))fail('Choose a PNG file up to 8 MiB.');if(!integer(bindingFile.size,1,MAX_BINDING)||!bindingFile.name?.toLowerCase().endsWith('.json'))fail('Choose the source binding JSON up to 128 KiB.');const [image,content,plane]=await Promise.all([pngFile.arrayBuffer(),bindingFile.text(),stpFile?.arrayBuffer()??null]);if(!valid()||revision!==fileRevision||png.files?.[0]!==pngFile||bindingInput.files?.[0]!==bindingFile||(stp.files?.[0]??null)!==stpFile)return false;const imageBytes=new Uint8Array(image),planeBytes=plane===null?null:new Uint8Array(plane);if(imageBytes.length!==pngFile.size||planeBytes&&planeBytes.length!==stpFile.size||typeof content!=='string'||new TextEncoder().encode(content).byteLength!==bindingFile.size)fail('Selected file contents differ from their bounded sizes.');const binding=decodeTexturePngBinding(JSON.parse(content),assetId,paletteIndex,context);if(!same(texturePngDimensions(imageBytes),{width:binding.profile.width,height:binding.profile.height})||planeBytes&&!same(texturePngDimensions(planeBytes),{width:binding.profile.width,height:binding.profile.height}))fail('PNG dimensions must match the fixed source image.');if(![4,8].includes(binding.profile.bpp)){paletteMode='existing';mode.value='existing';}const [pngHash,stpHash]=await Promise.all([byteHash(imageBytes),planeBytes===null?null:byteHash(planeBytes)]);if(!valid()||revision!==fileRevision||png.files?.[0]!==pngFile||bindingInput.files?.[0]!==bindingFile||(stp.files?.[0]??null)!==stpFile)return false;candidate={binding,png_base64:encode(imageBytes),stp_png_base64:planeBytes===null?null:encode(planeBytes),pngHash,stpHash,pngFile,bindingFile,stpFile,revision:fileRevision,paletteMode};status.textContent=`Ready to review ${pngFile.name}${stpFile?' with explicit STP':''}.`;return true;});}
  bindingInput.onchange=stp.onchange=readFiles;png.onchange=()=>{origin.textContent='';return readFiles();};clearStp.onclick=()=>{if(clearStp.disabled)return false;stp.value='';return readFiles();};
  mode.onchange=()=>{if(!contextCurrent()||pending==='apply'||busy()!==false&&busyOwner===null)return false;const p=candidate?.binding.profile??exportData?.binding.profile,next=mode.value;if(!['existing','rebuild'].includes(next)||!p||next==='rebuild'&&![4,8].includes(p.bpp)){mode.value=paletteMode;return false;}const accepted=candidate;revision++;paletteMode=next;invalidate();mode.value=next;candidate=accepted?{...accepted,revision,paletteMode}:null;status.textContent='Palette mode changed. Review the selected files again.';updateState();return true;};
  glb.onchange=()=>{if(!contextCurrent()||pending==='apply')return false;revision++;invalidate();candidate=null;glbSource=glbCatalog=null;imageChoice.replaceChildren();origin.textContent='';const selected=glb.files?.[0];updateState();if(!selected)return false;return run('glb-files',async(signal,valid)=>{if(!selected.name.toLowerCase().endsWith('.glb')||!integer(selected.size,28,32*1024*1024))fail('Choose a GLB up to 32 MiB.');const bytes=new Uint8Array(await selected.arrayBuffer()),digest=await byteHash(bytes);if(!valid()||glb.files?.[0]!==selected)return false;const content=encode(bytes),catalog=decodeTextureGlbImages(await post('/api/texture-glb-images',{content_base64:content},signal),digest);if(!valid()||glb.files?.[0]!==selected)return false;glbSource={file:selected,content,hash:digest};glbCatalog=catalog;for(const row of catalog.images){const option=element('option',`Image ${row.image_index} · ${row.name??'unnamed'} · ${row.width} × ${row.height}`);option.value=String(row.image_index);imageChoice.append(option);}status.textContent=`${catalog.images.length} embedded PNG images qualified; ${catalog.excluded_image_indices.length} unsupported/URI image slots excluded. Choose an image and Use embedded PNG.`;return true;});};
  imageChoice.onchange=()=>{revision++;invalidate();candidate=null;updateState();};
  extractPng.onclick=async()=>{updateState();if(extractPng.disabled)return false;const source=glbSource,catalog=glbCatalog,index=Number(imageChoice.value),row=catalog.images.find(row=>row.image_index===index);let adopted=null;const result=await run('glb-image',async(signal,valid)=>{const value=await post('/api/texture-glb-image',{content_base64:source.content,image_index:index,glb_sha256:source.hash,png_sha256:row.png_sha256},signal,MAX_ENVELOPE),bytes=await decodeTextureGlbImage(value,catalog,index);if(!valid()||glbSource!==source||Number(imageChoice.value)!==index)return false;adopted=new File([bytes],`glb-image-${index}.png`,{type:'image/png'});return true;});if(!result||!adopted||!contextCurrent())return false;const transfer=new DataTransfer();transfer.items.add(adopted);png.files=transfer.files;origin.textContent=`PNG input from ${source.file.name} · image ${index} · GLB SHA-256 ${source.hash} · PNG SHA-256 ${row.png_sha256}. Extraction is read-only; Review and explicit Apply are required.`;return readFiles();};
  prepare.onclick=()=>run('export',async(signal,valid)=>{exportData=null;status.textContent='Preparing source-bound PNG export…';const value=await post('/api/texture-png-export',{asset_id:assetId,palette_index:paletteIndex},signal,MAX_ENVELOPE);if(!valid())return false;const keys=['path','filename','stp_path','stp_filename','binding_path','binding_filename','png_base64','stp_png_base64','binding','report'];if(!exact(value,keys))fail('PNG export returned invalid file metadata.');metadata(Object.fromEntries(Object.entries(value).filter(([key])=>!['png_base64','stp_png_base64'].includes(key))),MAX_METADATA);const binding=decodeTexturePngBinding(value.binding,assetId,paletteIndex,context),image=pngBytes(value.png_base64,binding.profile),plane=value.stp_png_base64===null?null:pngBytes(value.stp_png_base64,binding.profile),[pngHash,stpHash]=await Promise.all([byteHash(image),plane===null?null:byteHash(plane)]);if(!valid())return false;const report=decodeTexturePngReview(value.report,binding,assetId,paletteIndex,context,pngHash,stpHash,'existing');if(report.pending_changes.total_change_count!==0)fail('PNG export does not preserve the current source bytes.');exportData={binding,image,stpBytes:plane,filename:filename(value.filename,'texture.png'),bindingFilename:filename(value.binding_filename,'texture.binding.json'),stpFilename:filename(value.stp_filename,'texture.stp.png')};if(!candidate&&![4,8].includes(binding.profile.bpp)){paletteMode='existing';mode.value='existing';}status.textContent='Export ready. Download PNG and binding; the STP plane is optional for editing.';return true;});
  for(const [control,kind] of [[getPng,'image'],[getBinding,'binding'],[getStp,'stp']])control.onclick=()=>{if(control.disabled||!contextCurrent()||busy()!==false||!exportData)return false;try{if(kind==='binding'){const pretty=JSON.stringify(exportData.binding,null,2)+'\n';download(new TextEncoder().encode(pretty).byteLength<=MAX_BINDING?pretty:JSON.stringify(exportData.binding),'application/json',exportData.bindingFilename);}else download(kind==='image'?exportData.image:exportData.stpBytes,'image/png',kind==='image'?exportData.filename:exportData.stpFilename);error.textContent='';return true;}catch(value){showError(value);return false;}};
  inspect.onclick=()=>{updateState();if(inspect.disabled||!filesCurrent(candidate))return false;const accepted=candidate;review=null;summary.hidden=true;return run('review',async(signal,valid)=>{status.textContent='Reviewing fixed-layout PNG changes…';const value=await post('/api/texture-png-preview',request(accepted),signal);if(!valid()||candidate!==accepted||!filesCurrent(accepted))return false;const report=decodeReview(value,accepted);review={candidate:accepted,report};appendReview(report);status.textContent=report.pending_changes.total_change_count?'Review complete. Explicit Apply is required.':'No change from the current texture.';return true;});};
  function returnFor(accepted){return ()=>{if(!acceptedCurrent(accepted)){dispose();return false;}if(!dialog.open)dialog.showModal();status.textContent='Review retained. Explicit Apply is required.';updateState();return true;};}
  pixels.onclick=()=>{updateState();if(pixels.disabled||!acceptedCurrent(review))return false;const accepted=review;return run('pixels',async(signal,valid)=>{const value=await post('/api/texture-png-pixels-preview',request(accepted.candidate),signal,MAX_ENVELOPE);if(!valid()||!acceptedCurrent(accepted))return false;const data=decodeTexturePngPixels(value,accepted.report,accepted.candidate.binding,assetId,paletteIndex,context,accepted.candidate.pngHash,accepted.candidate.stpHash,accepted.candidate.paletteMode);removePixels();const popup=element('dialog');popup.className='project-dialog';popup.dataset.texturePngPixels='';Object.assign(popup.style,{width:'min(540px,94vw)',maxHeight:'92vh',overflowY:'auto'});popup.append(element('h2','Current / Proposed pixels'),element('p',`${data.width} × ${data.height} source pixels · read-only numeric samples`));const grid=element('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'12px'});for(const [label,key] of [['Current','current_png_base64'],['Proposed','proposed_png_base64']]){const pane=element('section'),image=element('img');image.alt=label+' texture pixels';image.src='data:image/png;base64,'+data[key];image.width=data.width;image.height=data.height;Object.assign(image.style,{maxWidth:'100%',height:'auto',imageRendering:'pixelated'});image.onerror=()=>{if(pixelDialog===popup&&acceptedCurrent(accepted))showError(new Error('The verified PNG pixel preview could not be displayed.'));};pane.append(element('h3',label),image);grid.append(pane);}const back=button('Return to PNG editor','return');popup.append(grid,back);document.body.append(popup);pixelDialog=popup;const returnToEditor=returnFor(accepted);back.onclick=()=>{removePixels();return returnToEditor();};popup.onclose=()=>{if(pixelDialog!==popup)return;removePixels();returnToEditor();};popup.showModal();retainedClose=true;dialog.close();return true;});};
  scene.onclick=()=>{updateState();if(scene.disabled||!acceptedCurrent(review)||!sceneAllowed())return false;const accepted=review;return run('scene',async(signal,valid)=>{const result=await onScenePreview(frozen({...request(accepted.candidate),review_key:accepted.report.review_key}),frozen(accepted.report),{returnToEditor:returnFor(accepted),isCurrent:()=>valid()&&acceptedCurrent(accepted),signal});if(!valid()||!acceptedCurrent(accepted)||result===false)return false;retainedClose=true;dialog.close();return true;});};
  apply.onclick=()=>{updateState();if(apply.disabled||!acceptedCurrent(review)||!review.report.pending_changes.total_change_count)return false;const accepted=review;return run('apply',async(signal,valid)=>{status.textContent='Applying reviewed texture…';let state;try{state=await post('/api/texture-png-import',{...request(accepted.candidate),review_key:accepted.report.review_key},signal);if(!object(state)||!object(state.project)||state.project.mode!=='edit'||state.project.path!==context.projectPath||!object(state.scene)||state.scene.id!==context.sceneId)fail('PNG import returned state for a different project or scene.');if(!same(decodeReview(state.texture_png_report,accepted.candidate),accepted.report))fail('PNG import result differs from the reviewed texture.');}catch(value){if(valid()){review=null;summary.hidden=true;status.textContent='Apply failed. Review the selected files again.';}throw value;}if(!valid()||!acceptedCurrent(accepted))return false;review=null;candidate=null;summary.hidden=true;await onApplied(state);if(!closed)dispose();return true;});};
  close.onclick=()=>{if(pending==='apply')return false;dispose();return true;};dialog.oncancel=event=>{if(pending==='apply'){event.preventDefault();status.textContent='Apply is in progress; wait for its result.';}};dialog.onclose=()=>{if(retainedClose){retainedClose=false;return;}dispose();};dialog.showModal();updateState();return {dialog,ready:Promise.resolve(true),updateState,dispose};
}
