import {openImageConversion} from './texture-image-conversion.js';
const hash=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v);
const integer=(v,a,b)=>Number.isInteger(v)&&v>=a&&v<=b;
const fail=m=>{throw new Error(m);};
const authored=v=>typeof v==='string'&&/^texture-new:\/\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v);
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));

const validLayout=l=>exact(l,['bpp','x','y','width','height','width_words'])&&[4,8,16,24].includes(l.bpp)&&integer(l.x,0,1023)&&integer(l.y,0,511)&&integer(l.width,1,4096)&&integer(l.width_words,1,1024)&&integer(l.height,1,512)&&l.width*l.bpp===l.width_words*16&&l.x+l.width_words<=1024&&l.y+l.height<=512;

export function decodeSlotReview(v,request,file,applied=false,editing=false){
  const keys=['schema_version','project_source_key','source_scene_id','anchor_asset_id','source_pack_sha256','source_slot_count','pack_entry_index','pack_descriptor_index','slot_index','proposed_sha256','byte_length','label','image_layout','allocation','footprint','accept_potential_overlap','can_apply','project_changed','gameplay_verified','palette_count','review_key'];
  if(editing)keys.push('asset_id','current_sha256','current_byte_length','current_label','current_layout','content_changed','layout_changed','changed');
  else if(applied)keys.push('asset_id');
  if(!exact(v,keys)||v.schema_version!==(editing?'legaia.texture-slot-edit-review.v1':'legaia.texture-slot-review.v1')||v.project_source_key!==request.source_key||(!editing&&v.anchor_asset_id!==request.anchor_asset_id||editing&&(!v.anchor_asset_id?.startsWith('texture://')||v.asset_id!==request.asset_id||v.current_sha256!==request.expected_sha256))||!hash(v.source_pack_sha256)||!hash(v.review_key)||v.proposed_sha256!==file.sha256||v.byte_length!==file.size||v.label!==request.label||v.accept_potential_overlap!==request.accept_potential_overlap||typeof v.accept_potential_overlap!=='boolean'||v.project_changed!==applied||v.gameplay_verified!==false||!integer(v.source_slot_count,1,1023)||!integer(v.slot_index,v.source_slot_count,1023)||!integer(v.pack_entry_index,0,65535)||!integer(v.pack_descriptor_index,-1,1023)||!integer(v.palette_count,0,32768)||(applied||editing)&&!authored(v.asset_id))fail('New texture review differs from the file, source or choices.');
  const l=v.image_layout,a=v.allocation,f=v.footprint;
  if(!exact(l,['bpp','x','y','width','height','width_words'])||![4,8,16,24].includes(l.bpp)||!integer(l.x,0,1023)||!integer(l.y,0,511)||!integer(l.width,1,4096)||!integer(l.width_words,1,1024)||!integer(l.height,1,512)||l.width*l.bpp!==l.width_words*16||l.x+l.width_words>1024||l.y+l.height>512||![4,8].includes(l.bpp)&&v.palette_count!==0||v.byte_length<20+l.width_words*l.height*2)fail('New texture review has invalid native dimensions or palette count.');
  if(!a||a.schema_version!=='legaia.texture-pack-slot-allocation.v1'||a.source_sha256!==v.source_pack_sha256||a.source_slot_count!==v.source_slot_count||(!editing&&a.slot_count!==v.slot_index+1||editing&&!integer(a.slot_count,v.slot_index+1,1024))||a.standalone!==(v.pack_descriptor_index===-1)||a.native_members_verified!==true||a.opaque_tails_preserved!==true||a.gameplay_verified!==false||!hash(a.proposed_sha256)||!integer(a.proposed_byte_length,1,8388608)||!Array.isArray(a.added_slot_indices)||JSON.stringify(a.added_slot_indices)!==JSON.stringify(Array.from({length:a.slot_count-v.source_slot_count},(_,i)=>v.source_slot_count+i))||!Array.isArray(a.members)||a.members.length!==a.slot_count)fail('New texture allocation contradicts its slot identity.');
  const last=a.members[v.slot_index];if(last.slot_index!==v.slot_index||last.added!==true||last.tim_sha256!==file.sha256||last.tim_byte_length!==file.size)fail('New texture allocation differs from the selected complete TIM.');
  if(!exact(f,['potential_overlap_count','rows','rows_truncated','coverage','runtime_residency_verified'])||!integer(f.potential_overlap_count,0,65536)||!Array.isArray(f.rows)||f.rows.length!==Math.min(f.potential_overlap_count,64)||f.rows_truncated!==(f.potential_overlap_count>64)||f.coverage!=='known-static-scene-authored-and-boot-uploads'||f.runtime_residency_verified!==false)fail('New texture overlap census is malformed.');
  for(const r of f.rows){const t=r.rectangle;if(!exact(r,['asset_id','kind','proposed_kind','overlap_words','rectangle'])||!(r.asset_id===null||typeof r.asset_id==='string'&&(r.asset_id.startsWith('texture://')||authored(r.asset_id)))||!['image','flattened-clut','boot-upload','proposed-clut'].includes(r.kind)||!['image','flattened-clut'].includes(r.proposed_kind)||!integer(r.overlap_words,1,524288)||!exact(t,['x','y','width_words','height'])||!integer(t.x,0,1023)||!integer(t.y,0,511)||!integer(t.width_words,1,524288)||!integer(t.height,1,512))fail('New texture overlap row is malformed.');}
  if(editing&&(!validLayout(v.current_layout)||!hash(v.current_sha256)||!integer(v.current_byte_length,20,1048576)||typeof v.current_label!=='string'||v.content_changed!==(v.current_sha256!==v.proposed_sha256)||v.layout_changed!==(JSON.stringify(v.current_layout)!==JSON.stringify(v.image_layout))||v.changed!==(v.content_changed||v.current_label!==v.label)))fail('Edited texture review contradicts Current content.');
  if(v.can_apply!==((!editing||v.changed)&&(f.potential_overlap_count===0||v.accept_potential_overlap)))fail('New texture Apply status contradicts the overlap choice.');
  return structuredClone(v);
}

export function decodeSlotPixels(v,review,request,file,paletteIndex,editing=false){
  if(!exact(v,editing?['report','palette_index','current_palette_index','current_png_base64','proposed_png_base64']:['report','palette_index','proposed_png_base64'])||v.palette_index!==paletteIndex||!integer(paletteIndex,0,Math.max(1,review.palette_count)-1))fail('New texture pixels differ from the selected palette.');
  const qualified=decodeSlotReview(v.report,request,file,false,editing);if(JSON.stringify(qualified)!==JSON.stringify(review))fail('New texture pixels differ from the reviewed proposal.');
  const encoded=v.proposed_png_base64;if(typeof encoded!=='string'||encoded.length>11184812||encoded.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))fail('New texture PNG is malformed or exceeds its budget.');
  const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),view=new DataView(bytes.buffer);
  if(bytes.length<33||bytes.length>8388608||![137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n)||view.getUint32(8)!==13||view.getUint32(12)!==0x49484452||view.getUint32(16)!==review.image_layout.width||view.getUint32(20)!==review.image_layout.height)fail('New texture PNG dimensions differ from the reviewed TIM.');
  const proposed=`data:image/png;base64,${encoded}`;
  if(!editing)return proposed;
  if(v.current_palette_index!==0)fail('Current slot comparison must use palette zero.');
  const current=v.current_png_base64===null?null:qualifyCurrentPng(v.current_png_base64,review.current_layout);
  return {current,proposed};
}

function qualifyCurrentPng(encoded,layout){
  if(typeof encoded!=='string'||encoded.length>11184812||encoded.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))fail('Current texture PNG is malformed.');
  const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),v=new DataView(bytes.buffer);
  if(bytes.length<33||bytes.length>8388608||![137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n)||v.getUint32(8)!==13||v.getUint32(12)!==0x49484452||v.getUint32(16)!==layout.width||v.getUint32(20)!==layout.height)fail('Current PNG differs from its TIM dimensions.');
  return `data:image/png;base64,${encoded}`;
}
export async function decodeSlotSource(v,assetId,context){
  const fields=['schema_version','asset_id','project_source_key','source_scene_id','anchor_asset_id','current_sha256','byte_length','label','slot_index','image_layout','palette_count','read_only','project_changed','content_base64'];if(Object.hasOwn(v,'image_source'))fields.push('image_source');
  if(!exact(v,fields)||v.image_source&&(v.image_source.format!=='png-tim-source-v1'||v.image_source.conversion_report?.proposed_sha256!==v.current_sha256)||v.schema_version!=='legaia.texture-slot-edit-source.v1'||v.asset_id!==assetId||!authored(v.asset_id)||v.project_source_key!==context.sourceKey||v.source_scene_id!==context.sceneId||!v.anchor_asset_id?.startsWith('texture://')||!hash(v.current_sha256)||!integer(v.byte_length,20,1048576)||!integer(v.slot_index,1,1023)||typeof v.label!=='string'||!v.label.trim()||v.label.length>128||!validLayout(v.image_layout)||!integer(v.palette_count,0,32768)||![4,8].includes(v.image_layout.bpp)&&v.palette_count!==0||v.read_only!==true||v.project_changed!==false||typeof v.content_base64!=='string'||v.content_base64.length>1398104||v.content_base64.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(v.content_base64))fail('Current slot source differs from the selected scene.');
  const bytes=Uint8Array.from(atob(v.content_base64),c=>c.charCodeAt(0));
  const actual=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');
  if(bytes.length!==v.byte_length||actual!==v.current_sha256)fail('Current TIM hash or length differs from its source.');
  return structuredClone(v);
}

const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const button=text=>{const n=node('button',text);n.type='button';return n;};
export function openTextureSlotEditor({assetId,getContext,busy,setBusy,onApplied,onError=()=>{}}){
  const context=structuredClone(getContext()),contextKey=JSON.stringify(context),editing=authored(assetId),route=editing?'/api/texture-slot-edit':'/api/texture-slot';
  if(context.mode!=='edit'||!hash(context.sourceKey)||typeof assetId!=='string'||!(assetId.startsWith('texture://')||editing))fail('New texture import requires a selected Retail pack in Edit mode.');
  const dialog=node('dialog');dialog.id='texture-slot-dialog';dialog.className='project-dialog';Object.assign(dialog.style,{width:'min(820px,94vw)',maxHeight:'92vh',overflowY:'auto',boxSizing:'border-box'});
  const heading=node('div');heading.className='dialog-heading';const close=button('×');close.setAttribute('aria-label',editing?'Close authored texture edit':'Close new texture import');heading.append(node('h2',editing?'Edit authored texture slot':'Import new texture slot'),close);
  const help=node('p','Append a complete TIM to the selected texture pack. Its native image and palette coordinates determine placement. Existing slots keep their indices. Review placement and Proposed pixels before Apply.');
  if(editing)help.textContent='Replace this authored slot with a complete TIM. Its ID and native index stay fixed. Review mode, palette layout and VRAM placement; material bindings are not retargeted automatically.';
  const fromPng=button('Convert source PNG'),conversionEvidence=node('details');conversionEvidence.hidden=true;
  const sourceDownload=button('Download retained image sources');sourceDownload.hidden=true;
  const download=button('Download Current TIM');download.hidden=!editing;
  const file=node('input');file.type='file';file.accept='.tim';file.setAttribute('aria-label',editing?'Authored slot TIM file':'New texture TIM file');const fileLabel=node('label','Complete TIM · up to 1 MiB');fileLabel.append(file);
  const label=node('input');label.type='text';label.maxLength=128;label.setAttribute('aria-label',editing?'Authored slot name':'New texture name');const nameLabel=node('label','Texture name');nameLabel.append(label);
  const palette=node('input');palette.type='number';palette.min='0';palette.max='32767';palette.step='1';palette.value='0';palette.setAttribute('aria-label',editing?'Authored slot inspection palette':'New texture inspection palette');const paletteLabel=node('label','Inspection palette');paletteLabel.append(palette);
  const overlap=node('input');overlap.type='checkbox';overlap.setAttribute('aria-label',editing?'Accept edited texture potential overlaps':'Accept new texture potential overlaps');const choice=node('label','Accept the listed potential overlaps for this import');Object.assign(choice.style,{display:'flex',flexDirection:'row',gap:'8px',alignItems:'center',margin:'16px 0'});overlap.style.width='auto';choice.prepend(overlap);
  const reviewButton=button('Review new texture'),pixelsButton=button('Inspect proposed texture pixels'),applyButton=button('Apply reviewed new texture');const actions=node('div');actions.className='dialog-actions';actions.append(reviewButton,pixelsButton,applyButton);
  const status=node('p','Choose a complete TIM. Review and pixel inspection do not change the project.'),summary=node('section'),error=node('p');error.className='dialog-error';error.setAttribute('role','alert');
  if(editing){reviewButton.textContent='Review texture edit';applyButton.textContent='Apply reviewed texture edit';choice.lastChild.textContent='Accept the listed potential overlaps for this edit';}
  dialog.append(heading,help,download,sourceDownload,fromPng,fileLabel,nameLabel,paletteLabel,choice,actions,status,conversionEvidence,summary,error);document.body.append(dialog);
  let editSource=null,content=null,review=null,pending=null,controller=null,owner=null,generation=0,closed=false,pixelDialog=null,conversionEditor=null;
  const current=()=>!closed&&JSON.stringify(getContext())===contextKey;
  const request=()=>({...editing?{asset_id:assetId,expected_sha256:editSource?.current_sha256}:{anchor_asset_id:assetId},source_key:context.sourceKey,label:label.value,accept_potential_overlap:overlap.checked,content_base64:content?.base64});
  const reviewed=()=>current()&&review&&JSON.stringify(review.request)===JSON.stringify(request());
  function controls(){if(!closed&&!current()){review=null;summary.replaceChildren();status.textContent='Project, scene, mode or source changed. Reopen new texture import.';}const blocked=!current()||pending!==null||busy()||editing&&!editSource;download.disabled=blocked;sourceDownload.disabled=blocked;fromPng.disabled=blocked;conversionEditor?.update();for(const input of [file,label,overlap,palette])input.disabled=blocked;reviewButton.disabled=blocked||!content||!label.value.trim();pixelsButton.disabled=blocked||!reviewed()||!integer(Number(palette.value),0,Math.max(1,review?.report.palette_count??0)-1)||palette.value.trim()==='';applyButton.disabled=blocked||!reviewed()||!review.report.can_apply;close.disabled=pending==='apply';}
  function release(token){if(token&&owner===token){owner=null;setBusy(false);}}
  function invalidate(){generation++;controller?.abort();controller=null;pending=null;release(owner);review=null;summary.replaceChildren();pixelDialog?.close();controls();}
  function dispose(){if(closed)return;closed=true;invalidate();pixelDialog?.remove();conversionEditor?.dispose();dialog.remove();}
  async function run(kind,work){if(!current()||pending||busy()||!dialog.open)return;const token={},ticket=++generation;owner=token;pending=kind;controller=new AbortController();const signal=controller.signal;setBusy(true);error.textContent='';controls();const valid=()=>current()&&generation===ticket&&!signal.aborted;try{await work(signal,valid);}catch(e){if(valid()&&e.name!=='AbortError'){review=null;summary.replaceChildren();error.textContent=e.message;onError(e);}}finally{release(token);if(ticket===generation){pending=null;controller=null;controls();}}}
  async function post(route,body,signal,max=1048576){const response=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal}),text=await response.text();if(new TextEncoder().encode(text).length>max)fail('New texture response exceeds its inspection budget.');const result=JSON.parse(text);if(!response.ok||result.error)fail(result.error||'New texture request failed.');return result;}
  for(const input of [label,overlap])input.oninput=()=>{invalidate();status.textContent='Choices changed. Review again before inspection or Apply.';};
  palette.oninput=()=>{pixelDialog?.close();controls();};
  file.onchange=()=>{invalidate();content=null;conversionEvidence.hidden=true;conversionEvidence.replaceChildren();controls();const selected=file.files?.[0];if(!selected)return;return run('file',async(signal,valid)=>{if(selected.size<20||selected.size>1048576)fail('Choose a complete TIM up to 1 MiB.');const bytes=new Uint8Array(await selected.arrayBuffer()),sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(!valid())return;let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));content={sha256,size:bytes.length,base64:btoa(binary)};if(!label.value.trim())label.value=selected.name.replace(/\.tim$/i,'').slice(0,128);status.textContent=`${selected.name} · ${bytes.length} bytes. Review the native allocation.`;});};
  fromPng.onclick=()=>{if(fromPng.disabled)return;conversionEditor?.dispose();let initialOptions=null;if(editSource){const bytes=Uint8Array.from(atob(editSource.content_base64),c=>c.charCodeAt(0)),native=new DataView(bytes.buffer),indexed=editSource.image_layout.bpp<=8&&(native.getUint32(4,true)&8)!==0;initialOptions={bpp:editSource.image_layout.bpp,image_x:editSource.image_layout.x,image_y:editSource.image_layout.y,clut_x:indexed?native.getUint16(12,true):0,clut_y:indexed?native.getUint16(14,true):0,stp_mode:'opaque'};}conversionEditor=openImageConversion({assetId,getContext,busy,setBusy,onError,initialOptions,currentSha256:editSource?.current_sha256??null,onRetained:next=>{onApplied(next);dispose();},onDraft:(draft,name)=>{if(!current())fail('Project changed before the converted draft returned.');invalidate();content=draft;file.value='';if(!label.value.trim())label.value=name.replace(/\.png$/i,'').slice(0,128);const pre=node('pre',JSON.stringify(draft.conversion,null,2));pre.style.overflowWrap='anywhere';conversionEvidence.replaceChildren(node('summary','Source PNG conversion evidence'),pre);conversionEvidence.hidden=false;status.textContent=`Converted ${name} to ${draft.size} TIM bytes. Review native placement and inspect Proposed pixels before Apply.`;controls();}});};
  reviewButton.onclick=()=>{if(reviewButton.disabled)return;review=null;summary.replaceChildren();const body=request(),selected=content;return run('review',async(signal,valid)=>{const result=await post(route+'-review',body,signal);if(!valid()||selected!==content||JSON.stringify(body)!==JSON.stringify(request()))return;const report=decodeSlotReview(result,body,selected,false,editing);if(report.source_scene_id!==context.sceneId)fail('New texture review belongs to another scene.');review={request:body,report};palette.max=String(Math.max(1,report.palette_count)-1);const l=report.image_layout;summary.append(node('h3','Proposed · not applied'),node('p',`Native slot ${report.slot_index} · ${l.width} × ${l.height} pixels · ${l.bpp} bpp · VRAM (${l.x}, ${l.y}) · ${report.palette_count} palettes`),node('p',`${report.footprint.potential_overlap_count} potential overlaps. Runtime residency and upload order remain unverified.`));const details=node('details'),pre=node('pre',JSON.stringify({overlaps:report.footprint,source_pack:report.source_pack_sha256,proposed:report.proposed_sha256,review:report.review_key},null,2));pre.style.overflowWrap='anywhere';details.append(node('summary','Placement evidence and hashes'),pre);summary.append(details);status.textContent=editing&&!report.changed?'Current TIM and name are unchanged. Choose a change before Apply.':report.can_apply?'Review complete. Inspect Proposed pixels or Apply, then Save project.':'Overlaps found. Accept that choice and review again to enable Apply.';});};
  pixelsButton.onclick=()=>{if(pixelsButton.disabled)return;const accepted=review,index=Number(palette.value),selected=content;return run('pixels',async(signal,valid)=>{const result=await post(route+'-pixels',{...accepted.request,review_key:accepted.report.review_key,palette_index:index},signal,16*1024*1024);if(!valid()||review!==accepted)return;const image=decodeSlotPixels(result,accepted.report,accepted.request,selected,index,editing);pixelDialog=node('dialog');pixelDialog.id='texture-slot-pixels-dialog';Object.assign(pixelDialog.style,{width:'min(1000px,94vw)',maxHeight:'92vh',overflowY:'auto'});const img=node('img');img.src=editing?image.proposed:image;img.alt='Proposed new texture pixels';img.style.maxWidth='100%';img.style.width=`${Math.min(768,Math.max(256,accepted.report.image_layout.width))}px`;img.style.height='auto';img.style.display='block';img.style.margin='16px 0';img.style.background='repeating-conic-gradient(#253239 0% 25%,#182328 0% 50%) 0 0 / 16px 16px';img.style.imageRendering='pixelated';const back=button(editing?'Return to texture edit review':'Return to new texture review');back.onclick=()=>pixelDialog.close();if(editing){pixelDialog.append(node('h3',accepted.report.current_layout.bpp>=16?'Current - direct color':'Current - palette 0'));if(image.current){const before=img.cloneNode();before.src=image.current;before.alt='Current authored texture pixels';pixelDialog.append(before);}else pixelDialog.append(node('p','Current has no complete local palette for pixel decoding.'));}
    pixelDialog.append(node('h2','Proposed texture · not applied'),node('p',`${accepted.report.image_layout.bpp>=16?'Direct color':`Palette ${index}`}. Transparent-zero alpha is shown; runtime STP blending is unverified.`),img,back);document.body.append(pixelDialog);pixelDialog.onclose=()=>{pixelDialog.remove();pixelDialog=null;};pixelDialog.showModal();});};
  applyButton.onclick=()=>{if(applyButton.disabled)return;const accepted=review,selected=content;return run('apply',async(signal,valid)=>{const next=await post(route+'-apply',{...accepted.request,review_key:accepted.report.review_key},signal,16*1024*1024);if(!valid()||review!==accepted)return;const report=decodeSlotReview(next.texture_slot_report,accepted.request,selected,true,editing);if(report.review_key!==accepted.report.review_key||next.project?.path!==context.projectPath||next.project?.mode!=='edit'||next.scene?.id!==context.sceneId)fail('New texture Apply returned another project, scene or review.');await onApplied(next);dispose();});};
  close.onclick=()=>{if(pending!=='apply')dispose();};dialog.oncancel=e=>{e.preventDefault();if(pending!=='apply')dispose();};dialog.onclose=dispose;dialog.showModal();controls();
  sourceDownload.onclick=()=>{if(sourceDownload.disabled||!editSource?.image_source)return;return run('sources',async(signal,valid)=>{const result=await post('/api/texture-slot-source-download',{asset_id:assetId,expected_sha256:editSource.current_sha256,source_key:context.sourceKey},signal,24*1024*1024);if(!valid())return;if(result.asset_id!==assetId||result.project_source_key!==context.sourceKey||result.effective_sha256!==editSource.current_sha256||JSON.stringify(result.source)!==JSON.stringify(editSource.image_source)||result.read_only!==true||result.project_changed!==false)fail('Retained sources differ from Current.');for(const [kind,encoded] of [['png',result.png_base64],['stp_png',result.stp_png_base64]]){if(encoded===null&&kind==='stp_png'&&result.source.stp_png_sha256===null)continue;if(typeof encoded!=='string'||encoded.length>11184812||encoded.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))fail('Retained PNG download is malformed.');const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(!valid())return;if(bytes.length!==result.source[kind+'_byte_length']||hash!==result.source[kind+'_sha256'])fail('Retained PNG hash or length changed.');const url=URL.createObjectURL(new Blob([bytes],{type:'image/png'})),a=node('a');a.href=url;a.download=kind==='png'?'source.png':'source-stp.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}const url=URL.createObjectURL(new Blob([JSON.stringify(result.source,null,2)],{type:'application/json'})),a=node('a');a.href=url;a.download='source-recipe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0);});};
  download.onclick=()=>{if(!current()||!editSource||download.disabled)return;const bytes=Uint8Array.from(atob(editSource.content_base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),a=node('a');a.href=url;a.download=editSource.label.replace(/[^a-zA-Z0-9_-]/g,'_')+'.tim';a.click();setTimeout(()=>URL.revokeObjectURL(url),0);};
  if(editing)run('source',async(signal,valid)=>{const result=await post(route+'-source',{asset_id:assetId,source_key:context.sourceKey},signal,2*1024*1024),qualified=await decodeSlotSource(result,assetId,context);if(!valid())return;editSource=qualified;sourceDownload.hidden=!qualified.image_source;label.value=qualified.label;status.textContent=`Current slot ${qualified.slot_index} - ${qualified.byte_length} bytes. Choose an edited complete TIM or download Current.`;});
  return {dialog,dispose,update:controls};
}
