// Source-bound P2 targets come from the SDK; this panel never decodes MAN or writes runtime RAM.
const hash=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v);
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const integer=(v,max)=>Number.isSafeInteger(v)&&v>=0&&v<=max;
const fail=message=>{throw new Error(message);};
export function triggerScriptEditable(record){return record?.type==='trigger'&&record.data?.table_source==='primary'&&record.data?.table_kind===1&&record.data?.encoded?.gate===1&&/^trigger:\/\/[A-Za-z0-9_-]{1,128}\/field-map\/primary\/kind-1\/[0-9]{4}$/.test(record.id);}
export function decodeTriggerScriptsReview(value,record,state){
  const keys=['schema_version','read_only','project_source_key','scene_id','trigger_id','source','map_sha256','targets','layers','requested_script_id','action','value','audit','proposed_map_sha256','project_change','activation','gameplay_verified','review_key'];
  if(!triggerScriptEditable(record)||record.sceneId!==state.scene?.id||state.project?.mode!=='edit'||!exact(value,keys)||value.schema_version!=='legaia.trigger-scripts-review.v1'||value.read_only!==true||value.project_source_key!==state.project_copy_source_key||!hash(value.project_source_key)||value.scene_id!==state.scene.id||value.trigger_id!==record.id||!hash(value.map_sha256)||!hash(value.proposed_map_sha256)||!hash(value.review_key)||typeof value.project_change!=='boolean'||value.activation!=='not_evaluated'||value.gameplay_verified!==false)fail('Trigger script review changed or has invalid source context.');
  const name=state.scene.id.slice(8),targetId=id=>typeof id==='string'&&new RegExp(`^script://${name}/scripts/man-p2/[0-9]{4}$`).test(id)&&Number(id.slice(-4))<=255;
  const source=value.source,catalog=record.data.source_record;
  if(!exact(source,['trigger_id','table_kind','record_index','byte_offset','byte_length','sha256','encoded','tile_bounds'])||source.trigger_id!==record.id||source.table_kind!==1||source.record_index!==record.data.record_index||source.byte_offset!==catalog?.byte_offset||source.byte_length!==4||source.sha256!==catalog?.sha256||!hash(source.sha256)||!exact(source.encoded,['tile_x','tile_z','record_index','gate'])||Object.keys(source.encoded).some(k=>source.encoded[k]!==record.data.encoded[k])||source.encoded.gate!==1)fail('Trigger review differs from its immutable catalog row.');
  if(!Array.isArray(value.targets)||value.targets.length>256)fail('Trigger target budget exceeded.');
  const targets=new Map();
  for(const target of value.targets){const src=target?.source_record;
    if(!exact(target,['script_id','source_sha256','record_index','source_record','inspection_status'])||!targetId(target.script_id)||target.record_index!==Number(target.script_id.slice(-4))||!hash(target.source_sha256)||targets.has(target.script_id)||src?.sha256!==target.source_sha256||src?.record_index!==target.record_index||src?.partition!==2||src?.record_alias_count!==1||!integer(src?.byte_offset,4*1024*1024)||!integer(src?.byte_length,4*1024*1024)||src.byte_length===0||!['decoded_lzs_descriptor','raw_man_payload'].includes(src.byte_coordinate_space)||src.disc?.sha256!==catalog?.disc?.sha256||src.disc?.serial!=='SCUS-94254'||src.iso_file!=='PROT.DAT'||typeof target.inspection_status!=='string'||target.inspection_status==='unavailable')fail('Trigger script target has invalid identity, hash or source ownership.');
    targets.set(target.script_id,target);
  }
  const layers=value.layers,imported=`script://${name}/scripts/man-p2/${String(source.encoded.record_index).padStart(4,'0')}`;
  if(!exact(layers,['imported','authored','current','proposed'])||layers.imported!==imported||![layers.current,layers.proposed].every(targetId)||layers.authored!==null&&!targets.has(layers.authored)||layers.current!==(layers.authored??imported)||!['set','clear'].includes(value.action)||value.requested_script_id!==null&&!targets.has(value.requested_script_id)||value.action==='clear'&&value.requested_script_id!==null||layers.proposed!==(value.action==='clear'?imported:value.requested_script_id??layers.current)||value.action==='set'&&value.requested_script_id===null&&value.project_change)fail('Trigger binding layers differ from the reviewed request.');
  const binding=value.value;
  if(!exact(binding,['source_sha256','edits'])||binding.source_sha256!==value.map_sha256||!Array.isArray(binding.edits)||binding.edits.length>2043||!Array.isArray(value.audit)||value.audit.length>binding.edits.length)fail('Invalid authored trigger binding or byte audit.');
  const edits=new Map();let previous='';
  for(const edit of binding.edits){if(!exact(edit,['trigger_id','script_id','script_sha256'])||typeof edit.trigger_id!=='string'||!new RegExp(`^trigger://${name}/field-map/primary/kind-1/[0-9]{4}$`).test(edit.trigger_id)||Number(edit.trigger_id.slice(-4))>2042||edits.has(edit.trigger_id)||edit.trigger_id<previous||!targets.has(edit.script_id)||edit.script_sha256!==targets.get(edit.script_id).source_sha256)fail('Trigger proposal binding has stale targets or invalid row ownership.');edits.set(edit.trigger_id,edit);previous=edit.trigger_id;}
  if((edits.get(record.id)?.script_id??imported)!==layers.proposed)fail('Selected trigger differs from the proposed scene binding.');
  const seen=new Set();for(const row of value.audit){const edit=edits.get(row?.trigger_id);
    if(!exact(row,['trigger_id','target_script_id','target_script_sha256','table_kind','record_index','field','byte_offset','before_value','after_value','scope'])||!edit||row.target_script_id!==edit.script_id||row.target_script_sha256!==edit.script_sha256||row.table_kind!==1||row.record_index!==Number(row.trigger_id.slice(-4))||row.field!=='trigger.record_index'||row.scope!=='source-MAP-trigger-P2-binding-only'||!integer(row.byte_offset,0x11fff)||row.byte_offset<0x10014||!integer(row.before_value,255)||row.after_value!==targets.get(edit.script_id).record_index||row.before_value===row.after_value||seen.has(row.byte_offset)||row.trigger_id===record.id&&(row.byte_offset!==source.byte_offset+2||row.before_value!==source.encoded.record_index))fail('Trigger audit differs from a reviewed target byte.');seen.add(row.byte_offset);}
  if(layers.proposed!==imported&&!value.audit.some(row=>row.trigger_id===record.id))fail('Missing selected trigger byte audit.');
  return structuredClone(value);
}

const element=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
export function openTriggerScripts({record,getState,current,busy,setBusy,api,onInspect,onError=()=>{}}){
  if(!triggerScriptEditable(record)||busy()||!current()||getState().project?.mode!=='edit')return null;
  const binding=getState().project_copy_source_key,dialog=element('dialog');dialog.id='trigger-scripts-dialog';dialog.className='project-dialog';Object.assign(dialog.style,{width:'min(850px,90vw)',maxHeight:'90vh',overflowY:'auto'});
  const heading=element('div');heading.className='dialog-heading';const close=element('button','×');close.type='button';close.setAttribute('aria-label','Close trigger script binding');heading.append(element('h2','Trigger script binding'),close);
  const note=element('p','Choose an existing partition-two source script. Only the encoded target-index byte changes; coordinates, gate and row order remain separately owned. Actual trigger activation and script dispatch require gameplay verification.');
  const label=element('label','Target script'),select=element('select');select.setAttribute('aria-label','Trigger target script');label.append(select);
  const status=element('p');status.setAttribute('role','status');const output=element('div');output.dataset.triggerScriptReview='';const actions=element('div');actions.className='dialog-actions';Object.assign(actions.style,{flexWrap:'wrap',justifyContent:'flex-start'});
  const button=text=>{const n=element('button',text);n.type='button';actions.append(n);return n;},reviewButton=button('Review binding'),reset=button('Review Retail binding'),inspectCurrent=button('Inspect Current script'),inspectProposed=button('Inspect Proposed script'),applyButton=button('Apply reviewed binding');dialog.append(heading,note,label,status,output,actions);
  let closed=false,pending=false,controller=null,generation=0,accepted=null;
  const fresh=()=>!closed&&current()&&getState().project?.mode==='edit'&&getState().project_copy_source_key===binding;
  const withdraw=()=>{accepted=null;output.replaceChildren();};
  function refresh(){const blocked=pending||busy()||!fresh();select.disabled=blocked;reviewButton.disabled=blocked||!select.value;reset.disabled=blocked;applyButton.disabled=blocked||!accepted?.project_change;inspectCurrent.disabled=blocked||!accepted||!accepted.targets.some(t=>t.script_id===accepted.layers.current);inspectProposed.disabled=blocked||!accepted||!accepted.targets.some(t=>t.script_id===accepted.layers.proposed);if(!fresh()&&!closed)status.textContent='Project or trigger context changed. Reopen this review.';}
  function dispose(){if(closed)return;closed=true;generation++;if(controller){controller.abort();controller=null;setBusy(false);}if(dialog.open)dialog.close();dialog.remove();}
  async function load(script=null,action='set',initial=false){
    if(pending||busy()||!fresh())return;withdraw();const token=++generation,choice=select.value,active=new AbortController();controller=active;pending=true;setBusy(true);refresh();status.textContent='Qualifying trigger row and source script targets…';
    try{const response=await fetch('/api/trigger-scripts-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trigger_id:record.id,script_id:script,action}),signal:active.signal}),value=await response.json();if(closed||token!==generation||active.signal.aborted||!fresh()||choice!==select.value)return;if(!response.ok||value.error)fail(value.error??'Trigger binding review failed.');const report=decodeTriggerScriptsReview(value,record,getState());if(report.requested_script_id!==script||report.action!==action)fail('Review differs from requested target.');accepted=report;
      if(initial){select.replaceChildren();for(const target of report.targets){const option=element('option',`Partition 2 script ${target.record_index} · ${target.inspection_status==='partial'?'Partial inspection':'Supported paths decoded'}`);option.value=target.script_id;select.append(option);}select.value=report.layers.current;if(!select.value){const option=element('option','Current binding unavailable · choose a qualified target');option.value='';option.selected=true;select.prepend(option);}}
      const table=element('table');for(const [layer,title] of [['imported','Retail'],['authored','Authored'],['current','Current'],['proposed','Proposed']]){const row=element('tr');row.append(element('th',title),element('td',report.layers[layer]??'None · inherit'));table.append(row);}const details=element('details'),summary=element('summary','Source target metadata and exact byte audit'),pre=element('pre');pre.className='diagnostic-detail';pre.textContent=JSON.stringify(report,null,2);details.append(summary,pre);output.append(table,details);status.textContent=report.project_change?'Ready for one undoable Apply.':'No project change.';
    }catch(error){if(!closed&&token===generation&&error.name!=='AbortError'){status.textContent=error.message;onError(error);}}
    finally{if(controller===active){controller=null;pending=false;setBusy(false);}refresh();}
  }
  select.onchange=()=>{withdraw();status.textContent='Target changed; review the binding again.';refresh();};reviewButton.onclick=()=>load(select.value);reset.onclick=()=>load(null,'clear');
  for(const [button,layer] of [[inspectCurrent,'current'],[inspectProposed,'proposed']])button.onclick=()=>{if(!fresh()||busy()||pending||!accepted||!accepted.targets.some(t=>t.script_id===accepted.layers[layer]))return;onInspect?.(accepted.layers[layer]);};
  applyButton.onclick=async()=>{if(!fresh()||busy()||pending||!accepted?.project_change)return;const report=accepted;pending=true;refresh();try{if(await api('/api/trigger-scripts-apply',{type:'apply_trigger_scripts',trigger_id:record.id,script_id:report.requested_script_id,action:report.action,review_key:report.review_key})){dispose();return;}withdraw();status.textContent='Apply rejected. Review the current binding again.';}catch(error){withdraw();status.textContent=error.message;onError(error);}finally{pending=false;refresh();}};
  close.onclick=()=>dialog.close();dialog.addEventListener('close',dispose);dialog.dispose=dispose;dialog.refresh=refresh;document.body.append(dialog);dialog.showModal();refresh();void load(null,'set',true);return dialog;
}
