import {triggerCellSource} from './trigger-cells.js';
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const hash=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v);
const cells=v=>exact(v,['tile_x','tile_z'])&&Object.values(v).every(n=>Number.isSafeInteger(n)&&n>=0&&n<=255);
const same=(a,b)=>['tile_x','tile_z'].every(k=>a[k]===b[k]);
const fail=message=>{throw new Error(message);};
export function decodeTriggerGroup(value,records,state,request){
  const keys=['schema_version','read_only','project_source_key','scene_id','trigger_ids','delta','action','rows','value','audit','proposed_map_sha256','project_change','changed_cell_count','scope','height_status','activation','gameplay_verified','review_key'];
  if(!exact(value,keys)||value.schema_version!=='legaia.trigger-group-review.v1'||value.read_only!==true||value.project_source_key!==state.project_copy_source_key||value.scene_id!==state.scene?.id||value.scope!=='source-MAP-trigger-cell-only'||value.height_status!=='unknown'||value.activation!=='not_evaluated'||value.gameplay_verified!==false||!hash(value.review_key)||!hash(value.proposed_map_sha256)||typeof value.project_change!=='boolean')fail('Trigger group review changed or has invalid source context.');
  const ids=[...request.trigger_ids].sort();
  if(ids.length<1||ids.length>128||new Set(ids).size!==ids.length||JSON.stringify(value.trigger_ids)!==JSON.stringify(ids)||value.action!==request.action||!['translate','retail'].includes(value.action)||!exact(value.delta,['x','z'])||Object.keys(value.delta).some(k=>value.delta[k]!==request.delta[k]||!Number.isSafeInteger(value.delta[k])||Math.abs(value.delta[k])>255)||value.action==='retail'&&Object.values(value.delta).some(Boolean))fail('Trigger group review differs from the requested selection or offset.');
  const sources=new Map(records.map(record=>[record.id,triggerCellSource(record,state)])),stored=state.authored_assets?.find(row=>row.id===state.scene.id)?.authored?.TriggerCells;
  const expected=new Map((stored?.edits??[]).map(row=>[row.trigger_id,{...row}]));
  if(!Array.isArray(value.rows)||value.rows.length!==ids.length||!exact(value.value,['source_sha256','edits'])||!hash(value.value.source_sha256)||state.scene_selection_map_sha256!=null&&state.scene_selection_map_sha256!==value.value.source_sha256||stored&&stored.source_sha256!==value.value.source_sha256||!Array.isArray(value.value.edits)||value.value.edits.length>2043)fail('Trigger group binding or reviewed rows are invalid.');
  let changed=0;
  for(const [index,row] of value.rows.entries()){
    const context=sources.get(ids[index]),source=row?.source,layers=row?.layers;
    if(!context||!exact(row,['trigger_id','source','layers'])||row.trigger_id!==ids[index]||!exact(source,['trigger_id','table_kind','record_index','byte_offset','byte_length','sha256','encoded','tile_bounds'])||source.trigger_id!==row.trigger_id||source.sha256!==context.source.sha256||source.byte_offset!==context.source.byte_offset||source.byte_length!==4||source.table_kind!==context.id.kind||source.record_index!==context.id.index||!exact(source.encoded,Object.keys(context.imported).concat(Object.keys(context.payload)))||Object.keys(source.encoded).some(k=>source.encoded[k]!==({...context.imported,...context.payload})[k])||!exact(source.tile_bounds,['x_min','x_max','z_min','z_max'])||source.tile_bounds.x_min!==context.imported.tile_x||source.tile_bounds.x_max!==context.imported.tile_x+1||source.tile_bounds.z_min!==context.imported.tile_z||source.tile_bounds.z_max!==context.imported.tile_z+1||!exact(layers,['imported','current','proposed'])||!Object.values(layers).every(cells)||!same(layers.imported,context.imported))fail('Trigger group row differs from its immutable source.');
    const current=expected.get(row.trigger_id)??context.imported;
    const proposed=value.action==='retail'?context.imported:{tile_x:current.tile_x+value.delta.x,tile_z:current.tile_z+value.delta.z};
    if(!same(layers.current,current)||!same(layers.proposed,proposed))fail('Trigger group coordinate layers differ from authored state or offset.');
    if(!same(current,proposed))changed++;
    if(same(proposed,context.imported))expected.delete(row.trigger_id);else expected.set(row.trigger_id,{trigger_id:row.trigger_id,...proposed});
  }
  const edits=[...expected.values()].sort((a,b)=>a.trigger_id<b.trigger_id?-1:a.trigger_id>b.trigger_id?1:0);
  const unchanged=stored?stored.edits.length===edits.length&&stored.edits.every(row=>expected.has(row.trigger_id)&&same(row,expected.get(row.trigger_id))):edits.length===0;
  if(value.project_change===unchanged)fail('Trigger group project-change claim differs from retained authored state.');
  if(value.changed_cell_count!==changed||changed>0&&!value.project_change||value.value.edits.length!==edits.length||value.value.edits.some((row,i)=>!exact(row,['trigger_id','tile_x','tile_z'])||row.trigger_id!==edits[i].trigger_id||!same(row,edits[i])))fail('Trigger group binding differs from reviewed rows or preserved unselected edits.');
  if(!Array.isArray(value.audit)||value.audit.length>4090)fail('Trigger group audit exceeds its byte budget.');
  const expectedAudit=new Map();for(const edit of edits){const source=sources.get(edit.trigger_id);if(!source)fail('Trigger group retained an unavailable source row.');for(const [offset,field] of ['tile_x','tile_z'].entries())if(edit[field]!==source.imported[field])expectedAudit.set(source.source.byte_offset+offset,{id:edit.trigger_id,field,before:source.imported[field],after:edit[field],kind:source.id.kind,index:source.id.index});}
  if(value.audit.length!==expectedAudit.size)fail('Trigger group audit lacks a changed source byte.');
  for(const row of value.audit){const expected=expectedAudit.get(row?.byte_offset);if(!expected||!exact(row,['trigger_id','table_kind','record_index','field','byte_offset','before_value','after_value','scope'])||row.trigger_id!==expected.id||row.table_kind!==expected.kind||row.record_index!==expected.index||row.field!=='trigger.'+expected.field||row.before_value!==expected.before||row.after_value!==expected.after||row.scope!=='source-MAP-trigger-cell-only')fail('Trigger group audit differs from an owned coordinate byte.');expectedAudit.delete(row.byte_offset);}
  return structuredClone(value);
}

const element=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
export function openTriggerGroup({record,records,getState,current,busy,setBusy,api,onError=()=>{}}){
  if(busy()||!current()||getState().project?.mode!=='edit')return null;
  const state=getState(),key=state.project_copy_source_key,scene=state.scene.id,available=records.filter(row=>row.type==='trigger'&&row.sceneId===scene&&row.data?.table_source==='primary'&&[0,1].includes(row.data?.table_kind));
  for(const row of available)triggerCellSource(row,state);
  if(!available.some(row=>row.id===record.id))fail('Choose a supported primary trigger cell.');
  const dialog=element('dialog');dialog.id='trigger-group-dialog';dialog.className='project-dialog';Object.assign(dialog.style,{width:'min(850px,90vw)',maxHeight:'90vh',overflowY:'auto'});
  const heading=element('div');heading.className='dialog-heading';const close=element('button','×');close.setAttribute('aria-label','Close trigger group');heading.append(element('h2','Move trigger cell group'),close);
  const note=element('p','Select up to 128 primary cells. Offsets use raw tile coordinates (128 world units per tile). Payloads, row order and unselected authored cells stay preserved. Moving cells can change first-match shadowing; height, activation and gameplay remain unverified.');
  const list=element('div');Object.assign(list.style,{maxHeight:'240px',overflowY:'auto'});const choices=[];
  for(const row of available){const label=element('label'),input=element('input');input.type='checkbox';input.value=row.id;input.checked=row.id===record.id;input.setAttribute('aria-label',row.id);Object.assign(label.style,{display:'flex',flexDirection:'row',alignItems:'center',gap:'8px',minHeight:'28px',margin:'4px 0'});Object.assign(input.style,{width:'16px',height:'16px',margin:'0',flexShrink:'0'});label.title=row.id;label.append(input,document.createTextNode(row.label));list.append(label);choices.push(input);}
  const controls=element('div');Object.assign(controls.style,{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'12px'});const offsets={};for(const axis of ['x','z']){const label=element('label',`Tile offset ${axis.toUpperCase()}`),input=element('input');input.type='number';input.min='-255';input.max='255';input.step='1';input.value='0';input.setAttribute('aria-label',`Trigger group tile offset ${axis.toUpperCase()}`);Object.assign(input.style,{width:'100%',minWidth:'0'});label.append(input);controls.append(label);offsets[axis]=input;}
  const status=element('p');status.setAttribute('role','status');const output=element('div'),actions=element('div');actions.className='dialog-actions';actions.style.flexWrap='wrap';
  const button=text=>{const node=element('button',text);node.type='button';actions.append(node);return node;},review=button('Review group move'),retail=button('Review Retail cells'),apply=button('Apply reviewed group');dialog.append(heading,note,list,controls,status,output,actions);
  let closed=false,pending=false,controller=null,accepted=null,generation=0;
  const fresh=()=>!closed&&current()&&getState().project?.mode==='edit'&&getState().project_copy_source_key===key;
  const selection=()=>choices.filter(input=>input.checked).map(input=>input.value).sort();
  const withdraw=()=>{generation++;accepted=null;output.replaceChildren();status.textContent='Selection or offset changed. Review again.';refresh();};
  function refresh(){const blocked=pending||busy()||!fresh(),count=selection().length;for(const input of [...choices,...Object.values(offsets)])input.disabled=blocked;review.disabled=retail.disabled=blocked||count<1||count>128;apply.disabled=blocked||!accepted?.project_change;}
  function dispose(){if(closed)return;closed=true;generation++;controller?.abort();if(controller)setBusy(false);controller=null;if(dialog.open)dialog.close();dialog.remove();}
  async function load(action){if(pending||busy()||!fresh())return;accepted=null;output.replaceChildren();const delta=action==='retail'?{x:0,z:0}:Object.fromEntries(Object.entries(offsets).map(([axis,input])=>[axis,input.value.trim()?Number(input.value):NaN])),request={scene_id:scene,trigger_ids:selection(),delta,action};if(Object.values(delta).some(n=>!Number.isSafeInteger(n)||Math.abs(n)>255)){status.textContent='Enter integer tile offsets in -255..255.';refresh();return;}
    const active=new AbortController(),token=++generation;controller=active;pending=true;setBusy(true);refresh();status.textContent='Qualifying selected source cells…';
    try{const response=await fetch('/api/trigger-group-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request),signal:active.signal}),value=await response.json();if(!fresh()||active.signal.aborted||token!==generation)return;if(!response.ok||value.error)fail(value.error??'Trigger group review failed.');accepted=decodeTriggerGroup(value,available,getState(),request);
      const table=element('table'),header=element('tr');Object.assign(table.style,{width:'100%',tableLayout:'fixed',fontSize:'12px',overflowWrap:'anywhere'});for(const label of ['Source cell','Retail X/Z','Current X/Z','Proposed X/Z'])header.append(element('th',label));table.append(header);for(const row of accepted.rows){const line=element('tr');line.append(element('td',row.trigger_id));for(const layer of ['imported','current','proposed'])line.append(element('td',`${row.layers[layer].tile_x}, ${row.layers[layer].tile_z}`));table.append(line);}const details=element('details'),summary=element('summary','Qualified source and exact coordinate-byte audit'),pre=element('pre');pre.className='diagnostic-detail';pre.textContent=JSON.stringify(accepted,null,2);details.append(summary,pre);output.append(table,details);status.textContent=`${accepted.changed_cell_count} changed cells · ${accepted.project_change?'Ready for one undoable Apply.':'No project change.'}`;
    }catch(error){if(!closed&&token===generation&&error.name!=='AbortError'){accepted=null;status.textContent=error.message;onError(error);}}finally{if(controller===active){controller=null;pending=false;setBusy(false);}refresh();}}
  for(const input of [...choices,...Object.values(offsets)])input.oninput=withdraw;
  review.onclick=()=>load('translate');retail.onclick=()=>load('retail');apply.onclick=async()=>{if(pending||busy()||!fresh()||!accepted?.project_change)return;const report=accepted;pending=true;refresh();try{if(await api('/api/trigger-group-apply',{type:'apply_trigger_group',scene_id:scene,trigger_ids:report.trigger_ids,delta:report.delta,action:report.action,review_key:report.review_key})){dispose();return;}withdraw();}catch(error){withdraw();status.textContent=error.message;onError(error);}finally{pending=false;refresh();}};
  close.onclick=()=>dialog.close();dialog.addEventListener('close',dispose);dialog.dispose=dispose;dialog.refresh=refresh;document.body.append(dialog);dialog.showModal();refresh();status.textContent='Choose cells and review a move or Retail reset.';return dialog;
}
