import assert from 'node:assert/strict';
import fs from 'node:fs';
import {npcScriptBindingSnapshot,npcDraftActionContext,npcScriptActionButtons} from '../editor/npc-draft-inspector.js';
const id='authored-actor://fixture',donor='scene://fixture/actors/man-p1/0001',families=['dialogue','waits','movement','facing','flags','branches','model_selectors','effect_colors'];
const state={actor_drafts:{[id]:{scene_id:'scene://fixture',donor_entity_id:donor}},npc_script_bindings:{[id]:{schema_version:'legaia.npc-script-binding.v1',entity_id:id,scene_id:'scene://fixture',donor_entity_id:donor,source_script_id:'script://fixture/actors/man-p1/0001',authored_draft_sha256:'a'.repeat(64),authored_counts:Object.fromEntries(families.map(f=>[f,0])),source_qualification:'inspect_retail_donor_script',generated_qualification:'inspect_saved_build_script',runtime_binding:'not_asserted'}}};
const snapshot=npcScriptBindingSnapshot(state,id);snapshot.authored_counts.flags=12;assert.equal(state.npc_script_bindings[id].authored_counts.flags,0);assert.equal(Object.keys(npcScriptActionButtons).length,10);
for(const mutate of [s=>s.npc_script_bindings[id].donor_entity_id='scene://other/actors/man-p1/0001',s=>s.npc_script_bindings[id].runtime_binding='confirmed',s=>s.npc_script_bindings[id].authored_counts.flags=1,s=>s.npc_script_bindings[id].authored_counts.flags=true,s=>s.npc_script_bindings[id].authored_counts.extra=0,s=>s.npc_script_bindings[id].source_script_id='script://wrong',s=>s.npc_script_bindings[id].authored_draft_sha256='bad']){const bad=structuredClone(state);mutate(bad);assert.throws(()=>npcScriptBindingSnapshot(bad,id));}
const before=npcDraftActionContext(state,id),changed=structuredClone(state);changed.actor_drafts[id].name='new';assert.notEqual(before,npcDraftActionContext(changed,id));
if(process.argv[2]){const actual=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));for(const owner of Object.keys(actual.actor_drafts))assert.equal(npcScriptBindingSnapshot(actual,owner).authored_counts.effect_colors,1);}
console.log('NPC script binding: detached authored counts, source ownership, live rejection, action coverage and freshness passed.');
