// Run against a fresh retail project fixture, not a fixture generated by the client.
import fs from 'node:fs';import assert from 'node:assert/strict';
import {decodeSampleOptions,decodeSampleReview,decodeSamplePcm,decodeSampleReceipt,decodeSampleUploadReview} from '../editor/audio-sample-contract.js';
import {openSampleAuthoring} from '../editor/audio-sample-authoring.js';
const file=process.argv[2];if(!file)throw Error('Provide a freshly qualified retail sample editor contract fixture.');
const f=JSON.parse(fs.readFileSync(file,'utf8')),{context,bank,sample,options,clear,pcm}=f;
assert.deepEqual(decodeSampleOptions(options,context,bank,sample),options);
assert.deepEqual(decodeSampleReview(clear,options,'clear'),clear);
for(const r of options.retained_inputs)decodeSampleReceipt(r,bank,sample);
if(f.apply){decodeSampleReview(f.apply,options,'apply',f.receipt);for(const mutation of [v=>v.native_audit.sample.native_sample_rate=32000,v=>v.native_audit.sample.maximum_absolute_error=65536,v=>v.native_audit.sample.input_wav_sha256='f'.repeat(64),v=>v.native_audit.sample.source_sha256='f'.repeat(64),v=>v.native_audit.sample.encoder='unknown',v=>v.native_audit.sample.extra=true]){const v=structuredClone(f.apply);mutation(v);assert.throws(()=>decodeSampleReview(v,options,'apply',f.receipt));}}
if(f.upload){const check=v=>decodeSampleUploadReview(v,context,bank,sample,f.upload.binding.wav_sha256,f.upload.binding.byte_length,options.retail);check(f.upload);for(const mutation of [v=>v.binding.wav_sha256='f'.repeat(64),v=>v.binding.byte_length++,v=>v.historical_inputs=false,v=>v.native_content_changed=true,v=>v.native_audit.sample.input_wav_rate++,v=>v.extra=true]){const v=structuredClone(f.upload);mutation(v);assert.throws(()=>check(v));}}
for(const mutation of [v=>v.authoring_key='f'.repeat(64),v=>v.sample_index=true,v=>v.current_sample_sha256='f'.repeat(64),v=>v.source_record.pieces[0].size_bytes++,v=>v.current.bins[0].minimum=-32769,v=>v.current.decoded_frames++,v=>v.retained_inputs.push(v.retained_inputs[0]),v=>v.authored_sample.receipt_key='f'.repeat(64),v=>v.current.sample_rate=32000,v=>v.extra=true]){const v=structuredClone(options);mutation(v);assert.throws(()=>decodeSampleOptions(v,context,bank,sample));}
for(const mutation of [v=>v.native_audit.before_entry_sha256='f'.repeat(64),v=>v.native_audit.changed_entry_byte_offsets=[v.native_audit.sample_entry_byte_offset+1],v=>v.native_audit.changed_entry_byte_offsets=[v.native_audit.sample_entry_byte_offset+options.retail.consumed_bytes],v=>v.no_change=true,v=>v.proposed_sample_sha256='f'.repeat(64),v=>v.proposed_binding.samples.push({sample_index:sample.index,receipt_key:'f'.repeat(64)}),v=>v.operation='apply',v=>v.extra=true]){const v=structuredClone(clear);mutation(v);assert.throws(()=>decodeSampleReview(v,options,'clear'));}
const result=await decodeSamplePcm(pcm,context,bank,sample,'current',options.current_sample_sha256);assert.equal(result.bytes.length,options.current.decoded_frames*2);
for(const mutation of [v=>v.layer='retail',v=>v.authoring_key='f'.repeat(64),v=>v.review_key='f'.repeat(64),v=>v.pcm_sha256='f'.repeat(64),v=>v.pcm_base64=v.pcm_base64.slice(4),v=>v.waveform.bins[0].minimum++,v=>v.waveform.sample_rate=32000,v=>v.extra=true]){const v=structuredClone(pcm);mutation(v);await assert.rejects(()=>decodeSamplePcm(v,context,bank,sample,'current',options.current_sample_sha256));}
console.log('Retail sample editor contracts passed: options, source ownership, review byte spans, flags/tail rejection, PCM hashes/envelopes and malformed/stale payloads.');

// Read ownership is independent of browser rendering: stale/closed reads cannot publish.
class Element{
 constructor(tag){this.tag=tag;this.children=[];this.style={};this.value='';this.textContent='';this.disabled=false;this.listeners={};}
 append(...nodes){this.children.push(...nodes);}
 replaceChildren(...nodes){this.children=nodes;}
 get firstChild(){return this.children[0];}
 setAttribute(k,v){this[k]=v;}
 addEventListener(k,fn){this.listeners[k]=fn;}
 showModal(){}
 close(){this.listeners.close?.();}
 remove(){this.removed=true;}
 getContext(){return {clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}};}
}
globalThis.document={createElement:tag=>new Element(tag),body:new Element('body')};
const find=(root,text)=>root.children.flatMap(c=>[c,...find(c,text)]).filter(c=>c.textContent===text);
let live=structuredClone(context),mutations=0,resolve;
const args={record:{id:bank.asset_id,label:'Retail fixture'},bank,sample,getContext:()=>({...live}),getAuthoringKey:()=>live.authoringKey,canEdit:()=>true,busy:()=>false,apply:async()=>{mutations++;return true;}};
const respond=v=>({ok:true,text:async()=>JSON.stringify(v)});
const closed=openSampleAuthoring({...args,request:()=>new Promise(r=>{resolve=r;})});closed.dispose();resolve(respond(options));await closed.ready;assert.equal(closed.dialog.removed,true);assert.equal(mutations,0);
const stale=openSampleAuthoring({...args,request:()=>new Promise(r=>{resolve=r;})});live.authoringKey='f'.repeat(64);resolve(respond(options));await stale.ready;assert.equal(find(stale.dialog,'Project inputs changed. Refresh sample editing.').length,1);assert.equal(find(stale.dialog,'Apply reviewed sample')[0].disabled,true);stale.dispose();
live=structuredClone(context);const editor=openSampleAuthoring({...args,request:async()=>respond(options)});await editor.ready;await find(editor.dialog,'Apply reviewed sample')[0].onclick();assert.equal(mutations,0);assert.equal(find(editor.dialog,'Apply reviewed sample')[0].disabled,true);editor.dispose();
console.log('Sample editor lifecycle passed: stale and closed reads cannot publish; unreviewed drafts cannot Apply.');
let finishResume,started=0,stopped=0,closedContexts=0;
const fakeContext={resume:()=>new Promise(r=>{finishResume=r;}),close:async()=>{closedContexts++;},createBuffer:(_channels,length)=>({getChannelData:()=>new Float32Array(length)}),createBufferSource:()=>({connect(){},disconnect(){},start(){started++;},stop(){stopped++;}})};
const audition=openSampleAuthoring({...args,audioContext:()=>fakeContext,request:async path=>respond(path==='/api/audio-sample-preview'?pcm:options)});await audition.ready;
await find(audition.dialog,'Load Current preview')[0].onclick();const play=find(audition.dialog,'Play Current')[0];assert.equal(play.disabled,true);
const rate=audition.dialog.children.flatMap(function walk(n){return [n,...n.children.flatMap(walk)];}).find(n=>n['aria-label']==='Current preview rate');rate.value='32000';rate.onchange();assert.equal(play.disabled,false);
const firstPlay=play.onclick();await find(audition.dialog,'Mono PCM WAV input')[0].children[0].onchange();finishResume();await firstPlay;assert.equal(started,0,'Changing the WAV draft cancels pending playback');
fakeContext.resume=async()=>{};await play.onclick();assert.equal(started,1);audition.dispose();assert.equal(stopped,1);assert.equal(closedContexts,1);
console.log('Layer audition requires a rate; changing WAV drafts cancels pending playback; close stops playback and releases the context.');
