import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {decodeTriggerCellsReview,triggerCellsGeometry,decodeTriggerCellsAnnotations,openTriggerCells} from '../editor/trigger-cells.js';

const FIELDS=['tile_x','tile_z'],BOUNDS=['x_min','x_max','z_min','z_max'],scene='scene://fixture',key='a'.repeat(64),mapHash='b'.repeat(64),blockHash='d'.repeat(64),imported={tile_x:8,tile_z:9};
const clone=value=>structuredClone(value),same=(a,b)=>FIELDS.every(field=>a[field]===b[field]),tiles=({tile_x:x,tile_z:z})=>({x_min:x,x_max:x+1,z_min:z,z_max:z+1}),world=value=>Object.fromEntries(BOUNDS.map(field=>[field,value[field]*128]));
function fixture(kind=1,gate=7){
  const id=`trigger://fixture/field-map/primary/kind-${kind}/0000`,payload=kind===0?{dest_x:17,dest_z:23}:{record_index:11,gate},rowHash=createHash('sha256').update(Buffer.from([...Object.values(imported),...Object.values(payload)])).digest('hex');
  const source={disc:{sha256:'e'.repeat(64),serial:'SCUS-94254'},iso_file:'PROT.DAT',prot_entry_index:1,prot_entry_name:'fixture',prot_start_lba:203,byte_offset:66692,byte_length:4,byte_coordinate_space:'prot_entry',sha256:rowHash,containing_span_sha256:blockHash,table_source:'primary',table_kind:kind,record_index:0,containing_span_byte_offset:65536,containing_span_byte_length:8192};
  const type=kind===0?'intra_scene_teleport':({0:'object_bind',1:'partition_2_trigger'}[gate]??'unknown_gate');
  const record={id,type:'trigger',sceneId:scene,label:'<literal trigger>',source:'fixture',data:{semantic_id:id,asset_kind:'trigger',table_source:'primary',table_kind:kind,record_index:0,encoded:{...imported,...payload},source_record:source,trigger_type:type,...(kind===0?{destination_world:{x:payload.dest_x*64+64,z:(payload.dest_z+1)*64}}:{})}};
  return {id,source,record,rowHash,kind,type};
}
const base=fixture(),{id,record,source,rowHash}=base,state={project:{mode:'edit'},scene:{id:scene},project_copy_source_key:key,scene_trigger_state_key:'0'.repeat(64),scene_selection_map_sha256:mapHash};
function review(requested={tile_x:255,tile_z:0},action='set',authored={},context=base){
  const current=Object.keys(authored).length?authored:imported,proposed=action==='clear'?imported:requested??current;
  const tileLayers=Object.fromEntries([['imported',imported],['current',current],['proposed',proposed]].map(([layer,value])=>[layer,tiles(value)]));
  return {schema_version:'legaia.trigger-cells-review.v1',read_only:true,project_source_key:key,scene_id:scene,trigger_id:context.id,review_key:'f'.repeat(64),source:{map_sha256:mapHash,row_sha256:context.rowHash,table_kind:context.kind,record_index:0,byte_offset:context.source.byte_offset,byte_length:4},trigger_kind:context.kind,values_layers:{imported:{...imported},authored:{...authored},current:{...current},proposed:{...proposed}},tile_bounds_layers:tileLayers,world_bounds_layers:Object.fromEntries(Object.entries(tileLayers).map(([layer,value])=>[layer,world(value)])),requested_values:requested===null?null:{...requested},action,effective_change_count:FIELDS.filter(field=>current[field]!==proposed[field]).length,project_change:requested===null&&action==='set'?false:!same(current,proposed)||action==='clear'&&Object.keys(authored).length>0,value:{source_sha256:mapHash,edits:same(imported,proposed)?[]:[{trigger_id:context.id,...proposed}]},scope:'source-MAP-trigger-cell-only',height_status:'unknown',activation:'not_evaluated',gameplay_verified:false};
}

const sourceReview=review(),snapshot=clone(sourceReview),decoded=decodeTriggerCellsReview(sourceReview,record,state);assert.deepEqual(decoded,sourceReview);decoded.values_layers.proposed.tile_x=0;decoded.value.edits[0].tile_x=0;assert.deepEqual(sourceReview,snapshot);
assert.deepEqual(triggerCellsGeometry(sourceReview,'proposed'),{id,kind:'trigger',world_bounds:{x_min:32640,x_max:32768,z_min:0,z_max:128},world_center:{x:32704,y:0,z:64}});
assert.deepEqual(triggerCellsGeometry(sourceReview,'imported').world_bounds,{x_min:1024,x_max:1152,z_min:1152,z_max:1280});assert.throws(()=>triggerCellsGeometry(sourceReview,'live'));
for(const context of [fixture(0),fixture(1,0),fixture(1,1),fixture(1,255)])assert.equal(decodeTriggerCellsReview(review({tile_x:0,tile_z:255},'set',{},context),context.record,state).trigger_kind,context.kind);
for(const coordinates of [{tile_x:0,tile_z:0},{tile_x:127,tile_z:128},{tile_x:255,tile_z:255}]){
  const report=review(coordinates),geometry=triggerCellsGeometry(report);decodeTriggerCellsReview(report,record,state);
  for(const [axis,value] of [['x',coordinates.tile_x],['z',coordinates.tile_z]]){const low=geometry.world_bounds[axis+'_min'],high=geometry.world_bounds[axis+'_max'];assert.equal(low>>7,value);assert.equal((high-1)>>7,value);assert.equal((low-1)>>7,value-1);assert.equal(high>>7,value+1);}
}
const noMapState=clone(state);delete noMapState.scene_selection_map_sha256;assert.deepEqual(decodeTriggerCellsReview(sourceReview,record,noMapState),sourceReview);assert.deepEqual(decodeTriggerCellsReview(review(null),record,state).values_layers.current,imported);
assert.deepEqual(decodeTriggerCellsReview(review(null,'clear',{tile_x:3,tile_z:4}),record,state).values_layers.proposed,imported);
for(const mutate of [
  r=>r.extra=true,r=>r.schema_version='other',r=>r.read_only=false,r=>r.project_source_key='0'.repeat(64),r=>r.scene_id='scene://other',r=>r.trigger_id=id.replace('primary','fallback'),r=>r.review_key='bad',r=>r.trigger_kind=0,r=>r.height_status='known',r=>r.activation='active',r=>r.gameplay_verified=true,r=>r.scope='all-MAP',
  r=>r.source.map_sha256=blockHash,r=>r.source.row_sha256=mapHash,r=>r.source.table_kind=0,r=>r.source.record_index=1,r=>r.source.byte_offset++,r=>r.source.byte_length=8,r=>r.source.extra=true,r=>r.effective_change_count=0,r=>r.effective_change_count=3,r=>r.project_change=false,r=>r.project_change=1,
  r=>r.values_layers.imported.tile_x++,r=>r.values_layers.authored={tile_x:1},r=>r.values_layers.current.tile_z=1,r=>r.values_layers.proposed.tile_x=true,r=>r.values_layers.proposed.tile_x=256,r=>r.values_layers.proposed.tile_z=-1,r=>r.values_layers.proposed.tile_z=1.5,r=>r.values_layers.proposed.gate=0,
  r=>r.tile_bounds_layers.proposed.x_max=255,r=>r.tile_bounds_layers.proposed.z_max=2,r=>r.world_bounds_layers.proposed.x_min+=64,r=>r.world_bounds_layers.proposed.y=0,r=>r.action='translate',r=>r.action='clear',r=>r.requested_values={tile_x:1},r=>r.requested_values.tile_x=1,
  r=>r.value.source_sha256=rowHash,r=>r.value.edits=[],r=>r.value.edits[0].tile_x=1,r=>r.value.edits.push(clone(r.value.edits[0])),r=>r.value.edits[0].trigger_id=id.replace('fixture','other'),r=>r.value.edits[0].trigger_id=id.replace('0000','2043'),r=>r.value.edits[0].gate=0,
]){const invalid=review();mutate(invalid);assert.throws(()=>decodeTriggerCellsReview(invalid,record,state));}
const wrongOrder=review();wrongOrder.value.edits.push({trigger_id:id.replace('kind-1','kind-0'),tile_x:3,tile_z:4});assert.throws(()=>decodeTriggerCellsReview(wrongOrder,record,state));
for(const change of [{type:'region'},{sceneId:'scene://other'},{id:id.replace('0000','0001')}])assert.throws(()=>decodeTriggerCellsReview(sourceReview,{...record,...change},state));
for(const change of [{project:{mode:'live'}},{scene:{id:'scene://other'}},{scene_selection_map_sha256:blockHash},{scene_trigger_state_key:null}])assert.throws(()=>decodeTriggerCellsReview(sourceReview,record,{...state,...change}));
for(const mutate of [r=>r.data.source_record.sha256=mapHash,r=>r.data.source_record.byte_length=8,r=>r.data.source_record.table_kind=0,r=>r.data.source_record.table_source='fallback',r=>r.data.source_record.byte_offset=65553,r=>r.data.source_record.byte_coordinate_space='ram',r=>r.data.encoded.gate=-1,r=>r.data.encoded.record_index=256,r=>r.data.encoded.extra=true,r=>r.data.trigger_type='partition_2_trigger']){const changed=clone(record);mutate(changed);assert.throws(()=>decodeTriggerCellsReview(sourceReview,changed,state));}
const teleport=fixture(0);teleport.record.data.destination_world.x++;assert.throws(()=>decodeTriggerCellsReview(review(null,'set',{},teleport),teleport.record,state));

function spatial(){const bounds=world(tiles(imported));return {schema_version:'legaia.field-spatial.v1',scene_id:scene,coordinate_system:'psx_guest_xz',units:'guest_integer_world_units',display_y:0,height_status:'unknown',quantization:{trigger:{tile_size:128,world_bias:0,rule:'tile = world >> 7'},region:{tile_size:128,world_bias:64,rule:'tile = (world - 64) >> 7'}},records:[{id,kind:'trigger',label:'Source trigger',table_source:'primary',table_kind:1,record_index:0,trigger_type:'unknown_gate',world_bounds:bounds,world_center:{x:(bounds.x_min+bounds.x_max)/2,y:0,z:(bounds.z_min+bounds.z_max)/2},source_tile_bounds:tiles(imported),source_record:clone(source),activation:'not_evaluated',height_status:'unknown'}]};}
function annotation(){return {trigger_id:id,row_sha256:rowHash,values_layers:{imported:{...imported},authored:{...sourceReview.values_layers.proposed},effective:{...sourceReview.values_layers.proposed}},tile_bounds_layers:{imported:tiles(imported),effective:clone(sourceReview.tile_bounds_layers.proposed)},world_bounds_layers:{imported:world(tiles(imported)),effective:clone(sourceReview.world_bounds_layers.proposed)}};}
const annotations=[annotation()],sourceSpatial=spatial(),spatialBefore=clone(sourceSpatial),detached=decodeTriggerCellsAnnotations(annotations,sourceSpatial);detached[0].values_layers.effective.tile_x=0;assert.deepEqual(sourceSpatial,spatialBefore);assert.equal(annotations[0].values_layers.effective.tile_x,255);assert.deepEqual(decodeTriggerCellsAnnotations([],sourceSpatial),[]);
const inherited=annotation();inherited.values_layers.authored={};inherited.values_layers.effective=clone(imported);inherited.tile_bounds_layers.effective=tiles(imported);inherited.world_bounds_layers.effective=world(tiles(imported));assert.equal(decodeTriggerCellsAnnotations([inherited],sourceSpatial).length,1);
for(const mutate of [r=>r.row_sha256=mapHash,r=>r.trigger_id=id.replace('primary','fallback'),r=>r.values_layers.imported.tile_x++,r=>r.values_layers.authored.tile_x=0,r=>r.values_layers.effective.tile_z=2.5,r=>r.tile_bounds_layers.effective.x_max++,r=>r.world_bounds_layers.effective.x_min+=64,r=>r.extra=true]){const changed=annotation();mutate(changed);assert.throws(()=>decodeTriggerCellsAnnotations([changed],sourceSpatial));}
assert.throws(()=>decodeTriggerCellsAnnotations([annotation(),annotation()],sourceSpatial));assert.throws(()=>decodeTriggerCellsAnnotations(Array(2044).fill(annotation()),sourceSpatial));assert.throws(()=>decodeTriggerCellsAnnotations([annotation()],{...sourceSpatial,height_status:'known'}));

// DOM lifecycle proof checks source freshness and accepted command routing.
class Node{
  constructor(tag,namespace=null){this.tagName=tag;this.namespaceURI=namespace;this.children=[];this.style={};this.dataset={};this.attributes={};this.listeners=new Map();this.open=false;this.hidden=false;this.textContent='';this.value='';this.disabled=false;this.removed=false;}
  append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(key,value){this.attributes[key]=String(value);}addEventListener(type,callback){const rows=this.listeners.get(type)??[];rows.push(callback);this.listeners.set(type,rows);}showModal(){this.open=true;}close(){this.open=false;for(const callback of this.listeners.get('close')??[])callback();}remove(){this.removed=true;}reportValidity(){return true;}
}
const savedDocument=globalThis.document,savedFetch=globalThis.fetch;globalThis.document={createElement:tag=>new Node(tag),createElementNS:(namespace,tag)=>new Node(tag,namespace),body:new Node('body')};
const descendants=node=>node.removed?[]:[node,...node.children.flatMap(descendants)],button=(dialog,text)=>descendants(dialog).find(node=>node.tagName==='button'&&node.textContent===text),input=(dialog,name)=>descendants(dialog).find(node=>node.tagName==='input'&&node.name===name),form=dialog=>descendants(dialog).find(node=>node.tagName==='form'),tick=()=>new Promise(resolve=>setImmediate(resolve));
let mutableState=clone(state),current=true,busy=false,requests=[],commands=[],inspections=[],frames=[],errors=[];
const settings={record,getState:()=>mutableState,busy:()=>busy,setBusy:value=>{busy=value;},current:()=>current,onInspection:(report,layer)=>inspections.push([report,layer]),onFrame:(report,layer)=>frames.push([report,layer]),onError:error=>errors.push(error),api:async(path,body)=>{assert.equal(busy,false,'The mutation API owns busy');commands.push([path,body]);return true;}};
function defaultFetch(path,options){requests.push([path,clone(JSON.parse(options.body)),options.signal]);return Promise.resolve({ok:true,json:async()=>review(JSON.parse(options.body).values,JSON.parse(options.body).action)});}
globalThis.fetch=defaultFetch;
try{
  let dialog=openTriggerCells(settings);await tick();assert.equal(dialog.open,true);assert.equal(busy,false);assert.deepEqual(requests[0].slice(0,2),['/api/trigger-cells-review',{trigger_id:id,values:null,action:'set'}]);assert.equal(input(dialog,'tile_x').value,'8');assert.equal(button(dialog,'Apply trigger cells').disabled,true);assert.ok(descendants(dialog).some(node=>node.textContent.includes('first-match shadowing')));assert.ok(descendants(dialog).some(node=>node.textContent.includes('gate 7 · gate meaning unknown')));
  input(dialog,'tile_x').value='20';form(dialog).oninput();assert.equal(button(dialog,'Inspect proposed cell').disabled,true);assert.equal(await form(dialog).onsubmit({preventDefault(){}}),true);assert.deepEqual(requests.at(-1)[1],{trigger_id:id,values:{tile_x:20,tile_z:9},action:'set'});assert.equal(button(dialog,'Apply trigger cells').disabled,false);
  assert.equal(button(dialog,'Inspect proposed cell').onclick(),true);assert.equal(dialog.open,false);assert.equal(inspections.at(-1)[1],'proposed');assert.equal(frames.at(-1)[1],'proposed');const strip=descendants(document.body).find(node=>node.id==='trigger-cells-preview');assert.equal(strip.hidden,false);assert.equal(button(strip,'Return to trigger review').onclick(),true);assert.equal(dialog.open,true);assert.equal(inspections.at(-1)[0],null);assert.equal(strip.hidden,true);
  busy=true;assert.equal(button(dialog,'Inspect current cell').onclick(),false);assert.equal(await button(dialog,'Apply trigger cells').onclick(),false);busy=false;
  assert.equal(await button(dialog,'Apply trigger cells').onclick(),true);assert.deepEqual(commands.at(-1),['/api/trigger-cells-apply',{type:'apply_trigger_cells',trigger_id:id,values:{tile_x:20,tile_z:9},action:'set',review_key:'f'.repeat(64)}]);assert.equal(dialog.removed,true);assert.equal(strip.removed,true);dialog.dispose();
  dialog=openTriggerCells(settings);await tick();await button(dialog,'Review retail reset').onclick();assert.equal(requests.at(-1)[1].action,'clear');assert.equal(requests.at(-1)[1].values,null);assert.equal(button(dialog,'Apply trigger cells').disabled,true);dialog.dispose();
  globalThis.fetch=(path,options)=>Promise.resolve({ok:true,json:async()=>review(JSON.parse(options.body).values,JSON.parse(options.body).action,{tile_x:12,tile_z:13})});dialog=openTriggerCells(settings);await tick();assert.equal(input(dialog,'tile_x').value,'12');await button(dialog,'Review retail reset').onclick();assert.equal(button(dialog,'Apply trigger cells').disabled,false);assert.equal(await button(dialog,'Apply trigger cells').onclick(),true);assert.deepEqual(commands.at(-1),['/api/trigger-cells-apply',{type:'apply_trigger_cells',trigger_id:id,values:null,action:'clear',review_key:'f'.repeat(64)}]);globalThis.fetch=defaultFetch;
  for(const field of ['project_copy_source_key','scene_trigger_state_key']){dialog=openTriggerCells(settings);await tick();button(dialog,'Inspect current cell').onclick();mutableState[field]='9'.repeat(64);dialog.refresh();assert.equal(inspections.at(-1)[0],null);assert.equal(button(dialog,'Review cells').disabled,true);assert.equal(button(dialog,'Apply trigger cells').disabled,true);assert.equal(await form(dialog).onsubmit({preventDefault(){}}),false);dialog.dispose();mutableState=clone(state);}
  dialog=openTriggerCells(settings);await tick();input(dialog,'tile_x').value='256';form(dialog).oninput();assert.equal(button(dialog,'Review cells').disabled,true);assert.equal(await form(dialog).onsubmit({preventDefault(){}}),false);input(dialog,'tile_x').value='1.5';form(dialog).oninput();assert.equal(button(dialog,'Review cells').disabled,true);dialog.dispose();
  let finish,signal;globalThis.fetch=(path,options)=>{signal=options.signal;return new Promise(resolve=>{finish=resolve;});};dialog=openTriggerCells(settings);assert.equal(busy,true);dialog.dispose();assert.equal(signal.aborted,true);assert.equal(busy,false);finish({ok:true,json:async()=>review(null)});await tick();assert.equal(dialog.removed,true);assert.equal(descendants(dialog).length,0);
  globalThis.fetch=defaultFetch;let finishApply,calls=0;dialog=openTriggerCells({...settings,api:()=>{calls++;return new Promise(resolve=>{finishApply=resolve;});}});await tick();input(dialog,'tile_x').value='20';form(dialog).oninput();await form(dialog).onsubmit({preventDefault(){}});const applying=button(dialog,'Apply trigger cells').onclick();assert.equal(await button(dialog,'Apply trigger cells').onclick(),false);assert.equal(calls,1);dialog.dispose();finishApply(true);assert.equal(await applying,true);
  dialog=openTriggerCells({...settings,api:async()=>false});await tick();input(dialog,'tile_x').value='20';form(dialog).oninput();await form(dialog).onsubmit({preventDefault(){}});assert.equal(await button(dialog,'Apply trigger cells').onclick(),false);assert.equal(dialog.open,true);assert.equal(button(dialog,'Apply trigger cells').disabled,true);dialog.dispose();
  globalThis.fetch=async()=>({ok:true,json:async()=>({...review(null),source:{...review(null).source,row_sha256:mapHash}})});dialog=openTriggerCells(settings);await tick();assert.equal(button(dialog,'Apply trigger cells').disabled,true);assert.ok(errors.at(-1).message.includes('source row'));dialog.dispose();
  current=false;assert.equal(openTriggerCells(settings),null);current=true;busy=true;assert.equal(openTriggerCells(settings),null);busy=false;assert.deepEqual(record.data.encoded,{...imported,record_index:11,gate:7});assert.deepEqual(sourceSpatial,spatialBefore);
}finally{if(savedDocument===undefined)delete globalThis.document;else globalThis.document=savedDocument;if(savedFetch===undefined)delete globalThis.fetch;else globalThis.fetch=savedFetch;}
console.log('Trigger cells: primary source/payload/key guards, raw half-open cell bounds, separated layers, unknown gate preservation, detached annotations, Review/reset/Apply, viewport Return, stale/pending/dispose checks passed.');
