import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createScriptFlagSandbox,mountScriptFlagSandbox} from '../editor/script-flag-sandbox.js';
import {createScriptSandboxScenario,replayScriptSandboxScenario} from '../editor/script-sandbox-scenarios.js';
import {scriptFlowReportHash} from '../editor/script-flow-identity.js';
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:webcrypto});
const context={project_path:'C:/private/project',scene_id:'scene://fixture',script_id:'script://fixture/actors/man-p1/0000',project_source_key:'a'.repeat(64),record_sha256:'b'.repeat(64),representation:'retail_source'},words={local:null,global:null,context:null};
const report={status:'decoded_supported_paths',entry_pc:0,instructions:[{pc:0,opcode:0x4a,length:3,mnemonic:'WAIT_FRAMES',target_context:null,operands:{duration_ticks:16,timing_units:'host_frame_delta_ticks',accumulator_width:'signed16'},successors:[{pc:3,condition:'encoded_continuation'}]},{pc:3,opcode:0x2e,length:2,mnemonic:'GFLAG_SET',target_context:null,operands:{bit:31,raw_operand:31},successors:[{pc:5,condition:'encoded_continuation'}]}],dialogues:[],stops:[]};
const engine=createScriptFlagSandbox(report);engine.start(0,words,{waitAccumulator:0});engine.run();engine.tick(1);engine.tick(5);engine.tick(10);engine.step();const snapshot=engine.snapshot(),saved=await createScriptSandboxScenario(report,snapshot,context),serialized=JSON.stringify(saved);assert.deepEqual((await replayScriptSandboxScenario(JSON.parse(serialized),report,context)).snapshot(),snapshot);assert.deepEqual(saved.steps,[{kind:'instruction'},{kind:'tick',delta_ticks:1},{kind:'tick',delta_ticks:5},{kind:'tick',delta_ticks:10},{kind:'instruction'}]);assert.equal(saved.result.banks.global.value,2147483648);assert(!serialized.includes('raw_hex'));assert.equal(saved.project_changed,false);assert.equal(saved.runtime_execution,'not_asserted');
for(const mutate of [s=>s.schema_version='other',s=>s.project_changed=true,s=>s.runtime_execution='observed',s=>s.assumptions='retail',s=>s.report_sha256='c'.repeat(64),s=>s.source.record_sha256='c'.repeat(64),s=>s.source.extra='bad',s=>s.initial.inputs.global=true,s=>s.initial.wait_accumulator=32768,s=>s.initial.extra=0,s=>s.steps[1].delta_ticks=32768,s=>s.steps[0].kind='command',s=>s.steps[0].extra=1,s=>s.steps.push({kind:'instruction'}),s=>s.result.banks.global.value=0,s=>s.steps=Array(257).fill({kind:'instruction'}),s=>s.result.extra=1]){const bad=JSON.parse(serialized);mutate(bad);await assert.rejects(()=>replayScriptSandboxScenario(bad,report,context));}
const other=structuredClone(report);other.instructions[0].operands.duration_ticks=17;await assert.rejects(()=>replayScriptSandboxScenario(saved,other,context));const broken=structuredClone(snapshot);broken.history[0].after.wait_accumulator=1;await assert.rejects(()=>createScriptSandboxScenario(report,broken,context));
for(const representation of ['authored_current','reviewed_proposed']){const proposed=representation==='reviewed_proposed',source={...context,representation,flow_proof:{state_key:'d'.repeat(64),report_sha256:await scriptFlowReportHash(report),review_key:proposed?'e'.repeat(64):null,branch_id:proposed?context.script_id+'/branch/0000':null,branch_value:proposed?{target_pc:3}:null}},scenario=await createScriptSandboxScenario(report,snapshot,source);assert.deepEqual((await replayScriptSandboxScenario(scenario,report,source)).snapshot(),snapshot);await assert.rejects(()=>replayScriptSandboxScenario(scenario,report,{...source,flow_proof:{...source.flow_proof,state_key:'f'.repeat(64)}}));}
engine.start(0,words);engine.step();const unknown=await createScriptSandboxScenario(report,engine.snapshot(),context);assert.equal((await replayScriptSandboxScenario(unknown,report,context)).snapshot().state.status,'unknown_wait');engine.start(0,words,{waitAccumulator:0});engine.step();for(let i=1;i<256;i++)engine.tick(0);const bounded=await createScriptSandboxScenario(report,engine.snapshot(),context);assert.equal((await replayScriptSandboxScenario(bounded,report,context)).snapshot().state.status,'step_limit');
class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.textContent='';}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this[k]=v;}click(){}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)];globalThis.document={createElement:tag=>new Element(tag)};let release,checks=0,live=true;const errors=[],host=new Element('div'),view=mountScriptFlagSandbox(host,{report,getContext:()=>context,requalify:async()=>{checks++;return await new Promise(resolve=>release=resolve);},selection:()=>0,current:()=>live,busy:()=>false,selectInstruction:()=>true,onError:e=>errors.push(e.message)}),button=t=>tree(host).find(n=>n.tagName==='button'&&n.textContent===t),file=tree(host).find(n=>n.type==='file');
file.files=[{size:serialized.length,text:async()=>serialized}];const loading=file.onchange();while(!release)await new Promise(resolve=>setTimeout(resolve,0));assert.equal(button('Start flag sandbox at entry').disabled,true);assert.equal(view.snapshot.state,null);release(true);await loading;assert.deepEqual(view.snapshot,snapshot);assert.equal(checks,1);
const before=JSON.stringify(view.snapshot);file.files=[{size:serialized.length,text:async()=>serialized.replace('2147483648','0')}];await file.onchange();assert.equal(JSON.stringify(view.snapshot),before);assert.equal(checks,1);assert.equal(errors.length,1);
release=null;file.files=[{size:serialized.length,text:async()=>serialized}];const late=file.onchange();while(!release)await new Promise(resolve=>setTimeout(resolve,0));live=false;release(true);await late;assert.equal(errors.length,2);view.update();assert.equal(view.snapshot.state,null);view.dispose();assert.equal(host.children.length,0);
const closedHost=new Element('div');let finish,signal;const closed=mountScriptFlagSandbox(closedHost,{report,getContext:()=>context,requalify:async options=>{signal=options.signal;return await new Promise(resolve=>finish=resolve);},selection:()=>0,current:()=>true,busy:()=>false,selectInstruction:()=>true,onError:e=>{throw e;}}),closedFile=tree(closedHost).find(n=>n.type==='file');closedFile.files=[{size:serialized.length,text:async()=>serialized}];const closing=closedFile.onchange();while(!finish)await new Promise(resolve=>setTimeout(resolve,0));closed.dispose();assert.equal(signal.aborted,true);finish(true);await closing;assert.equal(closedHost.children.length,0);assert.equal(closed.snapshot.state,null);
console.log('Sandbox scenarios: exact wait/flag recipe replay, unknown/limit states, source/report/current/proposed identity, false claims/tampering refusal, detached history, atomic load and pending/stale ownership passed');
