import assert from 'node:assert/strict';
import {interpolateEffectiveAxis,decodeEffectiveInterpolation} from '../editor/animation-effective-interpolation.js';
import {validateRetainedAxes} from '../editor/animation-record-edit.js';
assert.equal(interpolateEffectiveAxis('translation',-1,0,1,2),0);assert.equal(interpolateEffectiveAxis('rotation_psx',4080,16,1,2),0);assert.equal(interpolateEffectiveAxis('rotation_psx',0,2048,1,2),1024);assert.equal(interpolateEffectiveAxis('rotation_psx',2048,0,1,2),3072);
const pose=(x,y)=>({translation:{x,y:0,z:0},rotation_psx:{x:0,y,z:0}}),before=[pose(-1,4080),pose(5,32),pose(0,16)],after=[pose(-1,4080),pose(0,0),pose(0,16)];
const request={scene_id:'scene://town01',record_id:'11111111-1111-4111-8111-111111111111',source_frame_indices:[1,0,1],edits:[{frame_index:0,object_index:0,translation:{x:-1}}],object_index:0,start:0,end:2,expected_source_key:'a'.repeat(64)},value={schema_version:'legaia.animation-record-interpolation.v1',scene_id:request.scene_id,record_id:request.record_id,project_source_key:request.expected_source_key,source_frame_indices:request.source_frame_indices,before_edits:request.edits,edits:after.map((p,i)=>({frame_index:i,object_index:0,...p})),object_index:0,start:0,end:2,poses:before.map((p,i)=>({frame_index:i,before:p,after:after[i]})),before_record_sha256:'b'.repeat(64),after_record_sha256:'c'.repeat(64),project_changed:false,gameplay_verified:false};
const held=structuredClone({value,request});assert.deepEqual(decodeEffectiveInterpolation(value,request,2,validateRetainedAxes),value);assert.deepEqual({value,request},held);
for(const mutate of [v=>v.poses[1].after.translation.x=1,v=>v.poses[0].before.translation.x=0,v=>v.poses.pop(),v=>v.edits[1].object_index=1,v=>v.poses[1].before.rotation_psx.y=1,v=>v.extra=1,v=>v.project_changed=true,v=>v.project_source_key='0'.repeat(64)]){const bad=structuredClone(value);mutate(bad);assert.throws(()=>decodeEffectiveInterpolation(bad,request,2,validateRetainedAxes));}
for(const args of [['rotation_psx',1,16,1,2],['translation',0,2048,1,2],['translation',0,1,3,2],['translation',0,1,0,0]])assert.throws(()=>interpolateEffectiveAxis(...args));
console.log('Exact signed half ties, shortest rotation wraps/half-turns, complete inherited-pose receipts, preservation and forged receipt refusal passed.');
