import assert from 'node:assert/strict';
import {decodeSequenceAuthoring,decodeSequenceReview,openSequenceAuthoring} from '../editor/audio-sequence-authoring.js';
const context={assetId:'audio://legaia/prot/0877',sceneId:'scene://town01',sourceKey:'a'.repeat(64),entryHash:'b'.repeat(64),authoringKey:'e'.repeat(64)};
const source={disc_sha256:'c'.repeat(64),iso_file:'PROT.DAT',prot_entry_index:877,entry_sha256:context.entryHash,entry_byte_offset:2048,entry_size_bytes:2048,sequence_offset:0,sequence_size_bytes:28,sequence_sha256:'d'.repeat(64)};
const bare={header:{header_variant:'legaia-u32-version',header_size:15,version:1,ppqn:480,initial_tempo_us_per_quarter:500000,time_signature_numerator:4,time_signature_denominator_power:2,event_stream_validated:false},events:[{index:0,offset:15,end_offset:19,delta_ticks:0,ticks:0,time_seconds:0,status:144,channel:0,kind:'note_on',values:[60,100],running_status:false},{index:1,offset:19,end_offset:24,delta_ticks:480,ticks:480,time_seconds:.5,status:128,channel:0,kind:'note_off',values:[60,0],running_status:false},{index:2,offset:24,end_offset:27,delta_ticks:0,ticks:480,time_seconds:.5,status:255,channel:null,kind:'end_of_track',values:[],running_status:false}],event_count:3,event_counts:{note_on:1,note_off:1,end_of_track:1},channels:[0],complete:true,encoded_end_of_track:true,stop_reason:null,stop_offset:null,decoded_byte_end:27,unparsed_bytes:1,decoded_ticks:480,decoded_time_seconds:.5,limitations:['Declared timing only.']};
const options={schema_version:'legaia.audio-sequence-authoring.v1',asset_id:context.assetId,authoring_key:context.authoringKey,source_key:context.sourceKey,scene_id:context.sceneId,source_record:source,current_entry_sha256:context.entryHash,current_sequence_sha256:source.sequence_sha256,binding_source_scene_id:context.sceneId,authored_edits:[],retail:structuredClone(bare),current:structuredClone(bare),max_edits:256,project_changed:false,runtime_state:'not_observed'};
const edits=[{event_offset:15,values:[61,100]}];
const proposal={schema_version:'legaia.audio-sequence-review.v1',asset_id:context.assetId,authoring_key:context.authoringKey,source_record:source,proposed_binding:{format:'seq-operands-v1',source_scene_id:context.sceneId,source_record:source,edits},native_audit:{source_entry_sha256:context.entryHash,before_entry_sha256:context.entryHash,after_entry_sha256:'f'.repeat(64),sequence_offset:0,sequence_size_bytes:28,changed_entry_byte_offsets:[17],sequence:{source_sha256:source.sequence_sha256,before_sha256:source.sequence_sha256,after_sha256:'f'.repeat(64),edits:[{event_offset:15,operand_offset:17,width:2,kind:'note_on',channel:0,source_values:[60,100],before_values:[60,100],after_values:[61,100]}],changed_byte_offsets:[17],complete:true,stop_reason:null,decoded_time_seconds:.5}},no_change:false,project_changed:false,runtime_state:'not_observed',review_key:'1'.repeat(64)};
assert.deepEqual(decodeSequenceAuthoring(options,context),options);
assert.deepEqual(decodeSequenceReview(proposal,options,edits),proposal);
const detached=decodeSequenceAuthoring(options,context);detached.current.events[0].values[0]=1;assert.equal(options.current.events[0].values[0],60);
for(const change of [v=>v.authoring_key='f'.repeat(64),v=>v.source_record.entry_sha256='f'.repeat(64),v=>v.current.events[0].values[0]=1,v=>v.current.events[1].offset++,v=>v.current_entry_sha256='f'.repeat(64),v=>v.authored_edits=edits,v=>v.max_edits=257,v=>v.unknown=true]){const bad=structuredClone(options);change(bad);assert.throws(()=>decodeSequenceAuthoring(bad,context));}
for(const change of [v=>v.review_key='x',v=>v.authoring_key='f'.repeat(64),v=>v.native_audit.changed_entry_byte_offsets=[18],v=>v.native_audit.sequence.edits[0].operand_offset++,v=>v.native_audit.sequence.edits[0].before_values=[61,100],v=>v.native_audit.sequence.decoded_time_seconds=1,v=>v.proposed_binding.edits[0].values=[62,100],v=>v.no_change=true,v=>v.project_changed=true,v=>v.native_audit.extra=1]){const bad=structuredClone(proposal);change(bad);assert.throws(()=>decodeSequenceReview(bad,options,edits));}
const authored=structuredClone(options);authored.authored_edits=structuredClone(edits);authored.current.events[0].values=[61,100];authored.current_entry_sha256=authored.current_sequence_sha256='f'.repeat(64);assert.deepEqual(decodeSequenceAuthoring(authored,context),authored);
const partial=structuredClone(options);for(const r of [partial.retail,partial.current]){r.events.pop();Object.assign(r,{event_count:2,event_counts:{note_on:1,note_off:1},complete:false,encoded_end_of_track:false,stop_reason:'Unknown meta length',stop_offset:24,decoded_byte_end:24,unparsed_bytes:4});}assert.equal(decodeSequenceAuthoring(partial,context).current.complete,false);
const tempo=structuredClone(options);tempo.source_record.sequence_size_bytes=30;
for(const report of [tempo.retail,tempo.current]){report.events=[{...bare.events[0],offset:15,end_offset:21,status:255,channel:null,kind:'set_tempo',values:[500000]},{...bare.events[1],offset:21,end_offset:26,status:144,kind:'note_on',values:[60,100]},{...bare.events[2],offset:26,end_offset:29}];report.event_counts={set_tempo:1,note_on:1,end_of_track:1};report.decoded_byte_end=29;}
decodeSequenceAuthoring(tempo,context);
const tempoReview=structuredClone(proposal),tempoEdit=[{event_offset:15,values:[1000000]}];tempoReview.source_record=structuredClone(tempo.source_record);tempoReview.proposed_binding.source_record=structuredClone(tempo.source_record);tempoReview.proposed_binding.edits=tempoEdit;tempoReview.native_audit.sequence_size_bytes=30;tempoReview.native_audit.changed_entry_byte_offsets=[18,19,20];Object.assign(tempoReview.native_audit.sequence,{edits:[{event_offset:15,operand_offset:18,width:3,kind:'set_tempo',channel:null,source_values:[500000],before_values:[500000],after_values:[1000000]}],changed_byte_offsets:[18,19,20],decoded_time_seconds:1});decodeSequenceReview(tempoReview,tempo,tempoEdit);
const wrongTempo=structuredClone(tempoReview);wrongTempo.native_audit.sequence.decoded_time_seconds=.5;assert.throws(()=>decodeSequenceReview(wrongTempo,tempo,tempoEdit));
console.log('Retail/Current ownership, canonical operands, native review spans/timing, partial streams, stale keys and detached DTOs passed.');

class Element{constructor(tag){this.tag=tag;this.style={};this.children=[];this.value='';this.listeners={};this.textContent='';}append(...nodes){this.children.push(...nodes);}setAttribute(){}replaceChildren(...nodes){this.children=[...nodes];}addEventListener(name,callback){this.listeners[name]=callback;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}remove(){this.removed=true;}}
globalThis.document={createElement:tag=>new Element(tag),body:new Element('body')};
const nodes=root=>[root,...root.children.flatMap(nodes)],button=(root,name)=>nodes(root).find(n=>n.tag==='button'&&n.textContent===name);
let now={...context},resolve;
const params={record:{id:context.assetId,label:'Source audio'},getContext:()=>now,getAuthoringKey:()=>now.authoringKey,canEdit:()=>true,busy:()=>false,apply:async()=>false};
let view=openSequenceAuthoring({...params,request:async()=>({ok:true,text:async()=>JSON.stringify(options)})});
try{await view.ready;const fields=nodes(view.dialog).filter(n=>n.tag==='input'&&n.type==='number');assert.equal(fields.length,3);fields[1].value='61';fields[1].oninput();assert(button(view.dialog,'Apply sequence operands').disabled);now={...now,authoringKey:'f'.repeat(64)};await new Promise(done=>setTimeout(done,350));assert(button(view.dialog,'Review sequence operands').disabled);assert.equal(nodes(view.dialog).filter(n=>n.tag==='table').length,0);}finally{view.dispose();}
now={...context};view=openSequenceAuthoring({...params,request:()=>new Promise(done=>resolve=done)});view.dispose();resolve({ok:true,text:async()=>JSON.stringify(options)});await view.ready;assert(view.dialog.removed);assert.equal(nodes(view.dialog).filter(n=>n.tag==='table').length,0);
console.log('Local draft cannot Apply without Review; stale state clears layers and close prevents late publication.');
