import assert from 'node:assert/strict';
import {worldmapAuthoringContext,decodeWorldmapValues,decodeWorldmapSnapshot,decodeWorldmapReview,worldmapMenuMarkers,mountWorldmapAuthoring} from '../editor/worldmap-authoring.js';

const context={projectPath:'C:/private/menu-project',mode:'edit',worldmapKey:'a'.repeat(64)},id=index=>'worldmap://legaia/menu/placements/'+String(index).padStart(4,'0');
const values=()=>({name_index:2,discovery_flag_index:39,destination_scene_id:291,menu_position:{x:96,y:112}});
const nextValues=()=>({...values(),menu_position:{x:97,y:112}});
const evidence={name_index:'retail_static_analysis',discovery_flag_index:'retail_static_analysis',destination_scene_id:'reference_interpretation',menu_position:'reference_interpretation'};
const snapshot=(authored=null,key=context.worldmapKey)=>({schema_version:'legaia.worldmap-authoring.v1',source_key:key,source_record:{iso_file:'SCUS_942.54',sha256:'b'.repeat(64),disc_sha256:'c'.repeat(64),load_address:0x80010000,table_file_offset:0x64298,name_table_file_offset:0x64318,terminator_record_index:2},current_executable_sha256:(authored?'d':'b').repeat(64),names:Array.from({length:16},(_,index)=>({index,name:'Landmark '+index,source_offset:0x64318+index*32})),destinations:[{id:291,label:'Town01'},{id:564,label:'Dolk2'}],placements:[0,1].map(index=>({semantic_id:id(index),record_index:index,retail_values:values(),authored_value:index===0?structuredClone(authored):null,current_values:index===0&&authored?structuredClone(authored):values(),retail_destination_label:'Town01',current_destination_label:index===0&&authored?.destination_scene_id===564?'Dolk2':'Town01',writable:true,reason:null})),limitations:['Names and discovery-index consumers are proved by retail static analysis.','Destination and encoded X/Y meanings are reference interpretations; travel activation is not observed.'],field_evidence:structuredClone(evidence),gameplay_verified:false});
const fieldNames=['name_index','discovery_flag_index','destination_scene_id','menu_position.x','menu_position.y'];
const scalar=(value,field)=>field.startsWith('menu_position.')?value.menu_position[field.slice(14)]:value[field];
const bytes=value=>[value.name_index,value.discovery_flag_index-32,value.destination_scene_id&255,value.destination_scene_id>>>8,value.menu_position.x,value.menu_position.y];
const reviewed=(source=snapshot(),requested=nextValues(),entityId=id(0))=>{
  const row=source.placements.find(row=>row.semantic_id===entityId),proposed=requested??row.retail_values,before=bytes(row.current_values),after=bytes(proposed),offset=source.source_record.table_file_offset+row.record_index*6;
  const changedBytes=before.flatMap((value,index)=>value===after[index]?[]:[{file_offset:offset+index,before_byte:value,after_byte:after[index]}]);
  return {...structuredClone(source),review:{review_key:'f'.repeat(64),entity_id:entityId,values:structuredClone(requested),no_op:JSON.stringify(row.authored_value)===JSON.stringify(requested===null||JSON.stringify(requested)===JSON.stringify(row.retail_values)?null:requested),proposed_values:structuredClone(proposed),proposed_destination_label:source.destinations.find(row=>row.id===proposed.destination_scene_id)?.label??null,audit:{scope:'worldmap-menu-record-only',changed_fields:fieldNames.filter(field=>scalar(row.current_values,field)!==scalar(proposed,field)).map(field=>({field,before:scalar(row.current_values,field),after:scalar(proposed,field)})),changed_bytes:changedBytes,file_offset:offset,byte_length:6,source_executable_sha256:source.source_record.sha256,current_executable_sha256:source.current_executable_sha256,candidate_executable_sha256:changedBytes.length?'e'.repeat(64):source.current_executable_sha256}}};
};

assert.deepEqual(worldmapAuthoringContext(context),context);
for(const change of [{extra:true},{worldmapKey:'bad'},{projectPath:null}])assert.throws(()=>worldmapAuthoringContext({...context,...change}));
assert.deepEqual(decodeWorldmapValues(values(),snapshot().destinations),values());
for(const mutate of [v=>v.name_index=16,v=>v.discovery_flag_index=31,v=>v.discovery_flag_index=288,v=>v.destination_scene_id=999,v=>v.menu_position.x=true,v=>v.menu_position.y=256,v=>v.menu_position.extra=0,v=>v.extra=0]){const value=values();mutate(value);assert.throws(()=>decodeWorldmapValues(value,snapshot().destinations));}
const detached=decodeWorldmapSnapshot(snapshot(),context);detached.placements[0].current_values.menu_position.x=200;assert.equal(snapshot().placements[0].current_values.menu_position.x,96);
for(const mutate of [v=>v.source_key='0'.repeat(64),v=>v.source_record.sha256='bad',v=>v.source_record.disc_sha256='bad',v=>v.source_record.table_file_offset++,v=>v.source_record.terminator_record_index=20,v=>v.names[1].index=0,v=>v.names[0].source_offset++,v=>v.destinations.push(v.destinations[0]),v=>v.placements[0].semantic_id=id(1),v=>v.placements[0].current_values.menu_position.x=97,v=>v.placements[0].current_destination_label='Dolk2',v=>v.placements[0].writable=false,v=>v.field_evidence.menu_position='retail_static_analysis',v=>v.gameplay_verified=true]){const value=snapshot();mutate(value);assert.throws(()=>decodeWorldmapSnapshot(value,context));}
const unknown=snapshot();unknown.placements[0].retail_values.name_index=19;unknown.placements[0].retail_values.destination_scene_id=999;unknown.placements[0].current_values=structuredClone(unknown.placements[0].retail_values);unknown.placements[0].retail_destination_label=unknown.placements[0].current_destination_label=null;assert.equal(decodeWorldmapSnapshot(unknown,context).placements[0].current_values.name_index,19);const unwritable=structuredClone(unknown);unwritable.placements[0].writable=false;unwritable.placements[0].reason='Source row is not uniquely qualified';assert.equal(decodeWorldmapSnapshot(unwritable,context).placements[0].writable,false);
const proposal=decodeWorldmapReview(reviewed(),snapshot(),id(0),nextValues(),context);assert.equal(proposal.review.audit.changed_bytes[0].file_offset,0x6429c);
for(const mutate of [v=>v.review.review_key='bad',v=>v.review.entity_id=id(1),v=>v.review.values.menu_position.x=98,v=>v.review.proposed_values.menu_position.y=113,v=>v.review.audit.changed_fields[0].field='menu_position.y',v=>v.review.audit.changed_bytes[0].file_offset++,v=>v.review.audit.changed_bytes[0].before_byte=90,v=>v.review.audit.byte_length=5,v=>v.review.audit.source_executable_sha256='0'.repeat(64),v=>v.review.audit.current_executable_sha256='0'.repeat(64),v=>v.review.audit.candidate_executable_sha256=v.current_executable_sha256,v=>v.review.no_op=true,v=>v.review.proposed_destination_label='Dolk2']){const value=reviewed();mutate(value);assert.throws(()=>decodeWorldmapReview(value,snapshot(),id(0),nextValues(),context));}
assert.equal(decodeWorldmapReview(reviewed(snapshot(),values()),snapshot(),id(0),values(),context).review.no_op,true);
const authored=snapshot(nextValues()),resetReport=reviewed(authored,null);assert.equal(decodeWorldmapReview(resetReport,authored,id(0),null,context).review.proposed_values.menu_position.x,96);
const redundant=snapshot(values()),cleanup=reviewed(redundant,null);assert.equal(cleanup.review.audit.changed_bytes.length,0);assert.equal(decodeWorldmapReview(cleanup,redundant,id(0),null,context).review.no_op,false);
const markers=worldmapMenuMarkers(snapshot(),reviewed().review);assert.equal(markers.length,5);assert.equal(markers.filter(row=>row.x===96&&row.y===112).length,4);assert.equal(new Set(markers.map(row=>row.entity_id)).size,2);assert.throws(()=>worldmapMenuMarkers(snapshot(),{...reviewed().review,entity_id:id(10)}));

class Node {
  constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.attributes={};this.value='';this.textContent='';this.disabled=false;this.hidden=false;this.open=false;}
  append(...nodes){for(const node of nodes){this.children.push(node);node.parent=this;}}
  prepend(...nodes){this.children.unshift(...nodes);for(const node of nodes)node.parent=this;}
  after(node){const index=this.parent.children.indexOf(this);this.parent.children.splice(index+1,0,node);node.parent=this.parent;}
  replaceChildren(...nodes){this.children=[];this.append(...nodes);}
  setAttribute(key,value){this.attributes[key]=String(value);}
  querySelectorAll(tag){return tree(this).slice(1).filter(node=>node.tagName===tag);}
  showModal(){this.open=true;}
  close(){this.open=false;this.onclose?.();}
  remove(){this.removed=true;if(this.parent)this.parent.children=this.parent.children.filter(node=>node!==this);}
}
const tree=node=>[node,...node.children.flatMap(tree)],action=(dialog,key)=>tree(dialog).find(node=>node.dataset.action===key),input=(dialog,label)=>tree(dialog).find(node=>node.attributes['aria-label']===label),hasText=(dialog,value)=>tree(dialog).some(node=>node.textContent.includes(value));
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const globals={document:globalThis.document,fetch:globalThis.fetch};globalThis.document={body:new Node('body'),createElement:tag=>new Node(tag),createElementNS:(_ns,tag)=>new Node(tag)};
try{
  let ctx=structuredClone(context),isBusy=false,control=null,queue=[],calls=[],commands=[],errors=[],pendingStates=[],inspected=[],apiResult=true,apiPending=null;
  globalThis.fetch=async(path,options)=>{calls.push({path,body:JSON.parse(options.body),signal:options.signal});const next=queue.shift();if(next instanceof Error)throw next;const value=next instanceof Promise?await next:next;assert.ok(value,'A source response must be queued');return {ok:!value.error,json:async()=>structuredClone(value)};};
  const settings={getContext:()=>ctx,busy:()=>isBusy,setBusy:value=>{isBusy=value;control?.updateState();},api:async(path,body)=>{assert.equal(isBusy,false,'Apply must delegate busy ownership to the parent api');commands.push({path,body});isBusy=true;control.updateState();const success=apiPending?await apiPending:apiResult;if(success===true)ctx={...ctx,worldmapKey:'9'.repeat(64)};isBusy=false;control.updateState();return success;},onInspectDestination:async(label,row)=>inspected.push({label,row}),onError:error=>errors.push(error),onDraftChange:pending=>pendingStates.push(pending)};
  const mount=()=>{const anchor=new Node('anchor');document.body.append(anchor);control=mountWorldmapAuthoring({after:anchor,...settings});const dialog=document.body.children.find(node=>Object.hasOwn(node.dataset,'worldmapAuthoring')&&!node.removed);return dialog;};
  const open=async(source=snapshot(),entityId=id(0))=>{const dialog=mount();queue=[source];assert.equal(await control.open(entityId),true);return dialog;};
  const edit=(dialog,label,value)=>{const field=input(dialog,label);field.value=String(value);field.oninput();};
  const review=async(dialog,source=snapshot(),proposed=nextValues())=>{edit(dialog,'Encoded menu X',proposed.menu_position.x);queue=[reviewed(source,proposed)];assert.equal(await action(dialog,'review').onclick(),true);};

  let dialog=await open();assert.equal(calls.at(-1).path,'/api/worldmap-authoring');assert.deepEqual(calls.at(-1).body,{});assert.equal(dialog.style.overflowY,'auto');assert.equal(action(dialog,'apply').disabled,true);assert.equal(hasText(dialog,'drawing and travel consumers are not yet proved'),true);assert.equal(input(dialog,'World-map placement').children.length,2);assert.equal(tree(dialog).filter(node=>Object.hasOwn(node.dataset,'markerLayer')).length,4);assert.equal(hasText(dialog,'Overlapping encoded X/Y 96,112 · 2 source records'),true);assert.equal(await action(dialog,'inspect-destination').onclick(),true);assert.equal(inspected.at(-1).label,'Town01');assert.equal(inspected.at(-1).row.semantic_id,id(0));
  edit(dialog,'Encoded menu X',97);assert.equal(pendingStates.at(-1),true);assert.equal(action(dialog,'apply').disabled,true);assert.equal(input(dialog,'World-map placement').disabled,true);input(dialog,'World-map placement').value=id(1);assert.equal(input(dialog,'World-map placement').onchange(),false);assert.equal(input(dialog,'World-map placement').value,id(0));assert.equal(await control.open(id(1)),false);assert.equal(action(dialog,'close').onclick(),false);let prevented=false;dialog.oncancel({preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(dialog.open,true);assert.equal(action(dialog,'inspect-destination').disabled,true);queue=[reviewed()];assert.equal(await action(dialog,'review').onclick(),true);assert.deepEqual(calls.at(-1).body,{entity_id:id(0),values:nextValues()});assert.equal(action(dialog,'apply').disabled,false);assert.equal(tree(dialog).filter(node=>node.dataset.markerLayer==='proposed').length,1);assert.equal(hasText(dialog,'menu_position.x: 96 → 97'),true);assert.equal(commands.length,0);edit(dialog,'Encoded menu X',98);assert.equal(action(dialog,'apply').disabled,true);assert.equal(tree(dialog).filter(node=>node.dataset.markerLayer==='proposed').length,0);assert.equal(action(dialog,'discard').onclick(),true);assert.equal(pendingStates.at(-1),false);assert.equal(input(dialog,'Encoded menu X').value,'96');assert.equal(await control.open(id(1)),true);assert.equal(input(dialog,'World-map placement').value,id(1));assert.equal(action(dialog,'close').onclick(),true);control.dispose();

  dialog=await open();await review(dialog);const fresh=snapshot(nextValues(),'9'.repeat(64));queue=[fresh];assert.equal(await action(dialog,'apply').onclick(),true);assert.deepEqual(commands.at(-1),{path:'/api/command',body:{type:'set_worldmap_menu',entity_id:id(0),values:nextValues(),review_key:'f'.repeat(64)}});assert.equal(calls.at(-1).path,'/api/worldmap-authoring');assert.equal(input(dialog,'Encoded menu X').value,'97');assert.equal(action(dialog,'apply').disabled,true);assert.equal(action(dialog,'reset').disabled,false);assert.equal(pendingStates.at(-1),false);assert.equal(isBusy,false);control.dispose();ctx=structuredClone(context);
  dialog=await open(authored);queue=[resetReport];assert.equal(await action(dialog,'reset').onclick(),true);assert.equal(calls.at(-1).body.values,null);assert.equal(input(dialog,'Encoded menu X').value,'96');queue=[snapshot(null,'9'.repeat(64))];assert.equal(await action(dialog,'apply').onclick(),true);assert.equal(commands.at(-1).body.values,null);control.dispose();ctx=structuredClone(context);
  dialog=await open();queue=[reviewed(snapshot(),values())];assert.equal(await action(dialog,'review').onclick(),true);assert.equal(action(dialog,'apply').disabled,true);assert.equal(await action(dialog,'apply').onclick(),false);assert.equal(action(dialog,'close').onclick(),true);control.dispose();
  dialog=await open(redundant);queue=[cleanup];assert.equal(await action(dialog,'reset').onclick(),true);assert.equal(action(dialog,'apply').disabled,false,'Explicit reset may remove redundant authored metadata without byte changes');assert.equal(action(dialog,'discard').onclick(),true);control.dispose();

  dialog=await open(unknown);assert.equal(hasText(dialog,'Unknown source name index 19'),true);assert.equal(hasText(dialog,'Unmapped source ID 999'),true);assert.equal(action(dialog,'review').disabled,true);edit(dialog,'Existing landmark name',2);edit(dialog,'Encoded destination definition',291);assert.equal(action(dialog,'review').disabled,false);queue=[reviewed(unknown,values())];assert.equal(await action(dialog,'review').onclick(),true);assert.equal(action(dialog,'apply').disabled,false);assert.equal(action(dialog,'discard').onclick(),true);control.dispose();
  dialog=await open(unwritable);assert.equal(hasText(dialog,'Source row is not uniquely qualified'),true);assert.equal(action(dialog,'review').disabled,true);assert.equal(input(dialog,'Encoded menu X').disabled,true);control.dispose();
  dialog=await open();edit(dialog,'Encoded menu X','');assert.equal(action(dialog,'review').disabled,true);assert.equal(pendingStates.at(-1),true);assert.equal(action(dialog,'close').onclick(),false);assert.equal(action(dialog,'discard').onclick(),true);control.dispose();

  dialog=await open();edit(dialog,'Encoded menu X',97);const late=deferred();queue=[late.promise];const pendingReview=action(dialog,'review').onclick();const reviewSignal=calls.at(-1).signal;edit(dialog,'Encoded menu X',98);assert.equal(reviewSignal.aborted,true);late.resolve(reviewed());assert.equal(await pendingReview,false);assert.equal(isBusy,false);assert.equal(action(dialog,'apply').disabled,true);assert.equal(action(dialog,'discard').onclick(),true);control.dispose();
  dialog=await open();edit(dialog,'Encoded menu X',97);const stale=deferred();queue=[stale.promise];const staleReview=action(dialog,'review').onclick();const staleSignal=calls.at(-1).signal;ctx={...ctx,worldmapKey:'9'.repeat(64)};control.updateState();assert.equal(staleSignal.aborted,true);assert.equal(pendingStates.at(-1),false);stale.resolve(reviewed());assert.equal(await staleReview,false);assert.equal(isBusy,false);assert.equal(action(dialog,'apply').disabled,true);assert.equal(tree(dialog).filter(node=>Object.hasOwn(node.dataset,'markerLayer')).length,0);ctx=structuredClone(context);control.updateState();assert.equal(action(dialog,'review').disabled,true,'A stale workspace cannot revive an old review');control.dispose();
  dialog=await open();await review(dialog);apiResult=false;assert.equal(await action(dialog,'apply').onclick(),false);assert.equal(action(dialog,'apply').disabled,true);assert.equal(action(dialog,'discard').onclick(),true);apiResult=true;control.dispose();
  dialog=await open();edit(dialog,'Encoded menu X',97);queue=[{error:'Executable source changed'}];assert.equal(await action(dialog,'review').onclick(),false);assert.equal(hasText(dialog,'Executable source changed'),true);assert.ok(errors.length);assert.equal(action(dialog,'apply').disabled,true);assert.equal(action(dialog,'discard').onclick(),true);control.dispose();
  dialog=await open();await review(dialog);queue=[{error:'Refreshed source could not be read'}];assert.equal(await action(dialog,'apply').onclick(),false);assert.equal(hasText(dialog,'Menu values were applied. Refreshed source records could not be verified'),true);assert.equal(input(dialog,'Encoded menu X').value,'');assert.equal(action(dialog,'review').disabled,true);assert.equal(action(dialog,'apply').disabled,true);assert.equal(pendingStates.at(-1),false);assert.equal(action(dialog,'close').onclick(),true);control.dispose();ctx=structuredClone(context);

  dialog=await open();await review(dialog);const inFlight=deferred();apiPending=inFlight.promise;const beforeCommands=commands.length;const applying=action(dialog,'apply').onclick();assert.equal(commands.length,beforeCommands+1);assert.equal(await action(dialog,'apply').onclick(),false);assert.equal(action(dialog,'close').onclick(),false);const beforeLoads=calls.length;control.dispose();inFlight.resolve(true);assert.equal(await applying,false);assert.equal(calls.length,beforeLoads);assert.equal(isBusy,false);apiPending=null;ctx=structuredClone(context);
  dialog=await open();edit(dialog,'Encoded menu X',97);const forced=deferred();queue=[forced.promise];const forcedReview=action(dialog,'review').onclick();const forcedSignal=calls.at(-1).signal;dialog.close();forced.resolve(reviewed());assert.equal(await forcedReview,false);assert.equal(forcedSignal.aborted,true);assert.equal(pendingStates.at(-1),false);assert.equal(isBusy,false);queue=[snapshot()];assert.equal(await control.open(id(1)),true);assert.equal(input(dialog,'World-map placement').value,id(1));assert.equal(action(dialog,'apply').disabled,true);control.dispose();
  dialog=mount();const loading=deferred();queue=[loading.promise];const pendingOpen=control.open(id(0));const loadSignal=calls.at(-1).signal;control.dispose();loading.resolve(snapshot());assert.equal(await pendingOpen,false);assert.equal(loadSignal.aborted,true);assert.equal(isBusy,false);assert.equal(dialog.removed,true);
}finally{
  for(const [key,value] of Object.entries(globals)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}
}
console.log('World-map source/evidence/layer and six-byte audit qualification; retained duplicate markers; explicit row draft, review/reset/Apply/refresh; repair, stale, closed, abort and delegated busy guards passed.');
