import assert from 'node:assert/strict';
import {decodeControllerSceneByteSnapshot,decodeControllerSceneByteReview,mountControllerSceneBytes} from '../editor/controller-scene-bytes.js';
const owner='scene://fixture/controllers/man-p1/0000',id='script://fixture/controllers/man-p1/0000/scene-byte/0005',context={projectPath:'C:/private',sceneId:'scene://fixture',mode:'edit',scriptKey:'a'.repeat(64)};
const values=value=>({value});
const report=value=>({status:'decoded_supported_paths',instructions:[{pc:5,length:3,byte_offset:105,mnemonic:'SCENE_STATE_BYTE_WRITE',raw_hex:'4cdf'+value.toString(16).padStart(2,'0'),target_context:null,operands:{sub_op:0xdf,...values(value),native_pointer_global:'0x801C6EA4',native_field_offset:97,scene_state_binding:'runtime_pointer_target_unresolved',value_semantics:'runtime_byte_meaning_unresolved',runtime_effect:'not_evaluated'},successors:[{pc:8,condition:'encoded_continuation'}]},{pc:8,length:3,byte_offset:108,mnemonic:'JMP_REL',raw_hex:'26fcff',target_context:null,operands:{},successors:[{pc:5,condition:'unconditional'}]}],dialogues:[],stops:[],opaque_regions:[],unvisited_instructions:[],unvisited_dialogues:[]});
const snapshot=()=>({schema_version:'legaia.controller-scene-bytes.v1',owner_id:owner,state_key:context.scriptKey,source_record_sha256:'b'.repeat(64),current_record_sha256:'b'.repeat(64),source:{owner_id:owner,record_kind:'man_partition_1_scene_controller',runtime_execution:'not_asserted'},source_report:report(5),current_report:report(5),targets:[{semantic_id:id,owner_id:owner,pc:5,mnemonic:'SCENE_STATE_BYTE_WRITE',sub_op:0xdf,target_context:null,decoded_byte_offset:107,source_record_sha256:'b'.repeat(64),values:values(5),current_values:values(5),authored_values:null}],supported:true,reason:null,limitations:[],gameplay_verified:false});
const proposal=()=>({...snapshot(),operand_id:id,value:values(6),proposed_record_sha256:'c'.repeat(64),review_key:'d'.repeat(64),proposed_report:report(6),changed_decoded_byte_offsets:[107],no_op:false,native_bytes_changed:true,project_changed:false});
assert.equal(decodeControllerSceneByteSnapshot(snapshot(),owner,context).targets.length,1);assert.equal(decodeControllerSceneByteReview(proposal(),snapshot(),id,values(6)).operand_id,id);
for(const change of [r=>r.owner_id='scene://foreign/controllers/man-p1/0000',r=>r.targets[0].owner_id='scene://foreign/controllers/man-p1/0000',r=>r.targets[0].values.value=256,r=>r.schema_version='actor',r=>r.state_key='f'.repeat(64),r=>r.gameplay_verified=true,r=>r.source.runtime_execution='observed',r=>r.targets.push(r.targets[0]),r=>r.targets[0].decoded_byte_offset++,r=>r.targets[0].current_values.value=7,r=>r.current_report.instructions[0].raw_hex='4cdf05ff',r=>r.targets=[],r=>r.current_report.instructions[0].raw_hex='4cde05',r=>r.targets[0].values.value=-1,r=>r.current_report.instructions[0].operands.scene_state_binding=42,r=>r.source_report.instructions[0].operands.value_semantics='none']){const r=snapshot();change(r);assert.throws(()=>decodeControllerSceneByteSnapshot(r,owner,context));}
for(const change of [r=>r.project_changed=true,r=>r.value.value=8,r=>r.changed_decoded_byte_offsets=[105],r=>r.changed_decoded_byte_offsets=[107,107],r=>r.proposed_report.instructions[1].raw_hex='26ffff',r=>r.proposed_report.instructions[0].successors[0].pc=12,r=>r.proposed_record_sha256=r.current_record_sha256,r=>r.proposed_report.instructions[0].operands.value=7]){const r=proposal();change(r);assert.throws(()=>decodeControllerSceneByteReview(r,snapshot(),id,values(6)));}
const retained=snapshot();retained.current_report.unvisited_instructions=[retained.current_report.instructions.shift()];assert.equal(decodeControllerSceneByteSnapshot(retained,owner,context).targets.length,1);
const extended=snapshot();extended.targets[0].target_context=7;extended.targets[0].decoded_byte_offset=108;
for(const report of [extended.source_report,extended.current_report]){const n=report.instructions[0];n.target_context=7;n.length=4;n.raw_hex='cc07'+n.raw_hex.slice(2);n.successors[0].pc=9;const jump=report.instructions[1];jump.pc=9;jump.byte_offset=109;jump.raw_hex='26fbff';}
assert.equal(decodeControllerSceneByteSnapshot(extended,owner,context).targets[0].values.value,5);
class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.value='';}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(name,value){this[name]=value;}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}}
globalThis.document={createElement:tag=>new Node(tag)};let queue=[],ctx=structuredClone(context),busy=false,commands=[],reopened=[];
globalThis.fetch=async()=>({ok:true,json:async()=>await queue.shift()});
const tree=n=>[n,...n.children.flatMap(tree)],button=(h,id)=>tree(h).find(n=>n.dataset.controllerSceneByteAction===id),input=h=>tree(h).filter(n=>n.tag==='input').at(-1);
const settings={owner,getContext:()=>ctx,busy:()=>busy,setBusy:v=>busy=v,api:async(route,body)=>{assert.equal(busy,false);commands.push(body);return true;},reopen:pc=>reopened.push(pc)};
async function mount(extra={},initial=snapshot()){ctx=structuredClone(context);const host=new Node();queue=[initial];const controls=mountControllerSceneBytes(host,{...settings,...extra});assert(await controls.ready);return {host,controls};}
let {host,controls}=await mount();assert.equal(tree(host).filter(n=>n.tag==='input').length,1);assert(tree(host).some(n=>n.textContent==='Retail: 5 \u00b7 Current: 5 \u00b7 Authored: None'));assert(tree(host).some(n=>n.textContent==='Controller Scene-State Byte Requests'));input(host).value='6';input(host).oninput();queue=[proposal()];assert(await button(host,'review').onclick());assert.equal(commands.length,0);assert.equal(tree(host).find(n=>'controllerOperandProposed' in n.dataset).hidden,false);assert(!button(host,'apply').disabled);input(host).value='256';input(host).oninput();assert(button(host,'apply').disabled);assert(button(host,'review').disabled);assert.equal(tree(host).find(n=>'controllerOperandProposed' in n.dataset).hidden,true);
button(host,'discard').onclick();input(host).value='6';input(host).oninput();queue=[proposal()];await button(host,'review').onclick();assert(await button(host,'apply').onclick());assert.equal(commands[0].type,'set_controller_scene_byte');assert.deepEqual(commands[0].value,values(6));assert.deepEqual(reopened,[5]);controls.dispose();
({host,controls}=await mount({api:async()=>false}));input(host).value='6';input(host).oninput();queue=[proposal()];await button(host,'review').onclick();assert.equal(await button(host,'apply').onclick(),false);assert(button(host,'apply').disabled);controls.dispose();
({host,controls}=await mount());input(host).value='6';input(host).oninput();let resolve;queue=[new Promise(r=>resolve=r)];const late=button(host,'review').onclick();ctx.scriptKey='f'.repeat(64);controls.updateState();resolve(proposal());assert.equal(await late,false);assert(button(host,'apply').disabled);assert.equal(busy,false);controls.dispose();
const authored=snapshot();authored.current_record_sha256='c'.repeat(64);authored.current_report=report(6);authored.targets[0].current_values=values(6);authored.targets[0].authored_values=values(6);
({host,controls}=await mount({},authored));queue=[{...proposal(),value:null,current_record_sha256:authored.current_record_sha256,current_report:authored.current_report,proposed_record_sha256:'b'.repeat(64),proposed_report:report(5)}];
assert(await button(host,'reset').onclick());assert.equal(input(host).value,'5');assert(!button(host,'apply').disabled);assert(await button(host,'apply').onclick());assert.equal(commands.at(-1).value,null);controls.dispose();
console.log('Controller scene-byte source/Review qualification, retained boundaries, bounded drafts, typed Apply, failed Apply withdrawal and stale-response rejection passed.');
