import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {decodeTransitionGraph,transitionGraphView} from '../editor/transition-graph.js';

const clone=value=>structuredClone(value),sha=value=>createHash('sha256').update(value).digest('hex'),key=sha('project state'),transitionKey=sha('transition annotations'),path='C:\\fixture',A='scene://alpha',B='scene://beta',U='scene://unavail',REMOTE='scene://remote';
const coverage=(count,partial=0,unavailable=0)=>({script_count:count,partial_script_count:partial,unavailable_script_count:unavailable});
function edge(source,target,{partition=1,index=1,pc=5,status='partial',extended=null,authored={}}={}){
  const route=partition===1?'actors/man-p1':'scripts/man-p2',script=`script://${source.slice(8)}/${route}/${String(index).padStart(4,'0')}`,id=script.replace('script://','transition://')+'/'+pc.toString(16).padStart(4,'0'),name=target===null?null:target.slice(8),imported={entry_x_encoded:97,entry_z_encoded:130,direction_encoded:255};
  return {id,source,target:target??id+'/unresolved-target',script_id:script,script_name:partition===1?`Actor ${index} script`:`Partition 2 script ${index}`,owner_id:script.replace('script://','scene://'),partition,script_status:status,source_record:{disc:{sha256:sha('retail disc'),serial:'SCUS-94254'},iso_file:'PROT.DAT',prot_entry_name:source.slice(8),prot_entry_index:3,partition,record_index:index,byte_offset:128+index*256,byte_length:256,byte_coordinate_space:'decoded_man_payload',sha256:sha(script),containing_decoded_size:4*1024*1024,record_alias_count:1,provenance:{carrier:'Verified source only'}},reference:{pc,byte_offset:128+index*256+pc,mnemonic:'SCENE_CHANGE',extended_target:extended,target_scene_name:name,target_in_scene_index:name===null?null:true,status:name===null?'unsupported_name_encoding':'encoded_named_reference',name_byte_length:name===null?7:name.length,name_sha256:sha(name??'Invalid'),...imported,reachability:'not_evaluated'},reachability:'not_evaluated',entry_layers:{imported,authored:{...authored},effective:{...imported,...authored},validation:Object.keys(authored).length?'reverified_on_build':'imported_reference',transition_id:script+'/transition/'+pc.toString(16).padStart(4,'0')}};
}
function projectGraph(){
  const edges=[edge(A,B,{authored:{entry_x_encoded:7}}),edge(A,B,{partition:2,index:0}),edge(A,null,{pc:32,extended:7}),edge(A,REMOTE,{index:3}),edge(B,A,{status:'decoded_supported_paths'}),edge(B,B,{index:2,status:'decoded_supported_paths'}),edge(B,U,{index:3,status:'decoded_supported_paths'})],unknown=edges[2].target;
  return {schema_version:'legaia.project-transitions.v1',read_only:true,project_path:path,source_key:key,scene_ids:[A,B,U],nodes:[{id:A,name:'alpha',imported:true,roles:['source','destination'],in_scene_index:true},{id:B,name:'beta',imported:true,roles:['source','destination'],in_scene_index:true},{id:U,name:'unavail',imported:true,roles:['destination'],in_scene_index:true},{id:REMOTE,name:'remote',imported:false,roles:['destination'],in_scene_index:true},{id:unknown,name:null,imported:false,roles:['destination'],in_scene_index:null}],edges,scenes:[{scene_id:A,scene_name:'alpha',status:'verified',reference_count:4,coverage:coverage(3,3)},{scene_id:B,scene_name:'beta',status:'verified',reference_count:3,coverage:coverage(3)},{scene_id:U,scene_name:'unavail',status:'unavailable',reason:'Unsupported source carrier'}],coverage:coverage(6,3),limitations:['Encoded instructions only; no reachable route or runtime connection is established.']};
}
const context={projectWide:true,projectPath:path,sceneId:A,sourceKey:key,sceneIds:[A,B,U]},raw=projectGraph(),before=clone(raw),graph=decodeTransitionGraph(raw,context);
assert.deepEqual(raw,before);assert.equal(graph.edges.length,7);assert.equal(graph.scenes.find(row=>row.scene_id===U).status,'unavailable');assert.equal(graph.nodes.find(node=>node.id===U).imported,true);assert.equal(graph.edges.find(row=>row.source===A&&row.partition===2).owner_id,'scene://alpha/scripts/man-p2/0000');
graph.edges[0].source_record.provenance.carrier='Detached';graph.edges[0].entry_layers.effective.entry_x_encoded=4;graph.scenes[0].coverage.script_count=9;graph.limitations.push('Detached');assert.deepEqual(raw,before);
const accepted=decodeTransitionGraph(raw,context),reversed=clone(raw);reversed.nodes.reverse();reversed.edges.reverse();reversed.scenes.reverse();reversed.scene_ids.reverse();assert.deepEqual(decodeTransitionGraph(reversed,context),accepted);

function sceneGraph(){const edges=clone(raw.edges.filter(row=>row.source===A)),targets=new Set(edges.map(row=>row.target));return {schema_version:'legaia.scene-transitions.v1',read_only:true,scene_id:A,source_key:key,transition_state_key:transitionKey,nodes:clone(raw.nodes.filter(node=>node.id===A||targets.has(node.id))).map(node=>({...node,roles:node.id===A?['source']:['destination']})),edges,coverage:coverage(3,3),limitations:clone(raw.limitations)};}
const activeContext={...context,projectWide:false,transitionStateKey:transitionKey},active=decodeTransitionGraph(sceneGraph(),activeContext);assert.equal(active.edges.length,4);assert.equal(Object.hasOwn(active,'scenes'),false);assert.equal(Object.hasOwn(active.edges[0],'script_stop_count'),false);
const self=sceneGraph();self.edges=[edge(A,A,{status:'partial'})];self.nodes=[{id:A,name:'alpha',imported:true,roles:['source','destination'],in_scene_index:true}];self.coverage=coverage(1,1);self.edges[0].reference.target_in_scene_index=false;assert.equal(decodeTransitionGraph(self,activeContext).nodes.length,1,'Source node metadata takes precedence for a self reference, as in the actual builder.');

for(const change of [{projectWide:false},{projectPath:'different'},{sourceKey:sha('stale')},{sceneIds:[A,B]},{sceneIds:[A,B,U,U]},{sourceKey:null}])assert.throws(()=>decodeTransitionGraph(raw,{...context,...change}));
for(const change of [{sceneId:B},{transitionStateKey:sha('stale')},{sceneIds:[B,U]}])assert.throws(()=>decodeTransitionGraph(sceneGraph(),{...activeContext,...change}));
for(const mutate of [
  value=>value.extra='unbounded',value=>value.schema_version='other',value=>value.read_only=false,value=>value.source_key=sha('stale'),value=>value.project_path='other',value=>value.scene_ids.push(A),value=>value.nodes.push(value.nodes[0]),value=>value.edges.push(value.edges[0]),value=>value.nodes.shift(),value=>value.edges[0].target='scene://missing',value=>value.nodes[0].name='other',value=>value.nodes[0].imported=false,value=>value.nodes[0].roles.push('reachable'),value=>value.nodes[2].roles.push('source'),value=>value.nodes.at(-1).imported=true,value=>value.nodes.at(-1).name='invented',value=>value.nodes.at(-1).in_scene_index=true,
  value=>value.coverage.script_count=-1,value=>value.coverage.partial_script_count=7,value=>value.coverage.extra=1,value=>value.scenes[0].reference_count=0,value=>value.scenes[0].scene_name='other',value=>value.scenes[0].coverage.script_count=1025,value=>value.scenes[2].reason='',value=>value.scenes[2].coverage=coverage(0),value=>value.scenes.push(value.scenes[0]),value=>value.limitations=[false],
  value=>value.edges[0].reachability='reachable',value=>value.edges[0].script_status='unavailable',value=>value.edges[0].script_id='script://other/actors/man-p1/0001',value=>value.edges[0].owner_id='scene://alpha/actors/man-p1/0002',value=>value.edges[0].partition=2,value=>value.edges[0].id+='wrong',value=>value.edges[0].script_stop_count=0,value=>value.edges[0].reference.pc=true,value=>value.edges[0].reference.pc=65536,value=>value.edges[0].reference.byte_offset++,value=>value.edges[0].reference.extended_target=256,value=>value.edges[0].reference.mnemonic='WARP',value=>value.edges[0].reference.target_scene_name='Beta',value=>value.edges[0].reference.name_byte_length=3,value=>value.edges[0].reference.target_in_scene_index=null,value=>value.edges[0].reference.name_sha256='bad',value=>value.edges[0].reference.reachability='evaluated',value=>value.edges[0].reference.status='runtime_destination',value=>value.edges[0].reference.direction_encoded=true,
  value=>value.edges[2].reference.target_scene_name='remote',value=>value.edges[2].reference.target_in_scene_index=false,value=>value.edges[2].target=REMOTE,value=>value.edges[2].entry_layers.authored={entry_x_encoded:1},
  value=>value.edges[0].source_record.byte_length=8,value=>value.edges[0].source_record.byte_offset=-1,value=>value.edges[0].source_record.sha256='g'.repeat(64),value=>value.edges[0].source_record.record_index=2,value=>value.edges[0].source_record.partition=2,value=>value.edges[0].source_record.prot_entry_name='other',value=>value.edges[0].source_record.disc.serial='other',value=>value.edges[0].source_record.containing_decoded_size=1,value=>value.edges[0].source_record.raw_hex='00',value=>value.edges[2].source_record.sha256=sha('different same-owner source'),value=>value.edges[2].script_status='decoded_supported_paths',
  value=>value.edges[0].entry_layers.imported.entry_x_encoded=8,value=>value.edges[0].entry_layers.authored.y=0,value=>value.edges[0].entry_layers.authored.entry_x_encoded=256,value=>value.edges[0].entry_layers.effective.entry_x_encoded=97,value=>value.edges[0].entry_layers.validation='already_applied',value=>value.edges[0].entry_layers.transition_id+='wrong',value=>value.edges[0].source_record.loop=value,
]){const changed=projectGraph();mutate(changed);assert.throws(()=>decodeTransitionGraph(changed,context));}
const invalidDestination=sceneGraph();invalidDestination.nodes.find(node=>node.id===B).in_scene_index=false;assert.throws(()=>decodeTransitionGraph(invalidDestination,activeContext));

const view=transitionGraphView(accepted),parallel=view.links.find(link=>link.source===A&&link.target===B);assert.equal(view.totalNodes,5);assert.equal(view.totalEdges,7);assert.equal(view.matchedNodes,5);assert.equal(view.matchedEdges,7);assert.equal(view.omittedEdges,0);assert.equal(view.links.length,6);assert.equal(parallel.edgeIds.length,2);assert.ok(parallel.edgeIds.some(id=>id.includes('/scripts/man-p2/0000/')));assert.ok(view.links.some(link=>link.source===B&&link.target===B),'Self links remain visible references.');assert.ok(view.links.some(link=>link.source===B&&link.target===A),'Cycles do not imply execution or traversal.');
for(const link of view.links){assert.ok(view.nodes.some(node=>node.id===link.source));assert.ok(view.nodes.some(node=>node.id===link.target));for(const id of link.edgeIds)assert.ok(view.edges.some(edge=>edge.id===id));}
assert.deepEqual(transitionGraphView(decodeTransitionGraph(reversed,context)),view);view.nodes[0].roles.push('detached');view.edges[0].reference.pc=0;parallel.edgeIds.length=0;assert.deepEqual(accepted,decodeTransitionGraph(raw,context));
const imported=transitionGraphView(accepted,{importedOnly:true});assert.equal(imported.matchedNodes,3);assert.equal(imported.matchedEdges,5);assert.ok(imported.edges.every(edge=>[A,B,U].includes(edge.source)&&[A,B,U].includes(edge.target)));
const focused=transitionGraphView(accepted,{focusId:A});assert.equal(focused.matchedEdges,5);assert.deepEqual(focused.nodes.map(node=>node.id).sort(),[A,B,REMOTE,raw.edges[2].target].sort());assert.ok(focused.edges.every(edge=>edge.source===A||edge.target===A));assert.ok(!focused.nodes.some(node=>node.id===U),'Direct neighbors exclude second-hop unavailable destination.');
assert.equal(transitionGraphView(accepted,{focusId:'scene://missing'}).matchedNodes,0);assert.equal(transitionGraphView(accepted,{focusId:raw.edges[2].target,importedOnly:true}).matchedEdges,0);
const named=transitionGraphView(accepted,{query:'Partition 2'});assert.equal(named.matchedEdges,1);assert.equal(named.edges[0].partition,2);assert.equal(named.matchedNodes,2);assert.equal(transitionGraphView(accepted,{query:'not-found'}).matchedNodes,0);assert.equal(transitionGraphView(accepted,{query:' PARTIAL '}).matchedEdges,4);assert.equal(transitionGraphView(accepted,{query:'unsupported_name_encoding'}).matchedEdges,1);
const unavailable=transitionGraphView(accepted,{query:'unavailable'});assert.equal(unavailable.matchedEdges,1);assert.ok(unavailable.nodes.some(node=>node.id===U));
const bounded=transitionGraphView(accepted,{maxNodes:2,maxLinks:1});assert.equal(bounded.edges.length,7,'The paginated reference list retains every matching instruction.');assert.equal(bounded.links.length,1);assert.equal(bounded.omittedNodes,3);assert.equal(bounded.omittedLinks,5);assert.equal(bounded.omittedEdges,5,'Two parallel instructions remain represented by the single visible link.');assert.ok(bounded.edges.some(edge=>!bounded.nodes.some(node=>node.id===edge.target)),'Off-canvas rows remain accessible in the list.');
const noLinks=transitionGraphView(accepted,{maxLinks:0});assert.equal(noLinks.omittedEdges,7);assert.equal(noLinks.omittedLinks,6);assert.equal(noLinks.edges.length,7);const noCanvas=transitionGraphView(accepted,{maxNodes:0});assert.equal(noCanvas.nodes.length,0);assert.equal(noCanvas.omittedNodes,5);assert.equal(noCanvas.omittedEdges,7);
const focusCap=transitionGraphView(accepted,{focusId:B,maxNodes:1});assert.deepEqual(focusCap.nodes.map(node=>node.id),[B]);assert.equal(focusCap.links[0].source,B);assert.equal(focusCap.links[0].target,B);
for(const options of [{query:false},{query:'x'.repeat(513)},{focusId:1},{importedOnly:1},{maxNodes:-1},{maxNodes:257},{maxLinks:1025},{maxLinks:2.5}])assert.throws(()=>transitionGraphView(accepted,options));

// Thousands of distinct unresolved names exercise honest canvas omissions.
const large=sceneGraph();large.edges=Array.from({length:3000},(_,index)=>edge(A,null,{pc:index*10,index:1,status:'partial'}));for(const row of large.edges)row.source_record.byte_length=65536;
large.nodes=[{id:A,name:'alpha',imported:true,roles:['source'],in_scene_index:true},...large.edges.map(row=>({id:row.target,name:null,imported:false,roles:['destination'],in_scene_index:null}))];large.coverage=coverage(1,1);
const big=decodeTransitionGraph(large,activeContext),bigView=transitionGraphView(big);assert.equal(bigView.edges.length,3000);assert.equal(bigView.nodes.length,80);assert.equal(bigView.links.length,79);assert.equal(bigView.omittedNodes,2921);assert.equal(bigView.omittedLinks,2921);assert.equal(bigView.omittedEdges,2921);assert.equal(transitionGraphView(big,{importedOnly:true}).nodes.length,1);assert.equal(transitionGraphView(big,{importedOnly:true}).edges.length,0);
const empty=sceneGraph();empty.nodes=[{id:A,name:'alpha',imported:true,roles:['source'],in_scene_index:true}];empty.edges=[];empty.coverage=coverage(1,1);assert.equal(transitionGraphView(decodeTransitionGraph(empty,activeContext)).nodes.length,1);
console.log('Transition graph: current scene/project API, source/coverage/entry guards, detached P1/P2 parallel/unknown/cycle/self records, deterministic filter/focus/grouping, complete list and bounded canvas omissions passed.');
