import assert from 'node:assert/strict';
import {renderNpcDraftInspector} from '../editor/npc-draft-inspector.js';
const property=(id,path,state)=>({id,label:id,path,type:'string',state}),schema={schema_version:'legaia.inspector-schema.v1',live_writes:false,property_states:{'read-only-project':{label:'Project',note:'Metadata'},'authored-through-command':{label:'Authored',note:'Command'},derived:{label:'Derived',note:'Source sample'},unresolved:{label:'Unresolved',note:'Unknown'}},components:{
 NpcDraftIdentity:{label:'NPC draft identity',layout:'read-only-properties',properties:[property('identity',['entity_id'],'read-only-project')],details:[{label:'Donor',path:['donor']}]},
 NpcDraftTransform:{label:'Authored placement',layout:'read-only-properties',properties:[property('X',['draft','position','x'],'authored-through-command')]},
 NpcDraftPreview:{label:'Preview snapshot',layout:'read-only-properties',properties:[property('X',['preview','position','x'],'derived'),property('Y',['preview','position','y'],'unresolved'),property('Surface Y',['preview','preview_position','y'],'derived')]}}};
const snapshot={entity_id:'authored-actor://fixture',draft:{position:{x:128,z:256}},donor:{source:'<retail>'},preview:{position:{x:192,y:null,z:256},preview_position:{x:192,y:12,z:256}}},before=structuredClone(snapshot),html=renderNpcDraftInspector(schema,snapshot,'current');
for(const id of Object.keys(schema.components))assert(html.includes(`data-npc-draft-component="${id}"`));assert(html.includes('<code>128</code>'));assert(html.includes('<code>192</code>'));assert(html.includes('<code>12</code>'));assert(html.includes('<code>—</code>'));assert(html.includes('&lt;retail&gt;'));assert(!html.includes('<input'));assert.deepEqual(snapshot,before);
assert(renderNpcDraftInspector(schema,snapshot,'pending').includes('refresh pending'));assert(renderNpcDraftInspector(schema,snapshot,'source-during-proposal').includes('Proposed viewport coordinates are not substituted'));
const missing=renderNpcDraftInspector(schema,{...snapshot,preview:undefined},'unavailable');assert(missing.includes('No NPC draft preview snapshot'));assert.equal((missing.match(/<code>128<\/code>/g)??[]).length,1);assert(!missing.includes('<code>192</code>'));assert(!missing.includes('<code>12</code>'));
assert.throws(()=>renderNpcDraftInspector(schema,snapshot,'proposal'));assert.throws(()=>renderNpcDraftInspector({...schema,components:{...schema.components,NpcDraftTransform:{...schema.components.NpcDraftTransform,properties:[{id:'X',authoring:{}}]}}},snapshot,'current'));
console.log('SDK NPC draft sections, authored/source preview separation, unknowns, safe details and pending/proposal labels passed.');
