import assert from 'node:assert/strict';
import {decodeTransitionResource,transitionResourceNavigationAllowed,openTransitionResource} from '../editor/transition-resource.js';
const hash='a'.repeat(64),fields=['entry_x_encoded','entry_z_encoded','direction_encoded'];
function arrival(values){const coordinate=value=>(value&127)*128+(value&128?128:64);return {x:coordinate(values.entry_x_encoded),z:coordinate(values.entry_z_encoded),facing_angle_12bit:(values.direction_encoded&7)*512,evidence:'retail_static_handler_and_table',runtime_verified:false,retail_source:'SCUS-94254 PROT[897] offset66312; SCUS_942.54 table80073F04',source:'crates/engine-core/src/world/field_loop.rs:275-308'};}
function resource({partition=1,target='town0b',inIndex=true,extended=null,authored={entry_x_encoded:255,direction_encoded:0xf9},status='decoded_supported_paths'}={}){
  const route=partition===1?'actors/man-p1':'scripts/man-p2',script=`script://fixture/${route}/0001`,id=script.replace('script://','transition://')+'/0005',imported={entry_x_encoded:0,entry_z_encoded:128,direction_encoded:0xfe},effective={...imported,...authored};
  return {semantic_id:id,id,asset_kind:'transition',read_only:true,name:'Scene change to '+(target??'unknown'),source:'scene://fixture',target:target===null?id+'/unresolved-target':'scene://'+target,script_id:script,script_name:'Fixture script',owner_id:'scene://'+script.slice(9),partition,script_status:status,script_stop_count:0,source_record:{synthetic:true,partition,record_index:1,byte_offset:128,byte_length:64,byte_coordinate_space:'synthetic_record',sha256:hash,extra:{carrier:'Synthetic source'}},reference:{pc:5,byte_offset:133,mnemonic:'SCENE_CHANGE',extended_target:extended,target_scene_name:target,target_in_scene_index:target===null?null:inIndex,status:target===null?'unsupported_name_encoding':'encoded_named_reference',name_byte_length:target===null?0:target.length,name_sha256:hash,...imported,reachability:'not_evaluated'},reachability:'not_evaluated',entry_layers:{imported,authored,effective,validation:Object.keys(authored).length?'reverified_on_build':'imported_reference',transition_id:script+'/transition/0005'},arrival_layers:{imported:arrival(imported),effective:arrival(effective)},trigger_position:null,runtime_verified:false,coverage:{script_count:4,partial_script_count:1,unavailable_script_count:1},limitations:['Encoded reference only; runtime route unknown.'],kind:'transition',layer:'derived',scene_id:'scene://fixture',catalog_limitations:['No trigger location is established.']};
}
const source=resource(),snapshot=structuredClone(source),decoded=decodeTransitionResource(source);decoded.entry_layers.effective.entry_x_encoded=0;decoded.source_record.extra.carrier='Detached';decoded.arrival_layers.effective.x=0;decoded.coverage.script_count=9;decoded.limitations.push('Detached');assert.deepEqual(source,snapshot);
assert.equal(decodeTransitionResource(source).arrival_layers.effective.x,16384);assert.equal(decoded.arrival_layers.imported.x,64);assert.equal(decoded.arrival_layers.imported.z,128);assert.equal(decoded.arrival_layers.imported.facing_angle_12bit,3072);
for(const options of [{partition:2,extended:255,authored:{}},{target:null,authored:{},status:'partial'},{target:'named',inIndex:false,authored:{}},{extended:0,authored:{entry_z_encoded:127}}])decodeTransitionResource(resource(options));
decodeTransitionResource(resource({status:'partial'}));
const bare=resource();for(const key of ['kind','layer','scene_id','catalog_limitations'])delete bare[key];decodeTransitionResource(bare);
for(const value of [0,1,127,128,129,255]){const row=resource({authored:{entry_x_encoded:value,entry_z_encoded:value,direction_encoded:value}}),expected=(value&127)*128+(value>=128?128:64);assert.equal(decodeTransitionResource(row).arrival_layers.effective.x,expected);assert.equal(decodeTransitionResource(row).arrival_layers.effective.z,expected);assert.equal(decodeTransitionResource(row).arrival_layers.effective.facing_angle_12bit,(value%8)*512);}
for(const mutate of [
  d=>d.read_only=false,d=>d.runtime_verified=true,d=>d.trigger_position={x:1,z:2},d=>d.reachability='reachable',d=>d.reference.reachability='known',d=>d.asset_kind='trigger',d=>d.id+='-wrong',d=>d.script_id='script://other/actors/man-p1/0001',d=>d.owner_id='scene://fixture/actors/man-p1/0002',d=>d.partition=2,d=>d.source='scene://other',d=>d.scene_id='scene://other',d=>d.layer='live',d=>d.kind='trigger',d=>d.script_stop_count=-1,d=>d.script_stop_count=1,d=>d.source_record.byte_length=15,d=>delete d.source_record.sha256,d=>d.source_record.byte_offset=-1,d=>d.source_record.byte_offset=129,d=>d.source_record.partition=2,d=>d.source_record.record_index=2,d=>d.source_record.byte_coordinate_space='',d=>d.source_record.sha256='bad',d=>d.source_record.payload=[1,2],d=>d.source_record.disc={sha256:hash,serial:'SLUS-00000'},d=>d.source_record.prot_entry_name='other',d=>d.reference.pc=-1,d=>d.reference.byte_offset=134,d=>d.reference.mnemonic='JMP',d=>d.reference.extended_target=256,d=>d.reference.target_scene_name=['town0b'],d=>d.reference.name_byte_length=5,d=>d.reference.name_sha256='bad',d=>d.reference.status='verified',d=>d.reference.entry_x_encoded=true,d=>d.target='scene://other',d=>d.entry_layers.imported.entry_x_encoded=1,d=>d.entry_layers.authored.y=3,d=>d.entry_layers.authored.direction_encoded=256,d=>d.entry_layers.effective.entry_x_encoded=0,d=>d.entry_layers.transition_id+='-wrong',d=>d.entry_layers.validation='applied',d=>d.arrival_layers.imported.x=0,d=>d.arrival_layers.effective.facing_angle_12bit=1,d=>d.arrival_layers.effective.runtime_verified=true,d=>d.arrival_layers.effective.source='guessed',d=>d.arrival_layers.effective.y=0,d=>d.coverage.script_count=0,d=>d.coverage.unavailable_script_count=4,d=>{d.script_status='partial';d.coverage.partial_script_count=0;},d=>d.limitations=[1],d=>d.catalog_limitations=[false],d=>d.source_record.circular=d
]){const bad=structuredClone(source);mutate(bad);assert.throws(()=>decodeTransitionResource(bad));}
const stopped=resource({authored:{},status:'partial'});stopped.script_stop_count=1;decodeTransitionResource(stopped);
const annotatedUnknown=resource({target:null});assert.throws(()=>decodeTransitionResource(annotatedUnknown));
const unknown=resource({target:null,authored:{}});unknown.target='scene://town0b';assert.throws(()=>decodeTransitionResource(unknown));
const gates={current:true,busy:false,canInspect:true,canNavigate:true};for(const action of ['parent','instruction','destination'])assert.equal(transitionResourceNavigationAllowed(source,action,gates),true);
for(const action of [null,5,'script','target',{},undefined])assert.equal(transitionResourceNavigationAllowed(source,action,gates),false);
for(const change of [{current:false},{busy:true},{open:false},{pending:true},{current:1},{busy:undefined}])for(const action of ['parent','instruction','destination'])assert.equal(transitionResourceNavigationAllowed(source,action,{...gates,...change}),false);
assert.equal(transitionResourceNavigationAllowed(source,'parent',{...gates,canInspect:false}),false);assert.equal(transitionResourceNavigationAllowed(source,'instruction',{...gates,canInspect:false}),false);assert.equal(transitionResourceNavigationAllowed(source,'destination',{...gates,canNavigate:false}),false);assert.equal(transitionResourceNavigationAllowed(resource({target:null,authored:{}}),'destination',gates),false);assert.equal(transitionResourceNavigationAllowed(null,'parent',gates),false);

// Small DOM double checks callback routing and closed-dialog generation guards.
class Node{constructor(tag){this.tagName=tag;this.children=[];this.style={};this.attributes={};this.listeners={};this.open=false;this.textContent='';}append(...nodes){this.children.push(...nodes);}setAttribute(key,value){this.attributes[key]=value;}addEventListener(type,callback){this.listeners[type]=callback;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}remove(){this.removed=true;}}
const savedDocument=globalThis.document;globalThis.document={createElement:tag=>new Node(tag),body:new Node('body')};const descendants=node=>[node,...node.children.flatMap(descendants)],button=(dialog,label)=>descendants(dialog).find(node=>node.tagName==='button'&&node.textContent===label);
const record={id:source.id,type:'transition',label:'<literal transition label>',source:'fixture',sceneId:'scene://fixture',data:source};let current=true,busy=false,canInspect=true,canNavigate=true,inspected=[],navigated=[],errors=[];
const settings={record,current:()=>current,busy:()=>busy,canInspect:()=>canInspect,canNavigate:target=>canNavigate&&target==='scene://town0b',onInspect:pc=>{inspected.push(pc);return true;},onNavigate:target=>{navigated.push(target);return true;},onError:error=>errors.push(error)};
try{
  let dialog=openTransitionResource(settings);assert.ok(dialog.open);assert.ok(descendants(dialog).some(node=>node.tagName==='h2'&&node.textContent===record.label));assert.ok(descendants(dialog).some(node=>node.textContent==='Unknown · no source marker'));assert.ok(descendants(dialog).some(node=>node.textContent.includes('4 scripts · 1 partial · 1 unavailable')));
  current=false;await button(dialog,'Inspect parent script').onclick();current=true;busy=true;await button(dialog,'Inspect transition 0x0005').onclick();busy=false;canInspect=false;await button(dialog,'Inspect transition 0x0005').onclick();canInspect=true;canNavigate=false;await button(dialog,'Open imported destination').onclick();assert.deepEqual(inspected,[]);assert.deepEqual(navigated,[]);canNavigate=true;await button(dialog,'Inspect transition 0x0005').onclick();assert.deepEqual(inspected,[5]);assert.equal(dialog.removed,true);
  dialog=openTransitionResource(settings);await button(dialog,'Inspect parent script').onclick();assert.deepEqual(inspected,[5,null]);dialog=openTransitionResource(settings);await button(dialog,'Open imported destination').onclick();assert.deepEqual(navigated,['scene://town0b']);assert.equal(dialog.open,false);
  let finish;dialog=openTransitionResource({...settings,onInspect:pc=>{inspected.push(pc);return new Promise(resolve=>{finish=resolve;});}});const pending=button(dialog,'Inspect transition 0x0005').onclick();assert.equal(button(dialog,'Open imported destination').disabled,true);await button(dialog,'Open imported destination').onclick();assert.deepEqual(navigated,['scene://town0b']);dialog.close();finish(true);assert.equal(await pending,false);assert.equal(dialog.removed,true);
  dialog=openTransitionResource({...settings,onNavigate:()=>false});assert.equal(await button(dialog,'Open imported destination').onclick(),false);assert.equal(dialog.open,true);dialog.close();
  const unresolved=resource({target:null,authored:{}});dialog=openTransitionResource({...settings,record:{...record,id:unresolved.id,data:unresolved}});assert.equal(button(dialog,'Open imported destination').disabled,true);await button(dialog,'Open imported destination').onclick();assert.deepEqual(navigated,['scene://town0b']);dialog.close();
  current=false;assert.equal(openTransitionResource(settings),null);current=true;busy=true;assert.equal(openTransitionResource(settings),null);busy=false;assert.equal(openTransitionResource({...settings,record:{...record,sceneId:'scene://other'}}),null);assert.equal(errors.length,1);assert.deepEqual(source,snapshot);
}finally{if(savedDocument===undefined)delete globalThis.document;else globalThis.document=savedDocument;}
console.log('Transition resources: source/PC/range identity, exact encoded and static arrival layers, unknown triggers, detached metadata, navigation/context/pending/close guards passed.');
