import assert from 'node:assert/strict';
import {decodeRetainedRotationOffset} from '../editor/animation-record-edit.js';
const request={scene_id:'scene://town01',record_id:'11111111-1111-4111-8111-111111111111',source_frame_indices:[1,0,1],edits:[{frame_index:0,object_index:0,translation:{x:17},rotation_psx:{x:4080,y:32}},{frame_index:2,object_index:1,translation:{z:7}}],object_index:0,start:0,end:1,delta:{x:32,y:-48,z:0},expected_source_key:'a'.repeat(64)};
const value={schema_version:'legaia.animation-record-rotation-offset.v1',scene_id:request.scene_id,record_id:request.record_id,project_source_key:request.expected_source_key,source_frame_indices:request.source_frame_indices,before_edits:request.edits,edits:[{frame_index:0,object_index:0,translation:{x:17},rotation_psx:{x:16,y:4080}},{frame_index:1,object_index:0,rotation_psx:{x:64,y:4032}},{frame_index:2,object_index:1,translation:{z:7}}],object_index:0,start:0,end:1,delta:request.delta,before_record_sha256:'b'.repeat(64),after_record_sha256:'c'.repeat(64),changed_axes:[{frame_index:0,axis:'x',before:4080,after:16},{frame_index:0,axis:'y',before:32,after:4080},{frame_index:1,axis:'x',before:32,after:64},{frame_index:1,axis:'y',before:4080,after:4032}],project_changed:false,gameplay_verified:false};
const original=structuredClone({request,value});assert.deepEqual(decodeRetainedRotationOffset(value,request,2),value);assert.deepEqual({request,value},original);
for(const mutate of [v=>v.changed_axes[0].after=48,v=>v.changed_axes[0].before=33,v=>v.changed_axes.pop(),v=>v.edits[0].translation.x=18,v=>v.after_record_sha256=v.before_record_sha256,v=>v.project_changed=true,v=>v.schema_version='legaia.animation-record-offset.v1',v=>v.extra=1]){const bad=structuredClone(value);mutate(bad);assert.throws(()=>decodeRetainedRotationOffset(bad,request,2));}
for(const delta of [{x:1},{x:4096},{x:-4096},{x:true},{x:32,y:-48,z:0,q:0}])assert.throws(()=>decodeRetainedRotationOffset({...value,delta},{...request,delta},2));
const zeroRequest={...request,delta:{x:0,y:0,z:0}},zero={...value,delta:zeroRequest.delta,edits:request.edits,changed_axes:[],after_record_sha256:value.before_record_sha256};assert.deepEqual(decodeRetainedRotationOffset(zero,zeroRequest,2),zero);
console.log('Signed native rotation wrapping, exact grid, draft preservation, zero offsets and forged receipt refusal passed.');
