import assert from 'node:assert/strict';
import {scriptBranchContext,decodeScriptBranchSnapshot,decodeScriptBranchReview,scriptBranchNeighborhood,mountScriptBranches} from '../editor/script-branches.js';

const owner='scene://fixture/actors/man-p1/0003';
const context={projectPath:'C:/private/project',sceneId:'scene://fixture',mode:'edit',scriptKey:'a'.repeat(64)};
const branchId=offset=>'script://fixture/actors/man-p1/0003/branch/'+offset.toString(16).padStart(4,'0');
const instruction=(pc,mnemonic,length,successors=[])=>({pc,mnemonic,length,target_context:null,raw_hex:'00'.repeat(length),successors});
const inspection=target=>({status:'decoded_supported_paths',entry_pc:5,instructions:[instruction(5,'JMP_REL',3,[{pc:target,condition:'unconditional'}]),...(target===10?[instruction(10,'WAIT',3,[{pc:13,condition:null}]),instruction(13,'JMP_REL',3,[{pc:20,condition:'unconditional'}])]:[]),instruction(20,'HALT',1)],dialogues:[],stops:[],opaque_regions:[]});
const snapshot=(authored=null)=>{
  const original=inspection(10),effective=inspection(authored??10);
  return {schema_version:'legaia.script-branches.v1',owner_id:owner,state_key:context.scriptKey,source_record_sha256:'b'.repeat(64),source_report:original,current_report:effective,targets:[5,13].map(offset=>({semantic_id:branchId(offset),owner_id:owner,pc:offset,mnemonic:'JMP_REL',condition:'unconditional',encoding:'relative_u16_wrap16',target_pc:offset===5?10:20,current_target_pc:offset===5?(authored??10):20,authored_value:offset===5&&authored!==null?{target_pc:authored}:null,successors:original.instructions.find(row=>row.pc===offset).successors,current_successors:offset===5?effective.instructions[0].successors:original.instructions.find(row=>row.pc===offset).successors,decoded_byte_offset:100+offset+1,source_record_sha256:'b'.repeat(64)})),destinations:original.instructions.map(({pc,mnemonic})=>({pc,mnemonic})),supported:true,reason:null,limitations:['Existing source target words only.','Encoded paths do not prove runtime activation.'],gameplay_verified:false};
};
const reviewed=(source=snapshot(),value={target_pc:20})=>{
  const target=source.targets[0],after=value?.target_pc??target.target_pc,before=target.current_target_pc,proposed=inspection(after),beforePCs=source.current_report.instructions.map(row=>row.pc),afterPCs=proposed.instructions.map(row=>row.pc);
  return {...structuredClone(source),review:{review_key:'d'.repeat(64),branch_id:target.semantic_id,value:structuredClone(value),no_op:after===before,audit:after===before?[]:[{owner_id:owner,branch_id:branchId(5),pc:5,mnemonic:'JMP_REL',field:'script.branch_target',scope:'script-branch-target-only',before,after,byte_offset:106,byte_length:2,changed_byte_offsets:[106],source_record_sha256:source.source_record_sha256,candidate_record_sha256:'c'.repeat(64)}],source_audit:[],proposed_report:proposed,newly_unreachable_source_pcs:beforePCs.filter(pc=>!afterPCs.includes(pc)),newly_reached_source_pcs:afterPCs.filter(pc=>!beforePCs.includes(pc))}};
};

assert.deepEqual(scriptBranchContext(context),context);
for(const mutate of [value=>value.extra=true,value=>value.scriptKey='bad',value=>value.sceneId='scene://other/actors',value=>value.projectPath=null]){const value=structuredClone(context);mutate(value);assert.throws(()=>scriptBranchContext(value));}
const detached=decodeScriptBranchSnapshot(snapshot(),owner,context);detached.targets[0].successors[0].pc=1;assert.equal(snapshot().targets[0].successors[0].pc,10);
for(const mutate of [value=>value.owner_id+='x',value=>value.state_key='e'.repeat(64),value=>value.source_record_sha256='bad',value=>value.gameplay_verified=true,value=>value.targets[0].semantic_id=branchId(6),value=>value.targets[0].successors[0].pc=13,value=>value.targets[0].condition='executed',value=>value.targets[0].current_successors[0].pc=20,value=>value.targets[0].decoded_byte_offset=true,value=>value.targets[0].source_record_sha256='e'.repeat(64),value=>value.destinations.push({pc:999,mnemonic:'WAIT'}),value=>value.destinations[0].mnemonic='WRONG',value=>value.destinations.push(value.destinations[0]),value=>value.source_report.instructions.push(value.source_report.instructions[0]),value=>value.current_report=null,value=>value.source_report.stops.push({pc:10,reason:'unknown opcode'})]){const value=snapshot();mutate(value);assert.throws(()=>decodeScriptBranchSnapshot(value,owner,context));}
assert.throws(()=>decodeScriptBranchSnapshot(snapshot(),'scene://other/actors/man-p1/0003',context));
const signed=snapshot();signed.targets[0].encoding='relative_i16_wrap16';assert.equal(decodeScriptBranchSnapshot(signed,owner,context).targets[0].encoding,'relative_i16_wrap16');
const messageSource=snapshot();messageSource.source_report.dialogues=[{pc:30,length:4,text:'Hello'}];messageSource.current_report.dialogues=structuredClone(messageSource.source_report.dialogues);messageSource.destinations.push({pc:30,mnemonic:'MES_SEGMENT'});assert.equal(decodeScriptBranchSnapshot(messageSource,owner,context).destinations.at(-1).mnemonic,'MES_SEGMENT');messageSource.destinations.at(-1).mnemonic='DIALOGUE_SEGMENT';assert.throws(()=>decodeScriptBranchSnapshot(messageSource,owner,context));
const partial=snapshot();partial.supported=false;partial.reason='Unknown source opcode at 0x0014';partial.current_report=null;partial.targets=[];partial.destinations=[];partial.source_report.status='partial';partial.source_report.stops=[{pc:20,reason:'unknown opcode'}];partial.source_report.opaque_regions=[{pc:21,length:4,reason:'unreached bytes'}];assert.equal(decodeScriptBranchSnapshot(partial,owner,context).current_report,null);

const checked=decodeScriptBranchReview(reviewed(),snapshot(),branchId(5),{target_pc:20},context);checked.review.audit[0].after=999;assert.equal(reviewed().review.audit[0].after,20);
for(const mutate of [value=>value.review.value.target_pc=13,value=>value.review.branch_id=branchId(13),value=>value.review.review_key='bad',value=>value.targets[0].current_target_pc=20,value=>value.review.audit[0].before=13,value=>value.review.audit[0].byte_offset=107,value=>value.review.audit[0].changed_byte_offsets=[108],value=>value.review.audit[0].source_record_sha256='e'.repeat(64),value=>value.review.audit[0].byte_length=3,value=>value.review.audit[0].after=true,value=>value.review.no_op=true,value=>value.review.audit=[],value=>value.review.newly_unreachable_source_pcs=[],value=>value.review.newly_reached_source_pcs=[10],value=>value.review.proposed_report.instructions[0].successors[0].pc=13,value=>value.review.proposed_report.stops=[{pc:21,reason:'unknown opcode'}]]){const value=reviewed();mutate(value);assert.throws(()=>decodeScriptBranchReview(value,snapshot(),branchId(5),{target_pc:20},context));}
const noop=reviewed(snapshot(),{target_pc:10});assert.equal(decodeScriptBranchReview(noop,snapshot(),branchId(5),{target_pc:10},context).review.no_op,true);
const escaped=reviewed();escaped.review.proposed_report.instructions.push(instruction(999,'HALT',1));escaped.review.newly_reached_source_pcs=[999];assert.throws(()=>decodeScriptBranchReview(escaped,snapshot(),branchId(5),{target_pc:20},context));
const resetting=reviewed(snapshot(20),null);assert.equal(decodeScriptBranchReview(resetting,snapshot(20),branchId(5),null,context).review.value,null);
const redundant=snapshot();redundant.targets[0].authored_value={target_pc:10};const removeRedundant=reviewed(redundant,null);removeRedundant.review.no_op=false;assert.equal(decodeScriptBranchReview(removeRedundant,redundant,branchId(5),null,context).review.audit.length,0);

let neighborhood=scriptBranchNeighborhood(inspection(10),inspection(20),5);assert.deepEqual(neighborhood.edges.map(row=>[row.target,row.layer]),[[10,'current'],[20,'proposed']]);
const graphFixture={status:'decoded_supported_paths',instructions:[instruction(5,'COND_JMP',3,[{pc:5,condition:'test_failed'},{pc:400,condition:'test_passed'}]),...Array.from({length:24},(_,index)=>instruction(20+index,'JMP_REL',1,[{pc:5,condition:'unconditional'}]))],dialogues:[],stops:[{pc:400,reason:'unqualified destination'}],opaque_regions:[]};
neighborhood=scriptBranchNeighborhood(graphFixture,null,5);assert.equal(neighborhood.nodes.length,21);assert.equal(neighborhood.omitted_edge_count,5);assert.ok(neighborhood.edges.some(row=>row.source===5&&row.target===5));assert.equal(neighborhood.nodes.find(row=>row.pc===400).decoded,false);assert.equal(neighborhood.nodes.find(row=>row.pc===400).reason,'unqualified destination');assert.deepEqual(scriptBranchNeighborhood(inspection(10),null,999).nodes,[]);

class Node {
  constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.attributes={};this.value='';this.textContent='';this.disabled=false;this.hidden=false;}
  append(...nodes){for(const node of nodes){this.children.push(node);node.parent=this;}}
  replaceChildren(...nodes){this.children=[];this.append(...nodes);}
  setAttribute(key,value){this.attributes[key]=String(value);}
  remove(){this.removed=true;if(this.parent)this.parent.children=this.parent.children.filter(node=>node!==this);}
}
const tree=node=>[node,...node.children.flatMap(tree)];
const action=(host,key)=>tree(host).find(node=>node.dataset.action===key);
const input=(host,label)=>tree(host).find(node=>node.attributes['aria-label']===label);
const hasText=(host,value)=>tree(host).some(node=>node.textContent.includes(value));
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const globals={document:globalThis.document,fetch:globalThis.fetch};
globalThis.document={createElement:tag=>new Node(tag),createElementNS:(_namespace,tag)=>new Node(tag)};
try{
  let ctx=structuredClone(context),isBusy=false,control=null,queue=[],calls=[],errors=[],drafts=[],selections=[],reopened=[],commands=[],applyResult=true,applying=null;
  globalThis.fetch=async(path,options)=>{calls.push({path,body:JSON.parse(options.body),signal:options.signal});const next=queue.shift();if(next instanceof Error)throw next;const value=next instanceof Promise?await next:next;assert.ok(value,'A response fixture must be queued');return {ok:!value.error,json:async()=>structuredClone(value)};};
  const settings={owner,getContext:()=>ctx,busy:()=>isBusy,setBusy:value=>{isBusy=value;control?.updateState();},api:async(path,body)=>{assert.equal(isBusy,false,'Apply delegates global busy ownership to the parent api');commands.push({path,body});isBusy=true;control.updateState();const result=applying?await applying:applyResult;if(result===true)ctx={...ctx,scriptKey:'e'.repeat(64)};isBusy=false;control.updateState();return result;},selectInstruction:pc=>{selections.push(pc);return true;},reopen:async pc=>reopened.push(pc),onDraftChange:value=>drafts.push(value),onError:error=>errors.push(error)};
  const mount=async(value=snapshot(),extra={})=>{const host=new Node('host');queue=[value];control=mountScriptBranches(host,{...settings,...extra});assert.equal(await control.ready,true);return host;};
  const choose=(host,pc)=>{const destination=input(host,'Qualified branch destination');destination.value=String(pc);destination.onchange();};
  const review=async(host,value=reviewed())=>{choose(host,value.review.value?.target_pc??10);queue=[value];assert.equal(await action(host,'review').onclick(),true);};

  isBusy=true;let host=new Node('host');queue=[snapshot()];const beforeLoad=calls.length;control=mountScriptBranches(host,settings);assert.equal(calls.length,beforeLoad);isBusy=false;control.updateState();assert.equal(await control.ready,true);assert.deepEqual(calls.at(-1).body,{entity:owner});assert.equal(calls.at(-1).path,'/api/script-branches');assert.equal(action(host,'apply').disabled,true);assert.equal(action(host,'reset').disabled,true);assert.equal(hasText(host,'Only SDK-qualified source instruction or atomic MES starts'),true);assert.equal(control.select(10),true);assert.deepEqual(selections,[]);const group=tree(host).find(node=>node.tagName==='g'&&node.dataset.pc==='5');group.onclick();assert.equal(selections.at(-1),5);assert.equal(control.select(999),false);
  input(host,'Filter qualified branch destinations').value='HALT';input(host,'Filter qualified branch destinations').oninput();assert.equal(input(host,'Qualified branch destination').children.length,2,'Selected source destination survives filtering');input(host,'Filter qualified branch destinations').value='';input(host,'Filter qualified branch destinations').oninput();
  choose(host,20);assert.deepEqual([...drafts.at(-1)],[[branchId(5),{target_pc:20}]]);drafts.at(-1).get(branchId(5)).target_pc=999;queue=[reviewed()];assert.equal(await action(host,'review').onclick(),true);assert.deepEqual(calls.at(-1).body,{entity:owner,branch_id:branchId(5),value:{target_pc:20}});assert.equal(action(host,'apply').disabled,false);assert.ok(tree(host).some(node=>node.dataset.edgeLayer==='current'&&node.textContent.includes('0x000A')));assert.ok(tree(host).some(node=>node.dataset.edgeLayer==='proposed'&&node.textContent.includes('0x0014')));assert.equal(commands.length,0);
  choose(host,13);assert.equal(action(host,'apply').disabled,true);const late=deferred();queue=[late.promise];const pendingReview=action(host,'review').onclick();const signal=calls.at(-1).signal;assert.equal(isBusy,true);choose(host,20);assert.equal(signal.aborted,true);assert.equal(isBusy,false);late.resolve(reviewed());assert.equal(await pendingReview,false);assert.equal(action(host,'apply').disabled,true);assert.equal(commands.length,0);control.dispose();control.dispose();assert.equal(host.children.length,0);

  host=await mount();await review(host);assert.equal(await action(host,'apply').onclick(),true);assert.deepEqual(commands.at(-1),{path:'/api/command',body:{type:'set_branch',entity:owner,branch_id:branchId(5),value:{target_pc:20},review_key:'d'.repeat(64)}});assert.deepEqual(reopened,[5]);assert.equal(drafts.at(-1).size,0);assert.equal(isBusy,false);assert.equal(action(host,'apply').disabled,true);control.dispose();ctx=structuredClone(context);
  host=await mount(snapshot(20));assert.equal(action(host,'reset').disabled,false);queue=[resetting];assert.equal(await action(host,'reset').onclick(),true);assert.equal(calls.at(-1).body.value,null);assert.equal(action(host,'apply').disabled,false);assert.equal(await action(host,'apply').onclick(),true);assert.equal(commands.at(-1).body.value,null);control.dispose();ctx=structuredClone(context);
  host=await mount(redundant);queue=[removeRedundant];assert.equal(await action(host,'reset').onclick(),true);assert.equal(action(host,'apply').disabled,false,'A redundant authored layer can be reviewed and removed without source byte changes');control.dispose();
  host=await mount();queue=[noop];assert.equal(await action(host,'review').onclick(),true);assert.equal(action(host,'apply').disabled,true);assert.equal(await action(host,'apply').onclick(),false);control.dispose();

  const pendingBranches=new Map([[branchId(5),{target_pc:20}],[branchId(13),{target_pc:10}]]);
  host=await mount(snapshot(),{initialDrafts:pendingBranches});pendingBranches.get(branchId(13)).target_pc=999;assert.equal(input(host,'Qualified branch destination').value,'20');assert.deepEqual([...drafts.at(-1)],[[branchId(5),{target_pc:20}],[branchId(13),{target_pc:10}]]);input(host,'Source branch').value=branchId(13);input(host,'Source branch').onchange();assert.equal(input(host,'Qualified branch destination').value,'10');input(host,'Source branch').value=branchId(5);input(host,'Source branch').onchange();queue=[reviewed()];assert.equal(await action(host,'review').onclick(),true);assert.equal(await action(host,'apply').onclick(),true);const preserved=new Map(drafts.at(-1));assert.deepEqual([...preserved],[[branchId(13),{target_pc:10}]]);control.dispose();const refreshed=snapshot(20);refreshed.state_key=ctx.scriptKey;host=await mount(refreshed,{initialDrafts:preserved});assert.equal(input(host,'Source branch').value,branchId(13));assert.equal(input(host,'Qualified branch destination').value,'10');assert.equal(action(host,'apply').disabled,true,'A restored draft requires a new review');assert.equal(action(host,'discard').disabled,false);assert.deepEqual([...drafts.at(-1)],[[branchId(13),{target_pc:10}]]);assert.equal(action(host,'discard').onclick(),true);assert.equal(drafts.at(-1).size,0);control.dispose();ctx=structuredClone(context);
  host=await mount(snapshot(20),{initialDrafts:new Map([[branchId(5),{target_pc:20}]])});assert.equal(drafts.at(-1).size,0,'Fresh Current already contains an applied pending choice');assert.equal(tree(host).find(node=>Object.hasOwn(node.dataset,'unavailableBranchDrafts')).hidden,true);control.dispose();
  host=await mount(snapshot(),{initialDrafts:new Map([[branchId(22),null],[branchId(13),{target_pc:999}]])});assert.equal(hasText(host,'This source branch no longer qualifies'),true);assert.equal(hasText(host,'Destination 0x03E7 is no longer a qualified source boundary'),true);assert.equal(drafts.at(-1).size,2);const unavailable=tree(host).filter(node=>node.dataset.action==='discard-unavailable');assert.equal(unavailable.length,2);assert.equal(unavailable[0].onclick(),true);assert.equal(drafts.at(-1).size,1);assert.equal(action(host,'discard-unavailable').onclick(),true);assert.equal(drafts.at(-1).size,0);control.dispose();
  host=new Node('host');queue=[{error:'Private MAN source is unavailable'}];control=mountScriptBranches(host,{...settings,initialDrafts:new Map([[branchId(5),{target_pc:20}]])});assert.equal(await control.ready,false);assert.equal(hasText(host,'The source could not be verified; this draft cannot be applied'),true);assert.equal(drafts.at(-1).size,1);assert.equal(action(host,'apply').disabled,true);assert.equal(action(host,'discard-unavailable').onclick(),true);assert.equal(drafts.at(-1).size,0);control.dispose();
  for(const initialDrafts of [new Map([['script://other/actors/man-p1/0003/branch/0005',{target_pc:20}]]),new Map([[branchId(5),{target_pc:true}]]),{entries:[]}]){host=new Node('host');const requestCount=calls.length;control=mountScriptBranches(host,{...settings,initialDrafts});assert.equal(await control.ready,false);assert.equal(calls.length,requestCount);assert.equal(host.children.length,0);assert.match(errors.at(-1).message,/Pending branch drafts require this source owner/);}

  host=await mount(snapshot(20));assert.equal(control.select(13),true);assert.equal(input(host,'Script flow layer').value,'retail');assert.equal(hasText(host,'Selected source boundary is not decoded in Current'),true);assert.equal(input(host,'Source branch').value,branchId(13));control.dispose();
  host=await mount(partial);assert.equal(input(host,'Script flow layer').value,'retail');assert.equal(input(host,'Script flow layer').children[0].disabled,true);assert.equal(hasText(host,'Unknown source opcode'),true);assert.equal(hasText(host,'Decoder stop: unknown opcode'),true);assert.equal(tree(host).find(node=>Object.hasOwn(node.dataset,'branchForm')).hidden,true);assert.equal(action(host,'review').disabled,true);assert.equal(action(host,'apply').disabled,true);control.dispose();

  host=await mount();choose(host,20);const changing=deferred();queue=[changing.promise];const staleReview=action(host,'review').onclick();const staleSignal=calls.at(-1).signal;ctx={...ctx,scriptKey:'e'.repeat(64)};control.updateState();assert.equal(staleSignal.aborted,true);changing.resolve(reviewed());assert.equal(await staleReview,false);assert.equal(isBusy,false);assert.equal(action(host,'review').disabled,true);ctx=structuredClone(context);control.updateState();assert.equal(action(host,'review').disabled,true,'A stale instance cannot be revived with an old context');control.dispose();
  host=await mount();await review(host);applyResult=false;const reopeningCount=reopened.length;assert.equal(await action(host,'apply').onclick(),false);assert.equal(reopened.length,reopeningCount);assert.equal(action(host,'apply').disabled,true);applyResult=true;control.dispose();
  host=await mount();choose(host,20);queue=[{error:'Source destination no longer qualified'}];assert.equal(await action(host,'review').onclick(),false);assert.equal(hasText(host,'Source destination no longer qualified'),true);assert.equal(action(host,'apply').disabled,true);assert.ok(errors.length);control.dispose();

  host=await mount();await review(host);const inFlight=deferred();applying=inFlight.promise;const commandCount=commands.length;const apply=action(host,'apply').onclick();assert.equal(commands.length,commandCount+1);assert.equal(await action(host,'apply').onclick(),false);ctx={...ctx,sceneId:'scene://other'};control.updateState();inFlight.resolve(true);assert.equal(await apply,false);assert.equal(reopened.length,reopeningCount);assert.equal(isBusy,false);applying=null;control.dispose();ctx=structuredClone(context);
  host=await mount();choose(host,20);const closing=deferred();queue=[closing.promise];const closeReview=action(host,'review').onclick();const closeSignal=calls.at(-1).signal;control.dispose();closing.resolve(reviewed());assert.equal(await closeReview,false);assert.equal(closeSignal.aborted,true);assert.equal(isBusy,false);assert.equal(host.children.length,0);
  host=new Node('host');const delayed=deferred();queue=[delayed.promise];control=mountScriptBranches(host,settings);const loadSignal=calls.at(-1).signal;control.dispose();delayed.resolve(snapshot());assert.equal(await control.ready,false);await Promise.resolve();assert.equal(loadSignal.aborted,true);assert.equal(host.children.length,0);assert.equal(isBusy,false);
}finally{
  for(const [key,value] of Object.entries(globals)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}
}
console.log('Script branch source and review qualification; bounded Current/Proposed graph navigation; queued load, reviewed reset and Apply; detached multiple-branch draft restoration, explicit unavailable-draft discard, context, abort and late-response guards passed.');
