import assert from 'node:assert/strict';
import {decodeRetainedComparison,mountRetainedComparison,comparisonChannelTarget} from '../editor/animation-record-comparison.js';
const scene='scene://town01',key='a'.repeat(64),owner=scene+'/actors/man-p1/0011',asset='asset://town01/models/scene-tmd/0001';
const left={record_id:'11111111-1111-4111-8111-111111111111',record_sha256:'b'.repeat(64),donor_asset_id:asset,object_count:1,frame_count:3,active:false,entity_id:owner,channel_owner_entity_id:owner,model_source_entity_id:owner,donor_animation_id:'animation://town01/scene-anm/0001'},right={...left,record_id:'22222222-2222-4222-8222-222222222222',record_sha256:'c'.repeat(64),frame_count:4,active:true};
const request={scene_id:scene,left_record_id:left.record_id,right_record_id:right.record_id,expected_source_key:key};
const entry=row=>({...row,source_frame_indices:Array(row.frame_count).fill(0)});
const result=()=>({schema_version:'legaia.animation-record-comparison.v1',scene_id:scene,project_source_key:key,left_entry:entry(left),right_entry:entry(right),left_active:false,right_active:true,paired_frame_count:3,left_only_frame_count:0,right_only_frame_count:1,differences:[{frame_index:1,object_index:0,field:'rotation_psx',axis:'x',left:4080,right:0,delta:-4080}],opaque_channel_difference_count:0,header_difference_count:1,native_byte_difference_count:9,native_bytes_equal:false,project_changed:false,gameplay_verified:false});
const report=decodeRetainedComparison(result(),request,left,right);report.differences[0].left=0;assert.equal(result().differences[0].left,4080);
for(const side of ['left','right']){const v=result(),target=comparisonChannelTarget(v,side,v.differences[0],left,right);assert.equal(target.row.record_id,(side==='left'?left:right).record_id);assert.deepEqual(target.channel,{frame:1,object:0,field:'rotation_psx',axis:'x',effective_value:side==='left'?4080:0});target.row.record_sha256='changed';assert.equal((side==='left'?left:right).record_sha256,side==='left'?'b'.repeat(64):'c'.repeat(64));}
assert.throws(()=>comparisonChannelTarget(result(),'foreign',result().differences[0],left,right));assert.throws(()=>comparisonChannelTarget(result(),'right',{...result().differences[0],object_index:1},left,right));assert.throws(()=>comparisonChannelTarget(result(),'right',result().differences[0],left,{...right,record_sha256:'f'.repeat(64)}));
for(const mutate of [v=>v.project_source_key='d'.repeat(64),v=>v.left_active=true,v=>v.right_only_frame_count=0,v=>v.differences[0].right=1,v=>v.differences[0].delta=16,v=>v.differences.push(v.differences[0]),v=>v.native_bytes_equal=true,v=>v.right_entry.record_sha256=left.record_sha256]){const value=result();mutate(value);assert.throws(()=>decodeRetainedComparison(value,request,left,right));}
class Node{constructor(tag){this.tagName=tag;this.style={};this.children=[];this.value='';this.disabled=false;this.textContent='';}append(...nodes){for(const n of nodes){this.children.push(n);n.parent=this;}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(){}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const old={document:globalThis.document,fetch:globalThis.fetch};globalThis.document={createElement:tag=>new Node(tag)};
try{let context={sceneId:scene,sourceKey:key},busy=false,hold=null,calls=[];globalThis.fetch=async(path,options)=>{calls.push(JSON.parse(options.body));if(hold)return hold;return {ok:true,json:async()=>result()};};const host=new Node('div'),control=mountRetainedComparison({host,getRows:()=>[left,right],getSelected:()=>left,getContext:()=>context,busy:()=>busy,setBusy:value=>busy=value,onError:e=>{throw e;}}),section=host.children[0],button=section.children[1];control.updateState();assert.equal(button.disabled,false);assert.equal(await button.onclick(),true);assert.deepEqual(calls[0],request);assert.equal(busy,false);assert(section.children[2].textContent.includes('1 changed axes'));
const navigationHost=new Node('div'),opened=[],navigation=mountRetainedComparison({host:navigationHost,getRows:()=>[left,right],getSelected:()=>left,getContext:()=>context,busy:()=>busy,setBusy:value=>busy=value,onError:e=>{throw e;},onOpen:(row,channel)=>opened.push({row,channel})});navigation.updateState();await navigationHost.children[0].children[1].onclick();const nativeRow=navigationHost.children[0].children[3].children[0].children[1],leftButton=nativeRow.children[3].children[0],rightButton=nativeRow.children[4].children[0];assert.equal(await rightButton.onclick(),true);assert.equal(opened[0].row.record_id,right.record_id);assert.equal(opened[0].channel.effective_value,0);busy=true;navigation.updateState();assert.equal(leftButton.disabled,true);assert.equal(await leftButton.onclick(),false);busy=false;navigation.updateState();assert.equal(await leftButton.onclick(),true);assert.equal(opened[1].row.record_id,left.record_id);context={...context,sourceKey:'e'.repeat(64)};assert.equal(await rightButton.onclick(),false);navigation.updateState();assert.equal(await leftButton.onclick(),false);navigation.dispose();assert.equal(await rightButton.onclick(),false);context={sceneId:scene,sourceKey:key};
const manyLeft={...left,frame_count:6,object_count:6},manyRight={...right,frame_count:6,object_count:6},many={...result(),left_entry:entry(manyLeft),right_entry:entry(manyRight),paired_frame_count:6,right_only_frame_count:0,differences:Array.from({length:101},(_,i)=>({frame_index:Math.floor(i/18),object_index:Math.floor(i%18/3),field:'translation',axis:'xyz'[i%3],left:0,right:1,delta:1})),native_byte_difference_count:102};
const savedFetch=globalThis.fetch;globalThis.fetch=async()=>({ok:true,json:async()=>many});const pagedHost=new Node('div'),paged=mountRetainedComparison({host:pagedHost,getRows:()=>[manyLeft,manyRight],getSelected:()=>manyLeft,getContext:()=>context,busy:()=>busy,setBusy:value=>busy=value,onError:e=>{throw e;}});paged.updateState();await pagedHost.children[0].children[1].onclick();const output=pagedHost.children[0].children[3];assert.equal(output.children[0].children.length,101);output.children.at(-1).onclick();assert.equal(output.children[0].children.length,2);assert.equal(output.children[1].disabled,false);paged.dispose();globalThis.fetch=savedFetch;
let resolve;hold=new Promise(done=>resolve=done);const pending=button.onclick();assert.equal(busy,true);context={...context,sourceKey:'d'.repeat(64)};control.updateState();assert.equal(busy,false);resolve({ok:true,json:async()=>result()});assert.equal(await pending,false);assert.equal(section.children[3].children.length,0);control.dispose();assert.equal(host.children.length,0);
}finally{for(const [key,value] of Object.entries(old)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
console.log('Retained native comparison source/model/count/grid checks, detached values, encoded deltas and stale in-flight withdrawal passed.');
