import assert from 'node:assert/strict';
import {decodeRetainedEditOptions,decodeRetainedEditReview,decodeRetainedEditPose,validateRetainedAxes,openRetainedAnimationEditor,retainedChannelSelection,restoreRetainedDonorAxes} from '../editor/animation-record-edit.js';
const entity='scene://town01/actors/man-p1/0011',id='11111111-1111-4111-8111-111111111111',asset='asset://town01/models/scene-tmd/0105';
const context={projectPath:'C:/private',sceneId:'scene://town01',sourceKey:'a'.repeat(64),mode:'edit'};
const row={record_id:id,record_sha256:'b'.repeat(64),donor_asset_id:asset,frame_count:3,object_count:6,active:true};
const entry={...row,source_frame_indices:[1,0,1],edits:[],donor_frame_count:20};
const options={schema_version:'legaia.animation-record-edit-options.v1',scene_id:context.sceneId,record_id:id,project_source_key:context.sourceKey,entry,revision:1,edit_available:true,active:true,maximum_frame_count:512,referencing_actors:[entity],gameplay_verified:false};
const binding={scene_id:context.sceneId,record_id:id,record_sha256:row.record_sha256,model_asset_id:asset};
const report=request=>{const after={...entry,source_frame_indices:request.source_frame_indices,edits:request.edits,record_sha256:'c'.repeat(64)};return {schema_version:'legaia.animation-record-edit-review.v1',scene_id:context.sceneId,record_id:id,project_source_key:context.sourceKey,before:entry,after,review_key:'d'.repeat(64),candidate_record_sha256:after.record_sha256,candidate_bank_sha256:'e'.repeat(64),project_change:true,project_changed:false,gameplay_verified:false,proposed_ledger:{schema_version:'legaia.animation-record-ledger.v1',source_scene_id:context.sceneId,revision:2,records:[after],removed_record_ids:[]},assignment_updates:{[entity]:{before:binding,after:{...binding,record_sha256:after.record_sha256}}}};};
const request={scene_id:context.sceneId,record_id:id,source_frame_indices:[1,0,1,0],edits:[{frame_index:0,object_index:0,translation:{x:2}}],expected_source_key:context.sourceKey};
const pose=r=>({schema_version:'legaia.model-preview.v1',semantic_id:asset,frames:Array.from({length:r.after.source_frame_indices.length},()=>({})),animation:{representation:'allocated_record_edit_preview',clip_id:'allocated-record-edit-preview',edit_proposal:r,source_record:{record_id:id,record_sha256:r.after.record_sha256}}});
decodeRetainedEditOptions(options,row,context);decodeRetainedEditReview(report(request),options,request);decodeRetainedEditPose(pose(report(request)),report(request));
for(const edit of [v=>v.candidate_record_sha256='0'.repeat(64),v=>v.assignment_updates={},v=>v.proposed_ledger.removed_record_ids=[id],v=>v.after.source_frame_indices=[0]]){const v=structuredClone(report(request));edit(v);assert.throws(()=>decodeRetainedEditReview(v,options,request));}
assert.throws(()=>validateRetainedAxes([{frame_index:0,object_index:0,rotation_psx:{x:1}}],3,6));assert.throws(()=>validateRetainedAxes([{frame_index:3,object_index:0,translation:{x:2}}],3,6));
class Node{constructor(tag){this.children=[];this.style={};this.dataset={};this.attributes={};this.value='';this.open=false;this.disabled=false;}append(...nodes){for(const n of nodes){this.children.push(n);n.parent=this;}}setAttribute(k,v){this.attributes[k]=v;}replaceChildren(...nodes){this.children=[];this.append(...nodes);}showModal(){this.open=true;}close(){this.open=false;this.onclose?.();}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)],action=(c,k)=>tree(c.dialog).find(n=>n.dataset.action===k),input=(c,k)=>tree(c.dialog).find(n=>n.attributes['aria-label']===k);
const old={document:globalThis.document,fetch:globalThis.fetch};globalThis.document={body:new Node('body'),createElement:t=>new Node(t)};
const authored=[{frame_index:0,object_index:0,translation:{x:12,z:34},rotation_psx:{x:16}},{frame_index:1,object_index:0,translation:{x:99}},{frame_index:0,object_index:1,translation:{x:-3}}],restoration={edits:authored,frameCount:3,objectCount:6,objectIndex:0,start:0,end:0,fields:['translation'],axes:['x']};
const restored=restoreRetainedDonorAxes(restoration);assert.equal(restored.removed_axes,1);assert.deepEqual(restored.edits,[{frame_index:0,object_index:0,translation:{z:34},rotation_psx:{x:16}},authored[1],authored[2]]);assert.equal(authored[0].translation.x,12);
assert.deepEqual(restoreRetainedDonorAxes({...restoration,allObjects:true,fields:['translation','rotation_psx'],axes:['x','y','z']}).edits,[authored[1]]);
assert.deepEqual(restoreRetainedDonorAxes({...restoration,fields:['rotation_psx']}).edits,[{frame_index:0,object_index:0,translation:{x:12,z:34}},authored[1],authored[2]]);
assert.deepEqual(restoreRetainedDonorAxes({...restoration,axes:['y']}),{edits:authored,removed_axes:0});
for(const bad of [{axes:[]},{axes:['x','x']},{fields:['scale']},{allObjects:1},{end:3},{start:1,end:0},{objectIndex:6}])assert.throws(()=>restoreRetainedDonorAxes({...restoration,...bad}));
Node.prototype.focus=function(){globalThis.document.activeElement=this;};
const target={frame:2,object:3,field:'rotation_psx',axis:'x',effective_value:16};
assert.deepEqual(retainedChannelSelection(target,row),target);
for(const bad of [{...target,frame:3},{...target,object:6},{...target,axis:'w'},{...target,field:'scale'},{...target,effective_value:17},{frame:0,object:0,effective_value:0}])assert.throws(()=>retainedChannelSelection(bad,row));
try{
 let current={...context},busy=false,applied=0,returned,calls=[],heldReport,delay=null;
 globalThis.fetch=async(path,settings)=>{const body=JSON.parse(settings.body);calls.push({path,body});if(delay?.path===path)return delay.promise;return {ok:true,json:async()=>path.endsWith('-options')?options:path.endsWith('-review')?(heldReport=report(body)):path.endsWith('-pose')?pose(heldReport):{project:{mode:'edit'}}};};
 const settings={row,getContext:()=>current,busy:()=>busy,setBusy:v=>busy=v,onApplied:()=>applied++,onPosePreview:async(_,callbacks)=>returned=callbacks.returnToEditor};
 const focused=await openRetainedAnimationEditor({...settings,initialChannel:target});assert.equal(await focused.ready,true);assert.equal(input(focused,'Allocated frame index').value,'2');assert.equal(input(focused,'Rigid object index').value,'3');assert.equal(globalThis.document.activeElement,input(focused,'Rotation X'));assert.equal(input(focused,'Rotation X').value,'');assert.equal(input(focused,'Rotation X').placeholder,'Compared: 16');await action(focused,'review').onclick();assert.deepEqual(calls.at(-1).body.edits,[]);input(focused,'Allocated frame index').value='1';input(focused,'Allocated frame index').onchange();assert.equal(input(focused,'Rotation X').placeholder,'');focused.dispose();
 let control=await openRetainedAnimationEditor(settings);await control.ready;
 input(control,'Translation X').value='12';input(control,'Translation X').oninput();input(control,'Rotation X').value='16';input(control,'Rotation X').oninput();await action(control,'review').onclick();assert.equal(action(control,'apply').disabled,false);const restoreDepth=calls.length;assert.equal(action(control,'restore-donor').onclick(),true);assert.equal(calls.length,restoreDepth);assert.equal(input(control,'Translation X').value,'');assert.equal(input(control,'Rotation X').value,'16');assert.equal(action(control,'apply').disabled,true);await action(control,'review').onclick();assert.deepEqual(calls.at(-1).body.edits,[{frame_index:0,object_index:0,rotation_psx:{x:16}}]);assert.equal(action(control,'restore-donor').onclick(),true);assert.equal(action(control,'apply').disabled,false);for(const axis of ['X','Y','Z'])input(control,'Restore donor '+axis).checked=false;assert.equal(action(control,'restore-donor').onclick(),false);assert.equal(action(control,'apply').disabled,false);control.dispose();control=await openRetainedAnimationEditor(settings);await control.ready;
 input(control,'Captured donor frame mapping').value='1,0,1,0';input(control,'Captured donor frame mapping').oninput();input(control,'Translation X').value='2';input(control,'Translation X').oninput();
 assert.equal(action(control,'apply').disabled,true);assert.equal(await action(control,'review').onclick(),true);assert.deepEqual(calls.at(-1).body,request);
 assert.equal(await action(control,'pose').onclick(),true);assert.equal(control.dialog.open,false);assert.equal(returned(),true);assert.equal(action(control,'apply').disabled,false);
 input(control,'Translation X').value='3';input(control,'Translation X').oninput();assert.equal(action(control,'apply').disabled,true);assert.equal(await action(control,'apply').onclick(),false);
 await action(control,'review').onclick();assert.equal(await action(control,'apply').onclick(),true);assert.equal(applied,1);assert.equal(calls.at(-1).body.review_key,'d'.repeat(64));assert.equal(busy,false);
 control=await openRetainedAnimationEditor(settings);await control.ready;input(control,'Translation X').value='2';input(control,'Translation X').oninput();await action(control,'review').onclick();const navigationDepth=calls.length,timelineFrame=n=>tree(control.dialog).find(b=>b.dataset.action==='timeline-frame'&&b.dataset.frame===String(n));assert.equal(timelineFrame(0).dataset.authored,'true');timelineFrame(2).onclick();assert.equal(input(control,'Allocated frame index').value,'2');assert.equal(input(control,'Translation X').value,'');assert.equal(action(control,'apply').disabled,false);timelineFrame(0).onclick({shiftKey:true});assert.equal(input(control,'Sequence start frame').value,'0');assert.equal(input(control,'Sequence end frame').value,'2');assert.equal(input(control,'Translation X').value,'2');assert.equal(action(control,'apply').disabled,false);assert.equal(calls.length,navigationDepth);const depth=calls.length;
 action(control,'reverse').onclick();assert.equal(calls.length,depth);assert.equal(action(control,'apply').disabled,true);assert.equal(input(control,'Allocated frame index').value,'2');await action(control,'review').onclick();assert.deepEqual(calls.at(-1).body.edits,[{frame_index:2,object_index:0,translation:{x:2}}]);
 input(control,'Sequence start frame').value='0';input(control,'Sequence end frame').value='2';action(control,'remove').onclick();assert.equal(input(control,'Captured donor frame mapping').value,'1,0,1');assert.equal(action(control,'apply').disabled,false); // Rejected operation retains accepted review and draft.
 input(control,'Sequence start frame').value='1';input(control,'Sequence end frame').value='2';action(control,'repeat').onclick();assert.equal(input(control,'Captured donor frame mapping').value,'1,0,1,0,1');assert.equal(action(control,'apply').disabled,true);await action(control,'review').onclick();assert.deepEqual(calls.at(-1).body.edits,[{frame_index:2,object_index:0,translation:{x:2}},{frame_index:4,object_index:0,translation:{x:2}}]);control.dispose();
 control=await openRetainedAnimationEditor(settings);await control.ready;input(control,'Translation X').value='-2';input(control,'Translation X').oninput();input(control,'Allocated frame index').value='2';input(control,'Allocated frame index').onchange();input(control,'Translation X').value='2';input(control,'Translation X').oninput();await action(control,'review').onclick();const interpolationDepth=calls.length;
 action(control,'interpolate').onclick();assert.equal(calls.length,interpolationDepth);assert.equal(action(control,'apply').disabled,true);await action(control,'review').onclick();assert.deepEqual(calls.at(-1).body.edits.map(r=>r.translation.x),[-2,0,2]);
 input(control,'Sequence end frame').value='0';action(control,'interpolate').onclick();assert.equal(action(control,'apply').disabled,false);assert.equal(calls.length,interpolationDepth+1);control.dispose();
 control=await openRetainedAnimationEditor(settings);await control.ready;await action(control,'review').onclick();current={...context,sourceKey:'f'.repeat(64)};control.updateState();assert.equal(await action(control,'apply').onclick(),false);assert.equal(action(control,'interpolate').disabled,true);assert.equal(action(control,'restore-donor').disabled,true);assert.equal(action(control,'restore-donor').onclick(),false);assert.equal(tree(control.dialog).filter(n=>n.dataset.action==='timeline-frame').length,0);control.dispose();
 current={...context};options.revision=64;options.edit_available=false;control=await openRetainedAnimationEditor(settings);await control.ready;const readonlyDepth=calls.length;assert.equal(timelineFrame(2).disabled,false);timelineFrame(2).onclick();assert.equal(input(control,'Allocated frame index').value,'2');assert.equal(input(control,'Translation X').disabled,true);assert.equal(action(control,'restore-donor').disabled,true);assert.equal(action(control,'restore-donor').onclick(),false);assert.equal(action(control,'review').disabled,true);assert.equal(calls.length,readonlyDepth);control.dispose();options.revision=1;options.edit_available=true;
 current={...context};control=await openRetainedAnimationEditor(settings);await control.ready;let resolve;delay={path:'/api/animation-record-edit-review',promise:new Promise(done=>resolve=done)};const late=action(control,'review').onclick();control.dispose();resolve({ok:true,json:async()=>report(request)});assert.equal(await late,false);assert.equal(applied,1);assert.equal(busy,false);
}finally{Object.assign(globalThis,old);}
console.log('Retained editor provenance, frame/axis draft, reference Review, Preview Return, exact Apply and stale/draft/late guards passed.');
