// Exercise the mounted vector editor handlers with unequal Retail/Current tables.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const code=readFileSync(new URL('../editor/editor.js',import.meta.url),'utf8');
const start=code.indexOf('    const load=()=>{const values=document.objects');
const end=code.indexOf('    object.onchange=kind.onchange=',start);
assert.ok(start>=0&&end>start);
const resetStart=code.indexOf("    form.querySelector('[data-retail-vector]').onclick=",end);
const resetEnd=code.indexOf("    form.querySelector('[data-locate-vector]').onclick=",resetStart);
assert.ok(resetStart>end&&resetEnd>resetStart);
const object={value:'0'},kind={value:'vertices'},index={value:'0'},xyz=[{},{},{}];
const nodes=new Map();
const form={querySelector(selector){if(!nodes.has(selector))nodes.set(selector,{});return nodes.get(selector);}};
const document={objects:[{vertices:[[1,2,3],[10,20,30]],normals:[[100,200,300]]}]};
const retail={objects:[{vertices:[[4,5,6]],normals:[]}]};
const handlers=new Function('document','retail','object','kind','index','xyz','form','moveVertex',`let valid=false,busy=false;${code.slice(start,end)}${code.slice(resetStart,resetEnd)}return {load,reset:form.querySelector('[data-retail-vector]').onclick};`)(document,retail,object,kind,index,xyz,form,{});
handlers.load();assert.equal(form.querySelector('[data-retail-vector]').disabled,false);
handlers.reset();assert.deepEqual(xyz.map(input=>input.value),[4,5,6]);
index.value='1';handlers.load();
assert.equal(form.querySelector('[data-retail-vector]').disabled,true);
assert.equal(form.querySelector('[type=submit]').disabled,false);
assert.match(form.querySelector('[data-retail]').textContent,/no Retail counterpart/);
assert.deepEqual(xyz.map(input=>input.value),[10,20,30]);
assert.doesNotThrow(()=>handlers.reset());assert.deepEqual(xyz.map(input=>input.value),[10,20,30]);
kind.value='normals';index.value='0';handlers.load();
assert.equal(form.querySelector('[data-retail-vector]').disabled,true);
assert.equal(form.querySelector('[type=submit]').disabled,false);
assert.deepEqual(xyz.map(input=>input.value),[100,200,300]);
assert.doesNotThrow(()=>handlers.reset());
index.value='1';handlers.load();assert.equal(form.querySelector('[type=submit]').disabled,true);
assert.equal(form.querySelector('[data-retail-vector]').disabled,true);
console.log('Mounted vector handlers preserve Current drafts and withhold absent Retail resets.');
