import assert from 'node:assert/strict';
import {decodeRetainedOffset,openRetainedAnimationEditor} from '../editor/animation-record-edit.js';
const id='11111111-1111-4111-8111-111111111111',context={projectPath:'C:/private',sceneId:'scene://town01',sourceKey:'a'.repeat(64),mode:'edit'},row={record_id:id,record_sha256:'b'.repeat(64),donor_asset_id:'asset://town01/models/scene-tmd/0105',frame_count:3,object_count:2,active:true};
const entry={...row,source_frame_indices:[1,0,1],edits:[],donor_frame_count:3},options={schema_version:'legaia.animation-record-edit-options.v1',scene_id:context.sceneId,record_id:id,project_source_key:context.sourceKey,entry,revision:1,edit_available:true,active:true,maximum_frame_count:512,referencing_actors:[],gameplay_verified:false};
const request={scene_id:context.sceneId,record_id:id,source_frame_indices:[1,0,1],edits:[{frame_index:0,object_index:0,translation:{x:17},rotation_psx:{y:32}}],object_index:0,start:0,end:1,delta:{x:5,y:0,z:0},expected_source_key:context.sourceKey};
function result(r){const edits=structuredClone(r.edits),changed=[];for(let frame=r.start;frame<=r.end;frame++){let row=edits.find(e=>e.frame_index===frame&&e.object_index===r.object_index);for(const axis of Object.keys(r.delta).sort()){if(!r.delta[axis])continue;const before=row?.translation?.[axis]??7,after=before+r.delta[axis];if(!row){row={frame_index:frame,object_index:r.object_index};edits.push(row);}(row.translation??={})[axis]=after;changed.push({frame_index:frame,axis,before,after});}}edits.sort((a,b)=>a.frame_index-b.frame_index||a.object_index-b.object_index);return {schema_version:'legaia.animation-record-offset.v1',scene_id:r.scene_id,record_id:r.record_id,project_source_key:r.expected_source_key,source_frame_indices:r.source_frame_indices,before_edits:r.edits,edits,object_index:r.object_index,start:r.start,end:r.end,delta:r.delta,before_record_sha256:'c'.repeat(64),after_record_sha256:changed.length?'d'.repeat(64):'c'.repeat(64),changed_axes:changed,project_changed:false,gameplay_verified:false};}
const value=result(request);decodeRetainedOffset(value,request,2);for(const change of [v=>v.project_changed=true,v=>v.gameplay_verified=true,v=>v.project_source_key='0'.repeat(64),v=>v.before_edits=[],v=>v.changed_axes[0].before=16,v=>v.changed_axes[1].after=2048,v=>v.edits[0].rotation_psx.y=48,v=>v.edits.push({frame_index:2,object_index:1,translation:{z:1}}),v=>v.changed_axes.pop(),v=>v.after_record_sha256=v.before_record_sha256,v=>v.extra=true]){const bad=structuredClone(value);change(bad);assert.throws(()=>decodeRetainedOffset(bad,request,2));}
const detached=decodeRetainedOffset(value,request,2);detached.edits[0].translation.x++;assert.equal(value.edits[0].translation.x,22);const zero={...request,delta:{x:0}};decodeRetainedOffset(result(zero),zero,2);
class Node{constructor(tag){this.children=[];this.style={};this.dataset={};this.attributes={};this.value='';this.open=false;this.disabled=false;}append(...nodes){for(const n of nodes){this.children.push(n);n.parent=this;}}setAttribute(k,v){this.attributes[k]=v;}replaceChildren(...nodes){this.children=[];this.append(...nodes);}showModal(){this.open=true;}close(){this.open=false;this.onclose?.();}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
globalThis.document={createElement:t=>new Node(t),body:new Node('body')};const tree=n=>[n,...n.children.flatMap(tree)],input=(ui,name)=>tree(ui.dialog).find(n=>n.attributes['aria-label']===name),action=(ui,id)=>tree(ui.dialog).find(n=>n.dataset.action===id);let busy=false,now={...context},resolve,pending=false,calls=[];
globalThis.fetch=async(path,args)=>{const body=JSON.parse(args.body);calls.push({path,body});if(path.endsWith('-options'))return {ok:true,json:async()=>options};if(pending)return new Promise(r=>resolve=()=>r({ok:true,json:async()=>result(body)}));return {ok:true,json:async()=>result(body)};};
const settings={row,getContext:()=>now,busy:()=>busy,setBusy:v=>busy=v};let ui=await openRetainedAnimationEditor(settings);await ui.ready;input(ui,'Translation offset X').value='5';assert.equal(await action(ui,'offset').onclick(),true);assert.equal(busy,false);assert.equal(action(ui,'apply').disabled,true);assert.equal(input(ui,'Translation X').value,'12');assert.equal(action(ui,'review').disabled,false);assert.equal(calls.at(-1).path,'/api/animation-record-offset');ui.dispose();
ui=await openRetainedAnimationEditor(settings);await ui.ready;pending=true;input(ui,'Translation offset X').value='5';let work=action(ui,'offset').onclick();await Promise.resolve();assert.equal(input(ui,'Translation X').disabled,true);assert.equal(input(ui,'Translation offset X').disabled,true);ui.dispose();resolve();await work;assert.equal(busy,false);assert(!tree(document.body).includes(ui.dialog));
pending=false;ui=await openRetainedAnimationEditor(settings);await ui.ready;pending=true;work=action(ui,'offset').onclick();await Promise.resolve();now={...context,sourceKey:'0'.repeat(64)};ui.updateState();resolve();await work;assert.equal(action(ui,'apply').disabled,true);assert.equal(action(ui,'offset').disabled,true);assert.equal(busy,false);ui.dispose();
console.log('Native offset contracts, inherited/draft bases, unchanged rotations/other objects, zero offsets, pending locks, stage-without-Apply, close/late and stale-source ownership passed.');
