import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {decodeBuildWavSnapshots,decodeBuildWavInputs,decodeBuildWavDownload,openBuildWavs} from '../editor/build-wav-inputs.js';
const key='a'.repeat(64),inputKey='b'.repeat(64),entry={id:'c'.repeat(16),archive_sha256:'d'.repeat(64)},base={id:entry.id,archive_sha256:entry.archive_sha256,project_key:key,historical_inputs:true,project_changed:false,package_integrity:'not_checked',gameplay_verified:false};
const snapshot={...base,schema_version:'legaia.build-wav-snapshots.v1',snapshots:[{input_key:inputKey,matches_current_inputs:false,integrity:'not_checked'}],truncated:false,coverage:'immediate_wav_input_directories_identity_order'};decodeBuildWavSnapshots(snapshot,entry,key);
for(const mutation of [v=>v.project_key='f'.repeat(64),v=>v.archive_sha256='f'.repeat(64),v=>v.snapshots.push(v.snapshots[0]),v=>v.snapshots[0].matches_current_inputs=true,v=>v.package_integrity='verified',v=>v.gameplay_verified=true,v=>v.extra=true]){const changed=structuredClone(snapshot);mutation(changed);assert.throws(()=>decodeBuildWavSnapshots(changed,entry,key));}
const wav=new Uint8Array(100),view=new DataView(wav.buffer),text=(at,s)=>{for(let i=0;i<s.length;i++)wav[at+i]=s.charCodeAt(i);};text(0,'RIFF');view.setUint32(4,92,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,32000,true);view.setUint32(28,64000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,56,true);
const r={schema_version:'legaia.audio-sample-source.v1',asset_id:'audio://legaia/prot/0877',source_scene_id:'scene://town01',source_record:{disc_sha256:'e'.repeat(64),iso_file:'PROT.DAT',prot_entry_index:877,entry_sha256:'f'.repeat(64),entry_byte_offset:2048,entry_size_bytes:4096,carrier:'split-vab-header-samples',pieces:[{bank_offset:0,entry_offset:4,size_bytes:3104},{bank_offset:3104,entry_offset:3112,size_bytes:16}]},bank_sha256:'1'.repeat(64),sample_index:0,source_sample_sha256:'2'.repeat(64),wav_sha256:createHash('sha256').update(wav).digest('hex'),byte_length:100,input_wav_rate:32000,decoded_frames:28,candidate_sample_sha256:'3'.repeat(64),review_key:'4'.repeat(64),receipt_key:'5'.repeat(64)};
const options={...base,schema_version:'legaia.build-wav-inputs-inspection.v1',input_key:inputKey,manifest_key:'6'.repeat(64),sources:[r],files:[{file:r.wav_sha256+'.wav',sha256:r.wav_sha256,byte_length:100}],integrity:'input_receipt_manifest_and_wavs_verified'};decodeBuildWavInputs(options,entry,key,inputKey);
for(const mutation of [v=>v.input_key=key,v=>v.manifest_key='bad',v=>v.sources.push(v.sources[0]),v=>v.files[0].byte_length++,v=>v.files[0].file='../file.wav',v=>v.sources[0].source_record.pieces[0].bank_offset=1,v=>v.sources[0].sample_index=true,v=>v.sources[0].input_wav_rate=0,v=>v.sources[0].decoded_frames=29,v=>v.extra=true]){const changed=structuredClone(options);mutation(changed);assert.throws(()=>decodeBuildWavInputs(changed,entry,key,inputKey));}
const recovered={...base,schema_version:'legaia.build-wav-download.v1',input_key:inputKey,manifest_key:options.manifest_key,selected:r,wav_base64:Buffer.from(wav).toString('base64'),integrity:options.integrity};assert.deepEqual(await decodeBuildWavDownload(recovered,entry,key,options,r),wav);
for(const mutation of [v=>v.input_key=key,v=>v.manifest_key='f'.repeat(64),v=>v.selected={...v.selected,sample_index:1},v=>v.wav_base64=v.wav_base64.slice(4),v=>v.gameplay_verified=true,v=>v.extra=true]){const changed=structuredClone(recovered);mutation(changed);await assert.rejects(()=>decodeBuildWavDownload(changed,entry,key,options,r));}
console.log('Frozen Build snapshot identity, historical receipt/inventory, bounded PCM bytes and exact download hashes passed; stale/tampered input and package/gameplay claim mismatches reject.');
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.value='';this.textContent='';this.listeners={};}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}setAttribute(k,v){this[k]=v;}addEventListener(k,fn){this.listeners[k]=fn;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}remove(){this.removed=true;}}
globalThis.document={createElement:tag=>new Element(tag),body:new Element('body')};
let fresh=true,resolve;const respond=v=>({ok:true,text:async()=>JSON.stringify(v)});
const closed=openBuildWavs({entry,key,fresh:()=>fresh,request:()=>new Promise(r=>{resolve=r;})});closed.dispose();resolve(respond(snapshot));await closed.ready;assert.equal(closed.dialog.removed,true);assert.equal(closed.dialog.children.find(n=>n.tag==='select').children.length,0);
const stale=openBuildWavs({entry,key,fresh:()=>fresh,request:()=>new Promise(r=>{resolve=r;})});fresh=false;resolve(respond(snapshot));await stale.ready;assert.equal(stale.dialog.children.find(n=>n.tag==='select').disabled,true);assert.equal(stale.dialog.children.find(n=>n.tag==='select').children.length,0);stale.dispose();fresh=true;
const editor=openBuildWavs({entry,key,fresh:()=>fresh,request:async()=>respond(snapshot)});await editor.ready;assert.equal(editor.dialog.children.find(n=>n.textContent==='Save frozen input WAV').disabled,true);editor.dispose();
console.log('Saved WAV editor lifecycle passed: closed/stale replies cannot publish and downloads require verified inputs.');
