import assert from 'node:assert/strict';
import {exportSceneSelection,importSceneSelection,SCENE_SELECTION_TRANSFER_BYTES} from '../editor/scene-selection-sets.js';
const scene='scene://town01',hash='a'.repeat(64),map='b'.repeat(64),actor=scene+'/actors/man-p1/0011',decor='environment://town01/field-map/decorations/00001',npc='authored-actor://12345678-1234-4123-8123-123456789abc';
const row={id:'scene-selection://11111111-2222-4333-8444-555555555555',name:'Road Group',scene_id:scene,import_sha256:hash,map_sha256:map,entity_ids:[actor,decor,npc].sort(),review_key:'c'.repeat(64)};
const state={scene:{id:scene,entities:[{id:actor}]},actor_selection_source_key:hash,scene_selection_map_sha256:map,scene_selection_eligible_ids:[actor,decor,npc],actor_drafts:{[npc]:{scene_id:scene}},scene_selection_sets:[row]};
const before=structuredClone(state),transfer=exportSceneSelection(row,state),command=importSceneSelection(transfer,state,' Road Group Copy ');
assert.deepEqual(command,{type:'create_scene_selection_set',scene_id:scene,import_sha256:hash,map_sha256:map,name:'Road Group Copy',entity_ids:row.entity_ids});assert.equal(Object.hasOwn(command,'id'),false);assert.equal(Object.hasOwn(transfer.source_selection,'review_key'),false);assert.equal(Object.hasOwn(command,'review_key'),false);
command.entity_ids.pop();assert.deepEqual(transfer.source_selection.entity_ids,row.entity_ids);transfer.source_selection.entity_ids.pop();assert.deepEqual(state,before);assert.equal(SCENE_SELECTION_TRANSFER_BYTES,256*1024);
const source=()=>exportSceneSelection(row,state);
for(const mutate of [v=>v.schema_version='unsupported',v=>v.editor_metadata_only=false,v=>v.extra=true,v=>v.source_selection.extra=true,v=>v.source_selection.id='scene-selection://invalid',v=>v.source_selection.scene_id='scene://other',v=>v.source_selection.import_sha256='d'.repeat(64),v=>v.source_selection.map_sha256='d'.repeat(64),v=>v.source_selection.entity_ids=[actor,actor],v=>v.source_selection.entity_ids=[],v=>v.source_selection.entity_ids=row.entity_ids.toReversed(),v=>v.source_selection.entity_ids=[actor,'environment://town01/field-map/decorations/99999'].sort(),v=>v.source_selection.name='bad\nname',v=>v.source_selection.name='\ud800']){const value=source();mutate(value);assert.throws(()=>importSceneSelection(value,state,'New group'));}
for(const bad of [null,'','Road Group',' road group ','x'.repeat(81),'bad\u007f','\ud800'])assert.throws(()=>importSceneSelection(source(),state,bad));
assert.equal(importSceneSelection(source(),state,'🐾'.repeat(80)).name,'🐾'.repeat(80));assert.throws(()=>importSceneSelection(source(),state,'🐾'.repeat(81)));
assert.throws(()=>exportSceneSelection({...row,name:'Forged'},state));assert.throws(()=>exportSceneSelection({...row,review_key:'d'.repeat(64)},state));
for(const change of [{actor_drafts:{}},{actor_drafts:{[npc]:{scene_id:'scene://other'}}},{scene_selection_eligible_ids:[actor,npc]},{scene_selection_map_sha256:'d'.repeat(64)}])assert.throws(()=>importSceneSelection(source(),{...state,...change},'New group'));
const actorsOnly={...source(),source_selection:{...source().source_selection,entity_ids:[actor],map_sha256:null}};assert.deepEqual(importSceneSelection(actorsOnly,state,'Actor Group').entity_ids,[actor]);assert.throws(()=>importSceneSelection({...actorsOnly,source_selection:{...actorsOnly.source_selection,map_sha256:map}},state,'Actor Group'));
const unsupported='runtime://node';assert.throws(()=>importSceneSelection({...actorsOnly,source_selection:{...actorsOnly.source_selection,entity_ids:[unsupported]}},{...state,scene_selection_eligible_ids:[unsupported]},'Runtime Group'));
const many=Array.from({length:128},(_,i)=>scene+'/actors/man-p1/'+String(i).padStart(4,'0')),manyState={...state,scene:{id:scene,entities:many.map(id=>({id}))},scene_selection_eligible_ids:many};assert.equal(importSceneSelection({...actorsOnly,source_selection:{...actorsOnly.source_selection,entity_ids:many}},manyState,'Bounded Group').entity_ids.length,128);assert.throws(()=>importSceneSelection({...actorsOnly,source_selection:{...actorsOnly.source_selection,entity_ids:[...many,actor]}},manyState,'Too many'));
const huge=source();huge.source_selection.name='x'.repeat(SCENE_SELECTION_TRANSFER_BYTES);assert.throws(()=>importSceneSelection(huge,state,'New group'),/256 KiB/);
assert.deepEqual(state,before);console.log('Scene selection transfer: detached exact metadata/new create command, actor/NPC/decoration source bindings, MAP types, canonical bounded membership, Unicode names, stale/foreign/missing/unsupported refusal and byte budget passed.');
