import assert from 'node:assert/strict';import {decodeNoteLinks,encodedToneCandidates,noteCandidateSeed,openNoteLinks} from '../editor/audio-note-links.js';
const context={assetId:'audio://legaia/prot/0877',sceneId:'scene://town01',sourceKey:'a'.repeat(64),entryHash:'b'.repeat(64),bankHash:'c'.repeat(64),projectPath:'C:/private/project'};
const report={schema_version:'legaia.audio-bank-inspection.v1',asset_id:context.assetId,scene_id:context.sceneId,source_key:context.sourceKey,read_only:true,project_changed:false,runtime_state:'not_observed',reference_commit:'d'.repeat(40),source_record:{disc_sha256:'e'.repeat(64),iso_file:'PROT.DAT',prot_entry_index:877,entry_sha256:context.entryHash,entry_byte_offset:2048,entry_size_bytes:4096,carrier:'split-vab-header-samples',pieces:[{bank_offset:0,entry_offset:4,size_bytes:3104},{bank_offset:3104,entry_offset:3112,size_bytes:16}]},header:{version:7,bank_id:1,declared_size:3120,program_count:1,tone_count:2,sample_count:1},bank_sha256:context.bankHash,bank_size_bytes:3120,sections:{program_offset:32,tone_offset:2080,sample_table_offset:2592,sample_offset:3104},programs:Array.from({length:128},(_,slot)=>({slot,offset:32+slot*16,tone_count:slot===12?1:0,volume:0,priority:0,mode:0,pan:0,attributes:0,source_sha256:'f'.repeat(64)})),tones:Array.from({length:16},(_,index)=>({page:0,index,offset:2080+index*32,priority:0,mode:0,volume:0,pan:0,center:60,shift:0,minimum_key:0,maximum_key:127,pitch_bend_down:0,pitch_bend_up:0,adsr1:0,adsr2:0,program_operand:12,sample_operand:index?0:1,sample_index:index?null:0,source_sha256:'f'.repeat(64)})),samples:[{index:0,table_index:1,size_units:2,offset:3104,size_bytes:16,block_aligned:true,source_sha256:'f'.repeat(64)}],sample_table_spacer:0,sample_table_unused_nonzero:0,used_program_slots:[12],declared_program_count_matches_used_slots:true,consumed_sample_end:3120,remaining_bank_bytes:0,limitations:['Packed pages are not program slot numbers.']};

const note={index:2,kind:'note_on',channel:0,values:[60,100]},program={index:0,kind:'program_change',channel:0,values:[12]},options={asset_id:context.assetId,authoring_key:'1'.repeat(64),current_entry_sha256:'2'.repeat(64),current_sequence_sha256:'3'.repeat(64),source_record:{sequence_offset:3200},current:{events:[program,{index:1,kind:'program_change',channel:1,values:[0]},note]}};
const value={schema_version:'legaia.audio-note-links.v1',asset_id:context.assetId,authoring_key:options.authoring_key,current_entry_sha256:options.current_entry_sha256,current_sequence_sha256:options.current_sequence_sha256,note,program_event:program,bank:report,project_changed:false,runtime_state:'not_observed'};
assert.deepEqual(decodeNoteLinks(value,options,2,context),value);const rows=encodedToneCandidates(value);assert.equal(rows.length,16);assert.equal(rows[0].sample.index,0);assert.equal(rows[1].sample,null);assert.equal(rows[0].tone.page,0);assert.equal(rows[0].tone.program_operand,12);
for(const change of [v=>v.authoring_key='4'.repeat(64),v=>v.current_entry_sha256='4'.repeat(64),v=>v.note.values[0]++,v=>v.program_event.index=1,v=>v.bank.samples[0].offset++,v=>v.bank=null,v=>v.extra=true]){const bad=structuredClone(value);change(bad);assert.throws(()=>decodeNoteLinks(bad,options,2,context));}
const initial=structuredClone(options);initial.current.events[0].kind='control_change';const unknown={...value,program_event:null};decodeNoteLinks(unknown,initial,2,context);assert.deepEqual(encodedToneCandidates(unknown),[]);
const standalone=structuredClone(options);standalone.source_record.sequence_offset=0;assert.equal(decodeNoteLinks({...value,bank:null},standalone,2,context).bank,null);assert.throws(()=>decodeNoteLinks(value,standalone,2,context));
const detached=decodeNoteLinks(value,options,2,context);detached.bank.tones[0].center++;assert.equal(value.bank.tones[0].center,60);rows[0].sample.offset++;assert.equal(value.bank.samples[0].offset,3104);
console.log('Current note/program identities, channel-specific program history, sparse packed pages, unresolved samples, standalone/initial unknowns and immutable candidates passed.');
class Element{constructor(tag){this.tag=tag;this.style={};this.children=[];this.listeners={};this.textContent='';this.value='';this.dataset={};}append(...nodes){this.children.push(...nodes);}prepend(...nodes){this.children.unshift(...nodes);}setAttribute(){}replaceChildren(...nodes){this.children=[...nodes];}addEventListener(name,callback){this.listeners[name]=callback;}showModal(){this.open=true;}close(){this.listeners.close?.();}remove(){this.removed=true;}}
globalThis.document={createElement:t=>new Element(t),body:new Element('body')};let now={...context},resolve;const params={record:{id:context.assetId,label:'Source'},options,index:2,getContext:()=>now,getAuthoringKey:()=>options.authoring_key,busy:()=>false};
let view=openNoteLinks({...params,request:async()=>({ok:true,text:async()=>JSON.stringify(value)})});try{await view.ready;assert(view.dialog.children.some(n=>n.textContent.includes('verified')));now={...now,sourceKey:'4'.repeat(64)};await new Promise(done=>setTimeout(done,350));assert(view.dialog.children.some(n=>n.textContent.includes('inputs changed')));}finally{view.dispose();}
now={...context};view=openNoteLinks({...params,request:()=>new Promise(done=>resolve=done)});view.dispose();resolve({ok:true,text:async()=>JSON.stringify(value)});await view.ready;assert(view.dialog.removed);assert(!view.dialog.children.some(n=>n.textContent.includes('verified')));
console.log('Stale Current inputs withdraw bank links and closed dialogs suppress late publication.');

const allNodes=root=>[root,...root.children.flatMap(allNodes)],retail=structuredClone(report);retail.bank_sha256=context.bankHash;
const currentLinks=structuredClone(value);currentLinks.bank.bank_sha256='8'.repeat(64);currentLinks.bank.tones[0].center=65;
const navigationParams={...params,record:{id:context.assetId,label:'Source',data:{bank_inspection:{bank_sha256:context.bankHash}}},canEdit:()=>true,apply:async()=>false};
let nativeRequests=0;
const navigationRequest=async(path,request)=>{if(path==='/api/audio-note-links')return {ok:true,text:async()=>JSON.stringify(currentLinks)};assert.equal(path,'/api/audio-bank');nativeRequests++;assert.deepEqual(JSON.parse(request.body),{asset_id:context.assetId,expected_source_key:context.sourceKey,expected_entry_sha256:context.entryHash});return {ok:true,text:async()=>JSON.stringify(retail)};};
for(const label of ['Open Retail program slot 12','Open Retail tone page 0 record 0','Open Retail sample 1']){
 view=openNoteLinks({...navigationParams,request:navigationRequest});try{await view.ready;allNodes(view.dialog).find(n=>n.textContent===label).onclick();await new Promise(done=>setTimeout(done,0));const child=document.body.children.at(-1);assert.equal(child.id,'audio-bank-dialog');assert(allNodes(child).some(n=>n.textContent==='Source bank tables verified.'));assert.equal(allNodes(child).find(n=>n.tag==='tbody').children.length,1);assert(allNodes(child).some(n=>n.textContent.includes(context.bankHash)));assert(!allNodes(child).some(n=>n.textContent.includes(currentLinks.bank.bank_sha256)));if(label.includes('tone'))assert(allNodes(child).some(n=>n.textContent==='0–127 / 60 / 0'));view.dispose();assert(child.removed);}finally{view.dispose();}
}
assert.equal(nativeRequests,3);
now={...context};view=openNoteLinks({...navigationParams,request:navigationRequest});try{await view.ready;allNodes(view.dialog).find(n=>n.textContent==='Open Retail sample 1').onclick();await new Promise(done=>setTimeout(done,0));const child=document.body.children.at(-1);now={...context,sourceKey:'9'.repeat(64)};await new Promise(done=>setTimeout(done,350));assert(child.removed);assert(!allNodes(view.dialog).some(n=>n.textContent==='Open Retail sample 1'));}finally{view.dispose();}
now={...context};view=openNoteLinks({...navigationParams,request:path=>path==='/api/audio-note-links'?Promise.resolve({ok:true,text:async()=>JSON.stringify(currentLinks)}):new Promise(done=>resolve=done)});await view.ready;allNodes(view.dialog).find(n=>n.textContent==='Open Retail program slot 12').onclick();const pendingChild=document.body.children.at(-1);view.dispose();assert(pendingChild.removed);resolve({ok:true,text:async()=>JSON.stringify(retail)});await new Promise(done=>setTimeout(done,0));assert(!allNodes(pendingChild).some(n=>n.textContent==='Source bank tables verified.'));
console.log('Current-to-Retail exact record navigation, source hash separation, readonly input, parent/stale disposal and pending-close ownership passed.');

const seed=noteCandidateSeed(currentLinks,currentLinks.bank.tones[0]);assert.equal(seed.key,60);assert.equal(seed.tone_page,0);assert.equal(seed.current_sequence_sha256,options.current_sequence_sha256);assert.throws(()=>noteCandidateSeed(currentLinks,currentLinks.bank.tones[1]));assert.throws(()=>noteCandidateSeed(currentLinks,{...currentLinks.bank.tones[0],center:66}));
let reads=0,releaseCandidate;now={...context};const candidateParams={...navigationParams,request:async(path)=>{assert.equal(path,'/api/audio-note-links');if(++reads===1)return {ok:true,text:async()=>JSON.stringify(currentLinks)};return new Promise(done=>releaseCandidate=done);}};
view=openNoteLinks(candidateParams);await view.ready;let action=allNodes(view.dialog).find(n=>n.textContent==='Audition Current candidate page 0 record 0');assert(!action.disabled);assert(allNodes(view.dialog).find(n=>n.textContent==='Audition Current candidate page 0 record 1').disabled);const opening=action.onclick();assert(action.disabled);assert(allNodes(view.dialog).find(n=>n.textContent==='Open Retail sample 1').disabled);const changed=structuredClone(currentLinks);changed.bank.tones[0].center++;releaseCandidate({ok:true,text:async()=>JSON.stringify(changed)});await opening;assert(allNodes(view.dialog).some(n=>n.textContent.includes('candidate changed')));assert.equal(document.body.children.at(-1),view.dialog);view.dispose();
reads=0;view=openNoteLinks(candidateParams);await view.ready;action=allNodes(view.dialog).find(n=>n.textContent==='Audition Current candidate page 0 record 0');const closing=action.onclick();view.dispose();releaseCandidate({ok:true,text:async()=>JSON.stringify(currentLinks)});await closing;assert.equal(document.body.children.at(-1),view.dialog);assert(view.dialog.removed);
console.log('Candidate note seed identity, unresolved sample refusal, pending control ownership, refreshed candidate drift and close/late-response refusal passed');
