import assert from 'node:assert/strict';
import {decodeTriggerGroup} from '../editor/trigger-group.js';
const key='a'.repeat(64),map='b'.repeat(64),scene='scene://fixture';
const records=[0,1,2].map(i=>{const id=`trigger://fixture/field-map/primary/kind-1/${String(i).padStart(4,'0')}`,encoded={tile_x:8+i,tile_z:9,record_index:1,gate:1},source={disc:{sha256:'e'.repeat(64),serial:'SCUS-94254'},iso_file:'PROT.DAT',prot_entry_index:1,prot_entry_name:'fixture',prot_start_lba:203,byte_offset:66692+i*4,byte_length:4,byte_coordinate_space:'prot_entry',sha256:'c'.repeat(64),containing_span_sha256:'d'.repeat(64),table_source:'primary',table_kind:1,record_index:i,containing_span_byte_offset:65536,containing_span_byte_length:8192};return {id,type:'trigger',sceneId:scene,data:{semantic_id:id,asset_kind:'trigger',table_source:'primary',table_kind:1,record_index:i,encoded,source_record:source,trigger_type:'partition_2_trigger'}};});
const retained={trigger_id:records[2].id,tile_x:13,tile_z:9},state={project:{mode:'edit'},scene:{id:scene},project_copy_source_key:key,scene_trigger_state_key:'0'.repeat(64),scene_selection_map_sha256:map,authored_assets:[{id:scene,authored:{TriggerCells:{source_sha256:map,edits:[retained]}}}]},request={trigger_ids:records.slice(0,2).map(r=>r.id),delta:{x:1,z:2},action:'translate'};
const rows=records.slice(0,2).map(r=>({trigger_id:r.id,source:{trigger_id:r.id,table_kind:1,record_index:r.data.record_index,byte_offset:r.data.source_record.byte_offset,byte_length:4,sha256:r.data.source_record.sha256,encoded:r.data.encoded,tile_bounds:{x_min:r.data.encoded.tile_x,x_max:r.data.encoded.tile_x+1,z_min:9,z_max:10}},layers:{imported:{tile_x:r.data.encoded.tile_x,tile_z:9},current:{tile_x:r.data.encoded.tile_x,tile_z:9},proposed:{tile_x:r.data.encoded.tile_x+1,tile_z:11}}}));
const edits=rows.map(r=>({trigger_id:r.trigger_id,...r.layers.proposed})).concat(retained),audit=[];
for(const edit of edits){const record=records.find(r=>r.id===edit.trigger_id);for(const [offset,field] of ['tile_x','tile_z'].entries())if(edit[field]!==record.data.encoded[field])audit.push({trigger_id:edit.trigger_id,table_kind:1,record_index:record.data.record_index,field:'trigger.'+field,byte_offset:record.data.source_record.byte_offset+offset,before_value:record.data.encoded[field],after_value:edit[field],scope:'source-MAP-trigger-cell-only'});}
const report={schema_version:'legaia.trigger-group-review.v1',read_only:true,project_source_key:key,scene_id:scene,trigger_ids:request.trigger_ids,delta:request.delta,action:request.action,rows,value:{source_sha256:map,edits},audit,proposed_map_sha256:'f'.repeat(64),project_change:true,changed_cell_count:2,scope:'source-MAP-trigger-cell-only',height_status:'unknown',activation:'not_evaluated',gameplay_verified:false,review_key:'e'.repeat(64)},before=structuredClone(report),decoded=decodeTriggerGroup(report,records,state,request);assert.deepEqual(decoded,report);decoded.rows[0].layers.proposed.tile_x=0;assert.deepEqual(report,before);
for(const mutate of [v=>v.project_source_key='0'.repeat(64),v=>v.trigger_ids.reverse(),v=>v.delta.x=2,v=>v.rows[0].source.encoded.gate=0,v=>v.rows[0].source.sha256='0'.repeat(64),v=>v.rows[0].source.byte_offset++,v=>v.rows[0].layers.current.tile_x++,v=>v.rows[0].layers.proposed.tile_x++,v=>v.value.edits.pop(),v=>v.value.edits[2].tile_x++,v=>v.audit.pop(),v=>v.audit[0].field='trigger.gate',v=>v.audit.push(v.audit[0]),v=>v.audit[0].byte_offset+=2,v=>v.value.source_sha256='0'.repeat(64),v=>v.changed_cell_count=1,v=>v.project_change=false,v=>v.activation='evaluated',v=>v.height_status='known',v=>v.gameplay_verified=true]){const bad=structuredClone(before);mutate(bad);assert.throws(()=>decodeTriggerGroup(bad,records,state,request));}
const reset=structuredClone(report);reset.action='retail';reset.delta={x:0,z:0};reset.rows.forEach(row=>row.layers.proposed={...row.layers.imported});reset.value.edits=[retained];reset.audit=report.audit.filter(row=>row.trigger_id===retained.trigger_id);reset.project_change=false;reset.changed_cell_count=0;assert.deepEqual(decodeTriggerGroup(reset,records,state,{...request,delta:reset.delta,action:'retail'}),reset);
console.log('Trigger group strict source/layer/offset qualification, retained unselected cells, exact byte audits and detached reports passed.');

// A changed draft or closed panel cannot publish a late asynchronous review.
const {openTriggerGroup}=await import('../editor/trigger-group.js');
class Element{constructor(tag){this.tag=tag;this.style={};this.children=[];this.dataset={};this.handlers={};}append(...children){this.children.push(...children);}setAttribute(){}replaceChildren(...children){this.children=children;}addEventListener(name,callback){this.handlers[name]=callback;}showModal(){this.open=true;}close(){this.open=false;this.handlers.close?.();}remove(){this.removed=true;}}
globalThis.document={createElement:tag=>new Element(tag),createTextNode:text=>({text}),body:new Element('body')};
let blocked=false,finish,signal,applies=0;globalThis.fetch=(_url,args)=>{signal=args.signal;return new Promise(resolve=>{finish=resolve;});};
const options={record:records[0],records,getState:()=>state,current:()=>true,busy:()=>blocked,setBusy:v=>{blocked=v;},api:async()=>{applies++;return true;}};
const dialog=openTriggerGroup(options),controls=dialog.children[3],actions=dialog.children[6],move=actions.children[0],applyButton=actions.children[2];
controls.children[0].children[0].value='1';const pending=move.onclick();assert.equal(blocked,true);controls.children[0].children[0].value='2';controls.children[0].children[0].oninput();finish({ok:true,json:async()=>report});await pending;assert.equal(blocked,false);assert.equal(applyButton.disabled,true);await applyButton.onclick();assert.equal(applies,0);dialog.dispose();
const closed=openTriggerGroup(options),loading=closed.children[6].children[0].onclick();closed.dispose();assert.equal(signal.aborted,true);assert.equal(blocked,false);finish({ok:true,json:async()=>report});await loading;assert.equal(closed.removed,true);assert.equal(applies,0);
console.log('Group review draft invalidation, busy controls and close/abort discard late replies without Apply.');

const {triggerGroupGeometry,triggerGroupFrame}=await import('../editor/trigger-group.js');
const sourceSnapshot=structuredClone(report),geometry=triggerGroupGeometry(report,'proposed');assert.equal(geometry.length,2);assert.deepEqual(geometry[0],{id:records[0].id,kind:'trigger',world_bounds:{x_min:9*128,x_max:10*128,z_min:11*128,z_max:12*128},world_center:{x:9.5*128,y:0,z:11.5*128}});
assert.deepEqual(triggerGroupFrame(report,'proposed').target,{x:10*128,y:0,z:11.5*128});assert.equal(triggerGroupGeometry(report,'current')[0].world_bounds.x_min,8*128);assert.deepEqual(report,sourceSnapshot);geometry[0].world_center.y=999;assert.equal(triggerGroupGeometry(report)[0].world_center.y,0);
for(const mutate of [v=>v.rows[0].layers.proposed.tile_x=256,v=>v.rows[0].layers.proposed.tile_x=1.5,v=>v.rows[0].trigger_id=v.rows[1].trigger_id,v=>v.rows.pop(),v=>v.height_status='known',v=>v.activation='active',v=>v.scene_id='scene://other',v=>v.gameplay_verified=true]){const bad=structuredClone(report);mutate(bad);assert.throws(()=>triggerGroupGeometry(bad));}assert.throws(()=>triggerGroupGeometry(report,'live'));
const edge=structuredClone(report);edge.rows.forEach(row=>row.layers.proposed={tile_x:255,tile_z:0});assert.deepEqual(triggerGroupGeometry(edge)[0].world_bounds,{x_min:32640,x_max:32768,z_min:0,z_max:128});
console.log('Group geometry preserves raw half-open 128-unit cells, bounded group framing and unknown height/activation semantics.');

// Viewport inspection retains the accepted review; Return clears only display geometry.
let current=true;const inspections=[],frames=[];const viewed=openTriggerGroup({...options,current:()=>current,onInspection:(report,layer)=>inspections.push(report?layer:null),onFrame:(_report,layer)=>frames.push(layer)});
viewed.children[2].children[1].children[0].checked=true;viewed.children[3].children[0].children[0].value='1';viewed.children[3].children[1].children[0].value='2';const loaded=viewed.children[6].children[0].onclick();finish({ok:true,json:async()=>report});await loaded;const viewedActions=viewed.children[6].children,strip=document.body.children.at(-1);
viewedActions[5].onclick();assert.equal(viewed.open,false);assert.equal(viewed.removed,undefined);assert.equal(strip.hidden,false);assert.equal(inspections.at(-1),'proposed');assert.equal(frames.at(-1),'proposed');assert.equal(applies,0);
strip.children[1].value='current';strip.children[1].onchange();assert.equal(inspections.at(-1),'current');strip.children[2].onclick();assert.equal(inspections.at(-1),null);assert.equal(viewed.open,true);assert.equal(viewedActions[2].disabled,false);assert.equal(strip.hidden,true);
viewedActions[5].onclick();blocked=true;strip.children[2].onclick();assert.equal(viewed.open,false);blocked=false;current=false;viewed.refresh();assert.equal(viewed.removed,true);assert.equal(strip.removed,true);assert.equal(inspections.at(-1),null);assert.equal(applies,0);
console.log('Viewport layer switching and Return retain the review without Apply; busy Return and stale source cleanup are guarded.');
