import assert from 'node:assert/strict';
import {captureInstructionSummary,appendCaptureSummary} from '../editor/script-capture.js';
const row={pc:34,length:14,opcode:52,mnemonic:'EFFECT_SPAWN_PACKET',raw_hex:'b438102020006a03880180000000',target_context:56,successors:[],operands:{sub_op:1,raw_selector:16,packet_bytes:[32,32,0,106,3,136,1,128,0,0,0],following_byte:64,runtime_actor_match:'not_observed',runtime_effect:'not_evaluated',unresolved_control_flow:'Conditional ownership remains unresolved',capture_payload:{pc:50,length:15,encoded_hex:'021e00140500086060000000007800'},conditional_continuations:{existing_actor:48,new_actor_capture:65}}};
const before=JSON.stringify(row);assert.deepEqual(captureInstructionSummary(row),{payload_pc:50,payload_length:15,existing_actor_pc:48,new_actor_pc:65});
const detached=captureInstructionSummary(row);detached.payload_pc=0;assert.equal(JSON.stringify(row),before);
for(const edit of [r=>r.mnemonic='OTHER',r=>r.opcode=0,r=>r.pc=-1,r=>r.length=13,r=>r.raw_hex+='00',r=>r.raw_hex='z'.repeat(28),r=>r.target_context=7,r=>r.successors=[{pc:65}],r=>r.operands.raw_selector=17,r=>r.operands.sub_op=2,r=>r.operands.packet_bytes[0]=31,r=>r.operands.following_byte=0,r=>r.operands.runtime_actor_match='resolved',r=>r.operands.runtime_effect='executed',r=>r.operands.unresolved_control_flow='',r=>r.operands.capture_payload.pc=51,r=>r.operands.capture_payload.length=256,r=>r.operands.capture_payload.encoded_hex+='00',r=>r.operands.conditional_continuations.existing_actor=49,r=>r.operands.conditional_continuations.new_actor_capture=64]){const changed=structuredClone(row);edit(changed);assert.equal(captureInstructionSummary(changed),null);}
for(const length of [0,255]){const changed=structuredClone(row);changed.operands.capture_payload.length=length;changed.operands.capture_payload.encoded_hex='00'.repeat(length);changed.operands.conditional_continuations.new_actor_capture=50+length;assert.equal(captureInstructionSummary(changed).payload_length,length);}
const ordinary=structuredClone(row);ordinary.raw_hex=ordinary.raw_hex.slice(0,2).replace('b4','34')+ordinary.raw_hex.slice(4);ordinary.length=13;ordinary.target_context=null;ordinary.operands.capture_payload.pc=49;ordinary.operands.conditional_continuations={existing_actor:47,new_actor_capture:64};assert.equal(captureInstructionSummary(ordinary).payload_pc,49);
for(const bad of [null,{},row.operands,'text'])assert.equal(captureInstructionSummary(bad),null);
class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.textContent='';}append(...children){this.children.push(...children);}}
globalThis.document={createElement:tag=>new Element(tag)};
const tree=node=>[node,...node.children.flatMap(tree)],cell=new Element('td');assert.equal(appendCaptureSummary(cell,row),true);
const elements=tree(cell),text=elements.map(e=>e.textContent).join('\n');assert.match(text,/Conditional capture · 15 bytes/);assert.match(text,/Payload starts at 0x32/);assert.match(text,/Existing actor match: continuation 0x30/);assert.match(text,/New actor capture: continuation 0x41/);assert.match(text,/not confirmed parent instruction boundaries/);assert.ok(elements.every(e=>!['button','a'].includes(e.tagName)&&!e.onclick));
const empty=new Element('td');assert.equal(appendCaptureSummary(empty,{}),false);assert.equal(empty.children.length,0);assert.equal(JSON.stringify(row),before);
console.log('Capture summary qualification, headers, zero/max payload, source detachment and read-only rendering pass');

const existing={pc:736,length:3,opcode:52,mnemonic:'EFFECT_EXISTING_ACTOR_CAPTURE_REQUEST',raw_hex:'b4f820',target_context:248,successors:[],operands:{sub_op:2,raw_selector:32,following_byte:64,runtime_actor_match:'not_observed',runtime_effect:'not_evaluated',unresolved_control_flow:'Conditional ownership remains unresolved',capture_payload:{pc:741,length:1,encoded_hex:'00'},conditional_continuations:{missing_actor:739,matched_actor_capture:742}}};
assert.deepEqual(captureInstructionSummary(existing),{payload_pc:741,payload_length:1,missing_actor_pc:739,matched_actor_pc:742});
const existingCell=new Element('td');assert.equal(appendCaptureSummary(existingCell,existing),true);
const existingElements=tree(existingCell),existingText=existingElements.map(e=>e.textContent).join('\n');
assert.match(existingText,/Missing actor: continuation 0x2E3/);assert.match(existingText,/Matched actor capture: continuation 0x2E6/);
assert.ok(existingElements.every(e=>!['button','a'].includes(e.tagName)&&!e.onclick));
for(const edit of [r=>r.length=2,r=>r.operands.sub_op=1,r=>r.operands.raw_selector=33,r=>r.operands.capture_payload.pc=740,r=>r.operands.conditional_continuations.missing_actor=740,r=>r.operands.conditional_continuations.matched_actor_capture=741,r=>r.target_context=7,r=>r.successors=[{pc:742}]]){const changed=structuredClone(existing);edit(changed);assert.equal(captureInstructionSummary(changed),null);}
const ordinaryExisting=structuredClone(existing);ordinaryExisting.length=2;ordinaryExisting.raw_hex='3420';ordinaryExisting.target_context=null;ordinaryExisting.operands.capture_payload.pc=740;ordinaryExisting.operands.conditional_continuations={missing_actor:738,matched_actor_capture:741};assert.equal(captureInstructionSummary(ordinaryExisting).payload_pc,740);
