import assert from 'node:assert/strict';import {mirrorObjectWords,qualifyObjectMirror} from '../editor/model-object-mirror.js';
const object={vertices:[[0,0,0],[1,0,0],[0,1,0],[1,1,0]],normals:[[100,0,0],[0,100,0]]},values={axis:'x',pivot:'center'},original=structuredClone(object),proposed=mirrorObjectWords(object,values);
assert.deepEqual(proposed,{vertices:[[1,0,0],[0,0,0],[1,1,0],[0,1,0]],normals:[[-100,0,0],[0,100,0]]});assert.deepEqual(mirrorObjectWords(proposed,values),object);assert.deepEqual(object,original);assert.deepEqual(mirrorObjectWords({...object,normals:[]},values).normals,[]);
for(const bad of [{axis:'bad'},{pivot:'bad'}])assert.throws(()=>mirrorObjectWords(object,{...values,...bad}));for(const obj of [{...object,normals:[[-32768,0,0]]},{...object,vertices:[[0,,0]]},{...object,vertices:[]}])assert.throws(()=>mirrorObjectWords(obj,values));
const before={objects:[{triangle_start:0,triangle_count:2}],triangles:[[0,1,2],[1,3,2],[4,5,6]],triangle_colors:[[[1,0,0],[0,1,0],[0,0,1]],[[0,1,0],[1,1,1],[0,0,1]],[[1,1,1],[1,1,1],[1,1,1]]],triangle_uvs:[[[0,0],[1,0],[0,1]],[[1,0],[1,1],[0,1]],null],triangle_normals:[[[100,0,0],[0,100,0],[100,0,0]],[[0,100,0],[0,100,0],[100,0,0]],null],triangle_materials:[0,0,1]},after=structuredClone(before);
for(const [i,order] of [[0,[0,2,1]],[1,[2,1,0]]])for(const key of ['triangles','triangle_colors','triangle_uvs','triangle_normals'])after[key][i]=order.map(c=>key==='triangle_normals'?before[key][i][c].map((v,a)=>a===0?-v:v):before[key][i][c]);
const report={values,object_index:0,object_mirror_words:{current:object,proposed},current_preview:structuredClone(before),preview:structuredClone(after),changes_from_current:[{kind:'vertex',object_index:0},{kind:'normal',object_index:0},{kind:'primitive',object_index:0,field:'uv'}]};assert.deepEqual(qualifyObjectMirror(report,object,values),proposed);
for(const change of [r=>r.values.axis='y',r=>r.object_mirror_words.proposed.vertices[0][0]++,r=>r.preview.triangles[0]=[0,1,2],r=>r.preview.triangle_uvs[1][0][0]++,r=>r.preview.triangle_colors[0][0][0]++,r=>r.preview.triangle_normals[0][0][0]++,r=>r.preview.triangles[2]=[6,5,4],r=>r.preview.triangle_materials[0]=1,r=>r.current_preview.objects[0].triangle_count=99,r=>r.changes_from_current[0].object_index=1,r=>r.changes_from_current[2].field='clut']){const bad=structuredClone(report);change(bad);assert.throws(()=>qualifyObjectMirror(bad,object,values));}
console.log('Native mirror exact words, quad diagonal and oriented corner coupling, other-object/material guards and immutable source passed.');
