import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const code=await readFile(new URL('../editor/build-review.js',import.meta.url),'utf8'),{decodeBuildReview}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64')),hash='a'.repeat(64);
const value={schema_version:'legaia.build-review.v1',source_key:hash,read_only:true,status:'ready_for_build',normal_build_ready:true,blockers:[],excluded_npc_draft_count:0,assessment_scope:'existing_imported_content_and_supported_overrides_excluding_npc_drafts',limitations:['Not packed or launched'],assessment:{report:{schema_version:'legaia.build-report.v1',changes:[],change_count:0,scene_count:0,overlay_bytes:0,validation:{retail_provenance:'fresh_import_match',live_runtime:'not_run',unchanged_opaque_bytes:true}},output_written:false,archive_packing:'not_run',runtime_status:'not_run',audit_sha256:hash,manifest_sha256:hash,source_disc_sha256:hash,overlay_count:0,build_kind:'retail',change_kinds:[]}};
const result=decodeBuildReview(value,hash);result.limitations.push('Detached');assert.equal(value.limitations.length,1);
for(const mutate of [v=>v.source_key='b'.repeat(64),v=>v.read_only=false,v=>v.blockers=[{kind:'npc_draft',owner_id:'draft://one',message:'Blocked'}],v=>v.assessment.output_written=true,v=>v.assessment.archive_packing='passed',v=>v.assessment.report.change_count=1,v=>v.assessment.report.validation.live_runtime='passed',v=>v.assessment=null,v=>v.excluded_npc_draft_count=1]){const bad=structuredClone(value);mutate(bad);assert.throws(()=>decodeBuildReview(bad,hash));}
const blocked=structuredClone(value);Object.assign(blocked,{status:'blocked',normal_build_ready:false,blockers:[{kind:'npc_draft',owner_id:'draft://one',message:'Retained'}],excluded_npc_draft_count:1});assert.equal(decodeBuildReview(blocked,hash).assessment.report.change_count,0);console.log('Build review contract and source/no-output guards passed');

const relocated=structuredClone(value);relocated.assessment.report.resource_relocation={package_bytes:4096,archive_growth_bytes:2048,texture_pack_count:1};decodeBuildReview(relocated,hash);for(const bad of [null,{}, {package_bytes:0,archive_growth_bytes:2048,texture_pack_count:1},{package_bytes:4096,archive_growth_bytes:-1,texture_pack_count:1},{package_bytes:4096,archive_growth_bytes:2048,texture_pack_count:true}]){const forged=structuredClone(relocated);forged.assessment.report.resource_relocation=bad;assert.throws(()=>decodeBuildReview(forged,hash));}
