import assert from 'node:assert/strict';
import {decodeWorldPlacements,placementSceneView} from '../editor/worldmap-placement-editor.js';
const key='a'.repeat(64),sha='b'.repeat(64),id='scene://map01/worldmap/placements/0064';
const values={offset:{x:4,y:8,z:12},yaw_units:64};
const report={schema_version:'legaia.worldmap-placement-authoring.v1',scene:'map01',source_key:key,gameplay_verified:false,project_changed:false,current_map_sha256:sha,source_record:{scene:'map01',source_disc_sha256:sha,source_map_sha256:sha,source_floor_lut_sha256:sha},limitations:[],records:[{record_id:'0005',object_record_index:5,source_record_sha256:sha,retail_values:values,current_values:values,authored_values:null,writable:true,source_cell_count:1,placements:[{entity_id:id,object_record_index:5,source_cell:100,source_record_sha256:sha}]}]};
assert.deepEqual(decodeWorldPlacements(report,'map01',key),report);
for(const mutate of [r=>r.gameplay_verified=true,r=>r.source_key='f'.repeat(64),r=>r.records[0].current_values.offset.x=32768,r=>r.records[0].source_cell_count=0,r=>r.records.push(structuredClone(r.records[0])),r=>r.records[0].placements[0].entity_id='scene://map02/worldmap/placements/0064']){const r=structuredClone(report);mutate(r);assert.throws(()=>decodeWorldPlacements(r,'map01',key));}
const proposed={offset:{x:132,y:24,z:76},yaw_units:1024};report.review={review_key:sha,record_id:'0005',candidate_map_sha256:sha,shared_record:false,no_op:false,values:proposed,proposed_values:proposed,changed_bytes:[{byte_offset:160,before_byte:4,after_byte:132}],affected_source_entities:[id]};assert(decodeWorldPlacements(report,'map01',key));
const base={assets:[],entities:[{entity_id:id,object_record_index:5,source_record_sha256:sha,source_position:{x:1000,y:200,z:3000},placement_scope:'source_spawn_seed'}]};const current=placementSceneView(base,report),preview=placementSceneView(base,report,true);assert.deepEqual(current.entities[0].authored_source_position,{x:1000,y:200,z:3000});assert.deepEqual(preview.entities[0].authored_source_position,{x:1128,y:216,z:2936});assert.equal(preview.entities[0].model_to_scene[7],-216);assert(Math.abs(preview.entities[0].model_to_scene[2]-1)<1e-12);assert(Math.abs(preview.entities[0].model_to_scene[8]+1)<1e-12);
for(const mutate of [r=>r.review.changed_bytes[0].byte_offset=167,r=>r.review.affected_source_entities=[],r=>r.review.candidate_map_sha256='bad']){const r=structuredClone(report);mutate(r);assert.throws(()=>decodeWorldPlacements(r,'map01',key));}
console.log('World placement source bounds, shared review ownership and independent matrix arithmetic passed');
