import assert from 'node:assert/strict';
import {decodeDraftGroupReview,decodeDraftGroupScene} from '../editor/draft-group.js';
const state={scene:{id:'scene'},scene_preview_source_key:'b'.repeat(64),actor_drafts:{a:{scene_id:'scene',donor_entity_id:'donor',name:'A',position:{x:128,z:512}},b:{scene_id:'scene',donor_entity_id:'donor',name:'B',position:{x:192,z:512}}}},request={entity_ids:['a','b'],delta:{x:64,z:-128}},report={schema_version:'legaia.draft-group-review.v1',scene_id:'scene',scene_preview_source_key:state.scene_preview_source_key,project_source_key:'c'.repeat(64),review_key:'d'.repeat(64),request,targets:['a','b'].map(id=>({entity_id:id,draft:state.actor_drafts[id],proposed:{x:state.actor_drafts[id].position.x+64,z:384}})),changed_count:2,gameplay_verified:false,limitations:['Scope']};
const accepted=decodeDraftGroupReview(report,request,state);accepted.targets[0].draft.name='Detached';assert.equal(state.actor_drafts.a.name,'A');
const reordered={...report,request:{delta:request.delta,entity_ids:request.entity_ids}};assert.deepEqual(decodeDraftGroupReview(reordered,request,state).request,reordered.request);
for(const edit of [v=>v.targets.reverse(),v=>v.targets[0].proposed.x+=64,v=>v.targets[0].draft.donor_entity_id='other',v=>v.scene_preview_source_key='stale',v=>v.changed_count=1,v=>v.gameplay_verified=true,v=>v.request.extra=0]){const bad=structuredClone(report);edit(bad);assert.throws(()=>decodeDraftGroupReview(bad,request,state));}
const entity=(id,x,z)=>({entity_id:id,kind:'actor_draft',donor_entity_id:'donor',name:id,position:{x,y:null,z},preview_position:{x,y:null,z},display_position:{x,y:0,z},preview_height_status:'unresolved_no_source_surface',model_to_scene:[1,0,0,x,0,1,0,0,0,0,1,z,0,0,0,1],authored_position:{x,z}});
const base={source_key:state.scene_preview_source_key,scene_id:'scene',assets:[],position_to_display:[],entities:[entity('a',128,512),entity('b',192,512),{entity_id:'unchanged',kind:'actor',position:{x:512,z:512}}]},scene={...structuredClone(base),schema:'legaia.scene-preview.v1',representation:'authored',entities:[entity('a',192,384),entity('b',256,384),structuredClone(base.entities[2])]},response={schema_version:'legaia.draft-group-scene.v1',project_source_key:report.project_source_key,scene_preview_source_key:base.source_key,scene_id:'scene',review_key:report.review_key,scene};
const decoded=decodeDraftGroupScene(response,report,base);decoded.entities[0].position.x=0;assert.equal(response.scene.entities[0].position.x,192);
for(const edit of [v=>v.review_key='stale',v=>v.scene.entities[2].position.x=0,v=>v.scene.entities[0].donor_entity_id='other',v=>v.scene.entities[0].model_to_scene[3]=0,v=>v.scene.entities[0].display_position.z=0,v=>v.scene.entities.pop(),v=>v.scene.assets.push({})]){const bad=structuredClone(response);edit(bad);assert.throws(()=>decodeDraftGroupScene(bad,report,base));}
console.log('NPC draft group source, exact targets, detached report/scene, unchanged content and model/display transforms passed.');
