import assert from 'node:assert/strict';
import {interpolateAnimationFrameRange,holdAnimationFrameRange,decodeImportedFrame} from '../editor/animation-range.js';
const pose=(object_index,x,r)=>({object_index,translation:{x,y:0,z:0},rotation_psx:{x:r,y:0,z:0}}),first=[pose(0,-12,4080),pose(1,20,0)],last=[pose(0,20,48),pose(1,-12,2048)],outside={frame_index:5,object_index:1,translation:{x:7}},args={first,last,start:0,end:4,frameCount:6,objectCount:2,edits:[outside,{frame_index:2,object_index:1,translation:{x:99}}],curve:'smoothstep'},held=structuredClone(args),result=interpolateAnimationFrameRange(args);
assert.deepEqual(result.proposed.filter(r=>r.object_index===0).map(r=>r.translation.x),[-12,-7,4,15,20]);assert.deepEqual(result.proposed.filter(r=>r.object_index===1).map(r=>r.translation.x),[20,15,4,-7,-12]);assert.deepEqual(result.proposed.filter(r=>r.object_index===0).map(r=>r.rotation_psx.x),[4080,0,16,32,48]);assert.equal(result.proposed[5].rotation_psx.x,1024);assert.deepEqual(result.edits.at(-1),outside);assert.equal(result.edits.length,11);assert.deepEqual(args,held);result.edits.at(-1).translation.x=10;assert.deepEqual(args,held);
for(const update of [{first:[first[1],first[0]]},{last:last.slice(1)},{objectCount:65},{start:4},{end:6},{curve:'cubic'},{edits:[outside,outside]},{edits:[{...outside,object_index:2}]}])assert.throws(()=>interpolateAnimationFrameRange({...args,...update}));
const many=Array.from({length:64},(_,o)=>pose(o,0,0));assert.equal(interpolateAnimationFrameRange({first:many,last:many,start:0,end:63,frameCount:65,objectCount:64,edits:[]}).edits.length,4096);assert.throws(()=>interpolateAnimationFrameRange({first:many,last:many,start:0,end:64,frameCount:65,objectCount:64,edits:[]}));assert.throws(()=>interpolateAnimationFrameRange({first:many,last:many,start:0,end:63,frameCount:65,objectCount:64,edits:[{frame_index:64,object_index:0,translation:{x:0}}]}));
const request={entityId:'actor',frame:0,binding:{bone_count:2,frame_count:6,semantic_id:'clip',source_record:{record_sha256:'a'.repeat(64)}},sourceKey:'b'.repeat(64)},report={schema_version:'legaia.imported-animation-frame.v1',frame_index:0,object_count:2,animation_id:'clip',source_record_sha256:'a'.repeat(64),effective_record_sha256:'c'.repeat(64),retail:first,effective:last,entity_id:'actor',project_source_key:'b'.repeat(64),project_changed:false,gameplay_verified:false};
const decoded=decodeImportedFrame(report,request);decoded.retail[0].translation.x=100;assert.equal(report.retail[0].translation.x,-12);
for(const update of [{entity_id:'other'},{project_source_key:'d'.repeat(64)},{effective_record_sha256:null},{frame_index:1},{retail:[first[1],first[0]]},{effective:last.slice(1)},{project_changed:true},{gameplay_verified:true},{extra:1}])assert.throws(()=>decodeImportedFrame({...report,...update},request));
console.log('Complete frame literal samples, ownership, snapshot refusals, exact budget and detached drafts passed.');

const holdArgs={first,start:2,end:2,frameCount:6,objectCount:2,edits:[outside,{frame_index:2,object_index:1,translation:{x:99}}]},beforeHold=structuredClone(holdArgs),single=holdAnimationFrameRange(holdArgs);
assert.equal(single.proposed.length,2);assert.deepEqual(single.proposed.map(({frame_index,object_index,...v})=>({object_index,...v})),first);assert.deepEqual(single.edits.at(-1),outside);assert.deepEqual(holdArgs,beforeHold);
const repeated=holdAnimationFrameRange({...holdArgs,start:1,end:4});assert.equal(repeated.proposed.length,8);for(const row of repeated.proposed){assert.deepEqual(row.translation,first[row.object_index].translation);assert.deepEqual(row.rotation_psx,first[row.object_index].rotation_psx);}repeated.edits[0].translation.x=100;assert.deepEqual(holdArgs,beforeHold);
for(const update of [{start:-1},{start:3,end:2},{end:6},{frameCount:513},{objectCount:65},{first:[first[1],first[0]]},{first:first.slice(1)},{first:[{...first[0],translation:{x:2048,y:0,z:0}},first[1]]},{edits:[outside,outside]}])assert.throws(()=>holdAnimationFrameRange({...holdArgs,...update}));
assert.equal(holdAnimationFrameRange({first:many,start:0,end:63,frameCount:65,objectCount:64,edits:[]}).edits.length,4096);assert.throws(()=>holdAnimationFrameRange({first:many,start:0,end:64,frameCount:65,objectCount:64,edits:[]}));assert.throws(()=>holdAnimationFrameRange({first:many,start:0,end:63,frameCount:65,objectCount:64,edits:[{frame_index:64,object_index:0,translation:{x:0}}]}));
console.log('Complete pose single-frame paste, exact holds, native grids, ownership, budget and detached outside contributions passed.');
