import assert from 'node:assert/strict';
import {nativeFaceSelectionTriangles,faceSelectionView} from '../editor/model-face-selection-view.js';
const row=(i,quad=false)=>({primitive_index:i,group_index:0,corner_count:quad?4:3,uvs:quad?[[0,0],[1,0],[0,1],[1,1]]:[[0,0],[1,0],[0,1]]});
const source={asset_id:'asset://fixture/model/0',project_source_key:'a'.repeat(64),effective_sha256:'b'.repeat(64),objects:[{vertex_count:4,primitives:[row(0,true),row(1)]},{vertex_count:3,primitives:[row(0)]}]};
const selection={asset_id:source.asset_id,project_source_key:source.project_source_key,effective_sha256:source.effective_sha256,can_stage:true,material_index:0,faces:[{object_index:0,group_index:0,primitive_index:0,textured:true,triangle_count:2,material_indices:[0]},{object_index:1,group_index:0,primitive_index:0,textured:true,triangle_count:1,material_indices:[0]}]};
const preview={objects:[{object_index:0,vertex_count:4,triangle_start:0,triangle_count:3},{object_index:1,vertex_count:3,triangle_start:3,triangle_count:1}],vertices:[[0,0,0],[10,0,0],[0,10,0],[10,10,0],[100,0,0],[110,0,0],[100,10,0]],triangles:[[0,1,2],[1,3,2],[0,1,2],[4,5,6]],materials:[{textured:true}],triangle_uvs:Array.from({length:4},()=>[[0,0],[1,0],[0,1]]),triangle_colors:Array.from({length:4},()=>[[80,80,80],[80,80,80],[80,80,80]]),triangle_materials:[0,0,0,0],textures:[{material_index:0,status:'unsupported'}]},before=structuredClone({source,selection,preview});
assert.deepEqual(nativeFaceSelectionTriangles(preview,source,selection),[0,1,3]);const result=faceSelectionView(preview,source,selection);assert.deepEqual(result.geometry.triangle_materials,[1,1,0,1]);assert.equal(result.geometry.triangle_uvs[0],null);assert.deepEqual(result.geometry.triangle_uvs[2],preview.triangle_uvs[2]);assert.deepEqual(result.geometry.triangle_colors[2],preview.triangle_colors[2]);assert.deepEqual(result.geometry.vertices,preview.vertices);assert.deepEqual(result.geometry.triangles,preview.triangles);assert.deepEqual(result.bounds,{min:[0,0,0],max:[110,10,0]});assert.deepEqual({source,selection,preview},before);
for(const change of [s=>s.effective_sha256='c'.repeat(64),s=>s.project_source_key='c'.repeat(64),s=>s.faces[0].triangle_count=1,s=>s.faces.push(s.faces[0]),s=>s.faces[1].group_index=1,s=>s.faces[0].material_indices=[0,1]]){const bad=structuredClone(selection);change(bad);assert.throws(()=>faceSelectionView(preview,source,bad));}
const bad=structuredClone(preview);bad.objects[1].triangle_start=2;assert.throws(()=>faceSelectionView(bad,source,selection));assert.deepEqual({source,selection,preview},before);console.log('Native tri/quad ownership, cross-object selection, isolated display colors, exact unchanged geometry and stale/layout rejection passed.');
