import assert from 'node:assert/strict';import {decodeAudioBank,openAudioBank} from '../editor/audio-bank.js';
const context={assetId:'audio://legaia/prot/0877',sceneId:'scene://town01',sourceKey:'a'.repeat(64),entryHash:'b'.repeat(64),bankHash:'c'.repeat(64),projectPath:'C:/private/project'};
const report={schema_version:'legaia.audio-bank-inspection.v1',asset_id:context.assetId,scene_id:context.sceneId,source_key:context.sourceKey,read_only:true,project_changed:false,runtime_state:'not_observed',reference_commit:'d'.repeat(40),source_record:{disc_sha256:'e'.repeat(64),iso_file:'PROT.DAT',prot_entry_index:877,entry_sha256:context.entryHash,entry_byte_offset:2048,entry_size_bytes:4096,carrier:'split-vab-header-samples',pieces:[{bank_offset:0,entry_offset:4,size_bytes:3104},{bank_offset:3104,entry_offset:3112,size_bytes:16}]},header:{version:7,bank_id:1,declared_size:3120,program_count:1,tone_count:2,sample_count:1},bank_sha256:context.bankHash,bank_size_bytes:3120,sections:{program_offset:32,tone_offset:2080,sample_table_offset:2592,sample_offset:3104},programs:Array.from({length:128},(_,slot)=>({slot,offset:32+slot*16,tone_count:slot===12?1:0,volume:0,priority:0,mode:0,pan:0,attributes:0,source_sha256:'f'.repeat(64)})),tones:Array.from({length:16},(_,index)=>({page:0,index,offset:2080+index*32,priority:0,mode:0,volume:0,pan:0,center:60,shift:0,minimum_key:0,maximum_key:127,pitch_bend_down:0,pitch_bend_up:0,adsr1:0,adsr2:0,program_operand:12,sample_operand:index?0:1,sample_index:index?null:0,source_sha256:'f'.repeat(64)})),samples:[{index:0,table_index:1,size_units:2,offset:3104,size_bytes:16,block_aligned:true,source_sha256:'f'.repeat(64)}],sample_table_spacer:0,sample_table_unused_nonzero:0,used_program_slots:[12],declared_program_count_matches_used_slots:true,consumed_sample_end:3120,remaining_bank_bytes:0,limitations:['Packed pages are not program slot numbers.']};
const decoded=decodeAudioBank(report,context);decoded.programs[12].slot=1;assert.equal(report.programs[12].slot,12);
for(const change of [r=>r.source_key='f'.repeat(64),r=>r.bank_sha256='f'.repeat(64),r=>r.source_record.entry_sha256='f'.repeat(64),r=>r.source_record.pieces[1].entry_offset++,r=>r.sections.sample_offset++,r=>r.programs[12].tone_count=17,r=>r.tones[0].sample_index=1,r=>r.tones[0].page=12,r=>r.samples[0].offset++,r=>r.samples[0].size_units=3,r=>r.samples[0].block_aligned=false,r=>r.remaining_bank_bytes=1,r=>r.used_program_slots=[0],r=>r.payload=true,r=>r.read_only=false]){const bad=structuredClone(report);change(bad);assert.throws(()=>decodeAudioBank(bad,context));}
console.log('Bank source pieces/fixed sections/table operands/sample spans, summary guards and detached metadata passed.');
class Element{constructor(tag){this.tag=tag;this.style={};this.children=[];this.dataset={};this.value='';this.listeners={};this.textContent='';}append(...nodes){this.children.push(...nodes);if(this.tag==='select'&&!this.value&&nodes[0])this.value=nodes[0].value;}setAttribute(){}replaceChildren(...nodes){this.children=[...nodes];}addEventListener(name,callback){this.listeners[name]=callback;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}remove(){this.removed=true;}}
globalThis.document={createElement:tag=>new Element(tag),body:new Element('body')};const find=(node,tag)=>node.tag===tag?node:node.children.map(child=>find(child,tag)).find(Boolean);let current={...context},resolve;const response=()=>({ok:true,text:async()=>JSON.stringify(report)});
let view=openAudioBank({record:{id:context.assetId,label:'Source'},getContext:()=>current,busy:()=>false,request:async()=>response()});try{await view.ready;assert.equal(find(view.dialog,'tbody').children.length,1);current={...current,bankHash:'f'.repeat(64)};await new Promise(done=>setTimeout(done,350));assert.equal(find(view.dialog,'tbody').children.length,0);assert(view.dialog.children.some(n=>n.textContent?.includes('sources changed')));}finally{view.dispose();}
current={...context};view=openAudioBank({record:{id:context.assetId,label:'Source'},getContext:()=>current,busy:()=>false,request:()=>new Promise(done=>resolve=done)});view.dispose();resolve(response());await view.ready;assert(view.dialog.removed);assert.equal(find(view.dialog,'tbody').children.length,0);console.log('Bank context withdrawal and close/late-response guards passed.');
