import assert from 'node:assert/strict';
import {decodeBuildReview} from '../editor/build-review.js';
import {decodeBuildVerification} from '../editor/build-history.js';
import {decodeBuildRuntimeSources} from '../editor/sdk-stability-sources.js';
const receipt={schema_version:'legaia.build-stability-source.v1',read_only:true,scope:'build_host_recorded_source_inclusion_only',basis_revision:'a'.repeat(40),execution_evidence_date:'2026-10-04',release_reference_revision:'b'.repeat(40),comparison_receipt_sha256:'c'.repeat(64),files:[{path:'runtime/source.c',category:'source_sha256',expected_sha256:'d'.repeat(64),actual_sha256:'d'.repeat(64),status:'matched'}],all_matched:true,execution_repeated:false,runtime_binary_verified:false,gameplay_verified:false};
assert.deepEqual(decodeBuildRuntimeSources(receipt),receipt);const clone=decodeBuildRuntimeSources(receipt);clone.files[0].path='other';assert.equal(receipt.files[0].path,'runtime/source.c');
for(const status of ['changed','missing','unreadable','unsafe','oversized','unstable']){const v=structuredClone(receipt);Object.assign(v.files[0],{status,actual_sha256:status==='changed'?'e'.repeat(64):null});v.all_matched=false;assert.deepEqual(decodeBuildRuntimeSources(v),v);}
for(const mutate of [v=>v.checked_at='2026-10-09',v=>v.runtime_binary_verified=true,v=>v.gameplay_verified=true,v=>v.execution_repeated=true,v=>v.scope='recorded_source_inclusion_only',v=>v.all_matched=false,v=>v.files[0].path='../outside',v=>v.files[0].extra=true,v=>v.files[0].actual_sha256='e'.repeat(64),v=>v.files[0].status='missing',v=>v.files.push(structuredClone(v.files[0]))]){const value=structuredClone(receipt);mutate(value);assert.throws(()=>decodeBuildRuntimeSources(value));}
console.log('Build-host source receipt: deterministic shape, explicit drift/unavailable states, detached reads and scope/hash/path/summary refusal passed.');

const hash='a'.repeat(64),r={schema_version:'legaia.build-report.v1',changes:[],change_count:0,scene_count:0,overlay_bytes:0,validation:{retail_provenance:'fresh_import_match',live_runtime:'not_run',unchanged_opaque_bytes:true,runtime_source_inclusion:receipt}};
const review={schema_version:'legaia.build-review.v1',source_key:hash,read_only:true,status:'ready_for_build',normal_build_ready:true,blockers:[],excluded_npc_draft_count:0,assessment_scope:'existing_imported_content_and_supported_overrides_excluding_npc_drafts',limitations:[],assessment:{report:r,output_written:false,archive_packing:'not_run',runtime_status:'not_run',audit_sha256:hash,manifest_sha256:hash,source_disc_sha256:hash,overlay_count:0,build_kind:'retail',change_kinds:[]}};
const saved={id:'a'.repeat(16),integrity:'verified',gameplay_verified:false,matches_current_inputs:true,source_disc_integrity:'not_checked',runtime_status:'package_built_not_launched',scope:'receipt_audit_manifest_package_source_files_and_ZIP_members',report:r};
assert.deepEqual(decodeBuildReview(review,hash).assessment.report.validation.runtime_source_inclusion,receipt);assert.deepEqual(decodeBuildVerification(saved,saved.id).report.validation.runtime_source_inclusion,receipt);
for(const mutate of [v=>v.runtime_binary_verified=true,v=>v.files[0].actual_sha256='e'.repeat(64),v=>v.all_matched=false]){const badReview=structuredClone(review),badSaved=structuredClone(saved);mutate(badReview.assessment.report.validation.runtime_source_inclusion);mutate(badSaved.report.validation.runtime_source_inclusion);assert.throws(()=>decodeBuildReview(badReview,hash));assert.throws(()=>decodeBuildVerification(badSaved,saved.id));}
for(const value of [review,saved]){const old=structuredClone(value);delete(old.assessment?.report??old.report).validation.runtime_source_inclusion;if(old.assessment)assert.doesNotThrow(()=>decodeBuildReview(old,hash));else assert.doesNotThrow(()=>decodeBuildVerification(old,old.id));}
console.log('Normal Build Review and saved verification validate the source evidence; older receipts remain readable without invented evidence.');
