import assert from 'node:assert/strict';
import {environmentLayoutOperation,decodeEnvironmentLayout} from '../editor/environment-layout.js';
const key='a'.repeat(64),scene='scene://fixture',ids=[1,2,3,4].map(cell=>`environment://fixture/field-map/decorations/${String(cell).padStart(5,'0')}`);
const rows=ids.map((entity_id,index)=>({entity_id,cell_index:index+1,retail:{x:0,z:0},current:{x:[-5,-5,0,5][index],z:20+index},proposed:{x:-5,z:20+index}}));
const align={kind:'align',axis:'x',anchor:ids[0]};
const report={schema_version:'legaia.environment-layout-review.v1',project_source_key:key,scene_id:scene,source_sha256:'b'.repeat(64),review_key:'c'.repeat(64),entity_ids:ids,operation:align,targets:rows,affected_count:2,project_change:true,value:{},scope:'static-decoration-instance-transform-only',gameplay_verified:false};
assert.deepEqual(environmentLayoutOperation({anchor:ids[0],axis:'x',kind:'align'},ids),align);
for(const invalid of [null,{}, {kind:'rotate',axis:'x'}, {kind:'align',axis:'y',anchor:ids[0]}, {kind:'align',axis:'x',anchor:ids[0],extra:1}, {kind:'align',axis:'x',anchor:'other'}, {kind:'distribute',axis:'z',anchor:ids[0]}])assert.throws(()=>environmentLayoutOperation(invalid,ids));
for(const invalidIds of [[ids[0]], [...ids].reverse(), [ids[0],ids[0]], [ids[0],'environment://fixture/field-map/decorations/16384'], Array(129).fill(ids[0])])assert.throws(()=>environmentLayoutOperation(align,invalidIds));
const decoded=decodeEnvironmentLayout(report,key,scene,ids,align);assert.deepEqual(decoded,report);decoded.targets[0].current.x=99;assert.equal(report.targets[0].current.x,-5);
for(const changes of [{schema_version:'bad'},{project_source_key:'d'.repeat(64)},{source_sha256:'bad'},{review_key:'bad'},{scene_id:'scene://other'},{gameplay_verified:true},{scope:'other'},{project_change:1},{affected_count:1},{entity_ids:[...ids].reverse()},{operation:{kind:'distribute',axis:'x'}},{targets:rows.slice(1)}])assert.throws(()=>decodeEnvironmentLayout({...report,...changes},key,scene,ids,align));
for(const change of [{cell_index:0},{cell_index:16384},{entity_id:ids[1]},{proposed:{x:-4,z:20}},{proposed:{x:-5,z:21}},{current:{x:1.5,z:20}},{retail:{x:NaN,z:0}}])assert.throws(()=>decodeEnvironmentLayout({...report,targets:[{...rows[0],...change},...rows.slice(1)]},key,scene,ids,align));
const distribute={kind:'distribute',axis:'x'},distributed={...report,operation:distribute,affected_count:2,targets:rows.map((row,index)=>({...row,proposed:{x:[-5,-2,2,5][index],z:row.current.z}}))};
assert.deepEqual(decodeEnvironmentLayout(distributed,key,scene,ids,distribute),distributed);
assert.throws(()=>decodeEnvironmentLayout({...distributed,targets:distributed.targets.map((row,index)=>index===1?{...row,proposed:{...row.proposed,x:-1}}:row)},key,scene,ids,distribute));
const halfIds=ids.slice(0,3),halfRows=rows.slice(0,3).map((row,index)=>({...row,current:{x:[-2,-1,1][index],z:0},proposed:{x:[-2,0,1][index],z:0}}));
const half={...distributed,entity_ids:halfIds,targets:halfRows,affected_count:1};
assert.deepEqual(decodeEnvironmentLayout(half,key,scene,halfIds,distribute),half);
assert.throws(()=>decodeEnvironmentLayout({...half,targets:halfRows.map(row=>({...row,current:{x:0,z:0}}))},key,scene,halfIds,distribute));
const zAlign={kind:'align',axis:'z',anchor:ids[2]},zReport={...report,operation:zAlign,affected_count:3,targets:rows.map(row=>({...row,proposed:{x:row.current.x,z:rows[2].current.z}}))};
assert.deepEqual(decodeEnvironmentLayout(zReport,key,scene,ids,zAlign),zReport);
const unchanged={...report,affected_count:0,project_change:false,targets:rows.map(row=>({...row,current:{x:9,z:row.current.z},proposed:{x:9,z:row.current.z}}))};assert.deepEqual(decodeEnvironmentLayout(unchanged,key,scene,ids,align),unchanged);
console.log('Scenery layout operation, source identity, canonical selection, alignment, deterministic distribution, half-up rounding and retained-report guards passed.');

const scale={kind:'scale',anchor:ids[2],percent:50},scaleReport={...report,operation:scale,affected_count:3,targets:rows.map((r,i)=>({...r,proposed:{x:[-3,-3,0,3][i],z:[21,22,22,23][i]}}))};
assert.deepEqual(environmentLayoutOperation(scale,ids),scale);assert.deepEqual(decodeEnvironmentLayout(scaleReport,key,scene,ids,scale),scaleReport);
const mirror={kind:'mirror',anchor:ids[2],axis:'x'},mirrorReport={...report,operation:mirror,affected_count:3,targets:rows.map(r=>({...r,proposed:{x:-r.current.x,z:r.current.z}}))};
assert.deepEqual(decodeEnvironmentLayout(mirrorReport,key,scene,ids,mirror),mirrorReport);
for(const op of [{...scale,percent:true},{...scale,percent:0},{...scale,percent:1001},{...scale,percent:50.5},{...scale,axis:'x'},{...mirror,anchor:'foreign'}])assert.throws(()=>environmentLayoutOperation(op,ids));
assert.throws(()=>decodeEnvironmentLayout({...scaleReport,targets:scaleReport.targets.map((r,i)=>i===0?{...r,proposed:{...r.proposed,x:-2}}:r)},key,scene,ids,scale));
console.log('Scenery scale/mirror exact signed half ties, both axes, preserved layers, native operation fields and response arithmetic passed.');
