import assert from 'node:assert/strict';
import {moveUvCorner,uvPointerByte,nativeUvTexture} from '../editor/model-uv-workspace.js';
const rows=[[0,1],[255,0],[255,255],[0,255]],before=structuredClone(rows);assert.deepEqual(moveUvCorner(rows,3,128,64),[[0,1],[255,0],[255,255],[128,64]]);assert.deepEqual(rows,before);
for(const args of [[rows,-1,0,0],[rows,4,0,0],[rows,1,256,0],[rows,1,0,-1],[rows,1,true,0],[[[0,1]],0,1,2]])assert.throws(()=>moveUvCorner(...args));
assert.equal(uvPointerByte(100,100,384),0);assert.equal(uvPointerByte(483.9,100,384),255);assert.equal(uvPointerByte(500,100,384),255);assert.equal(uvPointerByte(99,100,384),0);assert.equal(uvPointerByte(292,100,384),128);assert.throws(()=>uvPointerByte(1,2,0));assert.throws(()=>uvPointerByte(NaN,0,100));
const source={asset_id:'asset://fixture/model/0',objects:[{object_index:0,vertex_count:4,primitives:[{primitive_index:0,corner_count:4}]}]},preview={semantic_id:source.asset_id,coordinate_system:'retail_tmd_object_local',objects:[{object_index:0,vertex_count:4,triangle_start:0,triangle_count:2}],triangle_materials:[0,0],triangle_uvs:[rows.slice(0,3),[rows[1],rows[3],rows[2]]],textures:[{material_index:0,status:'address_match',width:2,height:1,uv_origin:[254,255],rgba_base64:Buffer.from([255,0,0,255,0,0,255,255]).toString('base64')}]};
const copy=structuredClone(preview),layer=nativeUvTexture(preview,source,0,0,rows);assert.deepEqual([...layer.pixels],[255,0,0,255,0,0,255,255]);layer.pixels[0]=0;layer.uv_origin[0]=0;assert.deepEqual(preview,copy);
for(const change of [p=>p.semantic_id='foreign',p=>p.posed=true,p=>p.objects[0].triangle_count=1,p=>p.triangle_materials[1]=1,p=>p.triangle_uvs[1].reverse(),p=>p.textures[0].width=3,p=>p.textures[0].rgba_base64='AA==',p=>p.textures.push(p.textures[0])]){const bad=structuredClone(preview);change(bad);assert.throws(()=>nativeUvTexture(bad,source,0,0,rows));}
const ambiguous=structuredClone(preview);ambiguous.textures[0]={material_index:0,status:'ambiguous',reason:'conflicting uploads'};assert.deepEqual(nativeUvTexture(ambiguous,source,0,0,rows),{status:'ambiguous',reason:'conflicting uploads'});assert.deepEqual(rows,before);console.log('Native byte dragging, clamped canvas coordinates, quad UV/material ownership, detached crop pixels and ambiguous/stale/malformed evidence guards passed.');
