import assert from 'node:assert/strict';
import {highlightSceneFaceDocument,highlightSceneFaceProposal} from '../editor/model-face-scene-selection.js';
const asset='asset://fixture/model/0',key='a'.repeat(64),sha='b'.repeat(64),source={asset_id:asset,project_source_key:key,effective_sha256:sha,objects:[{vertex_count:4,primitives:[{primitive_index:0,group_index:0,corner_count:4,uvs:[[0,0],[1,0],[0,1],[1,1]]},{primitive_index:1,group_index:1,corner_count:3,uvs:[[0,0],[1,0],[0,1]]}]}]},selection={asset_id:asset,project_source_key:key,effective_sha256:sha,can_stage:true,material_index:0,faces:[{object_index:0,group_index:0,primitive_index:0,textured:true,triangle_count:2,material_indices:[0]}]};
const preview={objects:[{object_index:0,vertex_count:4,triangle_start:0,triangle_count:3}],vertices:[[0,0,0],[10,0,0],[0,10,0],[10,10,0]],triangles:[[0,1,2],[1,3,2],[0,1,2]],materials:[{textured:true}],triangle_materials:[0,0,0],triangle_colors:Array.from({length:3},()=>[[80,80,80],[80,80,80],[80,80,80]]),triangle_uvs:Array.from({length:3},()=>[[0,0],[1,0],[0,1]])},otherPose={...structuredClone(preview),vertices:preview.vertices.map(v=>[v[0]+100,v[1],v[2]])};
const assets=[{asset_id:asset,geometry_key:'pose-0',preview},{asset_id:asset,geometry_key:'pose-1',preview:otherPose},{asset_id:'asset://fixture/other',geometry_key:'context',preview}],entities=[{asset_id:asset,geometry_key:'pose-0',entity_id:'a',renderable:true,model_to_scene:[1,0,0,50,0,1,0,60,0,0,1,70,0,0,0,1]},{asset_id:asset,geometry_key:'pose-1',entity_id:'b',renderable:true,model_to_scene:[1,0,0,500,0,1,0,600,0,0,1,700,0,0,0,1]},{asset_id:'asset://fixture/other',geometry_key:'context',entity_id:'c',renderable:true}];
const scene={project_source_key:key,assets,entities},report={project_source_key:key,asset_id:asset,effective_sha256:sha,proposed_sha256:'c'.repeat(64),instance_scope:'all_model_instances',preview,proposal_assets:assets.slice(0,2),proposal_instances:entities.slice(0,2)},before=structuredClone({scene,report,source,selection});
const current=highlightSceneFaceDocument(scene,source,selection),proposed=highlightSceneFaceProposal(report,source,selection);
for(const result of [current.assets,proposed.proposal_assets])for(let i=0;i<2;i++){assert.deepEqual(result[i].preview.vertices,assets[i].preview.vertices);assert.deepEqual(result[i].preview.triangles,preview.triangles);assert.deepEqual(result[i].preview.triangle_materials,[1,1,0]);assert.deepEqual(result[i].preview.triangle_colors[2],preview.triangle_colors[2]);assert.equal(result[i].geometry_key,assets[i].geometry_key);}
assert.deepEqual(current.entities,scene.entities);assert.deepEqual(current.assets[2],scene.assets[2]);assert.deepEqual(proposed.proposal_instances,report.proposal_instances);assert.equal(proposed.proposed_sha256,report.proposed_sha256);assert.deepEqual({scene,report,source,selection},before);
for(const mutate of [r=>r.project_source_key='stale',r=>r.asset_id='asset://wrong',r=>r.effective_sha256='f'.repeat(64),r=>r.instance_scope='single',r=>r.proposal_assets[0].asset_id='asset://wrong']){const bad=structuredClone(report);mutate(bad);assert.throws(()=>highlightSceneFaceProposal(bad,source,selection));}
const bad=structuredClone(scene);bad.assets[0].asset_id='asset://wrong';assert.throws(()=>highlightSceneFaceDocument(bad,source,selection));const missing=structuredClone(scene);missing.assets.splice(1,1);assert.throws(()=>highlightSceneFaceDocument(missing,source,selection));const duplicate=structuredClone(scene);duplicate.assets.push(duplicate.assets[0]);assert.throws(()=>highlightSceneFaceDocument(duplicate,source,selection));assert.deepEqual({scene,report,source,selection},before);console.log('Shared posed scene face highlights preserve source geometry, placements, context and reviewed hashes; stale/foreign ownership rejected.');
