import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {decodeWavRecovery,decodeWavRemoval,inspectInputWav} from '../editor/audio-sample-recovery.js';
const key='a'.repeat(64),wav=new Uint8Array(100),view=new DataView(wav.buffer),text=(at,s)=>{for(let i=0;i<s.length;i++)wav[at+i]=s.charCodeAt(i);};
text(0,'RIFF');view.setUint32(4,92,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,32000,true);view.setUint32(28,64000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,56,true);for(let i=44;i<100;i++)wav[i]=i;
const receipt={receipt_key:'b'.repeat(64),wav_sha256:createHash('sha256').update(wav).digest('hex'),byte_length:100,input_wav_rate:32000,decoded_frames:28};
const recovered={schema_version:'legaia.audio-sample-sources.v1',authoring_key:key,imports:[receipt],historical_inputs:true,project_changed:false,runtime_state:'not_observed',selected:receipt,wav_base64:Buffer.from(wav).toString('base64')};
assert.deepEqual(await decodeWavRecovery(recovered,key,receipt),wav);
for(const mutation of [v=>v.authoring_key='c'.repeat(64),v=>v.selected={...v.selected,byte_length:99},v=>v.imports=[],v=>v.imports.push(v.selected),v=>v.wav_base64=v.wav_base64.slice(4),v=>v.wav_base64=Buffer.from(new Uint8Array(100)).toString('base64'),v=>v.project_changed=true,v=>v.extra=true]){const value=structuredClone(recovered);mutation(value);await assert.rejects(()=>decodeWavRecovery(value,key,receipt));}
const removal={schema_version:'legaia.audio-sample-source-removal.v1',authoring_key:key,receipt_key:receipt.receipt_key,wav_sha256:receipt.wav_sha256,source_file_deleted:false,native_content_changed:false,registered_bytes_released:100,review_key:'d'.repeat(64)};
decodeWavRemoval(removal,key,receipt);decodeWavRemoval({...removal,registered_bytes_released:0},key,receipt);
for(const mutation of [v=>v.authoring_key='c'.repeat(64),v=>v.receipt_key='c'.repeat(64),v=>v.wav_sha256='c'.repeat(64),v=>v.source_file_deleted=true,v=>v.native_content_changed=true,v=>v.registered_bytes_released=99,v=>v.review_key='bad',v=>v.extra=true]){const value=structuredClone(removal);mutation(value);assert.throws(()=>decodeWavRemoval(value,key,receipt));}
for(const [offset,value,width] of [[4,91,4],[16,18,4],[20,3,2],[22,2,2],[24,44100,4],[28,1,4],[32,4,2],[34,8,2],[40,55,4]]){const changed=wav.slice(),v=new DataView(changed.buffer);width===2?v.setUint16(offset,value,true):v.setUint32(offset,value,true);assert.throws(()=>inspectInputWav(changed,receipt));}
// Unknown RIFF chunks remain exact; odd-sized chunks require their padded extent.
const padded=new Uint8Array(110);padded.set(wav.subarray(0,36));padded.set([74,85,78,75,1,0,0,0,42,0],36);padded.set(wav.subarray(36),46);new DataView(padded.buffer).setUint32(4,102,true);assert.deepEqual(inspectInputWav(padded,receipt),{frames:28,rate:32000});assert.throws(()=>inspectInputWav(padded.subarray(0,109),receipt));
console.log('Exact original WAV recovery, stale/hash/extent guards, mono PCM fields, padded unknown chunks and nondeleting/native-unchanged removal contracts passed.');
