import assert from 'node:assert/strict';
import fs from 'node:fs';
import {webcrypto,createHash} from 'node:crypto';
import {decodeAudioInputRecord,decodeAudioInput,decodeAudioInputDownload,openAudioInput} from '../editor/audio-input-assets.js';
import {decodeAssetReferences,assetReferenceRelationLabel} from '../editor/asset-references.js';
import {assetInspectorRegistry} from '../editor/asset-inspector.js';
globalThis.crypto??=webcrypto;
// An independently supplied receipt allows the suite to run without retail files.
const bytes=new Uint8Array(100),view=new DataView(bytes.buffer),text=(at,s)=>[...s].forEach((c,i)=>bytes[at+i]=c.charCodeAt(0));text(0,'RIFF');text(8,'WAVE');text(12,'fmt ');text(36,'data');view.setUint32(4,92,true);view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,32000,true);view.setUint32(28,64000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);view.setUint32(40,56,true);
const sha=createHash('sha256').update(bytes).digest('hex'),id='audio-input://legaia/wav/'+sha,context={assetId:id,sourceKey:'a'.repeat(64),projectPath:'C:/private/project'};
const input={schema_version:'legaia.audio-input-asset.v1',wav_sha256:sha,byte_length:100,input_wav_rate:32000,decoded_frames:28,channels:1,bits_per_sample:16};
const data={id,semantic_id:id,kind:'audio',asset_kind:'audio',name:'WAV input '+sha.slice(0,12),layer:'authored_input',source_kind:'retained_wav_input',format:'pcm-wav',source_record:{kind:'project_wav_input',sha256:sha,byte_length:100,relative_path:'Authored/Audio/Sources/'+sha+'.wav'},audio_input:input};
const receipt={schema_version:'legaia.audio-sample-source.v1',asset_id:'audio://legaia/prot/0877',source_scene_id:'scene://town01',source_record:{disc_sha256:'b'.repeat(64),iso_file:'PROT.DAT',prot_entry_index:877,entry_sha256:'c'.repeat(64),entry_byte_offset:0,entry_size_bytes:32,carrier:'standalone-vab',pieces:[{bank_offset:0,entry_offset:0,size_bytes:32}]},bank_sha256:'d'.repeat(64),sample_index:0,source_sample_sha256:'e'.repeat(64),wav_sha256:sha,byte_length:100,input_wav_rate:32000,decoded_frames:28,candidate_sample_sha256:'f'.repeat(64),review_key:'1'.repeat(64),receipt_key:'2'.repeat(64)};
const report={schema_version:'legaia.audio-input-inspection.v1',asset_id:id,source_key:context.sourceKey,project_path:context.projectPath,record:data,receipts:[receipt],historical_inputs:true,read_only:true,project_changed:false,runtime_binding:'not_asserted',gameplay_verified:false},download={...report,wav_base64:Buffer.from(bytes).toString('base64')},record={id,type:'audio',data};
assert.deepEqual(decodeAudioInput(report,context),report);assert.deepEqual((await decodeAudioInputDownload(download,context)).bytes,bytes);
for(const mutate of [v=>v.extra=true,v=>v.source_key='0'.repeat(64),v=>v.project_path+='x',v=>v.runtime_binding='active',v=>v.gameplay_verified=true,v=>v.record.audio_input.channels=2,v=>v.record.source_record.relative_path='../file.wav',v=>v.receipts[0].wav_sha256='0'.repeat(64),v=>v.receipts[0].sample_index=true,v=>v.receipts[0].source_record.prot_entry_index=878,v=>v.receipts[0].source_record.pieces[0].size_bytes=33,v=>v.receipts.push(v.receipts[0])]){const bad=structuredClone(report);mutate(bad);assert.throws(()=>decodeAudioInput(bad,context));}
await assert.rejects(()=>decodeAudioInputDownload({...download,wav_base64:Buffer.from(new Uint8Array(100)).toString('base64')},context));
const copy=decodeAudioInputRecord(data,id);copy.audio_input.decoded_frames=56;assert.equal(data.audio_input.decoded_frames,28);
assert.deepEqual(Object.keys(assetInspectorRegistry(record,()=>{})),['inspect-audio-input']);assert.equal(Object.hasOwn(assetInspectorRegistry({type:'audio',data:{}},()=>{}),'inspect-audio-input'),false);
class Element{constructor(tag){this.tag=tag;this.style={};this.children=[];this.listeners={};this.textContent='';}append(...nodes){this.children.push(...nodes);}setAttribute(){}replaceChildren(...nodes){this.children=[...nodes];}addEventListener(name,callback){this.listeners[name]=callback;}showModal(){this.open=true;}close(){this.listeners.close?.();}remove(){this.removed=true;}click(){this.clicked=true;}}
globalThis.document={createElement:t=>new Element(t),body:new Element('body')};let now={...context},resolve;
const params={record,getContext:()=>now,busy:()=>false},response=v=>({ok:true,text:async()=>JSON.stringify(v)});
let ui=openAudioInput({...params,request:async()=>response(report)});try{await ui.ready;assert(ui.dialog.children.some(n=>n.textContent.includes('verified')));now={...context,sourceKey:'0'.repeat(64)};await new Promise(r=>setTimeout(r,350));assert(ui.dialog.children.some(n=>n.textContent.includes('sources changed')));assert.equal(ui.dialog.children.at(-1).disabled,true);}finally{ui.dispose();}
now={...context};ui=openAudioInput({...params,request:()=>new Promise(r=>resolve=r)});ui.dispose();resolve(response(report));await ui.ready;assert(ui.dialog.removed);assert(!ui.dialog.children.some(n=>n.textContent.includes('verified')));
now={...context};ui=openAudioInput({...params,record:{id},request:async()=>response(report)});try{await ui.ready;assert(ui.dialog.children.some(n=>n.textContent.includes('verified')));}finally{ui.dispose();}
now={...context};ui=openAudioInput({...params,record:{...record,data:{...data,format:'wrong'}},request:async()=>response(report)});try{await ui.ready;await new Promise(r=>setTimeout(r,350));assert.equal(ui.dialog.children.at(-1).disabled,true);}finally{ui.dispose();}
now={...context};let calls=0;ui=openAudioInput({...params,request:async()=>response(++calls===1?report:{...download,receipts:[{...receipt,review_key:'3'.repeat(64)}]})});try{await ui.ready;await ui.dialog.children.at(-1).onclick();assert(ui.dialog.children.some(n=>n.textContent.includes('receipts changed')));assert.equal(ui.dialog.children.at(-1).disabled,true);}finally{ui.dispose();}
if(process.env.LEGAIA_AUDIO_INPUT_FIXTURE){const f=JSON.parse(fs.readFileSync(process.env.LEGAIA_AUDIO_INPUT_FIXTURE,'utf8'));await decodeAudioInputDownload(f.report,f.context);const meta={...f.report};delete meta.wav_base64;decodeAudioInput(meta,f.context);const graph=decodeAssetReferences(f.graph,f.context.assetId,f.referenceKey);assert.equal(graph.incoming.length,1);assert(assetReferenceRelationLabel(graph.incoming[0]).includes('Current assignment unknown'));for(const mutate of [v=>v.incoming[0].layer='effective',v=>v.incoming[0].wav_input_evidence.relationship='active_assignment',v=>v.incoming[0].wav_input_evidence.sample_index=-1,v=>v.incoming[0].target_id='audio-input://legaia/wav/'+'0'.repeat(64)]){const bad=structuredClone(f.graph);mutate(bad);assert.throws(()=>decodeAssetReferences(bad,f.context.assetId,f.referenceKey));}console.log('Qualified retail WAV and historical reference fixture passed.');}
console.log('WAV record/receipt validation, exact download hash/PCM, action isolation, stale context, close/late responses and changed receipts passed.');
