import assert from 'node:assert/strict';
import {decodeDraftGroupReview,decodeDraftGroupScene,draftGroupPositions} from '../editor/draft-group.js';
const state={scene:{id:'scene'},scene_preview_source_key:'b'.repeat(64),actor_drafts:{a:{scene_id:'scene',donor_entity_id:'donor',name:'A',position:{x:128,z:512}},b:{scene_id:'scene',donor_entity_id:'donor',name:'B',position:{x:192,z:512}}}},request={entity_ids:['a','b'],delta:{x:64,z:-128}},report={schema_version:'legaia.draft-group-review.v1',scene_id:'scene',scene_preview_source_key:state.scene_preview_source_key,project_source_key:'c'.repeat(64),review_key:'d'.repeat(64),request,targets:['a','b'].map(id=>({entity_id:id,draft:state.actor_drafts[id],proposed:{x:state.actor_drafts[id].position.x+64,z:384}})),changed_count:2,gameplay_verified:false,limitations:['Scope']};
const accepted=decodeDraftGroupReview(report,request,state);accepted.targets[0].draft.name='Detached';assert.equal(state.actor_drafts.a.name,'A');
const reordered={...report,request:{delta:request.delta,entity_ids:request.entity_ids}};assert.deepEqual(decodeDraftGroupReview(reordered,request,state).request,reordered.request);
for(const edit of [v=>v.targets.reverse(),v=>v.targets[0].proposed.x+=64,v=>v.targets[0].draft.donor_entity_id='other',v=>v.scene_preview_source_key='stale',v=>v.changed_count=1,v=>v.gameplay_verified=true,v=>v.request.extra=0]){const bad=structuredClone(report);edit(bad);assert.throws(()=>decodeDraftGroupReview(bad,request,state));}
const entity=(id,x,z)=>({entity_id:id,kind:'actor_draft',donor_entity_id:'donor',name:id,position:{x,y:null,z},preview_position:{x,y:null,z},display_position:{x,y:0,z},preview_height_status:'unresolved_no_source_surface',model_to_scene:[1,0,0,x,0,1,0,0,0,0,1,z,0,0,0,1],authored_position:{x,z}});
const base={source_key:state.scene_preview_source_key,scene_id:'scene',assets:[],position_to_display:[],entities:[entity('a',128,512),entity('b',192,512),{entity_id:'unchanged',kind:'actor',position:{x:512,z:512}}]},scene={...structuredClone(base),schema:'legaia.scene-preview.v1',representation:'authored',entities:[entity('a',192,384),entity('b',256,384),structuredClone(base.entities[2])]},response={schema_version:'legaia.draft-group-scene.v1',project_source_key:report.project_source_key,scene_preview_source_key:base.source_key,scene_id:'scene',review_key:report.review_key,scene};
const decoded=decodeDraftGroupScene(response,report,base);decoded.entities[0].position.x=0;assert.equal(response.scene.entities[0].position.x,192);
for(const edit of [v=>v.review_key='stale',v=>v.scene.entities[2].position.x=0,v=>v.scene.entities[0].donor_entity_id='other',v=>v.scene.entities[0].model_to_scene[3]=0,v=>v.scene.entities[0].display_position.z=0,v=>v.scene.entities.pop(),v=>v.scene.assets.push({})]){const bad=structuredClone(response);edit(bad);assert.throws(()=>decodeDraftGroupScene(bad,report,base));}
console.log('NPC draft group source, exact targets, detached report/scene, unchanged content and model/display transforms passed.');

const layoutDrafts={a:{position:{x:128,z:512}},b:{position:{x:192,z:640}},c:{position:{x:320,z:768}}};
assert.deepEqual([...draftGroupPositions({entity_ids:['a','b','c'],layout:{kind:'align',axis:'x',anchor_entity_id:'b'}},layoutDrafts).values()],[{x:192,z:512},{x:192,z:640},{x:192,z:768}]);
assert.deepEqual([...draftGroupPositions({entity_ids:['a','b','c'],layout:{kind:'distribute',axis:'x'}},layoutDrafts).values()],[{x:128,z:512},{x:256,z:640},{x:320,z:768}]);
for(const layout of [{kind:'align',axis:'x',anchor_entity_id:'missing'},{kind:'distribute',axis:'x',extra:1},{kind:'distribute',axis:'y'}])assert.throws(()=>draftGroupPositions({entity_ids:['a','b','c'],layout},layoutDrafts));
assert.throws(()=>draftGroupPositions({entity_ids:['a','b','c'],layout:{kind:'distribute',axis:'x'}},{a:{position:{x:128,z:512}},b:{position:{x:128,z:512}},c:{position:{x:192,z:512}}}));
const alignRequest={entity_ids:['a','b'],layout:{kind:'align',axis:'x',anchor_entity_id:'a'}},aligned={...structuredClone(report),request:alignRequest,changed_count:1,targets:report.targets.map(row=>({...structuredClone(row),proposed:{x:128,z:512}}))};
assert.equal(decodeDraftGroupReview(aligned,alignRequest,state).changed_count,1);assert.throws(()=>decodeDraftGroupReview({...aligned,changed_count:2},alignRequest,state));
console.log('NPC alignment anchor, rounded native-grid spacing/endpoints, axis preservation and changed-count qualification passed.');

const removalRequest={entity_ids:['a','b'],remove:true},removalReport={...structuredClone(report),request:removalRequest,targets:report.targets.map(row=>({...structuredClone(row),proposed:null}))};
assert.equal(decodeDraftGroupReview(removalReport,removalRequest,state).changed_count,2);
assert.throws(()=>draftGroupPositions({...removalRequest,remove:1},state.actor_drafts));
const removalResponse={...structuredClone(response),scene:{...structuredClone(scene),entities:[structuredClone(base.entities[2])]}};
assert.equal(decodeDraftGroupScene(removalResponse,removalReport,base).entities.length,1);
for(const edit of [v=>v.scene.entities.push(structuredClone(base.entities[0])),v=>v.scene.entities[0].position.x=64,v=>v.scene.assets.push({})]){const bad=structuredClone(removalResponse);edit(bad);assert.throws(()=>decodeDraftGroupScene(bad,removalReport,base));}
console.log('Reviewed NPC removal qualifies exact absent targets and unchanged imported/unselected scene content.');

assert.throws(()=>decodeDraftGroupReview({...removalReport,request:{...removalRequest,remove:false}},removalRequest,state));

const nativeIds=[1,2,3].map(n=>'authored-actor://00000000-0000-4000-8000-'+String(n).padStart(12,'0')),nativeDrafts=Object.fromEntries(nativeIds.map((id,i)=>[id,{position:[{x:512,z:512},{x:576,z:640},{x:704,z:768}][i]}]));
for(const [operation,expected] of [[{kind:'rotate',quarter_turns:1},[{x:512,z:512},{x:384,z:576},{x:256,z:704}]],[{kind:'scale',percent:50},[{x:512,z:512},{x:576,z:576},{x:640,z:640}]],[{kind:'mirror',axis:'x'},[{x:512,z:512},{x:448,z:640},{x:320,z:768}]]])assert.deepEqual([...draftGroupPositions({entity_ids:nativeIds,layout:{...operation,anchor_entity_id:nativeIds[0]}},nativeDrafts).values()],expected);
for(const layout of [{kind:'rotate',quarter_turns:0},{kind:'scale',percent:0},{kind:'mirror',axis:'y'},{kind:'scale',percent:1001},{kind:'rotate',quarter_turns:true}])assert.throws(()=>draftGroupPositions({entity_ids:nativeIds,layout:{...layout,anchor_entity_id:nativeIds[0]}},nativeDrafts));
const nativeState={...state,actor_drafts:Object.fromEntries(nativeIds.map(id=>[id,{...nativeDrafts[id],scene_id:'scene',name:id,donor_entity_id:'donor'}]))},nativeRequest={entity_ids:nativeIds,layout:{kind:'rotate',quarter_turns:1,anchor_entity_id:nativeIds[0]}},nativePositions=draftGroupPositions(nativeRequest,nativeDrafts),nativeReport={...structuredClone(report),request:nativeRequest,changed_count:2,targets:nativeIds.map(id=>({entity_id:id,draft:nativeState.actor_drafts[id],proposed:nativePositions.get(id)}))};
assert.equal(decodeDraftGroupReview(nativeReport,nativeRequest,nativeState).changed_count,2);const forged=structuredClone(nativeReport);forged.targets[1].proposed.x+=64;assert.throws(()=>decodeDraftGroupReview(forged,nativeRequest,nativeState));
console.log('NPC native rotation, half-step scale rounding, mirror, fixed anchor, typed fields and forged proposals passed.');
