import assert from 'node:assert/strict';
import {decodeBankAuthoring,decodeBankReview,openBankAuthoring} from '../editor/audio-bank-authoring.js';
// Independent fixed offsets and scalar widths; no editor field registry reuse.
const definitions={header:[['master_volume',24,1,false],['pan',25,1,false],['attributes1',26,1,false],['attributes2',27,1,false]],program:[['volume',1,1,false],['priority',2,1,false],['mode',3,1,false],['pan',4,1,false],['attributes',6,2,false]],tone:[['priority',0,1,false],['mode',1,1,false],['volume',2,1,false],['pan',3,1,false],['center',4,1,false],['shift',5,1,false],['minimum_key',6,1,false],['maximum_key',7,1,false],['vibrato_width',8,1,false],['vibrato_time',9,1,false],['portamento_width',10,1,false],['portamento_time',11,1,false],['pitch_bend_down',12,1,false],['pitch_bend_up',13,1,false],['adsr1',16,2,false],['adsr2',18,2,false],['program_operand',20,2,true],['sample_operand',22,2,true]]};
const context={assetId:'audio://legaia/prot/0877',sceneId:'scene://town01',sourceKey:'a'.repeat(64),entryHash:'b'.repeat(64),bankHash:'c'.repeat(64),authoringKey:'d'.repeat(64)};
const source={disc_sha256:'e'.repeat(64),iso_file:'PROT.DAT',prot_entry_index:877,entry_sha256:context.entryHash,entry_byte_offset:2048,entry_size_bytes:4096,carrier:'split-vab-header-samples',pieces:[{bank_offset:0,entry_offset:4,size_bytes:3104},{bank_offset:3104,entry_offset:3112,size_bytes:16}]};
const bank={source_record:source,bank_sha256:context.bankHash,header:{version:7,bank_id:0,declared_size:3120,program_count:1,tone_count:1,sample_count:1},sections:{program_offset:32,tone_offset:2080,sample_table_offset:2592,sample_offset:3104},used_program_slots:[12],programs:Array.from({length:128},(_,slot)=>({slot,offset:32+slot*16})),tones:Array.from({length:16},(_,index)=>({page:0,index,offset:2080+index*32})),samples:[{}]};
const rows=[];for(const [section,records] of [['header',[{}]],['program',bank.programs],['tone',bank.tones]])for(const record of records)for(const [field,offset,width,signed] of definitions[section])rows.push({section,field,...(section==='program'?{slot:record.slot}:section==='tone'?{page:record.page,index:record.index}:{}),bank_byte_offset:(record.offset??0)+offset,byte_length:width,signed,value:signed?-1:width===2?256:60});
const profile={bank_sha256:context.bankHash,header:bank.header,sections:bank.sections,used_program_slots:[12],sample_count:1,parameters:rows,limitations:['Encoded widths only.']};
const options={schema_version:'legaia.audio-bank-authoring.v1',asset_id:context.assetId,scene_id:context.sceneId,source_key:context.sourceKey,authoring_key:context.authoringKey,source_record:source,current_entry_sha256:context.entryHash,binding_source_scene_id:context.sceneId,sequence_authored:false,samples_authored:false,authored_edits:[],retail:structuredClone(profile),current:structuredClone(profile),max_edits:256,project_changed:false,runtime_state:'not_observed'};
assert.deepEqual(decodeBankAuthoring(options,context,bank),options);
for(const mutate of [v=>v.authoring_key='f'.repeat(64),v=>v.retail.parameters[0].bank_byte_offset++,v=>v.current.parameters[0].value++,v=>v.current.parameters[0].value=true,v=>v.retail.parameters.pop(),v=>v.current_entry_sha256='f'.repeat(64),v=>v.source_record.pieces[0].size_bytes++,v=>v.extra=true,v=>v.current.header.tone_count++,v=>v.authored_edits=[{section:'header',field:'pan',value:60}]]){const bad=structuredClone(options);mutate(bad);assert.throws(()=>decodeBankAuthoring(bad,context,bank));}
const seqOnly=structuredClone(options);seqOnly.sequence_authored=true;seqOnly.current_entry_sha256='f'.repeat(64);decodeBankAuthoring(seqOnly,context,bank);seqOnly.current.bank_sha256='f'.repeat(64);assert.throws(()=>decodeBankAuthoring(seqOnly,context,bank));
const waveOnly=structuredClone(options);waveOnly.samples_authored=true;waveOnly.current.bank_sha256=waveOnly.current_entry_sha256='f'.repeat(64);decodeBankAuthoring(waveOnly,context,bank);
const edits=[{section:'header',field:'master_volume',value:61}];
const proposal={schema_version:'legaia.audio-bank-review.v1',asset_id:context.assetId,authoring_key:context.authoringKey,source_record:source,proposed_binding:{format:'vab-parameters-v1',source_scene_id:context.sceneId,source_record:source,edits},native_audit:{source_entry_sha256:context.entryHash,before_entry_sha256:context.entryHash,after_entry_sha256:'f'.repeat(64),carrier:source.carrier,pieces:source.pieces,changed_entry_byte_offsets:[28],bank:{source_sha256:context.bankHash,before_sha256:context.bankHash,after_sha256:'f'.repeat(64),edits:[{...edits[0],bank_byte_offset:24,byte_length:1,signed:false,source_value:60,before_value:60,after_value:61}],changed_bank_byte_offsets:[24]}},no_change:false,project_changed:false,runtime_state:'not_observed',review_key:'1'.repeat(64)};
assert.deepEqual(decodeBankReview(proposal,options,edits),proposal);
for(const mutate of [v=>v.native_audit.changed_entry_byte_offsets=[24],v=>v.native_audit.bank.edits[0].before_value=59,v=>v.native_audit.bank.edits[0].signed=true,v=>v.proposed_binding.edits[0].value=62,v=>v.proposed_binding.source_scene_id='scene://town02',v=>v.no_change=true,v=>v.native_audit.bank.changed_bank_byte_offsets=[],v=>v.native_audit.bank.edits[0].reserved=1]){const bad=structuredClone(proposal);mutate(bad);assert.throws(()=>decodeBankReview(bad,options,edits));}
// Every supported scalar: byte ownership, unsigned extrema and signed encoding.
for(const [section,defs] of Object.entries(definitions))for(const [field,offset,width,signed] of defs){
 const row=rows.find(r=>r.section===section&&r.field===field&&(section!=='program'||r.slot===12)&&(section!=='tone'||r.index===0));
 const edit={section,...(section==='program'?{slot:12}:section==='tone'?{page:0,index:0}:{}),field,value:signed?-32768:width===1?255:65535},expected=[];
 for(let i=0;i<width;i++)if((row.value>>>(8*i)&255)!==(edit.value>>>(8*i)&255))expected.push(row.bank_byte_offset+i);
 const p=structuredClone(proposal);p.proposed_binding.edits=[edit];p.native_audit.changed_entry_byte_offsets=expected.map(n=>n+4);p.native_audit.bank.changed_bank_byte_offsets=expected;p.native_audit.bank.edits=[{...edit,bank_byte_offset:row.bank_byte_offset,byte_length:width,signed,source_value:row.value,before_value:row.value,after_value:edit.value}];decodeBankReview(p,options,[edit]);
}
const authored=structuredClone(options);authored.authored_edits=edits;authored.current.parameters[0].value=61;authored.current.bank_sha256=authored.current_entry_sha256='f'.repeat(64);decodeBankAuthoring(authored,context,bank);
for(const name of ['bank','entry']){const bad=structuredClone(authored);if(name==='bank')bad.current.bank_sha256=context.bankHash;else bad.current_entry_sha256=context.entryHash;assert.throws(()=>decodeBankAuthoring(bad,context,bank));}
const restored=structuredClone(proposal);restored.proposed_binding=null;restored.native_audit.before_entry_sha256='f'.repeat(64);restored.native_audit.after_entry_sha256=context.entryHash;Object.assign(restored.native_audit.bank,{before_sha256:'f'.repeat(64),after_sha256:context.bankHash,edits:[{section:'header',field:'master_volume',value:60,bank_byte_offset:24,byte_length:1,signed:false,source_value:60,before_value:61,after_value:60}]});decodeBankReview(restored,authored,[{section:'header',field:'master_volume',value:60}]);
const badRestore=structuredClone(restored);badRestore.native_audit.bank.after_sha256='1'.repeat(64);assert.throws(()=>decodeBankReview(badRestore,authored,[{section:'header',field:'master_volume',value:60}]));
const withWave=structuredClone(authored);withWave.samples_authored=true;withWave.current.bank_sha256=withWave.current_entry_sha256='1'.repeat(64);const waveRestore=structuredClone(restored);waveRestore.native_audit.before_entry_sha256='1'.repeat(64);waveRestore.native_audit.after_entry_sha256='f'.repeat(64);waveRestore.native_audit.bank.before_sha256='1'.repeat(64);waveRestore.native_audit.bank.after_sha256='f'.repeat(64);decodeBankReview(waveRestore,withWave,[{section:'header',field:'master_volume',value:60}]);
const noop=structuredClone(proposal);noop.proposed_binding=null;noop.no_change=true;noop.native_audit.after_entry_sha256=context.entryHash;Object.assign(noop.native_audit,{changed_entry_byte_offsets:[]});Object.assign(noop.native_audit.bank,{after_sha256:context.bankHash,changed_bank_byte_offsets:[],edits:[{section:'header',field:'master_volume',value:60,bank_byte_offset:24,byte_length:1,signed:false,source_value:60,before_value:60,after_value:60}]});decodeBankReview(noop,options,[{section:'header',field:'master_volume',value:60}]);
const detached=decodeBankAuthoring(options,context,bank);detached.retail.parameters[0].value=1;assert.equal(options.retail.parameters[0].value,60);
console.log('All 27 bank fields, exact native spans, signed/unsigned encoding, canonical bindings, shared entry hashes, no-op and restoration passed.');
class Element{constructor(tag){this.tag=tag;this.style={};this.children=[];this.value='';this.listeners={};this.textContent='';}append(...nodes){this.children.push(...nodes);}setAttribute(){}replaceChildren(...nodes){this.children=[...nodes];}addEventListener(name,callback){this.listeners[name]=callback;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}remove(){this.removed=true;}}
globalThis.document={createElement:tag=>new Element(tag),body:new Element('body')};
const nodes=root=>[root,...root.children.flatMap(nodes)],button=(root,name)=>nodes(root).find(n=>n.tag==='button'&&n.textContent===name);
let now={...context},resolve;const params={record:{id:context.assetId,label:'Source bank'},bank,getContext:()=>now,getAuthoringKey:()=>now.authoringKey,canEdit:()=>true,busy:()=>false,apply:async()=>false};
let view=openBankAuthoring({...params,request:async()=>({ok:true,text:async()=>JSON.stringify(options)})});
try{await view.ready;const input=nodes(view.dialog).find(n=>n.tag==='input'&&n.max==='255');assert(input);input.value='61';input.oninput();assert(button(view.dialog,'Apply bank parameter').disabled);now={...now,authoringKey:'f'.repeat(64)};await new Promise(done=>setTimeout(done,350));assert(button(view.dialog,'Review bank parameter').disabled);assert.equal(nodes(view.dialog).filter(n=>n.tag==='table').length,0);}finally{view.dispose();}
now={...context};view=openBankAuthoring({...params,request:()=>new Promise(done=>resolve=done)});view.dispose();resolve({ok:true,text:async()=>JSON.stringify(options)});await view.ready;assert(view.dialog.removed);assert.equal(nodes(view.dialog).filter(n=>n.tag==='table').length,0);
console.log('Local drafts cannot Apply without Review; stale contexts withdraw layers and close prevents late publication.');
