import assert from 'node:assert/strict';import fs from 'node:fs';
import {renderGaussianEnvelopePitch} from '../editor/audio-native-gaussian.js';
import {referenceNotePitch} from '../editor/audio-note-pitch.js';
import {mountEnvelopeAudition} from '../editor/audio-envelope-audition.js';
assert.equal(referenceNotePitch(60,60,0,44100).pitchRegister,4096);assert.equal(referenceNotePitch(60,60,0,22050).pitchRegister,2048);assert.equal(referenceNotePitch(72,60,0,22050).pitchRegister,4096);assert.equal(referenceNotePitch(48,60,0,22050).pitchRegister,1024);assert.equal(referenceNotePitch(60,60,100,44100).pitchRegister,3866);assert.equal(referenceNotePitch(60,60,156,44100).pitchRegister,4340);assert.equal(referenceNotePitch(60,60,255,44100).fineCents,-1);const capped=referenceNotePitch(127,0,0,44100);assert.equal(capped.pitchRegister,16384);assert.equal(capped.renderable,false);assert(capped.clamped);assert.equal(referenceNotePitch(0,255,127,11025).pitchRegister,1);
for(const args of [[true,60,0,44100],[60,256,0,44100],[60,60,-1,44100],[60,60,256,44100],[128,60,0,44100],[60,60,0,22051],[60,60,0,null]])assert.throws(()=>referenceNotePitch(...args));
const f=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),g=f.groups.loop;
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.value='';this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(k,v){this.attrs[k]=v;}}
globalThis.document={createElement:tag=>new Element(tag)};const nodes=n=>[n,...n.children.flatMap(nodes)],control=(root,label)=>nodes(root).find(n=>n.attrs['aria-label']===label),button=(root,label)=>nodes(root).find(n=>n.tag==='button'&&n.textContent===label);
let live=true,stops=0,played;const request=async(path,init)=>{const body=JSON.parse(init.body),value=path==='/api/audio-sample-authoring'?g.options:path==='/api/audio-sample-adpcm'?g.adpcm[body.layer]:g.pcm[body.layer];return {ok:true,text:async()=>JSON.stringify(value)};};const audioContext=()=>({destination:{},resume:async()=>{},close:async()=>{},createGain:()=>({gain:{value:0},connect(){},disconnect(){}}),createBuffer(c,count){played=new Float32Array(count);return {getChannelData:()=>played};},createBufferSource:()=>({connect(){},disconnect(){},start(){},stop(){stops++;}})});
const host=new Element('section'),errors=[],view=mountEnvelopeAudition(host,{bank:g.bank,request,audioContext,fresh:()=>live,onError:e=>errors.push(e.message)}),config=structuredClone(g.config);config.layers=config.layers.map((r,i)=>({...r,center:60,shift:i===0?0:100}));view.update(config);const mode=control(host,'Envelope sample playback'),filter=control(host,'Envelope native interpolation'),pitch=control(host,'Envelope pitch source'),note=control(host,'Envelope reference note key'),rate=control(host,'Envelope sample rate'),layer=control(host,'Envelope audition layer'),load=button(host,'Load envelope sample'),play=button(host,'Play envelope audition'),save=button(host,'Save envelope preview WAV');
await load.onclick();mode.value='native-loop';mode.onchange();await load.onclick();filter.value='gaussian';filter.onchange();pitch.value='note';pitch.onchange();assert(play.disabled);rate.value='22050';rate.onchange();assert(play.disabled);note.value='60';note.oninput();assert(!play.disabled&&!rate.disabled);assert(nodes(host).some(n=>n.textContent.includes('pitch register 2048')));await play.onclick();const expected=renderGaussianEnvelopePitch(Uint8Array.from(Buffer.from(g.adpcm.retail.adpcm_base64,'base64')),2048,config.layers[0].adsr1,config.layers[0].adsr2,{keyOffFrame:22050}).bytes,expectedView=new DataView(expected.buffer);for(let i=0;i<played.length;i++)assert.equal(played[i],expectedView.getInt16(i*2,true)/32768);note.value='72';note.oninput();assert.equal(stops,1);assert(nodes(host).some(n=>n.textContent.includes('pitch register 4096')));for(const v of ['','128','-1','1.5']){note.value=v;note.oninput();assert(play.disabled&&save.disabled);}note.value='127';note.oninput();assert(play.disabled&&save.disabled);assert(nodes(host).some(n=>n.textContent.includes('Reference step0x4000')));note.value='60';note.oninput();layer.value='Current';layer.onchange();await load.onclick();mode.value='native-loop';mode.onchange();await load.onclick();filter.value='gaussian';filter.onchange();pitch.value='note';pitch.onchange();assert(nodes(host).some(n=>n.textContent.includes('pitch register 1933')));assert(!play.disabled);await play.onclick();filter.value='linear';filter.onchange();assert.equal(stops,2);assert.equal(pitch.value,'rate');assert(note.disabled);view.clear();view.update(config);assert.equal(note.value,'');assert.equal(pitch.value,'rate');view.update({...config,referenceNote:{key:61,note_index:2,channel:0}});assert.equal(layer.value,'Current');assert.equal(note.value,'61');assert.equal(rate.value,'');assert(nodes(host).some(n=>n.textContent.includes('encoded Current note event 2 / channel 0 / key 61')));live=false;note.oninput();assert(host.hidden&&play.disabled);assert.deepEqual(errors,[]);
console.log('Reference note model: literal octave/fine-sign/rate/cap cases, strict inputs, native sample gate, source-layer tuning, explicit key/rate, playback stop, reset and stale withdrawal passed');
