import assert from 'node:assert/strict';
import {decodePresetBatchScene} from '../editor/preset-batch.js';
const row=id=>({entity_id:id,asset_id:'old',source_actor_id:id,appearance_authored:false,renderable:true,geometry_key:'old',position:{x:128,y:null,z:256},preview_position:{x:128,y:32,z:256},preview_ground_sample:{y:32,cell_index:0},display_position:{x:128,y:-32,z:256},preview_height_status:'source_surface',model_to_scene:[1,0,0,128,0,-1,0,-32,0,0,1,256,0,0,0,1],authored_position:{},evidence:{position:'imported placement plus authored overrides',height:'source terrain',heading:'unknown',scale:'unknown'}});
const current={schema:'legaia.scene-preview.v1',scene_id:'scene',source_key:'source',coordinate_system:'source',position_to_display:[1],entities:['a','b','c'].map(row),assets:[{geometry_key:'old',asset_id:'old',preview:{vertices:[[1,2,3]]}}]};
const report={scene_id:'scene',scope:'authored-actor-preset-v1',review_key:'review',targets:['a','b'].map(entity_id=>({entity_id,proposed_position:{x:512,y:null,z:256},proposed_donor:'donor',after:{Transform:{position:{x:512}}},appearance:{donor_entity_id:'donor',asset_id:'new'}}))};
const scene=structuredClone(current);scene.representation='authored';scene.source_key='proposal';scene.assets.push({geometry_key:'new',asset_id:'new',preview:{vertices:[[4,5,6]]}});
for(const target of scene.entities.slice(0,2))Object.assign(target,{asset_id:'new',source_actor_id:'donor',appearance_authored:true,geometry_key:'new',position:{x:512,y:null,z:256},preview_position:{x:512,y:64,z:256},preview_ground_sample:{y:64,cell_index:1},display_position:{x:512,y:-64,z:256},model_to_scene:[1,0,0,512,0,-1,0,-64,0,0,1,256,0,0,0,1],authored_position:{x:512}});
const response={schema_version:'legaia.actor-preset-batch-scene.v1',scene_id:'scene',project_source_key:'source',review_key:'review',scene},before=structuredClone(response);const decoded=decodePresetBatchScene(response,report,current);decoded.entities[0].position.x=0;assert.deepEqual(response,before);
for(const mutate of [r=>r.review_key='stale',r=>r.project_source_key='stale',r=>r.scene.entities[1].position.y=0,r=>r.scene.entities[1].model_to_scene[3]=0,r=>r.scene.entities[0].authored_position.x=0,r=>r.scene.entities[1].preview_ground_sample.y=1,r=>r.scene.entities[1].source_actor_id='wrong',r=>r.scene.entities[2].position.x=0,r=>r.scene.assets[0].preview.vertices[0][0]=99,r=>r.scene.entities.push(structuredClone(r.scene.entities[0]))]){const bad=structuredClone(response);mutate(bad);assert.throws(()=>decodePresetBatchScene(bad,report,current));}
const position=structuredClone(report);position.scope='authored-position-v1';const positionScene=structuredClone(response);positionScene.scene.assets=structuredClone(current.assets);for(const target of positionScene.scene.entities.slice(0,2)){target.asset_id='old';target.source_actor_id=target.entity_id;target.appearance_authored=false;target.geometry_key='old';}decodePresetBatchScene(positionScene,position,current);positionScene.scene.assets[0].preview.vertices[0][0]=99;assert.throws(()=>decodePresetBatchScene(positionScene,position,current));
console.log('Group preset scene detached position+appearance, owner/geometry/matrix/source/unknown-Y guards and position-only preservation passed.');
