import assert from 'node:assert/strict';import {parseHierarchyQuery,hierarchyMatches,matchingActorIds} from '../editor/hierarchy-query.js';import {parseAssetQuery} from '../editor/asset-search.js';
const actors=[{id:'scene://fixture/actors/man-p1/0001',name:'Actor One',type:'actor',components:['Transform','Position'],authored:'true',visibility:'hidden'},{id:'scene://fixture/actors/man-p1/0002',name:'Actor Two',type:'actor',components:[],authored:'false',visibility:'shown'}],environment={id:'environment://fixture/0001',name:'House',type:'environment',components:[],authored:'unknown',visibility:'shown'},before=structuredClone(actors);
assert(hierarchyMatches(actors[0],parseHierarchyQuery('type:actor component:transform authored:true visibility:hidden')));assert(!hierarchyMatches(environment,parseHierarchyQuery('authored:false')));assert(hierarchyMatches(environment,parseHierarchyQuery('authored:unknown')));assert.deepEqual(matchingActorIds([...actors,environment],parseHierarchyQuery('type:actor -authored:true')),[actors[1].id]);assert.deepEqual(matchingActorIds(actors,parseHierarchyQuery('name:"Actor One"')), [actors[0].id]);assert(hierarchyMatches(actors[0],parseHierarchyQuery('scene://fixture/actors')));assert(!hierarchyMatches(actors[0],parseHierarchyQuery('name:One -visibility:hidden')));assert.deepEqual(actors,before);
for(const query of ['bad:field','name:','"unterminated','-','x'.repeat(2049),Array(33).fill('a').join(' ')])assert.throws(()=>parseHierarchyQuery(query));assert.throws(()=>parseAssetQuery('component:transform'));assert.throws(()=>parseAssetQuery('name:a',[]));assert.throws(()=>matchingActorIds(Array.from({length:129},(_,i)=>({...actors[0],id:'actor'+i})),[]));assert.deepEqual(matchingActorIds([actors[0],actors[0]],[]),[actors[0].id]);console.log('Hierarchy typed/layered metadata queries, exclusions, phrases, URI terms, unknown authorship, unchanged asset grammar and bounded actor matches passed.');

const {hierarchyAttachedComponents}=await import('../editor/hierarchy-query.js');
const source={Transform:{imported:{position:{x:64,z:128}}},ModelRenderer:{asset_id:'asset://fixture/model'},RetailMetadata:{confidence:'unknown'},Unregistered:{}},schema={components:{Transform:{label:'Position'},ModelRenderer:{label:'Model Renderer'},RetailMetadata:{label:'Retail Evidence'}}},sourceBefore=structuredClone(source);
const unchanged={...actors[1],attached:hierarchyAttachedComponents(source,schema)},changed={...actors[0],attached:hierarchyAttachedComponents(source,schema)};
assert(hierarchyMatches(unchanged,parseHierarchyQuery('type:actor attached:Transform authored:false')));assert(hierarchyMatches(unchanged,parseHierarchyQuery('attached:"Model Renderer"')));assert(hierarchyMatches(unchanged,parseHierarchyQuery('attached:Unregistered')));assert(!hierarchyMatches(unchanged,parseHierarchyQuery('component:Transform')));assert(hierarchyMatches(changed,parseHierarchyQuery('attached:ModelRenderer component:Transform authored:true')));assert(!hierarchyMatches(unchanged,parseHierarchyQuery('-attached:Transform')));assert.deepEqual(matchingActorIds([unchanged,changed,environment],parseHierarchyQuery('attached:ModelRenderer -authored:true')),[unchanged.id]);assert.deepEqual(source,sourceBefore);
const terms=hierarchyAttachedComponents(source,schema);terms.length=0;assert(hierarchyAttachedComponents(source,schema).length);for(const invalid of [null,undefined,[],false])assert.deepEqual(hierarchyAttachedComponents(invalid,schema),[]);assert.deepEqual(hierarchyAttachedComponents({Mystery:{}},{components:{Mystery:{label:{invented:true}}}}),['Mystery']);assert.throws(()=>parseAssetQuery('attached:Transform'));
console.log('Attached SDK component IDs and metadata labels find unchanged actors while authored-component search and bounded group matching remain separate.');
