import assert from 'node:assert/strict';
import {renderComponentProperties,navigableComponentReference} from '../editor/component-inspector.js';
import {resolveComponentReference,bindComponentReferences} from '../editor/component-references.js';
const id='asset://fixture/models/1',actor='actor://fixture/1';
const schema={schema_version:'legaia.inspector-schema.v1',live_writes:false,components:{Reference:{layout:'layered-properties',layers:[{id:'imported',label:'Imported'},{id:'effective',label:'Effective'}],properties:[{id:'asset',label:'Model',path:['asset'],type:'asset-reference',layers:['imported','effective']}]}}};
const component={imported:{asset:id},effective:{asset:'asset://fixture/models/2'}};
const html=renderComponentProperties(schema,'Reference',component,false,true);
assert(html.includes(`data-component-reference="${id}"`));assert(html.includes('Inspect Imported Model reference:'));assert(html.includes('Inspect Effective Model reference:'));
assert(!renderComponentProperties(schema,'Reference',component).includes('<button'));
const excluded=renderComponentProperties(schema,'Reference',component,false,true,[id]);assert(!excluded.includes(`data-component-reference="${id}"`));assert(excluded.includes(`<code>${id}</code>`));assert(excluded.includes('data-component-reference="asset://fixture/models/2"'));
for(const exclusions of [null,[id,id],['C:/private/file'],Array.from({length:33},(_,i)=>'asset://fixture/'+i)])assert.throws(()=>renderComponentProperties(schema,'Reference',component,false,true,exclusions));
for(const value of ['javascript:alert(1)','C:/private/file',0,null,'asset://fixture/<script>','asset://fixture/"bad','asset://fixture/white space'])assert(!navigableComponentReference(value,'asset-reference'));
assert(!navigableComponentReference(id,'string'));
const model={id,type:'model'},entity={id:actor,type:'actor'};
assert.equal(resolveComponentReference([model,entity],id,'asset-reference'),model);
assert.equal(resolveComponentReference([model],id,'entity-reference'),null);
assert.throws(()=>resolveComponentReference([model,model],id,'asset-reference'));
let valid=true,isBusy=false,calls=0,discoveries=0,rows=[],release,errors=[];
const button={dataset:{componentReference:id,referenceType:'asset-reference'},disabled:false};
bindComponentReferences({querySelectorAll:()=>[button]},{current:()=>valid,busy:()=>isBusy,records:()=>rows,discover:async()=>{discoveries++;await new Promise(resolve=>release=resolve);rows=[model];},open:record=>{assert.equal(record,model);calls++;},onError:error=>errors.push(error.message)});
const pending=button.onclick();await button.onclick();assert.equal(discoveries,1);assert(button.disabled);release();await pending;assert.equal(calls,1);assert(!button.disabled);
isBusy=true;await button.onclick();assert.equal(calls,1);isBusy=false;valid=false;await button.onclick();assert.equal(calls,1);valid=true;
rows=[];const stale=button.onclick();valid=false;release();await stale;assert.equal(calls,1);assert.deepEqual(errors,[]);
valid=true;rows=[model,model];await button.onclick();assert.equal(calls,1);assert.equal(errors.length,1);
console.log('Layer-qualified reference buttons, exact catalog resolution, invalid/ambiguous IDs and pending/busy/stale navigation passed.');
