import assert from 'node:assert/strict';
import {sceneGroundPositionCommand,decodeGroundPositionPreview} from '../editor/scene-ground-position.js';
const position={x:128,z:256};const actor=sceneGroundPositionCommand('actor','scene://fixture/actors/0001',position),npc=sceneGroundPositionCommand('npc','authored-actor://fixture',position);assert.equal(actor.type,'set_transform');assert.equal(npc.type,'set_actor_draft_position');assert.deepEqual(actor.position,position);actor.position.x=999;assert.equal(position.x,128);assert.deepEqual(Object.keys(npc.position),['x','z']);
for(const bad of [{x:65,z:256},{x:0,z:256},{x:16448,z:256},{x:128,z:256,y:0},{x:NaN,z:256},null])assert.throws(()=>sceneGroundPositionCommand('actor','id',bad));assert.throws(()=>sceneGroundPositionCommand('scenery','id',position));
console.log('Actor/NPC picked positions use detached X/Z-only existing Project commands and reject unsupported axes/grid.');

const context={id:'actor',scene:'scene',source:'a'.repeat(64),preview:'b'.repeat(64),position:{x:64,y:512,z:128}},before={entity_id:'actor',renderable:true,position:context.position,display_position:{x:64,y:-512,z:128}},after={...before,position:{x:128,y:512,z:256},display_position:{x:128,y:-512,z:256}};
const review={schema_version:'legaia.actor-position-review.v1',entity_id:'actor',kind:'actor',scene_id:'scene',project_source_key:context.source,scene_preview_source_key:context.preview,current_position:context.position,proposed_position:after.position,command:sceneGroundPositionCommand('actor','actor',position),project_changed:false,gameplay_verified:false,height_authoring:'preserved_existing_or_unknown',review_key:'c'.repeat(64)};
const value={schema_version:'legaia.actor-position-scene.v1',review,current_instance:before,proposed_instance:after,geometry_unchanged:true,unrelated_instances_unchanged:true,project_changed:false,gameplay_verified:false};
const decoded=decodeGroundPositionPreview(value,context,'actor',position,before);decoded.proposed_instance.display_position.x=999;assert.equal(value.proposed_instance.display_position.x,128);
for(const change of [v=>v.review.proposed_position.y=0,v=>v.review.project_source_key='stale',v=>v.unrelated_instances_unchanged=false,v=>v.current_instance.display_position.y=0,v=>v.proposed_instance.display_position.y=null,v=>v.proposed_instance.entity_id='other',v=>v.gameplay_verified=true]){const bad=structuredClone(value);change(bad);assert.throws(()=>decodeGroundPositionPreview(bad,context,'actor',position,before));}
const reordered=structuredClone(value);reordered.review.command={position:{z:256,x:128},entity_id:'actor',type:'set_transform'};assert.doesNotThrow(()=>decodeGroundPositionPreview(reordered,context,'actor',position,before));
console.log('Reviewed position preview checks source/target/XZ/preserved Y, displayed current instance, immutable flags and finite proposed display coordinates.');
