import assert from 'node:assert/strict';
import {decodeNpcTransitionsSource,decodeNpcTransitionsReview} from '../editor/npc-transitions.js';
import {npcCurrentTransitionSelection} from '../editor/npc-current-script.js';
const id='authored-actor://fixture',owner='scene://fixture/actors/man-p1/0001',key='a'.repeat(64),target='script://fixture/actors/man-p1/0001/transition/0005',draft={scene_id:'scene://fixture',donor_entity_id:owner},state={scene:{id:draft.scene_id},project:{mode:'edit'},project_copy_source_key:key,actor_drafts:{[id]:draft},capabilities:{npc_transition_authoring:true}};
const row={owner_id:owner,pc:5,semantic_id:target,destination:'town01',record_byte_offset:100,decoded_byte_offset:115,instruction_length:13,mnemonic:'SCENE_CHANGE',target_context:null,raw_instruction_hex:'3f000006746f776e3031010203',values:{entry_x_encoded:1,entry_z_encoded:2,direction_encoded:3},authored_values:null,effective_values:{entry_x_encoded:1,entry_z_encoded:2,direction_encoded:3},source_record_sha256:'b'.repeat(64)};
const source={schema_version:'legaia.npc-transitions-source.v1',entity_id:id,scene_id:draft.scene_id,project_source_key:key,draft,options:{transitions:[row],supported:true},gameplay_verified:false,transition_activation:'not_asserted',destination_name_changed:false};
// Header1 + fixed3 + name6 + arrival3 =13; operand begins at100+5+10.
assert.deepEqual(decodeNpcTransitionsSource(source,id,state),source);
for(const mutate of [v=>v.options.transitions[0].destination='town02',v=>v.options.transitions[0].decoded_byte_offset++,v=>v.options.transitions[0].values.direction_encoded=4,v=>v.options.transitions[0].target_context=7,v=>v.options.transitions.push(v.options.transitions[0]),v=>v.gameplay_verified=true]){const bad=structuredClone(source);mutate(bad);assert.throws(()=>decodeNpcTransitionsSource(bad,id,state));}
const request={entity_id:id,entries:{[target]:{direction_encoded:7}}},review={schema_version:'legaia.npc-transitions-review.v1',entity_id:id,project_source_key:key,request,current:draft,proposed:{...draft,transitions:{donor_entity_id:owner,entries:request.entries}},review_key:key,gameplay_verified:false,transition_activation:'not_asserted',destination_name_changed:false,changes:[{transition_id:target,owner_id:owner,pc:5,field:'direction_encoded',decoded_byte_offset:117,record_relative_byte_offset:17,source_record_sha256:row.source_record_sha256,source_decoded_man_sha256:key,before_byte:3,after_byte:7}]};assert.deepEqual(decodeNpcTransitionsReview(review,request,source,state),review);
for(const mutate of [v=>v.changes[0].after_byte=8,v=>v.changes[0].record_relative_byte_offset++,v=>v.changes[0].field='destination',v=>v.proposed.name='invented',v=>v.changes.push(v.changes[0])]){const bad=structuredClone(review);mutate(bad);assert.throws(()=>decodeNpcTransitionsReview(bad,request,source,state));}
const raw='0000000000'+row.raw_instruction_hex,node={pc:5,mnemonic:'SCENE_CHANGE',length:13,target_context:null,raw_hex:row.raw_instruction_hex,operands:{scene_name_ascii:'town01'}},current={schema_version:'legaia.npc-current-script.v1',representation:'npc_authored_script_source',generated_code:false,gameplay_verified:false,runtime_binding:'not_asserted',entity_id:id,project_source_key:key,draft,inspection:{instructions:[node],record:{raw_hex:raw}},donor:{inspection:{instructions:[node],record:{sha256:row.source_record_sha256,byte_offset:100}}}};
assert.equal(npcCurrentTransitionSelection(current,source,5,state).pc,5);
for(const mutate of [v=>v.inspection.instructions[0].target_context=7,v=>v.inspection.instructions[0].raw_hex='00',v=>v.inspection.record.raw_hex='00',v=>v.draft.name='changed']){const bad=structuredClone(current);mutate(bad);assert.throws(()=>npcCurrentTransitionSelection(bad,source,5,state));}
const live=structuredClone(state);live.project.mode='live';assert.throws(()=>npcCurrentTransitionSelection(current,source,5,live));
console.log('Native named arrival source, per-byte Review, selected Current ownership/full-record agreement, forgery and Live refusal passed.');
