import assert from 'node:assert/strict';
import {decodeTriggerScriptsReview,triggerScriptEditable} from '../editor/trigger-scripts.js';
const id='trigger://fixture/field-map/primary/kind-1/0000',target='script://fixture/scripts/man-p2/0002',imported='script://fixture/scripts/man-p2/0000',disc={sha256:'d'.repeat(64),serial:'SCUS-94254'};
const record={id,type:'trigger',sceneId:'scene://fixture',data:{table_source:'primary',table_kind:1,record_index:0,encoded:{tile_x:2,tile_z:3,record_index:0,gate:1},source_record:{byte_offset:65554,sha256:'f'.repeat(64),disc}}};
const state={project:{mode:'edit'},scene:{id:'scene://fixture'},project_copy_source_key:'c'.repeat(64)};
const source={trigger_id:id,table_kind:1,record_index:0,byte_offset:65554,byte_length:4,sha256:'f'.repeat(64),encoded:structuredClone(record.data.encoded),tile_bounds:{x_min:2,x_max:3,z_min:3,z_max:4}};
const report={schema_version:'legaia.trigger-scripts-review.v1',read_only:true,project_source_key:state.project_copy_source_key,scene_id:state.scene.id,trigger_id:id,source,map_sha256:'e'.repeat(64),targets:[{script_id:target,source_sha256:'a'.repeat(64),record_index:2,source_record:{sha256:'a'.repeat(64),record_index:2,partition:2,record_alias_count:1,byte_offset:40,byte_length:16,byte_coordinate_space:'decoded_lzs_descriptor',disc,iso_file:'PROT.DAT'},inspection_status:'partial'}],layers:{imported,authored:null,current:imported,proposed:target},requested_script_id:target,action:'set',value:{source_sha256:'e'.repeat(64),edits:[{trigger_id:id,script_id:target,script_sha256:'a'.repeat(64)}]},audit:[{trigger_id:id,target_script_id:target,target_script_sha256:'a'.repeat(64),table_kind:1,record_index:0,field:'trigger.record_index',byte_offset:65556,before_value:0,after_value:2,scope:'source-MAP-trigger-P2-binding-only'}],proposed_map_sha256:'d'.repeat(64),project_change:true,activation:'not_evaluated',gameplay_verified:false,review_key:'b'.repeat(64)};
const before=JSON.stringify(report),decoded=decodeTriggerScriptsReview(report,record,state);assert.deepEqual(decoded,report);decoded.targets[0].source_record.byte_offset=100;assert.equal(JSON.stringify(report),before);assert(triggerScriptEditable(record));
for(const mutate of [r=>r.project_source_key='0'.repeat(64),r=>r.source.encoded.gate=0,r=>r.targets[0].source_record.record_alias_count=2,r=>r.targets[0].source_record.disc.sha256='0'.repeat(64),r=>r.targets[0].script_id='script://other/scripts/man-p2/0002',r=>r.targets.push(r.targets[0]),r=>r.layers.current=target,r=>r.layers.proposed=imported,r=>r.value.edits[0].trigger_id=id+'/0001',r=>r.value.edits[0].script_sha256='0'.repeat(64),r=>r.audit[0].byte_offset++,r=>r.audit=[],r=>r.audit[0].after_value=3,r=>r.activation='verified',r=>r.gameplay_verified=true,r=>r.unknown=true]){const value=JSON.parse(before);mutate(value);assert.throws(()=>decodeTriggerScriptsReview(value,record,state));}
for(const mutate of [r=>r.data.encoded.gate=0,r=>r.data.table_source='fallback',r=>r.type='actor']){const value=structuredClone(record);mutate(value);assert.equal(triggerScriptEditable(value),false);assert.throws(()=>decodeTriggerScriptsReview(report,value,state));}
assert.throws(()=>decodeTriggerScriptsReview(report,record,{...state,project:{mode:'live'}}));
console.log('Trigger script report qualification preserves source data and rejects stale, aliased, cross-scene, malformed and false-runtime claims.');
