import assert from 'node:assert/strict';
import {worldPlacementRecordRows} from '../editor/worldmap-placement-state.js';
import {worldmapHierarchyRows} from '../editor/worldmap-scene.js';
const id=n=>'scene://map02/worldmap/placements/'+n.toString(16).padStart(4,'0');
const entities=[{entity_id:id(1),asset_id:'model://one',placement_scope:'source_instance',object_record_index:461,model_pool_index:7,source_cell:1,source_position:{x:10,y:20,z:30},authored_source_position:{x:74,y:-80,z:94}},{entity_id:id(2),asset_id:'model://one',placement_scope:'source_instance',object_record_index:461,model_pool_index:7,source_cell:2,source_position:{x:20,y:20,z:30},authored_source_position:{x:84,y:-80,z:94}},{entity_id:id(3),asset_id:'model://two',placement_scope:'source_instance',object_record_index:3,model_pool_index:8,source_cell:3,source_position:{x:0,y:0,z:0}}],report={records:[{record_id:'0461',source_cell_count:2,writable:true,authored_values:{},placements:entities.slice(0,2)},{record_id:'0003',source_cell_count:4,writable:false,authored_values:null,placements:[entities[2]]}]};const scene={entities};
const original=structuredClone({report,scene});assert.equal(worldmapHierarchyRows({entities:[{entity_id:'scene://map02/worldmap/ground',asset_id:'ground',placement_scope:'source_ground',source_position:{x:0,y:0,z:0}}]},'0000').matching,0);
for(const q of ['0461','record:461','model:7','cell:2','x:84 y:-80 z:94']){const found=worldPlacementRecordRows(report,scene,q,'all','0003');assert.equal(found.matching,1);assert.equal(found.rows[0].recordId,'0461');assert.equal(found.rows[1].matches,false);assert.equal(found.selectedOutsideFilter,true);}
for(const scope of ['authored','writable'])assert.equal(worldPlacementRecordRows(report,scene,'',scope).matching,1);assert.equal(worldPlacementRecordRows(report,scene,'','shared').matching,2);assert.equal(worldPlacementRecordRows(report,scene,'','unavailable').rows[0].recordId,'0003');
assert.equal(worldPlacementRecordRows(report,scene,'not-present','all','0461').matching,0);assert.equal(worldPlacementRecordRows(report,scene,'x:20','all').matching,0);assert.equal(worldmapHierarchyRows(scene,'x:84',id(1)).rows.length,2);assert.equal(worldmapHierarchyRows(scene,'x:84',id(1)).selectedOutsideFilter,true);
const reflected={entities:[{...entities[2],displayed_source_position:{x:40,y:-16,z:80}}]};assert.equal(worldmapHierarchyRows(reflected,'y:-16').matching,1);assert.equal(worldmapHierarchyRows(reflected,'y:16').matching,0);
for(const q of ['x:','x:1.5','y:NaN','z:131073','x:-131073','record:-1','a '.repeat(17),'a'.repeat(513)])assert.throws(()=>worldPlacementRecordRows(report,scene,q));for(const args of [[report,scene,'','bad'],[report,scene,'','all','foreign'],[{records:[...report.records,...report.records]},scene]])assert.throws(()=>worldPlacementRecordRows(...args));
assert.deepEqual({report,scene},original);console.log('Record/member search qualifies native displayed coordinates, bounded exact fields, all record scopes and retained selections without input mutation.');
