import assert from 'node:assert/strict';
import {CONTROLLER_BUILD_TARGETS} from '../editor/controller-build-navigation.js';
import {controllerOperandSource,decodeControllerOperandFile,decodeControllerOperandReview,mountControllerOperandFiles} from '../editor/controller-operand-files.js';
const owner='scene://fixture/controllers/man-p1/0000',hash='a'.repeat(64),other='b'.repeat(64),families={};
for(const [family,kind] of Object.values(CONTROLLER_BUILD_TARGETS))families[family]={owner_id:owner,state_key:hash,source_record_sha256:hash,current_record_sha256:hash,targets:[{semantic_id:owner.replace('scene://','script://')+'/'+kind+'/0005',values:{value:0},authored_values:null}]};
const source=controllerOperandSource(families,owner,hash);
assert.throws(()=>controllerOperandSource({},owner,hash));assert.throws(()=>controllerOperandSource(families,'foreign',hash));
function fixture(family='ControllerPartySelectors'){
 const id=families[family].targets[0].semantic_id,value={value:1},file={schema_version:'legaia.controller-operand-file.v1',scene_id:'scene://fixture',owner_id:owner,source_import_sha256:hash,source_record_sha256:hash,components:{[family]:{entries:{[id]:value}}}};
 const report={schema_version:'legaia.controller-operand-review.v1',owner_id:owner,scene_id:'scene://fixture',state_key:hash,source_import_sha256:hash,source_record_sha256:hash,current_record_sha256:hash,proposed_record_sha256:other,before:null,after:{[family]:{source_record_sha256:hash,entries:{[id]:value}}},entries:[{component:family,operand_id:id,before:null,after:value,changed:true}],change_count:1,changed_decoded_byte_offsets:[105],native_bytes_changed:true,no_op:false,review_key:other,project_changed:false,gameplay_verified:false};return {file,report,id};
}
for(const family of Object.keys(families)){
 const {file,report,id}=fixture(family);assert.equal(decodeControllerOperandFile(file,source).owner_id,owner);const result=decodeControllerOperandReview(report,file,source);result.after[family].entries[id].value=9;assert.equal(report.after[family].entries[id].value,1);
 for(const change of [{state_key:other},{owner_id:'foreign'},{source_record_sha256:other},{source_import_sha256:other},{before:{}},{after:null},{entries:[]},{change_count:2},{no_op:true},{project_changed:true},{gameplay_verified:true},{native_bytes_changed:false},{changed_decoded_byte_offsets:[105,105]},{review_key:null}])assert.throws(()=>decodeControllerOperandReview({...report,...change},file,source));
 for(const change of [{extra:true},{components:{Unknown:{entries:{}}}},{owner_id:'foreign'},{source_record_sha256:other},{components:{[family]:{entries:{foreign:{}}}}}])assert.throws(()=>decodeControllerOperandFile({...file,...change},source));
}
const clear=fixture(),clearFamilies=structuredClone(families);clearFamilies.ControllerPartySelectors.targets[0].authored_values={value:1};for(const snapshot of Object.values(clearFamilies))snapshot.current_record_sha256=other;
const clearSource=controllerOperandSource(clearFamilies,owner,hash);clear.file.components.ControllerPartySelectors.entries[clear.id]=null;
const clearReport={...clear.report,before:clearSource.before,after:null,current_record_sha256:other,proposed_record_sha256:hash,entries:[{component:'ControllerPartySelectors',operand_id:clear.id,before:{value:1},after:null,changed:true}]};assert.equal(decodeControllerOperandReview(clearReport,clear.file,clearSource).change_count,1);
clear.file.components.ControllerPartySelectors.entries[clear.id]={value:0};assert.equal(decodeControllerOperandReview(clearReport,clear.file,clearSource).after,null);
const noop=fixture();noop.file.components.ControllerPartySelectors.entries[noop.id]=null;const noopReport={...noop.report,after:null,entries:[{component:'ControllerPartySelectors',operand_id:noop.id,before:null,after:null,changed:false}],change_count:0,no_op:true,native_bytes_changed:false,changed_decoded_byte_offsets:[],proposed_record_sha256:hash};assert.equal(decodeControllerOperandReview(noopReport,noop.file,source).no_op,true);
class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.files=[];}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}setAttribute(name,value){this[name]=value;}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}click(){}}
globalThis.document={createElement:tag=>new Node(tag)};let key=hash,busy=false,replies=[],commands=[],reopened=0;globalThis.fetch=async()=>({ok:true,json:async()=>await replies.shift()});
const tree=n=>[n,...n.children.flatMap(tree)],button=(host,name)=>tree(host).find(n=>n.tag==='button'&&n.textContent===name),input=host=>tree(host).find(n=>n.tag==='input');
function mount(api=async(route,command)=>{assert.equal(busy,false);commands.push(command);return true;}){key=hash;const host=new Node('host'),controls=mountControllerOperandFiles(host,{families,owner,getKey:()=>key,current:()=>true,busy:()=>busy,setBusy:v=>busy=v,api,reopen:()=>reopened++});return {host,controls};}
const {file,report}=fixture();const selected={size:1024,text:async()=>JSON.stringify(file)};
let {host,controls}=mount();input(host).files=[selected];input(host).onchange();replies=[report];await button(host,'Review Controller Operand File').onclick();assert.equal(commands.length,0);assert(!button(host,'Apply Reviewed Controller Operands').disabled);input(host).onchange();assert(button(host,'Apply Reviewed Controller Operands').disabled);replies=[report];await button(host,'Review Controller Operand File').onclick();button(host,'Discard Controller File Proposal').onclick();assert(button(host,'Apply Reviewed Controller Operands').disabled);replies=[report];await button(host,'Review Controller Operand File').onclick();await button(host,'Apply Reviewed Controller Operands').onclick();assert.equal(commands[0].type,'import_controller_operand_file');assert.equal(commands[0].entity_id,owner);assert.equal(reopened,1);controls.dispose();
({host,controls}=mount(async()=>false));input(host).files=[selected];replies=[report];await button(host,'Review Controller Operand File').onclick();await button(host,'Apply Reviewed Controller Operands').onclick();assert(button(host,'Apply Reviewed Controller Operands').disabled);controls.dispose();
({host,controls}=mount());input(host).files=[{...selected,size:65537}];input(host).onchange();assert(button(host,'Review Controller Operand File').disabled);input(host).files=[selected];let resolve;replies=[new Promise(r=>resolve=r)];const pending=button(host,'Review Controller Operand File').onclick();await Promise.resolve();await Promise.resolve();key=other;controls.updateState();resolve(report);await pending;assert(button(host,'Apply Reviewed Controller Operands').disabled);assert.equal(busy,false);controls.dispose();
console.log('Eleven-family file/Review binding, exact proposals, detached state, file changes, discard, Apply locking, failed Apply, limits and stale replies passed.');
