import assert from 'node:assert/strict';
import {decodeControllerTileSnapshot,decodeControllerTileReview,mountControllerTileRects} from '../editor/controller-tile-rects.js';
const owner='scene://fixture/controllers/man-p1/0000',id='script://fixture/controllers/man-p1/0000/tile-rect/0005',context={projectPath:'C:/private',sceneId:'scene://fixture',mode:'edit',scriptKey:'a'.repeat(64)};
const values=value=>({column_start:1,row_start:2,column_end:3,row_end:4,value});
const report=value=>({status:'decoded_supported_paths',instructions:[{pc:5,length:7,byte_offset:105,mnemonic:'FIELD_TILE_RECT_REQUEST',raw_hex:'4c8301020304'+value.toString(16).padStart(2,'0'),target_context:null,operands:values(value),successors:[{pc:12,condition:'encoded_continuation'}]},{pc:12,length:3,byte_offset:112,mnemonic:'JMP_REL',raw_hex:'26f8ff',target_context:null,operands:{},successors:[{pc:5,condition:'unconditional'}]}],dialogues:[],stops:[],opaque_regions:[],unvisited_instructions:[],unvisited_dialogues:[]});
const snapshot=()=>({schema_version:'legaia.controller-tile-rects.v1',owner_id:owner,state_key:context.scriptKey,source_record_sha256:'b'.repeat(64),current_record_sha256:'b'.repeat(64),source:{owner_id:owner,record_kind:'man_partition_1_scene_controller',runtime_execution:'not_asserted'},source_report:report(5),current_report:report(5),targets:[{semantic_id:id,owner_id:owner,pc:5,mnemonic:'FIELD_TILE_RECT_REQUEST',target_context:null,decoded_byte_offset:107,source_record_sha256:'b'.repeat(64),values:values(5),current_values:values(5),authored_values:null}],supported:true,reason:null,limitations:[],gameplay_verified:false});
const proposal=()=>({...snapshot(),operand_id:id,value:values(6),proposed_record_sha256:'c'.repeat(64),review_key:'d'.repeat(64),proposed_report:report(6),changed_decoded_byte_offsets:[111],no_op:false,native_bytes_changed:true,project_changed:false});
assert.equal(decodeControllerTileSnapshot(snapshot(),owner,context).targets.length,1);assert.equal(decodeControllerTileReview(proposal(),snapshot(),id,values(6)).operand_id,id);
for(const change of [r=>r.schema_version='actor',r=>r.state_key='f'.repeat(64),r=>r.gameplay_verified=true,r=>r.source.runtime_execution='observed',r=>r.targets.push(r.targets[0]),r=>r.targets[0].decoded_byte_offset++,r=>r.targets[0].current_values.value=7,r=>r.current_report.instructions[0].raw_hex='4c830102030405ff',r=>r.targets=[]]){const r=snapshot();change(r);assert.throws(()=>decodeControllerTileSnapshot(r,owner,context));}
for(const change of [r=>r.project_changed=true,r=>r.value.value=8,r=>r.changed_decoded_byte_offsets=[105],r=>r.changed_decoded_byte_offsets=[111,111],r=>r.proposed_report.instructions[1].raw_hex='26ffff',r=>r.proposed_report.instructions[0].successors[0].pc=13,r=>r.proposed_record_sha256=r.current_record_sha256,r=>r.proposed_report.instructions[0].operands.value=7]){const r=proposal();change(r);assert.throws(()=>decodeControllerTileReview(r,snapshot(),id,values(6)));}
const retained=snapshot();retained.current_report.unvisited_instructions=[retained.current_report.instructions.shift()];assert.equal(decodeControllerTileSnapshot(retained,owner,context).targets.length,1);
class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.value='';}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}setAttribute(name,value){this[name]=value;}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}}
globalThis.document={createElement:tag=>new Node(tag)};let queue=[],ctx=structuredClone(context),busy=false,commands=[],reopened=[];
globalThis.fetch=async()=>({ok:true,json:async()=>await queue.shift()});
const tree=n=>[n,...n.children.flatMap(tree)],button=(h,id)=>tree(h).find(n=>n.dataset.controllerTileAction===id),input=h=>tree(h).filter(n=>n.tag==='input').at(-1);
const settings={owner,getContext:()=>ctx,busy:()=>busy,setBusy:v=>busy=v,api:async(route,body)=>{assert.equal(busy,false);commands.push(body);return true;},reopen:pc=>reopened.push(pc)};
async function mount(extra={}){ctx=structuredClone(context);const host=new Node();queue=[snapshot()];const controls=mountControllerTileRects(host,{...settings,...extra});assert(await controls.ready);return {host,controls};}
let {host,controls}=await mount();input(host).value='6';input(host).oninput();queue=[proposal()];assert(await button(host,'review').onclick());assert.equal(commands.length,0);assert(!button(host,'apply').disabled);input(host).value='999';input(host).oninput();assert(button(host,'apply').disabled);assert(button(host,'review').disabled);
button(host,'discard').onclick();input(host).value='6';input(host).oninput();queue=[proposal()];await button(host,'review').onclick();assert(await button(host,'apply').onclick());assert.equal(commands[0].type,'set_controller_tile_rect');assert.deepEqual(commands[0].value,values(6));assert.deepEqual(reopened,[5]);controls.dispose();
({host,controls}=await mount({api:async()=>false}));input(host).value='6';input(host).oninput();queue=[proposal()];await button(host,'review').onclick();assert.equal(await button(host,'apply').onclick(),false);assert(button(host,'apply').disabled);controls.dispose();
({host,controls}=await mount());input(host).value='6';input(host).oninput();let resolve;queue=[new Promise(r=>resolve=r)];const late=button(host,'review').onclick();ctx.scriptKey='f'.repeat(64);controls.updateState();resolve(proposal());assert.equal(await late,false);assert(button(host,'apply').disabled);assert.equal(busy,false);controls.dispose();
console.log('Controller tile source/Review qualification, retained boundaries, bounded drafts, typed Apply, failed Apply withdrawal and stale-response rejection passed.');
