import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const preview=await fs.readFile(new URL('../editor/npc-creation-preview.js',import.meta.url),'utf8'),build=await fs.readFile(new URL('../editor/build-review.js',import.meta.url),'utf8'),source=await fs.readFile(new URL('../editor/npc-creation-build-review.js',import.meta.url),'utf8');
const {decodeNpcCreationBuildReview}=await import('data:text/javascript;base64,'+Buffer.from(source.replace("'/npc-creation-preview.js'",JSON.stringify('data:text/javascript;base64,'+Buffer.from(preview+'\n//# sourceURL=npc-creation-preview.js').toString('base64'))).replace("'/build-review.js'",JSON.stringify('data:text/javascript;base64,'+Buffer.from(build.replace("'./sdk-stability-sources.js'",JSON.stringify(new URL('../editor/sdk-stability-sources.js',import.meta.url).href))+'\n//# sourceURL=build-review.js').toString('base64')))+'\n//# sourceURL=npc-creation-build-review.js').toString('base64'));
const request={donor_entity_id:'donor',name:'Resident',position:{x:128,z:256},project_source_key:'a'.repeat(64)},context={scene_id:'scene',source_key:'b'.repeat(64),existing_npc_draft_count:1},review={schema_version:'legaia.npc-creation-review.v1',scene_id:'scene',project_source_key:request.project_source_key,scene_preview_source_key:context.source_key,identity_scope:'temporary_preview_only',preview_entity_id:'authored-actor://00000000-0000-0000-0000-000000000001',draft:{scene_id:'scene',donor_entity_id:'donor',name:'Resident',position:request.position},command:{type:'create_actor_draft',donor_entity_id:'donor',name:'Resident',position:request.position},project_changed:false,gameplay_verified:false,review_key:'c'.repeat(64)},key='d'.repeat(64);
const buildReview={schema_version:'legaia.build-review.v2',source_key:key,read_only:true,status:'blocked',normal_build_ready:false,blockers:[{kind:'serialization',owner_id:null,message:'Existing unsupported Y'}],excluded_npc_draft_count:0,included_npc_draft_count:2,assessment:null,assessment_scope:'all_supported_authored_content_including_source_qualified_npc_drafts',npc_build_scope:'qualified_man_source_candidates',npc_gameplay_verified:false,limitations:['No package written']};
const value={schema_version:'legaia.npc-creation-build-review.v1',review,prospective_build_source_key:key,build_review:buildReview,existing_npc_draft_count:1,proposed_npc_draft_count:2,read_only:true,project_changed:false,output_written:false,gameplay_verified:false,assessment_scope:'complete_supported_project_with_one_prospective_npc'};
const decoded=decodeNpcCreationBuildReview(value,request,context);decoded.review.draft.name='changed';assert.equal(review.draft.name,'Resident');
for(const change of [v=>v.proposed_npc_draft_count=1,v=>v.existing_npc_draft_count=0,v=>v.review.draft.position.x=129,v=>v.build_review.source_key='e'.repeat(64),v=>v.build_review.included_npc_draft_count=1,v=>v.output_written=true,v=>v.gameplay_verified=true]){const bad=structuredClone(value);change(bad);assert.throws(()=>decodeNpcCreationBuildReview(bad,request,context));}
console.log('Prospective NPC Build review binds donor/name/XZ/source and complete candidate count, reuses normal Build validation, rejects output/gameplay claims and remains detached.');
