import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const code=await readFile(new URL('../editor/asset-references.js',import.meta.url),'utf8');
const {decodeAssetReferences}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const hash='a'.repeat(64),root='scene://fixture',actor=root+'/actors/0001';
const value={schema_version:'legaia.asset-references.v1',asset_id:root,source_key:hash,read_only:true,nodes:[{id:root,kind:'scene',scene_id:root,label:'Fixture',available:true},{id:actor,kind:'actor',scene_id:root,label:'Actor 0001',available:true}],incoming:[],outgoing:[{id:'b'.repeat(64),source_id:root,target_id:actor,kind:'scene_actor',scene_id:root,layer:'imported',runtime_binding:'not_asserted',source_import_sha256:hash}],coverage:{verified_scene_ids:[root],resource_scene_id:root,unresolved_reference_count:1},limitations:['Recorded source only']};
const result=decodeAssetReferences(value,root,hash);result.nodes[0].label='Detached';assert.equal(value.nodes[0].label,'Fixture');
for(const mutate of [v=>v.read_only=false,v=>v.source_key='c'.repeat(64),v=>v.nodes.push(v.nodes[0]),v=>v.outgoing[0].target_id='missing',v=>v.outgoing[0].runtime_binding='confirmed',v=>v.outgoing[0].layer='live',v=>v.outgoing[0].kind='inferred_model',v=>v.coverage.verified_scene_ids=[],v=>v.nodes[1].scene_id='scene://missing',v=>v.outgoing[0].pc=-1,v=>v.outgoing[0].layer='decoded']){const bad=structuredClone(value);mutate(bad);assert.throws(()=>decodeAssetReferences(bad,root,hash));}
console.log('asset reference decoder: bounded source contract, detached output and invalid records passed');
const material=structuredClone(value);material.asset_id='asset://model';material.nodes[0]={id:material.asset_id,kind:'model',scene_id:root,label:'Model',available:true};material.nodes[1]={id:'texture://fixture',kind:'texture',scene_id:root,label:'TIM',available:true};Object.assign(material.outgoing[0],{source_id:material.asset_id,target_id:'texture://fixture',kind:'static_material_texture_source',layer:'decoded',source_catalog_key:hash,material_evidence:{material_index:0,tpage:128,clut:0,uv_bounds:[0,0,1,1],model_source_sha256:hash,evidence:'static_vram_addresses_not_runtime_residency'}});decodeAssetReferences(material,material.asset_id,hash);
for(const mutate of [v=>v.outgoing[0].material_evidence.tpage=512,v=>v.outgoing[0].material_evidence.uv_bounds=[2,0,1,1],v=>v.outgoing[0].material_evidence.model_source_sha256='bad',v=>v.outgoing[0].material_evidence.evidence='live',v=>v.material_diagnostics={model_id:v.asset_id,materials:[{status:'confirmed'}]}]){const bad=structuredClone(material);mutate(bad);assert.throws(()=>decodeAssetReferences(bad,bad.asset_id,hash));}
const clip=structuredClone(value);clip.asset_id=actor;clip.nodes[0]={id:actor,kind:'actor',scene_id:root,label:'Actor',available:true};clip.nodes[1]={id:'animation://fixture/0',kind:'animation',scene_id:root,label:'Clip',available:true};Object.assign(clip.outgoing[0],{source_id:actor,target_id:'animation://fixture/0',kind:'effective_initial_animation_binding',layer:'effective',source_catalog_key:hash,effective_animation_evidence:{donor_entity_id:actor,model_id:'asset://fixture/0',initial_animation_id:2}});decodeAssetReferences(clip,actor,hash);
for(const mutate of [v=>v.outgoing[0].layer='live',v=>v.outgoing[0].effective_animation_evidence.initial_animation_id=0,v=>v.outgoing[0].effective_animation_evidence.model_id='',v=>v.outgoing[0].source_catalog_key='bad']){const bad=structuredClone(clip);mutate(bad);assert.throws(()=>decodeAssetReferences(bad,actor,hash));}
