import assert from 'node:assert/strict';
import {decodeModelSources,openModelSources,decodeModelSourceRemoval} from '../editor/model-sources.js';
const hash=letter=>letter.repeat(64),request={asset_id:'asset://town01/models/scene-tmd/0000',expected_source_key:hash('a')},context={projectPath:'C:/private/model-project',sceneId:'scene://town01',mode:'edit',sourceKey:hash('a')};
const record={schema_version:'legaia.model-source.v1',asset_id:request.asset_id,scene_id:context.sceneId,glb_sha256:hash('b'),byte_length:100,binding:{asset_id:request.asset_id,scene_id:context.sceneId},candidate_sha256:hash('c'),review_key:hash('d'),receipt_key:hash('e')};
const response=()=>({schema_version:'legaia.model-sources.v1',asset_id:request.asset_id,scene_id:context.sceneId,project_source_key:request.expected_source_key,imports:[structuredClone(record)],historical_inputs:true,project_changed:false});
assert.deepEqual(decodeModelSources(response(),request).imports,[record]);
for(const change of [v=>v.project_changed=true,v=>v.scene_id='bad',v=>v.project_source_key=hash('f'),v=>v.imports.push(v.imports[0]),v=>v.imports[0].byte_length=0,v=>v.imports[0].binding.asset_id='other']){const value=response();change(value);assert.throws(()=>decodeModelSources(value,request));}
class Node{constructor(){this.children=[];this.style={};this.open=false;this.disabled=false;}append(...nodes){this.children.push(...nodes);}setAttribute(){}showModal(){this.open=true;}close(){this.open=false;this.onclose?.();}remove(){this.removed=true;}}
const removal={schema_version:'legaia.model-source-removal.v1',...request,project_source_key:request.expected_source_key,project_path:context.projectPath,scene_id:context.sceneId,receipt_key:record.receipt_key,glb_sha256:record.glb_sha256,review_key:hash('f'),collection_key:hash('a'),native_key:hash('c'),native_content_changed:false,source_file_deleted:false,receipt_count_before:2,receipt_count_after:1,shared_blob_receipts:2,registered_bytes_released:0};
assert.equal(decodeModelSourceRemoval(removal,request,record,context.projectPath).registered_bytes_released,0);for(const change of [v=>v.source_file_deleted=true,v=>v.native_content_changed=true,v=>v.shared_blob_receipts=0,v=>v.registered_bytes_released=100,v=>v.project_path='other']){const value=structuredClone(removal);change(value);assert.throws(()=>decodeModelSourceRemoval(value,request,record,context.projectPath));}
const oldDocument=globalThis.document,oldFetch=globalThis.fetch;globalThis.document={body:new Node(),createElement:()=>new Node()};let resolve,signal,isBusy=false;globalThis.fetch=(_route,request)=>{signal=request.signal;return new Promise(done=>resolve=done);};
try{const controller=await openModelSources({assetId:request.asset_id,getContext:()=>context,busy:()=>isBusy,setBusy:v=>isBusy=v});assert.equal(isBusy,true);controller.dispose();assert.equal(signal.aborted,true);assert.equal(isBusy,false);isBusy=true;resolve({ok:true,json:async()=>response()});assert.equal(await controller.ready,false);assert.equal(isBusy,true,'A closed recovery read cannot release a later operation');assert.equal(controller.dialog.removed,true);}finally{globalThis.document=oldDocument;globalThis.fetch=oldFetch;}
console.log('Model input recovery receipt/context guards and close/abort busy ownership passed.');
