import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {decodeNpcScriptComparison} from '../editor/npc-script-comparison.js';
const id='authored-actor://11111111-1111-4111-8111-111111111111',owner='scene://town01/actors/man-p1/0012',build='a'.repeat(16),hash='b'.repeat(64),key='c'.repeat(64),input='d'.repeat(64),draft={scene_id:'scene://town01',name:'NPC',donor_entity_id:owner,position:{x:64,z:128}},source={record_index:12,byte_offset:128,byte_length:4},entry={id:build,status:'completed',matches_current_inputs:true,archive_sha256:hash,source_disc_sha256:hash},state={scene:{id:draft.scene_id,entities:[{id:owner,components:{RetailMetadata:{source_record:source}}}]},actor_drafts:{[id]:draft},project_copy_source_key:key,build_review_source_key:input};
const record=(raw,offset,index)=>({raw_hex:raw,script_offset:2,byte_length:4,byte_offset:offset,record_index:index,sha256:createHash('sha256').update(Buffer.from(raw,'hex')).digest('hex')}),retailRecord=record('61626364',128,12),generatedRecord=record('61586364',1000,53),base={schema_version:'legaia.actor-script-inspection.v1',read_only:true,instructions:[],dialogues:[]},retail={schema_version:'legaia.npc-donor-script.v1',project_source_key:key,scene_id:draft.scene_id,entity_id:id,draft,donor_entity_id:owner,donor_source_record:source,representation:'retail_donor_source',generated_code:false,runtime_binding:'not_asserted',gameplay_verified:false,inspection:{...base,semantic_id:'script://town01/actors/man-p1/0012',actor_semantic_id:owner,source_record:source,record:retailRecord}},generated={schema_version:'legaia.npc-build-script.v1',entity_id:id,scene_id:draft.scene_id,project_source_key:key,build_input_key:input,draft,donor_entity_id:owner,representation:'saved_build',generated_code:true,runtime_binding:'not_asserted',gameplay_verified:false,build:{...entry,integrity:'verified',source_disc_integrity:'verified',delivery:'relocated_PROT'},man_source:{payload_sha256:hash,decoded_size:2048},inspection:{...base,semantic_id:'script://generated-npc/'+id.replace('authored-actor://','')+'/'+build,actor_semantic_id:id,source_record:{...generatedRecord,build_id:build,archive_sha256:hash,man_sha256:hash,byte_coordinate_space:'generated_decoded_MAN'},record:generatedRecord}};
const difference={comparison_scope:'same_relative_record_byte_offsets',retail_length:4,generated_length:4,changed_byte_count:1,unchanged_common_byte_count:3,record_bytes_equal:false,script_tail_bytes_equal:true,changes:[{relative_offset:1,retail_byte:98,generated_byte:88,scope:'record_header'}]},report={schema_version:'legaia.npc-script-comparison.v1',project_source_key:key,entity_id:id,scene_id:draft.scene_id,read_only:true,gameplay_verified:false,runtime_binding:'not_asserted',retail,generated,difference,limitations:['Byte comparison only.']};
const decoded=decodeNpcScriptComparison(report,id,state,entry);decoded.difference.changes[0].retail_byte=0;assert.equal(difference.changes[0].retail_byte,98);
for(const change of [r=>r.project_source_key='stale',r=>r.difference.changed_byte_count=0,r=>r.difference.changes[0].generated_byte=99,r=>r.difference.changes[0].scope='script_or_remaining_record_bytes',r=>r.difference.script_tail_bytes_equal=false,r=>r.generated.build.archive_sha256='wrong',r=>r.retail.donor_entity_id='wrong']){const bad=structuredClone(report);change(bad);assert.throws(()=>decodeNpcScriptComparison(bad,id,state,entry));}
console.log('NPC script comparison exact byte rows/counts, separate qualified records, header/tail scope and stale/forged rejection pass.');

const waiting=structuredClone(report),waitingState=structuredClone(state),wait='script://town01/actors/man-p1/0012/wait/0000';waitingState.actor_drafts[id].waits={donor_entity_id:owner,entries:{[wait]:{duration_ticks:11}}};waiting.retail.draft=waitingState.actor_drafts[id];waiting.generated.draft=waitingState.actor_drafts[id];waiting.retail.inspection.record=record('000a0061',128,12);waiting.generated.inspection.record=record('000b0061',1000,53);waiting.difference.changes=[{relative_offset:1,retail_byte:10,generated_byte:11,scope:'record_header'}];waiting.authored_spans=[{category:'own_wait',source_operand_id:wait,relative_offset:1,byte_length:2,before_hex:'0a00',after_hex:'0b00'}];
assert.deepEqual(decodeNpcScriptComparison(waiting,id,waitingState,entry),waiting);
for(const mutate of [v=>v.authored_spans[0].after_hex='0c00',v=>v.authored_spans[0].relative_offset=2,v=>v.authored_spans[0].source_operand_id=wait.replace('0012','0040'),v=>v.authored_spans.push(v.authored_spans[0]),v=>v.authored_spans[0].category='initial_appearance']){const v=structuredClone(waiting);mutate(v);assert.throws(()=>decodeNpcScriptComparison(v,id,waitingState,entry));}
console.log('NPC authored explanations verify exact before/after spans, current wait binding, ownership and nonoverlap independently.');

for(const [instruction,mnemonic,field,n,relative] of [[[0x23,0,128],'MOVE_TO','x',128,1],[[0xa3,7,0,128],'MOVE_TO','x',128,2],[[0x4c,0x51,0,128,171,9],'NPC_RUN','move_id',10,5],[[0xcc,7,0x51,0,128,171,9],'NPC_RUN','x',128,3],[[0x22,9],'EXEC_MOVE','move_id',10,1],[[0xa2,7,9],'EXEC_MOVE','move_id',10,2]]){
 const moving=structuredClone(report),movingState=structuredClone(state),pc=5,at=pc+relative,movement=`script://town01/actors/man-p1/0012/movement/${pc.toString(16).padStart(4,'0')}`,a=[0,8,9,0,0,...instruction],b=[...a];b[at]=field==='move_id'?n:128;
 movingState.actor_drafts[id].movement={donor_entity_id:owner,entries:{[movement]:{[field]:n}}};moving.retail.draft=movingState.actor_drafts[id];moving.generated.draft=movingState.actor_drafts[id];
 const makeRecord=(data,offset,index)=>({...record(Buffer.from(data).toString('hex'),offset,index),script_offset:5,byte_length:data.length});moving.retail.inspection.record=makeRecord(a,128,12);moving.generated.inspection.record=makeRecord(b,1000,53);
 const sourceSpan={record_index:12,byte_offset:128,byte_length:a.length};movingState.scene.entities[0].components.RetailMetadata.source_record=sourceSpan;moving.retail.donor_source_record=sourceSpan;moving.retail.inspection.source_record=sourceSpan;moving.generated.inspection.source_record={...moving.generated.inspection.source_record,byte_length:b.length};moving.retail.inspection.instructions=[{pc,mnemonic,target_context:instruction[0]&128?7:null}];
 moving.difference={comparison_scope:'same_relative_record_byte_offsets',retail_length:a.length,generated_length:b.length,changed_byte_count:1,unchanged_common_byte_count:a.length-1,record_bytes_equal:false,script_tail_bytes_equal:false,changes:[{relative_offset:at,retail_byte:a[at],generated_byte:b[at],scope:'script_or_remaining_record_bytes'}]};moving.authored_spans=[{category:'own_movement',source_operand_id:movement,movement_field:field,relative_offset:at,byte_length:1,before_hex:a[at].toString(16).padStart(2,'0'),after_hex:b[at].toString(16).padStart(2,'0')}];
 assert.deepEqual(decodeNpcScriptComparison(moving,id,movingState,entry),moving);assert.throws(()=>decodeNpcScriptComparison({...moving,authored_spans:Array(8193).fill(moving.authored_spans[0])},id,movingState,entry));
 const substituted=structuredClone(moving),other=(b[at]+1)%256;substituted.generated.inspection.record=makeRecord(b.map((v,i)=>i===at?other:v),1000,53);substituted.difference.changes[0].generated_byte=other;substituted.authored_spans[0].after_hex=other.toString(16).padStart(2,'0');assert.throws(()=>decodeNpcScriptComparison(substituted,id,movingState,entry));
 for(const mutate of [v=>v.authored_spans[0].movement_field='y',v=>v.authored_spans[0].source_operand_id=movement.replace('0012','0040'),v=>v.authored_spans[0].relative_offset++,v=>v.authored_spans[0].byte_length=2,v=>delete v.authored_spans[0].movement_field,v=>v.authored_spans.push(v.authored_spans[0]),v=>v.retail.inspection.instructions[0].target_context=255,v=>v.retail.inspection.stops=[{reason:'unknown'}]]){const bad=structuredClone(moving);mutate(bad);assert.throws(()=>decodeNpcScriptComparison(bad,id,movingState,entry));}
}
console.log('Movement explanations independently qualify raw ordinary/extended instructions, authored operand encoding, fields, offsets and nonoverlap.');

for(const [instruction,mnemonic,relative] of [[[0x38,0xa3,0x80],'CAM_CFG',1],[[0xb8,7,0xa3,0x80],'CAM_CFG',2],[[0x4c,0x51,0,128,0xb3,9],'NPC_RUN',4],[[0xcc,7,0x51,0,128,0xb3,9],'NPC_RUN',5]]){
 const facing=structuredClone(report),facingState=structuredClone(state),pc=5,at=pc+relative,face=`script://town01/actors/man-p1/0012/facing/${pc.toString(16).padStart(4,'0')}`,a=[0,8,9,0,0,...instruction],b=[...a];b[at]=(a[at]&240)|7;
 facingState.actor_drafts[id].facing={donor_entity_id:owner,entries:{[face]:{sector:7}}};facing.retail.draft=facingState.actor_drafts[id];facing.generated.draft=facingState.actor_drafts[id];
 const makeRecord=(data,offset,index)=>({...record(Buffer.from(data).toString('hex'),offset,index),script_offset:5,byte_length:data.length});facing.retail.inspection.record=makeRecord(a,128,12);facing.generated.inspection.record=makeRecord(b,1000,53);
 const sourceSpan={record_index:12,byte_offset:128,byte_length:a.length};facingState.scene.entities[0].components.RetailMetadata.source_record=sourceSpan;facing.retail.donor_source_record=sourceSpan;facing.retail.inspection.source_record=sourceSpan;facing.generated.inspection.source_record={...facing.generated.inspection.source_record,byte_length:b.length};facing.retail.inspection.instructions=[{pc,mnemonic,target_context:instruction[0]&128?7:null}];
 facing.difference={comparison_scope:'same_relative_record_byte_offsets',retail_length:a.length,generated_length:b.length,changed_byte_count:1,unchanged_common_byte_count:a.length-1,record_bytes_equal:false,script_tail_bytes_equal:false,changes:[{relative_offset:at,retail_byte:a[at],generated_byte:b[at],scope:'script_or_remaining_record_bytes'}]};facing.authored_spans=[{category:'own_facing',source_operand_id:face,relative_offset:at,byte_length:1,before_hex:a[at].toString(16),after_hex:b[at].toString(16)}];
 assert.deepEqual(decodeNpcScriptComparison(facing,id,facingState,entry),facing);
 for(const mutate of [v=>v.authored_spans[0].source_operand_id=face.replace('0012','0040'),v=>v.authored_spans[0].relative_offset++,v=>v.authored_spans[0].byte_length=2,v=>v.authored_spans.push(v.authored_spans[0]),v=>v.retail.inspection.instructions[0].target_context=255,v=>v.retail.inspection.stops=[{reason:'unknown'}],v=>v.authored_spans[0].sector=7]){const bad=structuredClone(facing);mutate(bad);assert.throws(()=>decodeNpcScriptComparison(bad,id,facingState,entry));}
 // Forged generated flags/dispatch or a parked composed target cannot be explained.
 for(const changed of [b.map((v,i)=>i===at?v^0x80:v),b.map((v,i)=>i===pc?v^0x80:v),b.map((v,i)=>mnemonic==='CAM_CFG'&&i===at+1?0:mnemonic==='NPC_RUN'&&(i===pc+(instruction[0]&128?2:1)+1||i===pc+(instruction[0]&128?2:1)+2)?255:v)]){
  const bad=structuredClone(facing);bad.generated.inspection.record=makeRecord(changed,1000,53);bad.authored_spans[0].after_hex=changed[at].toString(16);assert.throws(()=>decodeNpcScriptComparison(bad,id,facingState,entry));
 }
}
console.log('Facing explanations independently qualify both raw opcode forms, typed sectors, upper flags, dispatch, modes and parked targets.');
