import assert from 'node:assert/strict';
import {createScriptFlagSandbox,parseSandboxWords,mountScriptFlagSandbox} from '../editor/script-flag-sandbox.js';
const f=(pc,opcode,raw)=>({pc,opcode,length:2,mnemonic:['LFLAG','GFLAG','CFLAG'][Math.floor((opcode-0x2b)/3)]+'_'+['SET','CLEAR','TEST'][(opcode-0x2b)%3],target_context:null,operands:{bit:raw&31,raw_operand:raw,...((opcode-0x2b)%3===2?{can_wait_for_flag:true}:{})},successors:[{pc:pc+2,condition:'encoded_continuation'}]});
const r=rows=>({status:'decoded_supported_paths',entry_pc:rows[0].pc,instructions:rows,dialogues:[],stops:[]});
const inputs={local:null,global:null,context:null};
assert.deepEqual(parseSandboxWords({local:'0xFFFF',global:'80000000',context:''}),{local:65535,global:2147483648,context:null});
for(const v of [{local:'10000',global:'',context:''},{local:'',global:'100000000',context:''},{local:'-1',global:'',context:''},{local:1,global:'',context:''},{local:'',global:'',context:'',extra:''}])assert.throws(()=>parseSandboxWords(v));
const report=r([f(0,0x2e,255),f(2,0x30,31),f(4,0x2f,31),f(6,0x30,31)]),saved=JSON.stringify(report),engine=createScriptFlagSandbox(report);
engine.start(0,inputs);assert.equal(engine.step().state.banks.global.value,2147483648);assert.equal(engine.snapshot().state.banks.global.known,2147483648);assert.equal(engine.step().state.pc,4);assert.equal(engine.step().state.banks.global.value,0);let stopped=engine.step();assert.equal(stopped.state.status,'flag_wait');assert.equal(stopped.state.pc,6);assert.throws(()=>engine.step());assert.equal(engine.back().state.status,'ready');assert.equal(engine.back().state.banks.global.value,2147483648);assert.equal(JSON.stringify(report),saved);
const d=engine.snapshot();d.state.banks.global.value=0;assert.equal(engine.snapshot().state.banks.global.value,2147483648);
for(const [row,reason] of [[f(0,0x2d,3),'unknown_flag'],[f(0,0x2b,16),'unsupported'],[f(0,0x31,8),'unsupported'],[f(0,0x32,10),'unsupported'],[{...f(0,0x2e,1),target_context:2},'unsupported'],[{...f(0,0x2e,1),opcode:0x2b},'unsupported']]){const e=createScriptFlagSandbox(r([row]));e.start(0,inputs);const s=e.step();assert.equal(s.state.status,reason);assert.deepEqual(s.state.banks,s.history[0].before.banks);}
const ordinary=createScriptFlagSandbox(r([f(0,0x31,31),f(2,0x33,31),f(4,0x32,31)]));ordinary.start(0,inputs);assert.equal(ordinary.run().state.status,'undecoded');assert.equal(ordinary.snapshot().state.banks.context.known,2147483648);assert.equal(ordinary.snapshot().state.banks.context.value,0);
const jump={pc:0,length:3,opcode:0x26,mnemonic:'JMP_REL',target_context:null,operands:{delta:-1},successors:[{pc:0,condition:'unconditional'}]},loop=createScriptFlagSandbox(r([jump]));loop.start(0,inputs);assert.equal(loop.run().state.status,'step_limit');assert.equal(loop.snapshot().history.length,256);assert.equal(loop.back().state.status,'ready');assert.equal(loop.step().state.status,'step_limit');loop.reset();assert.equal(loop.snapshot().state,null);
const nop={pc:0,length:1,opcode:0x21,mnemonic:'NOP',target_context:null,operands:{},successors:[{pc:1,condition:'encoded_continuation'}]},unknown={pc:1,length:1,opcode:0x22,mnemonic:'EXEC_MOVE',target_context:null,operands:{},successors:[{pc:2,condition:'encoded_continuation'}]},halt=createScriptFlagSandbox(r([nop,unknown]));halt.start(0,inputs);assert.equal(halt.run().state.pc,1);assert.equal(halt.snapshot().state.status,'unsupported');assert.equal(halt.snapshot().history.length,2);
for(const v of [{local:65536,global:null,context:null},{local:null,global:true,context:null},{local:null,global:null},{local:null,global:4294967296,context:null}])assert.throws(()=>engine.start(0,v));
class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.textContent='';}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this[k]=v;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)];globalThis.document={createElement:tag=>new Element(tag)};let live=true,blocked=false,errors=[];const selected=[],host=new Element('div'),view=mountScriptFlagSandbox(host,{report,selection:()=>0,current:()=>live,busy:()=>blocked,selectInstruction:(pc,reveal)=>selected.push([pc,reveal]),onError:e=>errors.push(e.message)}),button=text=>tree(host).find(n=>n.tagName==='button'&&n.textContent===text);
button('Start flag sandbox at entry').onclick();button('Simulate one instruction').onclick();assert.equal(view.snapshot.state.pc,2);assert.deepEqual(selected.at(-1),[2,false]);blocked=true;view.update();assert.equal(button('Simulate until boundary').disabled,true);button('Simulate one instruction').onclick();assert.equal(view.snapshot.state.pc,2);blocked=false;button('Back one simulated instruction').onclick();assert.equal(view.snapshot.state.pc,0);const field=tree(host).find(n=>n['aria-label']==='Hypothetical local flag word');field.value='BADHEX';button('Start flag sandbox at selection').onclick();assert.equal(errors.length,1);assert.equal(view.snapshot.state.pc,0);live=false;view.update();assert.equal(view.snapshot.state,null);assert.equal(button('Start flag sandbox at entry').disabled,true);view.dispose();assert.equal(host.children.length,0);
console.log('Flag sandbox: partial known bits, bit31, set/clear/test wait, unresolved/refused semantics, bounded loops, exact Back, detached state, input widths and UI busy/stale/disposal passed');
