import assert from 'node:assert/strict';
import {createEditorStartup,mountEditorStartup} from '../editor/editor-startup.js';
const pause=()=>new Promise(resolve=>setTimeout(resolve,0)),deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
let loads=0,connections=0,states=[];const normal=createEditorStartup({load:async()=>{loads++;return {initializeEditor:async({signal})=>{assert(!signal.aborted);connections++;return true;}};},onState:s=>states.push(s)});assert(await normal.start());assert.equal(normal.state.phase,'ready');assert.equal(await normal.start(),false);assert.equal(loads,1);assert.equal(connections,1);assert.deepEqual(states.map(s=>s.phase),['loading','connecting','ready']);normal.dispose();
for(const load of [async()=>{throw Error('Module unavailable');},async()=>({})]){const failed=createEditorStartup({load,onState:()=>{}});assert.equal(await failed.start(),false);assert.equal(failed.state.phase,'failed');assert.equal(failed.state.canRetry,false);assert.equal(await failed.start(),false);failed.dispose();}
const slow=deferred();let lateConnections=0;const timed=createEditorStartup({load:()=>slow.promise,loadTimeoutMs:5,onState:()=>{}});assert.equal(await timed.start(),false);assert.equal(timed.state.phase,'failed');slow.resolve({initializeEditor:async()=>{lateConnections++;return true;}});await pause();assert.equal(lateConnections,0);assert.equal(timed.state.phase,'failed');timed.dispose();
let attempts=0,retryLoads=0;const retry=createEditorStartup({load:async()=>{retryLoads++;return {initializeEditor:async()=>{if(++attempts===1)throw Error('Local service unavailable');return true;}};},onState:()=>{}});assert.equal(await retry.start(),false);assert(retry.state.canRetry);assert(await retry.start());assert.equal(retryLoads,1);assert.equal(attempts,2);retry.dispose();
const held=deferred();let receivedSignal,connectCalls=0;const timeout=createEditorStartup({load:async()=>({initializeEditor:({signal})=>{connectCalls++;receivedSignal=signal;return connectCalls===1?held.promise:Promise.resolve(true);}}),connectionTimeoutMs:5,onState:()=>{}});const pending=timeout.start();await pause();assert.equal(await timeout.start(),false);assert.equal(await pending,false);assert(receivedSignal.aborted);assert.equal(timeout.state.canRetry,false);assert.equal(await timeout.start(),false);held.resolve(false);await pause();assert(timeout.state.canRetry);assert(await timeout.start());assert.equal(connectCalls,2);timeout.dispose();
const cancelled=deferred(),observed=[];let cancelledCalls=0;const closed=createEditorStartup({load:()=>cancelled.promise,onState:s=>observed.push(s)});const closing=closed.start();closed.dispose();cancelled.resolve({initializeEditor:async()=>{cancelledCalls++;return true;}});assert.equal(await closing,false);await pause();assert.equal(cancelledCalls,0);assert.deepEqual(observed.map(s=>s.phase),['loading']);
const nodes=Object.fromEntries(['status','retry','reload'].map(k=>[k,{}])),root={hidden:false,querySelector:key=>nodes[key.match(/startup-(\w+)/)[1]]},background=[{inert:true}],connect=deferred();let refreshes=0;
const view=mountEditorStartup({root,background,load:async()=>({initializeEditor:()=>connect.promise}),reload:()=>refreshes++});const opening=view.start();await pause();assert(background[0].inert);assert(!root.hidden);assert(nodes.retry.hidden);connect.reject(Error('Connection refused'));assert.equal(await opening,false);assert(!nodes.retry.hidden);nodes.reload.onclick();assert.equal(refreshes,1);view.dispose();
const readyView=mountEditorStartup({root,background,load:async()=>({initializeEditor:async()=>true}),reload:()=>refreshes++});assert(await readyView.start());assert(root.hidden);assert(!background[0].inert);nodes.reload.onclick();assert.equal(refreshes,1);readyView.dispose();
for(const config of [{load:1,onState:()=>{}},{load:()=>{},onState:1},{load:()=>{},onState:()=>{},loadTimeoutMs:0},{load:()=>{},onState:()=>{},connectionTimeoutMs:120001}])assert.throws(()=>createEditorStartup(config));
console.log('Editor startup: module/state phases, explicit retry, read-only handshake, deadlines, cancellation, late reply ownership, serialized retry, interaction gating and recovery UI passed.');
