import assert from 'node:assert/strict';import {createHash,webcrypto} from 'node:crypto';
import {decodeAudioPcm,encodePreviewWav,mountAudioAudition} from '../editor/audio-audition.js';
globalThis.crypto??=webcrypto;
const sample={index:0,table_index:1,size_units:2,offset:3104,size_bytes:16,block_aligned:true,source_sha256:'b'.repeat(64)},bank={asset_id:'audio://legaia/prot/0877',scene_id:'scene://town01',source_key:'a'.repeat(64),source_record:{entry_sha256:'c'.repeat(64)},reference_commit:'d'.repeat(40),bank_sha256:'e'.repeat(64)};
const waveform={schema_version:'legaia.audio-waveform-inspection.v1',...bank,sample,read_only:true,project_changed:false,runtime_state:'not_observed',decoder:'psx-spu-adpcm-integer-v1',history:'zero-initialized',source_size_bytes:16,source_sha256:sample.source_sha256,decoded_blocks:1,decoded_frames:28,consumed_bytes:16,remaining_bytes:0,termination:{reason:'encoded-end',byte_offset:0},markers:[{block_index:0,frame_offset:0,flags:1,encoded_shift:0,effective_shift:0}],bins:Array.from({length:28},(_,frame_offset)=>({frame_offset,frame_count:1,minimum:frame_offset%2?-32768:4096,maximum:frame_offset%2?-32768:4096})),frame_limit:114688,sample_rate:null,limitations:[]};
const pcm=Buffer.alloc(56);for(let i=0;i<28;i++)pcm.writeInt16LE(i%2?-32768:4096,i*2);
const payload={schema_version:'legaia.audio-pcm-preview.v1',waveform,format:'s16le-mono',pcm_sha256:createHash('sha256').update(pcm).digest('hex'),pcm_base64:pcm.toString('base64')};
const decoded=await decodeAudioPcm(payload,bank,sample,waveform);assert.deepEqual(Buffer.from(decoded),pcm);
for(const change of [r=>r.pcm_sha256='f'.repeat(64),r=>r.pcm_base64+=' ',r=>r.pcm_base64=r.pcm_base64.slice(4),r=>r.waveform.source_key='f'.repeat(64),r=>r.extra=true,r=>r.format='s16be-mono']){const bad=structuredClone(payload);change(bad);await assert.rejects(decodeAudioPcm(bad,bank,sample,waveform));}
const wrong=Buffer.from(pcm);wrong.writeInt16LE(0,0);await assert.rejects(decodeAudioPcm({...payload,pcm_base64:wrong.toString('base64'),pcm_sha256:createHash('sha256').update(wrong).digest('hex')},bank,sample,waveform),/amplitudes/);
for(const rate of [11025,22050,32000,44100,48000]){const wav=encodePreviewWav(decoded,rate),view=new DataView(wav.buffer);assert.equal(Buffer.from(wav).subarray(0,4).toString(),'RIFF');assert.equal(view.getUint32(4,true),92);assert.equal(view.getUint16(22,true),1);assert.equal(view.getUint32(24,true),rate);assert.equal(view.getUint16(34,true),16);assert.deepEqual(Buffer.from(wav.slice(44)),pcm);}
assert.throws(()=>encodePreviewWav(decoded,12345));assert.throws(()=>encodePreviewWav(new Uint8Array(1),22050));
// Largest allowed preview catches payload/encoding limits, without retail bytes.
const large=structuredClone(waveform);large.sample={...sample,size_units:8192,size_bytes:65536};large.source_size_bytes=65536;large.decoded_blocks=4096;large.decoded_frames=114688;large.consumed_bytes=65536;large.termination.byte_offset=65520;large.markers=[{block_index:4095,frame_offset:114660,flags:1,encoded_shift:0,effective_shift:0}];large.bins=Array.from({length:512},(_,i)=>({frame_offset:i*224,frame_count:224,minimum:0,maximum:0}));const zeros=Buffer.alloc(229376);assert.equal((await decodeAudioPcm({...payload,waveform:large,pcm_base64:zeros.toString('base64'),pcm_sha256:createHash('sha256').update(zeros).digest('hex')},bank,large.sample,large)).length,229376);
class Element{constructor(tag){this.tag=tag;this.style={};this.dataset={};this.children=[];this.value='';}append(...nodes){this.children.push(...nodes);}setAttribute(){}}
globalThis.document={createElement:tag=>new Element(tag)};const find=(host,text)=>host.children.flatMap(n=>[n,...n.children]).find(n=>n.textContent===text);let current={sourceKey:bank.source_key},starts=0,stops=0,closes=0,resumeResolve;
const fakeAudio=()=>({destination:{},createGain:()=>({gain:{value:0},connect(){},disconnect(){}}),resume:()=>new Promise(done=>resumeResolve=done),createBuffer:(channels,frames,rate)=>({getChannelData:()=>new Float32Array(frames)}),createBufferSource:()=>({connect(){},disconnect(){},start(){starts++;},stop(){stops++;}}),close:async()=>{closes++;}});
let host=new Element('div'),view=mountAudioAudition(host,{bank,sample,waveform,getContext:()=>current,request:async()=>({ok:true,text:async()=>JSON.stringify(payload)}),audioContext:fakeAudio});
await find(host,'Load audition').onclick();assert.equal(starts,0);const rate=host.children[1].children[1],play=find(host,'Play sample'),stop=find(host,'Stop sample');assert(play.disabled);rate.value='22050';rate.onchange();assert(!play.disabled);const pending=play.onclick();assert(!stop.disabled);stop.onclick();resumeResolve();await pending;assert.equal(starts,0);
const playing=play.onclick();resumeResolve();await playing;assert.equal(starts,1);current={sourceKey:'f'.repeat(64)};stop.onclick();assert.equal(stops,1);assert.equal(closes,1);assert(play.disabled);view.dispose();
current={sourceKey:bank.source_key};let resolve;host=new Element('div');view=mountAudioAudition(host,{bank,sample,waveform,getContext:()=>current,request:()=>new Promise(done=>resolve=done),audioContext:fakeAudio});const late=find(host,'Load audition').onclick();view.dispose();resolve({ok:true,text:async()=>JSON.stringify(payload)});await late;assert(find(host,'Play sample').disabled);assert.equal(starts,1);
console.log('PCM hash/envelope/source qualification, max budget, exact mono WAV, explicit rate/no-autoplay, pending Stop, stale cleanup and late-close guards passed.');
