import assert from 'node:assert/strict';
import {decodeSavedSceneView} from '../editor/scene-views.js';
const state={scene:{id:'scene'},scene_view_source_key:'source'},value={scene_id:'scene',import_sha256:'source',display:{camera:{projection:'orthographic',yaw:0,pitch:Math.PI/2,distance:1000,target:{x:2880,y:-64,z:5440}},representation:'retail',layers:{actors:true,scenery:true,ground:false}}};
const before=structuredClone(value),view=decodeSavedSceneView(value,state);view.camera.target.x=0;assert.deepEqual(value,before);
for(const change of [v=>v.scene_id='other',v=>v.import_sha256='stale',v=>v.display.camera.pitch=-.001,v=>v.display.camera.distance=Infinity,v=>v.display.camera.target.y=null,v=>v.display.layers.actors=1,v=>v.display.runtime={},v=>v.display.camera.projection='invalid']){const bad=structuredClone(value);change(bad);assert.throws(()=>decodeSavedSceneView(bad,state));}
console.log('Saved scene view source/display guards and detached recall passed.');

const front=structuredClone(value);front.display.camera.pitch=0;assert.equal(decodeSavedSceneView(front,state).camera.pitch,0);front.display.camera.projection='perspective';assert.throws(()=>decodeSavedSceneView(front,state));

const {decodeSceneViewVisibility,captureSceneViewVisibility}=await import('../editor/scene-views.js'),actor='actor://scene/0000',decor='environment://scene/field-map/decorations/00001',ground='environment://scene/field-map/ground',source='a'.repeat(64),visibilityState={...state,scene:{id:'scene',entities:[{id:actor}]},scene_view_entity_ids:[actor,decor,ground],scene_view_renderable_ids:[actor,decor,ground],scene_view_map_sha256:source};
const saved=structuredClone(value);saved.display.grid=false;saved.display.visibility=captureSceneViewVisibility(new Set([ground,actor]),decor,visibilityState);const savedBefore=structuredClone(saved),decoded=decodeSavedSceneView(saved,visibilityState);assert.equal(decoded.grid,false);assert.deepEqual(decoded.visibility.hidden_entity_ids,[actor,ground].sort());decoded.visibility.hidden_entity_ids.length=0;assert.deepEqual(saved,savedBefore);
const actorOnly=captureSceneViewVisibility(new Set([actor]),null,visibilityState);assert.equal(actorOnly.map_sha256,null);assert.deepEqual(decodeSceneViewVisibility(actorOnly,visibilityState),actorOnly);
for(const mutate of [v=>v.display.grid=1,v=>v.display.visibility.hidden_entity_ids.reverse(),v=>v.display.visibility.hidden_entity_ids.push(actor),v=>v.display.visibility.isolated_entity_id=actor,v=>v.display.visibility.hidden_entity_ids=['unknown'],v=>v.display.visibility.map_sha256='b'.repeat(64),v=>v.display.visibility.runtime_address=4096]){const bad=structuredClone(saved);mutate(bad);assert.throws(()=>decodeSavedSceneView(bad,visibilityState));}
assert.throws(()=>decodeSavedSceneView(saved,{...visibilityState,scene_view_renderable_ids:[actor,ground]}));assert.throws(()=>captureSceneViewVisibility(new Set(['draft://unproven']),null,visibilityState));assert.equal(decodeSavedSceneView(value,visibilityState).grid,undefined);assert.equal(decodeSavedSceneView(value,visibilityState).visibility,undefined);
console.log('Saved visibility/grid: source-bound full instance state, isolated renderability, canonical IDs, detached recall and legacy preservation passed.');

const group=captureSceneViewVisibility(new Set([ground]),[decor,actor],visibilityState);assert.deepEqual(group.isolated_entity_ids,[decor,actor].sort());assert.equal(group.map_sha256,source);assert(!Object.hasOwn(group,'isolated_entity_id'));const detached=decodeSceneViewVisibility(group,visibilityState);detached.isolated_entity_ids.length=0;assert.equal(group.isolated_entity_ids.length,2);
const {sceneViewIsolationIds}=await import('../editor/scene-views.js');assert.deepEqual(sceneViewIsolationIds(group),group.isolated_entity_ids);assert.deepEqual(sceneViewIsolationIds(actorOnly),[]);assert.deepEqual(sceneViewIsolationIds(saved.display.visibility),[decor]);
for(const mutate of [v=>v.isolated_entity_ids=[],v=>v.isolated_entity_ids.reverse(),v=>v.isolated_entity_ids.push(actor),v=>v.isolated_entity_ids=[actor,ground].sort(),v=>v.isolated_entity_ids=new Array(2),v=>v.isolated_entity_ids=null,v=>v.isolated_entity_id=actor,v=>v.map_sha256='b'.repeat(64),v=>v.isolated_entity_ids=[actor,'unknown'].sort()]){const bad=structuredClone(group);mutate(bad);assert.throws(()=>decodeSceneViewVisibility(bad,visibilityState));}
assert.throws(()=>decodeSceneViewVisibility(group,{...visibilityState,scene_view_renderable_ids:[actor,ground]}));assert.throws(()=>captureSceneViewVisibility(new Set(),new Array(129).fill(actor),visibilityState));console.log('Group isolation: legacy recall, canonical bounded membership, per-instance rendering and source MAP guards passed.');
