import assert from 'node:assert/strict';import fs from 'node:fs';
import {renderEnvelopePcm,encodeEnvelopeWav,mountEnvelopeAudition} from '../editor/audio-envelope-audition.js';
const pcm=values=>{const bytes=new Uint8Array(values.length*2),view=new DataView(bytes.buffer);values.forEach((value,i)=>view.setInt16(i*2,value,true));return bytes;},samples=bytes=>Array.from({length:bytes.length/2},(_,i)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getInt16(i*2,true));
const raw=pcm([16000,16000,16000]),before=raw.slice(),result=renderEnvelopePcm(raw,44100,15,31,{frameCount:6,keyOffFrame:4});
// Literal fast-attack counters: 14336, 28672, 32767. Source runs once.
assert.deepEqual(samples(result.bytes),[7000,14000,15999,0,0,0]);assert.deepEqual(raw,before);
const interpolation=renderEnvelopePcm(pcm([16000,0]),11025,15,31,{frameCount:10,keyOffFrame:9});assert.deepEqual(samples(interpolation.bytes).slice(0,3),[7000,10500,7999]);assert(samples(interpolation.bytes).slice(8).every(value=>value===0));
assert(samples(renderEnvelopePcm(pcm([-32768,32767,-32768]),44100,15,31,{frameCount:3,keyOffFrame:2}).bytes).every(value=>value>=-32768&&value<=32767));
assert(samples(renderEnvelopePcm(raw,44100,0x7f00,31,{frameCount:6,keyOffFrame:4}).bytes).every(value=>value===0));
for(const args of [[new Uint8Array(),44100,15,31],[new Uint8Array(3),44100,15,31],[new Uint8Array(229378),44100,15,31],[raw,22051,15,31],[raw,44100,true,31],[raw,44100,15,31,{frameCount:220501,keyOffFrame:1}]])assert.throws(()=>renderEnvelopePcm(...args));
const wav=encodeEnvelopeWav(result.bytes),header=new DataView(wav.buffer);assert.equal(new TextDecoder().decode(wav.slice(0,4)),'RIFF');assert.equal(header.getUint32(4,true),wav.length-8);assert.equal(header.getUint32(24,true),44100);assert.equal(header.getUint32(28,true),88200);assert.equal(header.getUint16(22,true),1);assert.equal(header.getUint16(34,true),16);assert.equal(header.getUint32(40,true),12);assert.deepEqual(wav.slice(44),result.bytes);assert.equal(encodeEnvelopeWav(new Uint8Array(441000)).length,441044);assert.throws(()=>encodeEnvelopeWav(new Uint8Array(441002)));
console.log('Literal gain/resampling values, one-pass end, frozen envelope, input preservation, bounds and WAV readback passed.');
const file=process.argv[2];if(!file)throw Error('Supply a freshly qualified Retail/Current envelope audition fixture.');const f=JSON.parse(fs.readFileSync(file,'utf8'));
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.value='';this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(key,value){this.attrs[key]=value;}}
globalThis.document={createElement:tag=>new Element(tag)};const nodes=root=>[root,...root.children.flatMap(nodes)],button=(host,title)=>nodes(host).find(node=>node.tag==='button'&&node.textContent===title),control=(host,title)=>nodes(host).find(node=>node.attrs['aria-label']===title);
let fresh=true,held=null,fail=null,contextClosed=0,stopped=0,started=0,captured=null;const errors=[],calls=[];
const request=async(path,init)=>{const body=JSON.parse(init.body);calls.push({path,body});if(held)return new Promise(resolve=>held.resolve=resolve);let value=path==='/api/audio-sample-authoring'?f.options:f.pcm[body.layer];value=structuredClone(value);if(fail)fail(value,path);return {ok:true,text:async()=>JSON.stringify(value)};};
const audioContext=()=>({destination:{},resume:async()=>{},close:async()=>{contextClosed++;},createGain:()=>({gain:{value:0},connect(){},disconnect(){}}),createBuffer:(channels,length,rate)=>{captured={channels,length,rate,data:new Float32Array(length)};return {getChannelData:()=>captured.data};},createBufferSource:()=>({connect(){},disconnect(){},start(){started++;},stop(){stopped++;}})});
const host=new Element('section'),view=mountEnvelopeAudition(host,{bank:f.bank,fresh:()=>fresh,request,audioContext,onError:error=>errors.push(error.message)});view.update(f.config);
const load=button(host,'Load envelope sample'),play=button(host,'Play envelope audition'),rate=control(host,'Envelope sample rate'),layer=control(host,'Envelope audition layer');assert(play.disabled);await load.onclick();assert(play.disabled);rate.value='44100';rate.onchange();assert(!play.disabled);await play.onclick();assert.equal(captured.rate,44100);assert.equal(captured.length,110250);assert.equal(started,1);layer.value='Current';layer.onchange();assert(stopped>0);assert(play.disabled);await load.onclick();await play.onclick();assert.equal(started,2);assert(calls.some(call=>call.path==='/api/audio-sample-preview'&&call.body.layer==='retail'));assert(calls.some(call=>call.path==='/api/audio-sample-preview'&&call.body.layer==='current'));
const count=calls.length;layer.value='Reviewed Proposed';layer.onchange();assert(load.disabled);await play.onclick();assert.equal(calls.length,count);assert.equal(started,3); // Proposed ADSR uses the qualified Current PCM, never a sample proposal.
view.update({...f.config,tone:{page:99,index:0}});assert(play.disabled);assert(contextClosed>0);assert.equal(rate.value,'');
fail=(value,path)=>{if(path==='/api/audio-sample-authoring')value.current_entry_sha256='f'.repeat(64);};await load.onclick();assert(play.disabled);assert(errors.at(-1).includes('entry differs'));fail=null;
held={};const pending=load.onclick();view.clear();held.resolve({ok:true,text:async()=>JSON.stringify(f.options)});await pending;assert(host.hidden&&play.disabled);held=null;
view.update(f.config);await load.onclick();rate.value='44100';rate.onchange();await play.onclick();fresh=false;await play.onclick();assert(host.hidden&&play.disabled);assert(contextClosed>=2);view.clear();
console.log('Qualified layer ownership, Proposed uses Current PCM, stop/close, tone invalidation, stale entry refusal and late response withdrawal passed.');
