import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createScriptFlagSandbox} from '../editor/script-flag-sandbox.js';
const words={local:null,global:null,context:null};
const branch=(bank,bit=31,delta=4)=>({pc:0,opcode:0x4c,length:5,target_context:null,mnemonic:'FLAG_WORD_BRANCH',operands:{sub_op:{context:0xa0,local:0xa1,global:0xa2}[bank],flag_word:{context:'actor_flags',local:'actor_local_flags',global:'global_story_word'}[bank],bit_encoded:bit,delta,target:(3+delta)&65535},successors:[{pc:(3+delta)&65535,condition:'flag_bit_set'},{pc:5,condition:'flag_bit_clear'}]});
const nop=pc=>({pc,opcode:0x21,length:1,target_context:null,mnemonic:'NOP',operands:{},successors:[{pc:pc+1,condition:'encoded_continuation'}]});
const report=row=>({status:'decoded_supported_paths',entry_pc:0,instructions:[row,...[...new Set([row.successors[0].pc,5])].filter(pc=>pc!==0).map(nop)],dialogues:[],stops:[]});
for(const bank of ['local','global','context'])for(const bit of [0,15,...(bank==='local'?[]:[31])]){
 const r=report(branch(bank,bit|0xe0)),text=JSON.stringify(r),e=createScriptFlagSandbox(r);e.start(0,{...words,[bank]:2**bit});let s=e.step();assert.equal(s.state.pc,7);assert.equal(s.history[0].effect.successor_index,0);assert.equal(s.history[0].effect.tested_value,true);assert.deepEqual(s.state.banks,s.history[0].before.banks);assert.equal(e.back().state.pc,0);e.start(0,{...words,[bank]:0});s=e.step();assert.equal(s.state.pc,5);assert.equal(s.history[0].effect.tested_value,false);assert.equal(s.history[0].effect.successor_index,1);e.start(0,words);s=e.step();assert.equal(s.state.status,'unknown_flag');assert.equal(s.state.pc,0);assert.equal(s.history[0].effect.successor_index,null);assert.equal(JSON.stringify(r),text);
}
for(const mutate of [n=>n.operands.sub_op=0xa0,n=>n.operands.target=6,n=>n.operands.delta=true,n=>n.operands.bit_encoded=256,n=>n.length=6,n=>n.opcode=0x2e,n=>n.target_context=0,n=>n.successors.reverse(),n=>n.successors[0].condition='test_passed']){const n=branch('global');mutate(n);const e=createScriptFlagSandbox(report(n));e.start(0,{...words,global:2147483648});const s=e.step();assert.equal(s.state.status,'unsupported');assert.equal(s.state.pc,0);assert.deepEqual(s.state.banks,s.history[0].before.banks);}
const local=createScriptFlagSandbox(report(branch('local',31)));local.start(0,{...words,local:65535});assert.equal(local.step().state.status,'unsupported');
const negative=createScriptFlagSandbox(report(branch('global',31,-3)));negative.start(0,{...words,global:2147483648});assert.equal(negative.run().state.status,'step_limit');assert.equal(negative.snapshot().state.pc,0);assert.equal(negative.back().state.status,'ready');
const wrapped=createScriptFlagSandbox(report(branch('global',1,-32768)));wrapped.start(0,{...words,global:2});assert.equal(wrapped.step().state.pc,32771);
const same=createScriptFlagSandbox(report(branch('global',0,2)));same.start(0,{...words,global:1});assert.equal(same.step().history[0].effect.successor_index,0);same.start(0,{...words,global:0});assert.equal(same.step().history[0].effect.successor_index,1);
if(process.argv[2]){const fixtures=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));for(const r of fixtures){const row=r.instructions[0],bank={actor_flags:'context',actor_local_flags:'local',global_story_word:'global'}[row.operands.flag_word],bit=row.operands.bit_encoded&31,e=createScriptFlagSandbox(r);e.start(0,{...words,[bank]:2**bit});assert.equal(e.step().state.pc,row.successors[0].pc);e.start(0,{...words,[bank]:0});assert.equal(e.step().state.pc,row.successors[1].pc);}console.log('Independent SDK-decoded byte fixtures matched both branch outcomes');}
console.log('Flag branches: three banks, masked selectors, bit31, exact set/clear/unknown outcomes, signed targets, duplicate destinations, immutable words, Back, loops and forged/extended/width refusal passed');
