import assert from 'node:assert/strict';
import {mountHierarchyNavigation} from '../editor/hierarchy-navigation.js';
const doc={activeElement:null},events=new Map();let scene='town01',items=[];
const host={ownerDocument:doc,tabIndex:0,contains:n=>n===host||items.includes(n),querySelectorAll:()=>items,addEventListener:(k,f)=>events.set(k,f),removeEventListener:(k,f)=>{if(events.get(k)===f)events.delete(k);},closest:()=>null,focus(){doc.activeElement=this;}};
function row(id,selected=false){return {title:id,hidden:false,disabled:false,tabIndex:0,getAttribute:k=>k==='role'?'treeitem':k==='aria-selected'?String(selected):null,closest(){return this;},focus(){doc.activeElement=this;events.get('focusin')?.({target:this});}};}
const control=mountHierarchyNavigation(host,()=>scene),outside={};doc.activeElement=outside;items=[row('a'),row('b',true),row('c')];control.afterRender(control.beforeRender());assert.deepEqual(items.map(n=>n.tabIndex),[-1,0,-1]);assert.equal(doc.activeElement,outside);
let prevented=false;function key(value,target=doc.activeElement,modifiers={}){prevented=false;events.get('keydown')({key:value,target,preventDefault(){prevented=true;},...modifiers});}
items[1].focus();key('ArrowDown');assert.equal(doc.activeElement.title,'c');assert(prevented);key('ArrowDown');assert.equal(doc.activeElement.title,'c');key('Home');assert.equal(doc.activeElement.title,'a');key('ArrowUp');assert.equal(doc.activeElement.title,'a');key('End');assert.equal(doc.activeElement.title,'c');key('ArrowUp');assert.equal(doc.activeElement.title,'b');key('ArrowDown',doc.activeElement,{shiftKey:true});assert(!prevented);assert.equal(doc.activeElement.title,'b');key('Enter');assert(!prevented);
let snapshot=control.beforeRender();items=[row('a'),row('b'),row('c',true)];control.afterRender(snapshot);assert.equal(doc.activeElement,items[1]);assert.deepEqual(items.map(n=>n.tabIndex),[-1,0,-1]);snapshot=control.beforeRender();items=[row('c')];control.afterRender(snapshot);assert.equal(doc.activeElement,items[0]);snapshot=control.beforeRender();items=[];control.afterRender(snapshot);assert.equal(doc.activeElement,host);assert.equal(host.tabIndex,0);
snapshot=control.beforeRender();items=[row('new',true)];scene='town02';control.afterRender(snapshot);assert.equal(doc.activeElement,host);assert.equal(items[0].tabIndex,0);
doc.activeElement=outside;snapshot=control.beforeRender();items=[row('new',true),row('hidden'),row('disabled')];items[1].hidden=true;items[2].disabled=true;control.afterRender(snapshot);assert.equal(doc.activeElement,outside);items[0].focus();key('End');assert.equal(doc.activeElement,items[0]);
const parent=row('Actors group'),child=row('actor'),sibling=row('other actor');parent.dataset={hierarchyGroup:'actors'};child.getAttribute=k=>k==='aria-level'?'2':k==='role'?'treeitem':null;child.previousElementSibling=sibling;sibling.previousElementSibling=parent;items=[parent,sibling,child];child.focus();key('ArrowLeft');assert(prevented);assert.equal(doc.activeElement,parent);assert.deepEqual(items.map(n=>n.tabIndex),[0,-1,-1]);
child.focus();parent.disabled=true;key('ArrowLeft');assert(!prevented);assert.equal(doc.activeElement,child);parent.disabled=false;key('ArrowLeft',child,{ctrlKey:true});assert(!prevented);key('ArrowDown',child,{defaultPrevented:true});assert(!prevented);assert.equal(doc.activeElement,child);child.previousElementSibling=null;key('ArrowLeft');assert(!prevented);
control.dispose();assert.equal(events.size,0);
console.log('Hierarchy roving focus, bounds, filter/rerender restoration, empty/context guards and native selection keys passed.');
