import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {decodeScriptFacing,mountScriptFacing} from '../editor/script-facing.js';

const owner='scene://fixture/actors/man-p1/0003',script=owner.replace('scene://','script://');
function fixture({extended=false,p2=false,authored=true}={}){
  const boundOwner=p2?'scene://fixture/scripts/man-p2/0003':owner,boundScript=boundOwner.replace('scene://','script://'),prefix=p2?[0,0,0,0]:[0,0,0,0,0],offset=100;
  const npc=extended?[0xcc,9,0x51,8,9,0xa3,1]:[0x4c,0x51,8,9,0xa3,1],cam=extended?[0xb8,2,0xf5,0x80]:[0x38,0xf5,0x80];
  const raw=[...prefix,...npc,...cam],hash=createHash('sha256').update(Buffer.from(raw)).digest('hex'),record={byte_offset:offset,byte_length:raw.length,script_offset:prefix.length,sha256:hash,...(!p2?{raw_hex:Buffer.from(raw).toString('hex')}:{header:{prefix_word_count:0,c0_count:0,c1_count:0,c2_count:0}})},source={partition:p2?2:1,record_index:3,byte_offset:offset,byte_length:raw.length,byte_coordinate_space:'decoded_man_payload',sha256:hash,prot_entry_name:'fixture'};
  const node=(bytes,pc,mnemonic)=>{const header=extended?2:1;return {pc,byte_offset:offset+pc,length:bytes.length,raw_hex:Buffer.from(bytes).toString('hex'),opcode:mnemonic==='NPC_RUN'?0x4c:0x38,mnemonic,target_context:extended?(mnemonic==='NPC_RUN'?9:2):null,operands:{encoded_hex:Buffer.from(bytes.slice(header)).toString('hex'),...(mnemonic==='NPC_RUN'?{sub_op:0x51,x_encoded:8,z_encoded:9,depth_encoded:0xa3,move_id:1}:{})}};};
  const instructions=[node(npc,prefix.length,'NPC_RUN'),node(cam,prefix.length+npc.length,'CAM_CFG')];
  const targets=instructions.map(row=>{const before=row.mnemonic==='NPC_RUN'?0xa3:0xf5,values={sector:before&15},authored_values=authored&&row.mnemonic==='NPC_RUN'?{sector:6}:{};return {semantic_id:boundScript+'/facing/'+row.pc.toString(16).padStart(4,'0'),owner_id:boundOwner,pc:row.pc,mnemonic:row.mnemonic,target_context:row.target_context,decoded_byte_offset:offset+row.pc+(extended?2:1)+(row.mnemonic==='NPC_RUN'?3:0),source_record_sha256:hash,before_raw:before,preservation_mask:240,values,authored_values,effective_values:{...values,...authored_values}};});
  const report={schema_version:p2?'legaia.partition-two-script-inspection.v1':'legaia.actor-script-inspection.v1',read_only:true,...(p2?{script_id:boundScript}:{semantic_id:boundScript,actor_semantic_id:boundOwner}),source_record:source,record,instructions,stops:[],facing_authoring:{supported:true,reason:null,targets,unavailable:[],unresolved_overrides:[]}};
  return {owner:boundOwner,report};
}

for(const options of [{},{extended:true},{p2:true},{p2:true,extended:true}]){const {report,owner:sourceOwner}=fixture(options),before=structuredClone(report),decoded=decodeScriptFacing(report,sourceOwner);assert.equal(decoded.targets.length,2);assert.equal(decoded.targets[0].before_raw,0xa3);assert.equal(decoded.targets[0].effective_values.sector,6);decoded.targets[0].values.sector=0;decoded.unavailable.push({});assert.deepEqual(report,before);}
const p1Locator=fixture().report;delete p1Locator.source_record.sha256;delete p1Locator.source_record.partition;p1Locator.source_record.record_kind='man_partition_1_actor_placement';assert.equal(decodeScriptFacing(p1Locator,owner).targets.length,2);p1Locator.source_record.record_kind='unknown';assert.throws(()=>decodeScriptFacing(p1Locator,owner));
for(let sector=0;sector<8;sector++){const {report}=fixture();report.facing_authoring.targets[0].authored_values={sector};report.facing_authoring.targets[0].effective_values={sector};assert.equal(decodeScriptFacing(report,owner).targets[0].effective_values.sector,sector);}

const mutations=[
  r=>r.read_only=false,r=>r.schema_version='other',r=>r.semantic_id=script+'/wrong',r=>r.actor_semantic_id='other',r=>r.source_record.sha256='a'.repeat(64),r=>r.record.sha256='bad',r=>r.source_record.partition=2,r=>r.source_record.record_index=4,r=>r.source_record.byte_offset=-1,r=>r.record.byte_length--,r=>r.record.raw_hex='00',r=>r.source_record.prot_entry_name='other',r=>r.instructions.push(r.instructions[0]),r=>r.stops.push({pc:0,reason:'unknown'}),
  r=>r.facing_authoring.supported=false,r=>r.facing_authoring.targets.push(r.facing_authoring.targets[0]),r=>r.facing_authoring.targets[0].semantic_id=script+'/facing/0006',r=>r.facing_authoring.targets[0].owner_id='other',r=>r.facing_authoring.targets[0].mnemonic='MOVE_TO',r=>r.facing_authoring.targets[0].pc=true,r=>r.facing_authoring.targets[0].target_context=0,r=>r.facing_authoring.targets[0].decoded_byte_offset++,r=>r.facing_authoring.targets[0].source_record_sha256='b'.repeat(64),r=>r.facing_authoring.targets[0].before_raw=3,r=>r.facing_authoring.targets[0].preservation_mask=0xf8,r=>r.facing_authoring.targets[0].values.sector=4,r=>r.facing_authoring.targets[0].authored_values.sector=8,r=>r.facing_authoring.targets[0].effective_values.sector=3,r=>r.facing_authoring.targets[0].values.yaw=90,r=>r.facing_authoring.targets[0].initial_heading=3,
  r=>r.instructions[0].length--,r=>r.instructions[0].byte_offset++,r=>r.instructions[0].raw_hex='cc510809a301',r=>r.instructions[0].operands.encoded_hex='5108090301',r=>r.instructions[0].operands.depth_encoded=3,r=>r.instructions[0].operands.move_id=2,r=>r.instructions[1].raw_hex='38f501',r=>r.facing_authoring.unavailable.push({pc:5,mnemonic:'CAM_CFG',reason:3}),r=>r.facing_authoring.unresolved_overrides.push('script://other/actors/man-p1/0003/facing/0005'),r=>r.facing_authoring.unresolved_overrides.push(script+'/facing/0005')
];
for(const mutate of mutations){const {report}=fixture();mutate(report);assert.throws(()=>decodeScriptFacing(report,owner));}
const unsupported=fixture().report;unsupported.facing_authoring={supported:false,reason:'Source path stopped.',targets:[],unavailable:[{pc:5,mnemonic:'NPC_RUN',reason:'Low nibble is unsupported.'}],unresolved_overrides:[script+'/facing/0005']};unsupported.stops=[{pc:0,reason:'Unresolved source path'}];assert.equal(decodeScriptFacing(unsupported,owner).targets.length,0);
const p2Wrong=fixture({p2:true,extended:true});p2Wrong.report.instructions[0].raw_hex='cc08510809a301';assert.throws(()=>decodeScriptFacing(p2Wrong.report,p2Wrong.owner));
const parked=fixture({p2:true}).report;parked.instructions[0].raw_hex='4c517f7fa301';Object.assign(parked.instructions[0].operands,{encoded_hex:'517f7fa301',x_encoded:127,z_encoded:127});assert.throws(()=>decodeScriptFacing(parked,'scene://fixture/scripts/man-p2/0003'));

// Small DOM double exercises actual callbacks and lifecycle rather than UI snapshots.
class Node{
  constructor(tag,namespaceURI){this.tagName=tag;this.namespaceURI=namespaceURI;this.children=[];this.dataset={};this.attributes={};this.style={};this.textContent='';this.value='';this.disabled=false;this.hidden=false;this.classList={add:()=>{}};}
  append(...children){this.children.push(...children);for(const child of children)child.parent=this;}
  setAttribute(name,value){this.attributes[name]=String(value);}
  remove(){this.removed=true;if(this.parent)this.parent.children=this.parent.children.filter(child=>child!==this);}
}
const originalDocument=globalThis.document;globalThis.document={createElement:tag=>new Node(tag),createElementNS:(namespace,tag)=>new Node(tag,namespace)};
const descendants=node=>[node,...node.children.flatMap(descendants)],find=(node,tag,label)=>descendants(node).find(child=>child.tagName===tag&&(label===undefined||child.textContent===label)),deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
try{
  const {report}=fixture(),original=structuredClone(report),drafts=new Map();let current=true,busy=false,commands=[],errors=[],reopens=0,draftChanges=0,apiResult=true;
  const host=new Node('host'),settings={report,owner,current:()=>current,busy:()=>busy,setBusy:value=>{busy=value;},api:async(path,command)=>{assert.equal(busy,false,'The API owns busy');commands.push({path,command});return apiResult;},reopen:async()=>{reopens++;},onError:error=>errors.push(error),drafts,onDraftChange:()=>draftChanges++};
  let control=mountScriptFacing(host,settings),forms=descendants(host).filter(node=>node.tagName==='form'),form=forms[0],input=find(form,'input'),apply=find(form,'button','Apply facing'),clear=find(form,'button','Clear facing override'),discard=find(form,'button','Discard facing draft');
  assert.equal(forms.length,2);assert.equal(input.value,'6');assert.equal(discard.hidden,true);assert.equal(clear.disabled,false);assert.equal(find(forms[1],'button','Clear facing override').disabled,true);assert.ok(descendants(form).some(node=>node.textContent==='Retail'));assert.ok(descendants(form).some(node=>node.textContent==='3072'));assert.ok(descendants(form).some(node=>node.textContent.includes('initial or current heading remain unknown'))===false);
  const svg=find(form,'svg');assert.equal(svg.attributes['aria-label'],'Instruction operand preview · Sector 6 · 12-bit 3072 · 270°');assert.ok(descendants(form).some(node=>node.textContent.includes('Preserve mask 0xf0')));assert.ok(descendants(host).some(node=>node.textContent.includes('initial or current heading remain unknown')));
  input.value='7';input.oninput();assert.deepEqual(drafts.get(report.facing_authoring.targets[0].semantic_id),{sector:'7'});assert.equal(discard.hidden,false);assert.equal(svg.attributes['aria-label'],'Instruction operand preview · Sector 7 · 12-bit 3584 · 315°');assert.equal(draftChanges,1);
  input.value='7.5';input.oninput();assert.equal(apply.disabled,true);assert.equal(await form.onsubmit({preventDefault(){}}),false);assert.equal(commands.length,0);input.value='';input.oninput();assert.equal(apply.disabled,true);input.value='0';input.oninput();assert.equal(apply.disabled,false);
  busy=true;control.updateState();assert.equal(input.disabled,true);await form.onsubmit({preventDefault(){}});await clear.onclick();assert.equal(commands.length,0);busy=false;current=false;control.updateState();assert.equal(apply.disabled,true);await form.onsubmit({preventDefault(){}});current=true;control.updateState();
  assert.equal(await form.onsubmit({preventDefault(){}}),true);assert.deepEqual(commands[0],{path:'/api/command',command:{type:'set_facing_target',entity_id:owner,facing_id:report.facing_authoring.targets[0].semantic_id,values:{sector:0}}});assert.equal(reopens,1);assert.equal(drafts.has(report.facing_authoring.targets[0].semantic_id),false);
  assert.equal(await clear.onclick(),true);assert.equal(commands[1].command.type,'clear_facing_target');assert.equal(Object.hasOwn(commands[1].command,'values'),false);assert.equal(reopens,2);
  input.value='3';input.oninput();discard.onclick();assert.equal(input.value,'6');assert.equal(drafts.size,0);assert.equal(discard.hidden,true);
  apiResult=false;input.value='2';input.oninput();assert.equal(await form.onsubmit({preventDefault(){}}),false);assert.equal(drafts.size,1);assert.equal(reopens,2);assert.ok(descendants(host).some(node=>node.textContent.includes('draft remains available')));control.dispose();assert.equal(host.children.length,0);control.dispose();assert.equal(await clear.onclick(),false);assert.deepEqual(report,original);

  const pending=deferred();commands=[];current=true;busy=false;const pendingHost=new Node('host');control=mountScriptFacing(pendingHost,{...settings,api:(path,command)=>{commands.push(command);return pending.promise;}});form=find(pendingHost,'form');input=find(form,'input');clear=find(form,'button','Clear facing override');const applying=form.onsubmit({preventDefault(){}});assert.equal(find(form,'button','Apply facing').disabled,true);assert.equal(clear.disabled,true);await clear.onclick();await form.onsubmit({preventDefault(){}});assert.equal(commands.length,1);control.dispose();pending.resolve(true);assert.equal(await applying,false);assert.equal(reopens,2);

  const stale=deferred(),staleHost=new Node('host');control=mountScriptFacing(staleHost,{...settings,api:()=>stale.promise});form=find(staleHost,'form');const staleApply=form.onsubmit({preventDefault(){}});current=false;stale.resolve(true);assert.equal(await staleApply,false);assert.equal(reopens,2);control.dispose();current=true;
  const rejectionHost=new Node('host');control=mountScriptFacing(rejectionHost,{...settings,api:()=>Promise.reject(new Error('source changed'))});assert.equal(await find(rejectionHost,'form').onsubmit({preventDefault(){}}),false);assert.equal(errors.at(-1).message,'source changed');assert.ok(descendants(rejectionHost).some(node=>node.textContent==='source changed'));control.dispose();

  commands=[];const unsupportedHost=new Node('host');control=mountScriptFacing(unsupportedHost,{...settings,report:unsupported,api:async(path,command)=>{commands.push(command);return true;}});assert.equal(descendants(unsupportedHost).filter(node=>node.tagName==='form').length,0);assert.ok(descendants(unsupportedHost).some(node=>node.textContent.includes('Source path stopped')));await find(unsupportedHost,'button').onclick();assert.deepEqual(commands,[{type:'clear_facing_target',entity_id:owner,facing_id:script+'/facing/0005'}]);control.dispose();
  const badHost=new Node('host');const bad=structuredClone(report);bad.facing_authoring.targets[0].before_raw=0;control=mountScriptFacing(badHost,{...settings,report:bad});assert.equal(badHost.children.length,0);assert.ok(errors.at(-1).message.startsWith('Invalid source facing report:'));control.updateState();control.dispose();
}finally{if(originalDocument===undefined)delete globalThis.document;else globalThis.document=originalDocument;}
console.log('Facing source/header/byte/nibble and P1/P2 qualification; layer/compass drafts; Apply/Clear; invalid values; busy/stale/pending/dispose/error guards passed.');
