import assert from 'node:assert/strict';import fs from 'node:fs';
import {decodeAssetReferences,assetReferenceRelationLabel,assetReferenceInstructionSite} from '../editor/asset-references.js';
const owner='authored-actor://one',scene='scene://fixture',script='script://fixture/actors/man-p1/0001',flag='flag-reference://fixture/actors/man-p1/0001/current/global/2',key='a'.repeat(64);
const donor={donor_entity_id:'scene://fixture/actors/man-p1/0001',source_record_sha256:'b'.repeat(64),reference_commit:'d6e64c68ede25813d35db20980da82a1a025549b',record_index:1,byte_offset:100,byte_length:50,byte_coordinate_space:'decoded_lzs_descriptor',authored_draft_sha256:'c'.repeat(64),script_status:'decoded_supported_paths'};
const edge={id:'d'.repeat(64),source_id:owner,target_id:flag,kind:'npc_script_flag_operand',scene_id:scene,layer:'authored',runtime_binding:'not_asserted',pc:5,source_import_sha256:key,source_catalog_key:key,flag_reference_evidence:{bank:'global',index:2,scope:'host_global_flags',extended_target:null,grouping_layer:'retail',operation:'set',mnemonic:'GFLAG_SET'},npc_flag_operand_evidence:{donor,operand_id:script+'/flag-bit/0005',retail_index:2,authored_index:4,effective_index:4,authored_operand_qualified:true}};
const report={schema_version:'legaia.asset-references.v1',asset_id:flag,source_key:key,read_only:true,nodes:[{id:owner,kind:'actor',scene_id:scene,label:'NPC',available:true},{id:flag,kind:'flag',scene_id:scene,label:'Source flag group',available:true}],incoming:[edge],outgoing:[],coverage:{verified_scene_ids:[scene],resource_scene_id:scene,unresolved_reference_count:0},limitations:['No runtime variables asserted.']};
const decoded=decodeAssetReferences(report,flag,key);assert(assetReferenceRelationLabel(edge).includes('NPC Current authored global flag operand 4'));const site=assetReferenceInstructionSite(edge,new Map(decoded.nodes.map(node=>[node.id,node])));assert.equal(site.script_id,script);assert.equal(site.owner_id,donor.donor_entity_id);assert.equal(site.pc,5);assert.equal(site.source_record_sha256,donor.source_record_sha256);
for(const mutate of [r=>r.incoming[0].npc_flag_operand_evidence.donor.source_record_sha256='bad',r=>r.incoming[0].npc_flag_operand_evidence.donor.reference_commit='0'.repeat(40),r=>r.incoming[0].npc_flag_operand_evidence.donor.authored_draft_sha256='bad',r=>r.incoming[0].npc_flag_operand_evidence.donor.record_index=2,r=>r.incoming[0].npc_flag_operand_evidence.authored_operand_qualified=false,r=>r.incoming[0].npc_flag_operand_evidence.operand_id=script+'/flag-bit/0007',r=>r.incoming[0].npc_flag_operand_evidence.effective_index=3,r=>r.incoming[0].npc_flag_operand_evidence.authored_index=true,r=>r.incoming[0].layer='decoded',r=>r.incoming[0].pc=50,r=>r.nodes[0].kind='script',r=>r.nodes[0].available=false,r=>r.incoming[0].npc_flag_operand_evidence.runtime_value=1,r=>r.incoming[0].flag_reference_evidence.scope='dispatch_context_flags',r=>r.incoming[0].kind='script_flag_reference']){const broken=structuredClone(report);mutate(broken);assert.throws(()=>decodeAssetReferences(broken,flag,key));}
const duplicate=structuredClone(report);duplicate.incoming.push({...structuredClone(edge),id:'e'.repeat(64)});assert.throws(()=>decodeAssetReferences(duplicate,flag,key));
const inherited=structuredClone(report);inherited.incoming[0].npc_flag_operand_evidence.authored_index=null;inherited.incoming[0].npc_flag_operand_evidence.authored_operand_qualified=false;inherited.incoming[0].npc_flag_operand_evidence.effective_index=2;inherited.incoming[0].npc_flag_operand_evidence.donor.script_status='partial';decodeAssetReferences(inherited,flag,key);assert(assetReferenceRelationLabel(inherited.incoming[0]).includes('inherited Retail'));
const forged=structuredClone(report),other={...structuredClone(edge),id:'e'.repeat(64),pc:7};other.npc_flag_operand_evidence.operand_id=script+'/flag-bit/0007';other.npc_flag_operand_evidence.donor.authored_draft_sha256='f'.repeat(64);forged.incoming.push(other);assert.throws(()=>decodeAssetReferences(forged,flag,key));
console.log('NPC flag graph contracts, Retail/Current separation, donor instruction sites and malformed/live/duplicate ownership guards passed.');
if(process.argv[2]){const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));for(const row of fixture.reports){const report=decodeAssetReferences(row.report,row.id,fixture.source_key,row.scope??'active');assert([...report.incoming,...report.outgoing].some(edge=>edge.kind==='npc_script_flag_operand'));}console.log('Fresh actual retail NPC and inverse flag reports decoded.');}
