import assert from 'node:assert/strict';
import {hierarchyGroupExpanded,revealHierarchyEntity} from '../editor/hierarchy-groups.js';
const state={collapsed:new Set(['actors','script'])};
assert.equal(hierarchyGroupExpanded('actors',state),false);assert.equal(hierarchyGroupExpanded('environment',state),true);
assert.equal(hierarchyGroupExpanded('actors',state,'actor 0002'),true);assert.equal(hierarchyGroupExpanded('actors',state,'  '),false);
assert.deepEqual([...state.collapsed],['actors','script']);
for(const id of ['Unknown','__proto__','constructor',null])assert.throws(()=>hierarchyGroupExpanded(id,state));
assert.throws(()=>hierarchyGroupExpanded('actors',{collapsed:[]}));
console.log('Hierarchy folds use explicit UI groups; search expands presentation without changing saved folds.');
const events=[],header={dataset:{hierarchyGroup:'actors'},getAttribute:()=> 'false',click(){events.push('expand');row.hidden=false;}};
const row={title:'scene://fixture/actors/man-p1/0001',hidden:true,disabled:false,previousElementSibling:header,scrollIntoView:options=>events.push(['scroll',options]),focus:options=>events.push(['focus',options])},root={querySelectorAll:()=>[row]};
assert.equal(revealHierarchyEntity(root,row.title),true);assert.deepEqual(events,['expand',['scroll',{block:'nearest'}],['focus',{preventScroll:true}]]);
assert.equal(revealHierarchyEntity(root,'unknown'),false);row.disabled=true;assert.equal(revealHierarchyEntity(root,row.title),false);assert.equal(revealHierarchyEntity(root,null),false);
console.log('Reveal expands an exact selected row and focuses without dispatching its entity selection action.');
