import assert from 'node:assert/strict';
import {sceneAnimationContext,decodeSceneAnimation,sceneAnimationSamples,sceneAnimationFrameIndex,createSceneAnimationController} from '../editor/scene-animation.js';

const h=letter=>letter.repeat(64),context={projectPath:'C:/private/scene-project',sceneId:'scene://town01',mode:'edit',sourceKey:h('a'),sceneSourceKey:h('b'),representation:'authored',ready:true,canStart:true};
const actor=index=>`scene://town01/actors/man-p1/${String(index).padStart(4,'0')}`,model=index=>`asset://town01/models/scene-tmd/${String(index).padStart(4,'0')}`;
const track=(key,index,frames,kind='imported_scene_animation_frame0')=>({geometry_key:key,asset_id:model(index),clip_id:`animation://town01/scene-anm/${String(index).padStart(4,'0')}`,pose_kind:kind,frame_count:frames,vertex_count:2,frames:Array.from({length:frames},(_,frame)=>[[frame,index,0],[frame+1,index,0]])});
const fixture=()=>({schema_version:'legaia.scene-animation.v1',scene_id:context.sceneId,project_source_key:context.sourceKey,scene_source_key:context.sceneSourceKey,representation:'authored',tracks:[track('geometry-a',0,2),track('geometry-b',1,3,'reference_party_idle')],instances:[{entity_id:actor(0),geometry_key:'geometry-a',asset_id:model(0),source_actor_id:actor(0)},{entity_id:actor(1),geometry_key:'geometry-a',asset_id:model(0),source_actor_id:actor(1)},{entity_id:actor(2),geometry_key:'geometry-b',asset_id:model(1),source_actor_id:actor(2)}],unavailable_instances:[{entity_id:actor(3),geometry_key:null,asset_id:null,pose_kind:'unavailable',reason:'Source clip assignment unavailable.'}],metrics:{animated_instances:3,static_or_unavailable_instances:1,track_count:2,frame_vertex_count:10,max_frame_count:3},limitations:['Caller-selected display rate, no retail timing claim.','Every qualified source clip loops by preview convention.'],project_changed:false,gameplay_verified:false});
const empty=()=>({...fixture(),tracks:[],instances:[],metrics:{animated_instances:0,static_or_unavailable_instances:1,track_count:0,frame_vertex_count:0,max_frame_count:0}});
const withNormals=()=>{const report=fixture(),track=report.tracks[0];track.normal_pose={source:{posed:false,vertices:track.frames[0],triangles:[[0,1,1]],objects:[{object_index:0,vertex_start:0,vertex_count:2,triangle_start:0,triangle_count:1}],triangle_normals:[[[4096,0,0],[0,4096,0],[0,0,0]]],normal_preview:{status:'source_unposed',coordinate_system:'retail_tmd_object_local'}},frames:track.frames.map((_,i)=>({posed:true,coordinate_system:'retail_psx_actor_local_y_down',object_transforms:[{object_index:0,rotation_psx:[0,0,i*1024],translation:[i,0,0]}]}))};return report;};
const qualified=decodeSceneAnimation(withNormals(),context),normalSample=sceneAnimationSamples(qualified,1)[0];assert(Math.abs(normalSample.normal_preview.triangle_normals[0][0][1]-4096)<1e-8);assert.equal(sceneAnimationSamples(qualified,2)[0].normal_preview.triangle_normals[0][0][0],4096);assert.equal(sceneAnimationSamples(qualified,1)[1].normal_preview,undefined);
for(const mutate of [v=>v.tracks[0].normal_pose.frames.pop(),v=>v.tracks[0].normal_pose.source.triangle_normals[0][0][0]=1.5,v=>v.tracks[0].normal_pose.frames[0].object_transforms[0].object_index=1,v=>v.tracks[0].normal_pose.source.vertices.pop(),v=>v.tracks[0].normal_pose.source.objects[0].triangle_count=0]){const value=withNormals();mutate(value);assert.throws(()=>decodeSceneAnimation(value,context));}
const normalBudget=withNormals(),limitedTrack=normalBudget.tracks[0];limitedTrack.frame_count=4096;limitedTrack.frames=Array.from({length:4096},()=>limitedTrack.frames[0]);limitedTrack.normal_pose.frames=Array.from({length:4096},()=>limitedTrack.normal_pose.frames[0]);limitedTrack.normal_pose.source.triangles=new Array(1000).fill([0,1,1]);assert.throws(()=>decodeSceneAnimation(normalBudget,context),/three million/);
assert.deepEqual(sceneAnimationContext(context),context);for(const patch of [{mode:'live'},{sceneId:null},{sourceKey:'old'},{ready:1},{representation:'proposed'},{extra:true}])assert.throws(()=>sceneAnimationContext({...context,...patch}));
const original=fixture(),decoded=decodeSceneAnimation(original,context);decoded.tracks[0].frames[0][0][0]=9;assert.equal(original.tracks[0].frames[0][0][0],0);assert.deepEqual(sceneAnimationSamples(original,2).map(row=>[row.geometry_key,row.frame_index]),[['geometry-a',0],['geometry-b',2]]);for(const [tick,indices] of [[3,[1,0]],[4,[0,1]],[6,[0,0]]]){const rows=sceneAnimationSamples(original,tick);assert.deepEqual(rows.map(row=>row.frame_index),indices,'Each clip must preserve its independent phase after the longest clip boundary.');assert.equal(rows[0].vertices,original.tracks[0].frames[indices[0]],'Absolute sampling reuses qualified source frames without allocation.');}for(const invalid of [-1,.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>sceneAnimationSamples(original,invalid));assert.equal(sceneAnimationSamples(original,Number.MAX_SAFE_INTEGER)[0].frame_index,1);assert.equal(decodeSceneAnimation(empty(),context).tracks.length,0);
for(const mutate of [value=>value.project_source_key=h('c'),value=>value.scene_source_key=h('c'),value=>value.representation='retail',value=>value.tracks[1].geometry_key='geometry-a',value=>value.tracks[0].pose_kind='guessed_animation',value=>value.tracks[0].frame_count=3,value=>value.tracks[0].frames[0][0][0]=NaN,value=>value.tracks[0].frames[0].pop(),value=>value.instances[0].asset_id=model(99),value=>value.instances[0].source_actor_id=null,value=>value.instances[1].entity_id=actor(0),value=>value.unavailable_instances[0].entity_id=actor(0),value=>value.unavailable_instances[0].reason='',value=>value.metrics.frame_vertex_count++,value=>value.metrics.max_frame_count=4,value=>value.metrics.animated_instances=4,value=>value.gameplay_verified=true]){const value=fixture();mutate(value);assert.throws(()=>decodeSceneAnimation(value,context));}
const unbound=fixture();unbound.instances=unbound.instances.filter(row=>row.geometry_key!=='geometry-b');unbound.metrics.animated_instances=2;assert.throws(()=>decodeSceneAnimation(unbound,context));const budget=fixture();budget.tracks[0]={...budget.tracks[0],frame_count:4096,vertex_count:100000,frames:Array.from({length:4096},()=>[])};assert.throws(()=>decodeSceneAnimation(budget,context),/one million/);

for(const count of [1,2,3,31,4096])for(const tick of [0,1,2,31,4096,Number.MAX_SAFE_INTEGER])for(const offset of [0,count-1])for(const mode of ['loop','hold','ping_pong','freeze']){
 const n=BigInt(count),t=BigInt(tick)+BigInt(offset),period=2n*(n-1n);
 const expected=count===1||mode==='freeze'?offset:mode==='hold'?Number(t<n?t:n-1n):mode==='loop'?Number(t%n):Number(t%period<n?t%period:period-t%period);
 assert.equal(sceneAnimationFrameIndex(count,tick,{mode,offset}),expected);
}
for(const settings of [new Map([['foreign',{mode:'loop',offset:0}]]),new Map([['geometry-a',{mode:'loop',offset:2}]]),new Map([['geometry-a',{mode:'foreign',offset:0}]]),new Map([['geometry-a',{mode:'freeze',offset:true}]]),new Map([['geometry-a',{mode:'loop',offset:0,extra:1}]]),{}])assert.throws(()=>sceneAnimationSamples(fixture(),0,settings));
const normalTrack=withNormals(),phasedNormalSample=sceneAnimationSamples(normalTrack,1)[0];assert.deepEqual(sceneAnimationSamples(normalTrack,0,new Map([['geometry-a',{mode:'freeze',offset:1}]]))[0],phasedNormalSample);

class Node {constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.style={};this.dataset={};this.textContent='';this.value='';this.disabled=false;}append(...nodes){this.children.push(...nodes);for(const node of nodes)node.parent=this;}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(key,value){this.attributes[key]=String(value);}remove(){this.removed=true;}}
const tree=node=>[node,...node.children.flatMap(tree)],action=(controller,name)=>tree(controller.element).find(node=>node.dataset.action===name),input=(controller,name)=>tree(controller.element).find(node=>node.attributes['aria-label']===name),hasText=(controller,fragment)=>tree(controller.element).some(node=>node.textContent.includes(fragment)),deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const globals={document:globalThis.document,fetch:globalThis.fetch,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame},listeners=new Map(),frames=new Map();let frameId=0;
globalThis.document={hidden:false,createElement:tag=>new Node(tag),addEventListener:(kind,callback)=>listeners.set(kind,callback),removeEventListener:(kind,callback)=>{if(listeners.get(kind)===callback)listeners.delete(kind);}};globalThis.requestAnimationFrame=callback=>{const id=++frameId;frames.set(id,callback);return id;};globalThis.cancelAnimationFrame=id=>frames.delete(id);const pump=time=>{const next=frames.entries().next().value;assert.ok(next,'A playback frame must be scheduled');frames.delete(next[0]);next[1](time);};
try{
  let ctx=structuredClone(context),isBusy=false,controller=null,calls=[],queue=[],errors=[],statuses=[],loads=[],samples=[],restores=[];
  globalThis.fetch=async(path,options)=>{calls.push({path,body:JSON.parse(options.body),signal:options.signal});const next=queue.shift(),value=next instanceof Promise?await next:next;assert.ok(value,'Queue a source report');return {ok:!value.error,text:async()=>JSON.stringify(value)};};
  const settings={getContext:()=>ctx,busy:()=>isBusy,setBusy:value=>{isBusy=value;controller?.updateState();},onError:value=>errors.push(value),onLoad:(value,options)=>{loads.push({value,options});ctx={...ctx,canStart:false};return true;},onSample:(rows,value)=>{samples.push({rows,value});return true;},onRestore:value=>{restores.push(value);ctx={...ctx,canStart:true};},onStatus:value=>{statuses.push(value);controller?.updateState();}};
  const open=extra=>{controller=null;controller=createSceneAnimationController({...settings,...extra});return controller;},start=async(value=fixture())=>{queue=[value];assert.equal(await controller.start(),true);};
  ctx={projectPath:undefined,sceneId:null,mode:undefined,sourceKey:undefined,sceneSourceKey:undefined,representation:'authored',ready:false,canStart:true};open();assert.equal(controller.active(),false);assert.equal(action(controller,'start').disabled,true);assert.equal(calls.length,0);ctx=structuredClone(context);controller.updateState();assert.equal(action(controller,'start').disabled,false);const statusCount=statuses.length;controller.updateState();assert.equal(statuses.length,statusCount,'Status callbacks must not recurse for unchanged state.');await start();assert.deepEqual(calls.at(-1).body,{representation:'authored',source_key:h('a')});assert.equal(calls.at(-1).path,'/api/scene-animation-preview');assert.equal(controller.active(),true);assert.equal(ctx.canStart,false,'Parent exclusive ownership must not stale an accepted load.');assert.equal(isBusy,false);assert.equal(Object.isFrozen(loads.at(-1).value.tracks[0].frames[0][0]),true);assert.equal(Object.isFrozen(samples.at(-1).rows),true);assert.equal(samples.at(-1).rows[0].frame_index,0);assert.equal(input(controller,'Scene animation preview tick').max,'2');assert.equal(hasText(controller,'3 animated'),true);assert.equal(hasText(controller,'reference_party_idle'),true);assert.equal(hasText(controller,'Source clip assignment unavailable.'),true);assert.equal(await controller.start(),false,'Start cannot overlap an active session.');
  input(controller,'Scene animation preview tick').value='2';assert.equal(input(controller,'Scene animation preview tick').oninput(),true);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[0,2]);const sampleCount=samples.length;assert.equal(action(controller,'play').onclick(),true);pump(0);pump(220);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[0,1]);assert.equal(input(controller,'Scene animation preview tick').value,'4');assert.equal(input(controller,'Scene animation preview tick').max,'4');assert.equal(hasText(controller,'absolute tick 4'),true);assert.equal(samples.length,sampleCount+1);assert.equal(action(controller,'play').onclick(),true);assert.equal(frames.size,0);assert.equal(controller.active(),true,'Pause retains transient ownership until Restore.');const rate=input(controller,'Scene animation preview fps');rate.value='31';assert.equal(rate.onchange(),false);assert.equal(action(controller,'play').disabled,true);rate.value='15';assert.equal(rate.onchange(),true);assert.equal(action(controller,'play').disabled,false);action(controller,'play').onclick();pump(300);pump(440);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[0,0]);assert.equal(input(controller,'Scene animation preview tick').value,'6');document.hidden=true;listeners.get('visibilitychange')();assert.equal(frames.size,0);assert.equal(controller.active(),true);document.hidden=false;controller.updateState();assert.equal(frames.size,0,'Visibility restoration must not resume playback automatically.');const restoreCount=restores.length;assert.equal(controller.stop(),true);assert.equal(restores.length,restoreCount+1);assert.equal(controller.active(),false);assert.equal(controller.stop(),false);controller.dispose();assert.equal(listeners.size,0);
  ctx=structuredClone(context);open();await start();assert.equal(action(controller,'play').onclick(),true);pump(0);for(const [time,tick,indices] of [[105,1,[1,1]],[215,2,[0,2]],[325,3,[1,0]],[435,4,[0,1]],[650,6,[0,0]]]){pump(time);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),indices);assert.equal(input(controller,'Scene animation preview tick').value,String(tick));assert.equal(input(controller,'Scene animation preview tick').max,String(Math.max(2,tick)));}assert.equal(action(controller,'play').onclick(),true);const absoluteScrub=input(controller,'Scene animation preview tick');absoluteScrub.value='3';assert.equal(absoluteScrub.oninput(),true);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[1,0]);assert.equal(absoluteScrub.max,'6','Scrubbing backward retains the complete elapsed range.');absoluteScrub.value='6';assert.equal(absoluteScrub.oninput(),true);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[0,0]);absoluteScrub.value='7';assert.equal(absoluteScrub.oninput(),false);assert.equal(absoluteScrub.value,'6');controller.dispose();
  ctx=structuredClone(context);open();await start();assert.equal(action(controller,'play').onclick(),true);pump(0);pump(Number.MAX_SAFE_INTEGER*100);assert.equal(input(controller,'Scene animation preview tick').value,String(Number.MAX_SAFE_INTEGER));assert.equal(input(controller,'Scene animation preview tick').max,String(Number.MAX_SAFE_INTEGER));const safeSamples=samples.length;pump(Number.MAX_SAFE_INTEGER*100+100);assert.equal(samples.length,safeSamples,'Overflow must not produce an unsafe sample or wrap clip phase.');assert.equal(frames.size,0);assert.equal(controller.active(),true);assert.equal(hasText(controller,'safe integer limit'),true);controller.dispose();
  ctx=structuredClone(context);open();const loadCount=loads.length;queue=[empty()];assert.equal(await controller.start(),false);assert.equal(loads.length,loadCount);assert.equal(controller.active(),false);assert.equal(hasText(controller,'No qualified animated tracks'),true);assert.equal(isBusy,false);controller.dispose();
  ctx=structuredClone(context);open({onLoad:()=>false});queue=[fixture()];const failedRestore=restores.length;assert.equal(await controller.start(),false);assert.equal(controller.active(),false);assert.equal(restores.length,failedRestore+1);controller.dispose();
  ctx=structuredClone(context);open({onSample:()=>false});queue=[fixture()];const sampleRestore=restores.length;assert.equal(await controller.start(),false);assert.equal(controller.active(),false);assert.equal(restores.length,sampleRestore+1);assert.equal(isBusy,false);controller.dispose();
  ctx=structuredClone(context);open();const waiting=deferred();queue=[waiting.promise];const starting=controller.start(),sourceSignal=calls.at(-1).signal;assert.equal(controller.active(),true,'Loading claims the authoring gate immediately.');assert.equal(isBusy,true);assert.equal(action(controller,'stop').disabled,false);const oldLoadCount=loads.length;ctx={...ctx,sourceKey:h('c')};controller.updateState();assert.equal(sourceSignal.aborted,true);assert.equal(controller.active(),false);assert.equal(isBusy,false);isBusy=true;waiting.resolve(fixture());assert.equal(await starting,false);assert.equal(loads.length,oldLoadCount);assert.equal(isBusy,true,'Late source results must not release another busy owner.');isBusy=false;controller.dispose();
  ctx=structuredClone(context);let loadOptions;const loadWait=deferred();open({onLoad:(value,options)=>{loads.push({value,options});loadOptions=options;ctx={...ctx,canStart:false};return loadWait.promise;}});queue=[fixture()];const loading=controller.start();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(controller.active(),true);const pendingRestore=restores.length;assert.equal(controller.stop(),true);assert.equal(loadOptions.signal.aborted,true);assert.equal(loadOptions.isCurrent(),false);assert.equal(restores.length,pendingRestore+1);loadWait.resolve(true);assert.equal(await loading,false);assert.equal(restores.length,pendingRestore+1,'Late onLoad must not restore a second time.');assert.equal(controller.active(),false);controller.dispose();
  ctx=structuredClone(context);open();await start();action(controller,'play').onclick();pump(0);const staleRestores=restores.length;ctx={...ctx,representation:'retail',sceneSourceKey:h('c')};controller.updateState();assert.equal(controller.active(),false);assert.equal(restores.length,staleRestores+1);assert.equal(frames.size,0);assert.equal(hasText(controller,'load fresh coverage'),true);controller.dispose();
  ctx={...context,representation:'retail',sceneSourceKey:h('c')};open();const retail={...fixture(),representation:'retail',scene_source_key:h('c')};await start(retail);assert.deepEqual(calls.at(-1).body,{representation:'retail',source_key:h('a')});assert.equal(hasText(controller,'Retail offline scene preview'),true);isBusy=true;controller.updateState();assert.equal(action(controller,'play').disabled,true);isBusy=false;controller.updateState();assert.equal(action(controller,'play').disabled,false);controller.dispose();assert.equal(controller.active(),false);assert.equal(isBusy,false);
  ctx=structuredClone(context);open();const closing=deferred();queue=[closing.promise];const closingStart=controller.start(),closeSignal=calls.at(-1).signal,previousErrors=errors.length;controller.dispose();closing.resolve({error:'Late closed error'});assert.equal(await closingStart,false);assert.equal(closeSignal.aborted,true);assert.equal(errors.length,previousErrors);assert.equal(isBusy,false);
  ctx=structuredClone(context);open();await start();const samplesBefore=samples.length;action(controller,'play').onclick();pump(0);ctx={...ctx,ready:false};pump(300);assert.equal(controller.active(),false);assert.equal(samples.length,samplesBefore);assert.equal(frames.size,0);controller.dispose();
  ctx=structuredClone(context);const views=[];open({onNormalView:value=>views.push(value)});await start(withNormals());const normal=input(controller,'Scene animation source normal directions');assert.equal(normal.disabled,false);assert.equal(Object.isFrozen(loads.at(-1).value.tracks[0].normal_pose.source.triangle_normals[0][0]),true);normal.checked=true;assert.equal(normal.onchange(),true);assert.deepEqual(views,[true]);controller.stop();assert.equal(normal.checked,false);assert.equal(normal.disabled,true);assert.deepEqual(views,[true,false]);controller.dispose();
  {ctx=structuredClone(context);open();await start();
  const previewInputs=()=>[input(controller,'Track preview mode geometry-a'),input(controller,'Track preview phase offset geometry-a'),input(controller,'Track preview mode geometry-b'),input(controller,'Track preview phase offset geometry-b')];
  const [modeA,offsetA,modeB,offsetB]=previewInputs(),sourceBefore=JSON.stringify(loads.at(-1).value),requestCount=calls.length;
  modeA.value='freeze';assert.equal(modeA.onchange(),true);offsetA.value='1';assert.equal(offsetA.onchange(),true);
  modeB.value='ping_pong';assert.equal(modeB.onchange(),true);offsetB.value='1';assert.equal(offsetB.onchange(),true);
  assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[1,1]);
  assert.equal(action(controller,'play').onclick(),true);pump(0);pump(300);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[1,0]);
  modeB.value='hold';assert.equal(modeB.onchange(),true);assert.equal(frames.size,0);assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[1,2]);
  const sampleCount=samples.length;offsetB.value='3';assert.equal(offsetB.onchange(),false);assert.equal(offsetB.value,'1');assert.equal(samples.length,sampleCount);
  isBusy=true;controller.updateState();assert(previewInputs().every(n=>n.disabled));modeB.value='loop';assert.equal(modeB.onchange(),false);isBusy=false;modeB.value='hold';controller.updateState();
  assert.equal(JSON.stringify(loads.at(-1).value),sourceBefore);assert.equal(calls.length,requestCount);
  controller.stop();assert(previewInputs().every(n=>n.disabled));assert.equal(modeA.value,'loop');assert.equal(offsetA.value,'0');
  await start();assert.deepEqual(samples.at(-1).rows.map(row=>row.frame_index),[0,0]);ctx={...ctx,sourceKey:h('f')};controller.updateState();assert.equal(controller.active(),false);assert(previewInputs().every(n=>!n||n.disabled));controller.dispose();
  }
}finally{for(const [key,value] of Object.entries(globals)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
console.log('Scene animation source/coverage/budget qualification; coordinated modulo samples, preview fps/play/scrub, no-track and failed-load/sample restore, loading/source/representation/late/busy/dispose guards passed.');
