import assert from 'node:assert/strict';
import {ANIMATION_PRESET_SCOPE,decodePresetAnimation,validatePresetComponentChange,decodePresetAnimationScene,presetReviewContext,validatePresetMetadata} from '../editor/preset-animation.js';
import {decodeActorPresetReview,decodeActorPresetScene} from '../editor/actor-preset-review.js';
import {decodePresetBatch,decodePresetBatchScene} from '../editor/preset-batch.js';
import {decodePresetFileExport,decodePresetImportReview} from '../editor/preset-files.js';
const scene='scene://town0b',entity=scene+'/actors/man-p1/0019',donor=scene+'/actors/man-p1/0049',other=scene+'/actors/man-p1/0050',model='asset://town0b/models/scene-tmd/0102',sourceKey='1'.repeat(64),sourceHash='2'.repeat(64),alternateHash='3'.repeat(64),reviewKey='4'.repeat(64);
function binding(id,index,sha){const skeleton='skeleton://town0b/models/scene-tmd/0102';return {schema_version:'legaia.animation-preview.v1',semantic_id:`animation://town0b/scene-anm/${String(index).padStart(4,'0')}`,asset_semantic_id:model,actor_semantic_id:id,clip_id:'placement',label:'Observed clip',reference_commit:'d6e64c68ede25813d35db20980da82a1a025549b',source_record:{disc:{sha256:'5'.repeat(64),serial:'SCUS-94254'},iso_file:'PROT.DAT',prot_entry_index:10,prot_entry_name:'town0b',scene_table_offset:24,descriptor_index:3,descriptor_type:5,compressed_stream_offset:128,compressed_bytes_consumed:256,record_index:index,byte_offset:96,byte_length:80,containing_size:4096,byte_coordinate_space:'decoded_scene_anm_descriptor',record_sha256:sha},frame_count:4,bone_count:2,header_a:2,header_flags:2,coordinate_system:'retail_psx_actor_local_y_down',looping:null,timing:{fps:null,wire_rate:null,evidence:'unresolved_scene_actor_playback_rate',note:'Rate unresolved.'},association:{kind:'verified_man_header_scene_anm_record_plus_one',animation_id:index+1,actor_source_record:{record_index:Number(id.slice(-4))},active_object_indices:[0,1],excluded_object_indices:[]},skeleton:{semantic_id:skeleton,topology:'independent_rigid_objects',hierarchy:null,channels:[0,1].map(i=>({semantic_id:`${skeleton}/channels/${String(i).padStart(2,'0')}`,object_index:i,parent_index:null}))},limitations:['Initial header only.']};}
const imported=binding(entity,13,sourceHash),alternate=binding(donor,12,alternateHash),assignment=b=>({donor_entity_id:b.actor_semantic_id,animation_asset_id:b.semantic_id,source_record_sha256:b.source_record.record_sha256});
const reference={asset_semantic_id:model,model_index:102,resolution_status:'resolved'},witness=b=>({entity_id:b.actor_semantic_id,source_record:structuredClone(b.association.actor_source_record),model_reference:structuredClone(reference)});
const animation={imported,base:imported,effective:imported,proposed:alternate,authored:null,after:assignment(alternate),witness:witness(alternate)};
const before={Transform:{position:{x:128}},Dialogue:{runs:{one:'Retained'}},AnimationChannels:{source_record_sha256:sourceHash,edits:[{frame_index:0,object_index:0,translation:{x:3}}]}},after={...structuredClone(before),ActorAnimation:assignment(alternate)};
const template={id:'template://12345678-1234-1234-1234-123456789abc',name:'Observed initial clip',scope:ANIMATION_PRESET_SCOPE,source:{disc_identity:'sha256:'+sourceHash,scene_id:scene,entity_id:entity},components:{ActorAnimation:assignment(alternate)}};
function actorState(id,b){return {id,components:{Transform:{imported:{position:{x:64,y:null,z:256}},authored:{position:{x:128}},effective:{position:{x:128,y:null,z:256}}},ActorAppearance:{authored:{}},ActorAnimation:{authored:{},effective:{animation_asset_id:b.semantic_id,donor_entity_id:b.actor_semantic_id}},ModelRenderer:{asset_id:model}}};}
const state={project:{path:'C:/private/preset',mode:'edit'},scene:{id:scene,entities:[actorState(entity,imported),actorState(other,binding(other,13,sourceHash))]},selection:{entity_id:entity},scene_preview_source_key:sourceKey,asset_reference_source_key:sourceKey,actor_templates:[template]};
const layers={imported_position:{x:64,y:null,z:256},authored_position:{x:128},effective_position:{x:128,y:null,z:256},proposed_position:{x:128,y:null,z:256},authored_donor:null,proposed_donor:null};
const report={schema_version:'legaia.actor-preset-review.v1',template_id:template.id,scope:template.scope,entity_id:entity,review_key:reviewKey,before,after,layers,appearance:null,animation,changed:true,build_issues:[],limitations:[]};
const decoded=decodeActorPresetReview(report,template,state.scene.entities[0],state);decoded.animation.witness.source_record.record_index=0;assert.equal(report.animation.witness.source_record.record_index,49);
for(const mutate of [r=>r.animation.proposed.source_record.record_sha256=sourceHash,r=>r.animation.witness.entity_id=entity,r=>r.animation.witness.model_reference.model_index=103,r=>r.animation.after.donor_entity_id=entity,r=>r.after.Dialogue.runs.one='Changed',r=>r.after.AnimationChannels.edits[0].translation.x=4,r=>r.after.ActorAnimation.source_record_sha256=sourceHash,r=>r.layers.proposed_position.x=64,r=>r.layers.proposed_donor=donor,r=>r.animation.authored=assignment(alternate),r=>r.scope='authored-actor-preset-v1']){const bad=structuredClone(report);mutate(bad);assert.throws(()=>decodeActorPresetReview(bad,template,state.scene.entities[0],state));}
// Final inherited appearance can differ from the target's current appearance.
const inherited=structuredClone(animation);inherited.base=alternate;inherited.after=null;decodePresetAnimation(inherited,entity,scene);
const inheritedRow={entity_id:entity,before,after:structuredClone(before),animation:inherited};validatePresetComponentChange(inheritedRow,template,state.scene.entities[0],scene);
// A qualified noncanonical saved witness is retained when the clip is omitted.
const retainedBefore={...structuredClone(before),ActorAnimation:assignment(alternate)},retainedAnimation={...structuredClone(animation),authored:assignment(alternate),effective:alternate};
const retainedRow={entity_id:entity,before:retainedBefore,after:{...structuredClone(retainedBefore),Transform:{position:{x:512}}},animation:retainedAnimation};
const legacy={...structuredClone(template),scope:'authored-position-v1',components:{Transform:{position:{x:512}}}},retainedActor=actorState(entity,alternate);retainedActor.components.ActorAnimation.authored=assignment(alternate);validatePresetComponentChange(retainedRow,legacy,retainedActor,scene);
for(const key of ['scene_preview_source_key','asset_reference_source_key']){const changed=structuredClone(state);changed[key]='9'.repeat(64);assert.notEqual(presetReviewContext(changed,[entity],template.id),presetReviewContext(state,[entity],template.id));}
for(const mutate of [s=>s.project.mode='live',s=>s.project.path='C:/other',s=>s.selection.entity_id=donor,s=>s.scene.id='scene://dolk2',s=>s.scene.entities[0].components.ActorAnimation.authored=assignment(alternate),s=>s.actor_templates[0].components.ActorAnimation.source_record_sha256=sourceHash]){const changed=structuredClone(state);mutate(changed);assert.notEqual(presetReviewContext(changed,[entity],template.id),presetReviewContext(state,[entity],template.id));}

const position={x:128,y:null,z:256},previewPosition={x:128,y:32,z:256},displayPosition={x:128,y:-32,z:256};
function instance(id,b,key){return {entity_id:id,asset_id:model,source_actor_id:id,source_record:structuredClone(b.association.actor_source_record),model_reference:structuredClone(reference),appearance_authored:false,animation_assignment_authored:false,renderable:true,geometry_key:key,pose_kind:'imported_scene_animation_frame0',reason:null,position:structuredClone(position),preview_position:structuredClone(previewPosition),display_position:structuredClone(displayPosition),preview_ground_sample:{y:32,cell_index:0},preview_height_status:'source_surface',model_to_scene:[1,0,0,128,0,-1,0,-32,0,0,1,256,0,0,0,1],authored_position:{x:128},evidence:{position:'source and authored',heading:'unknown',scale:'unknown'}};}
function geometry(b,key){const pose=structuredClone(b);delete pose.source_record.record_sha256;pose.frame_index=0;pose.object_transforms=[{object_index:0,translation:[0,0,0],rotation_psx:[0,0,0]},{object_index:1,translation:[0,0,0],rotation_psx:[0,0,0]}];return {geometry_key:key,asset_id:model,preview:{vertices:[[b.source_record.record_index,2,3]],pose},pose_kind:'imported_scene_animation_frame0'};}
const current={schema:'legaia.scene-preview.v1',scene_id:scene,source_key:sourceKey,representation:'authored',coordinate_system:'retail_psx_scene_y_down',position_to_display:[1],entities:[instance(entity,imported,'current'),instance(donor,alternate,'alternate'),instance(other,binding(other,13,sourceHash),'current')],assets:[geometry(imported,'current'),geometry(alternate,'alternate')]};
const proposed=structuredClone(current);proposed.source_key='proposal';Object.assign(proposed.entities[0],{source_actor_id:donor,source_record:structuredClone(witness(alternate).source_record),model_reference:structuredClone(reference),geometry_key:'alternate',animation_assignment_authored:true,pose_kind:'authored_initial_animation_frame0'});
const response={schema_version:'legaia.actor-preset-scene.v1',scene_id:scene,project_source_key:sourceKey,review_key:reviewKey,scene:proposed};
const accepted=decodeActorPresetScene(response,report,current);accepted.entities[0].source_record.record_index=0;assert.equal(response.scene.entities[0].source_record.record_index,49);
for(const mutate of [r=>r.scene.entities[0].source_actor_id=entity,r=>r.scene.entities[0].source_record.record_index=19,r=>r.scene.entities[0].model_reference.model_index=103,r=>r.scene.entities[0].animation_assignment_authored=false,r=>r.scene.entities[0].appearance_authored=true,r=>r.scene.entities[0].pose_kind='imported_scene_animation_frame0',r=>r.scene.assets[1].preview.pose.semantic_id=imported.semantic_id,r=>r.scene.assets[1].preview.pose.frame_index=1,r=>r.scene.assets[1].preview.pose.source_record.record_index=13,r=>r.scene.assets[1].preview.vertices[0][0]=99,r=>r.scene.entities[2].position.x=512]){const bad=structuredClone(response);mutate(bad);assert.throws(()=>decodeActorPresetScene(bad,report,current));}
const cleared=structuredClone(proposed);cleared.entities[0].animation_assignment_authored=false;cleared.entities[0].pose_kind='imported_scene_animation_frame0';decodePresetAnimationScene(cleared,current,[{entity_id:entity,after:before,animation:inherited}]);
const batch={schema_version:'legaia.actor-preset-batch.v1',scene_id:scene,template_id:template.id,scope:template.scope,source_scene_id:scene,source_import_sha256:sourceHash,review_key:reviewKey,changed_count:2,targets:[entity,other].map(id=>({entity_id:id,before:structuredClone(before),after:structuredClone(after),appearance:null,animation:{...structuredClone(animation),imported:binding(id,13,sourceHash),effective:binding(id,13,sourceHash)},...structuredClone(layers),changed:true,build_issues:[]})),limitations:[]};
decodePresetBatch(batch,template,[other,entity],state);const batchScene=structuredClone(proposed);Object.assign(batchScene.entities[2],{source_actor_id:donor,source_record:structuredClone(witness(alternate).source_record),geometry_key:'alternate',animation_assignment_authored:true,pose_kind:'authored_initial_animation_frame0'});decodePresetBatchScene({...response,schema_version:'legaia.actor-preset-batch-scene.v1',scene:batchScene},batch,current);
const badBatch=structuredClone(batch);badBatch.targets[1].after.AnimationChannels.edits=[];assert.throws(()=>decodePresetBatch(badBatch,template,[entity,other],state));

const file={schema_version:'legaia.actor-preset-file.v2',template:structuredClone(template),source_import_sha256:sourceHash};decodePresetFileExport(file,template);const content=JSON.stringify(file),importedTemplate={...structuredClone(template),id:'template://87654321-1234-1234-1234-123456789abc',name:'Imported clip'},importReport={schema_version:'legaia.actor-preset-import-review.v1',template:importedTemplate,source_import_sha256:sourceHash,review_key:reviewKey,limitations:[]};decodePresetImportReview(importReport,content,'Imported clip');
const exported=decodePresetFileExport(file,template);exported.template.components.ActorAnimation.source_record_sha256=sourceHash;assert.equal(file.template.components.ActorAnimation.source_record_sha256,alternateHash);
for(const mutate of [f=>f.schema_version='legaia.actor-preset-file.v1',f=>f.source_import_sha256='bad',f=>f.template.components.ActorAnimation.donor_entity_id=entity,f=>f.template.components.ActorAnimation.source_record_sha256=sourceHash,f=>f.template.components.ActorAnimation.frames=[],f=>f.payload='retail']){const bad=structuredClone(file);mutate(bad);assert.throws(()=>decodePresetFileExport(bad,template));}
for(const scope of ['authored-position-v1','authored-appearance-v1','authored-actor-preset-v1']){const t={...structuredClone(template),scope,components:scope==='authored-position-v1'?{Transform:{position:{x:128}}}:scope==='authored-appearance-v1'?{ActorAppearance:{donor_entity_id:donor}}:{Transform:{position:{x:128}},ActorAppearance:{donor_entity_id:donor}}};decodePresetFileExport({schema_version:'legaia.actor-preset-file.v1',template:t,source_import_sha256:sourceHash},t);assert.throws(()=>decodePresetFileExport({schema_version:'legaia.actor-preset-file.v2',template:t,source_import_sha256:sourceHash},t));}
for(const mutate of [t=>t.components.ActorAnimation=null,t=>t.components.Transform=null,t=>t.components.ActorAppearance=null,t=>t.components.ActorAnimation.animation_asset_id='animation://dolk2/scene-anm/0012',t=>t.components.ActorAnimation.animation_asset_id='animation://town0b/scene-anm/0255']){const bad=structuredClone(template);mutate(bad);assert.throws(()=>validatePresetMetadata(bad));}
const driftedImport=structuredClone(importReport);driftedImport.template.components.ActorAnimation.source_record_sha256=sourceHash;assert.throws(()=>decodePresetImportReview(driftedImport,content,'Imported clip'));
console.log('Animation presets: independent clip/appearance witnesses, exact retained owners, inherited normalization, single/group scene proofs, context drift, portable v1/v2 metadata and detached values passed.');
