import assert from 'node:assert/strict';
import {createScriptFlagSandbox,parseSandboxSignedTicks,mountScriptFlagSandbox} from '../editor/script-flag-sandbox.js';
const words={local:null,global:null,context:null};
const wait=(pc,target)=>({pc,length:3,opcode:0x4a,mnemonic:'WAIT_FRAMES',target_context:null,operands:{duration_ticks:target,timing_units:'host_frame_delta_ticks',accumulator_width:'signed16'},successors:[{pc:pc+3,condition:'encoded_continuation'}]});
const report={status:'decoded_supported_paths',entry_pc:0,instructions:[wait(0,16),wait(3,2)],dialogues:[],stops:[]};
assert.equal(parseSandboxSignedTicks('',{unknown:true}),null);for(const n of ['0','-32768','32767','-1'])assert.equal(parseSandboxSignedTicks(n),Number(n));for(const n of ['',true,'1.1','+1','32768','-32769','0x10'])assert.throws(()=>parseSandboxSignedTicks(n));
const e=createScriptFlagSandbox(report),saved=JSON.stringify(report);e.start(0,words);assert.equal(e.step().state.status,'unknown_wait');assert.throws(()=>e.tick(1));e.start(0,words,{waitAccumulator:0});assert.equal(e.run().state.status,'waiting_ticks');assert.equal(e.snapshot().state.wait_accumulator,0);assert.equal(e.snapshot().history.length,1);assert.throws(()=>e.step());assert.equal(e.tick(1).state.wait_accumulator,1);assert.equal(e.tick(5).state.wait_accumulator,6);const s=e.tick(10);assert.equal(s.state.pc,3);assert.equal(s.state.status,'ready');assert.equal(s.state.wait_accumulator,0);assert.equal(s.history.at(-1).effect.completed,true);assert.equal(e.back().state.wait_accumulator,6);assert.equal(e.snapshot().state.status,'waiting_ticks');e.tick(10);e.run();assert.equal(e.tick(2).state.pc,6);assert.equal(e.snapshot().state.status,'undecoded');assert.equal(JSON.stringify(report),saved);
const before=e.snapshot();before.history.length=0;assert(e.snapshot().history.length);e.start(0,words,{waitAccumulator:32760});e.step();const saturated=e.tick(32767).history.at(-1).effect;assert.equal(saturated.accumulated_ticks,32767);assert.equal(saturated.accumulator_after,0);e.start(0,words,{waitAccumulator:-32760});e.step();assert.equal(e.tick(-32767).state.wait_accumulator,-32768);const prior=JSON.stringify(e.snapshot());for(const d of [null,true,1.5,32768,-32769])assert.throws(()=>e.tick(d));assert.equal(JSON.stringify(e.snapshot()),prior);
for(const seed of [true,1.5,32768,-32769])assert.throws(()=>e.start(0,words,{waitAccumulator:seed}));
for(const change of [n=>n.operands.duration_ticks=32768,n=>n.operands.accumulator_width='unsigned16',n=>n.operands.timing_units='seconds',n=>n.opcode=0x22,n=>n.target_context=0,n=>n.successors[0].condition='wait_completed']){const r=structuredClone(report);change(r.instructions[0]);const engine=createScriptFlagSandbox(r);engine.start(0,words,{waitAccumulator:0});assert.equal(engine.step().state.status,'unsupported');assert.equal(engine.snapshot().state.wait_accumulator,0);}
const zero=createScriptFlagSandbox({...report,instructions:[wait(0,0)]});zero.start(0,words,{waitAccumulator:0});zero.step();assert.equal(zero.tick(0).state.pc,3);e.start(0,words,{waitAccumulator:0});e.step();for(let i=1;i<256;i++)e.tick(0);assert.equal(e.snapshot().state.status,'step_limit');assert.equal(e.snapshot().history.length,256);assert.equal(e.back().state.status,'waiting_ticks');
class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.textContent='';}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this[k]=v;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)];globalThis.document={createElement:tag=>new Element(tag)};let live=true,blocked=false;const errors=[],host=new Element('div'),view=mountScriptFlagSandbox(host,{report,selection:()=>0,current:()=>live,busy:()=>blocked,selectInstruction:()=>true,onError:e=>errors.push(e.message)}),button=t=>tree(host).find(n=>n.tagName==='button'&&n.textContent===t),input=t=>tree(host).find(n=>n['aria-label']===t);
input('Initial hypothetical wait accumulator').value='0';button('Start flag sandbox at entry').onclick();button('Simulate until boundary').onclick();assert.equal(button('Advance one simulated tick').disabled,false);input('Hypothetical tick delta').value='6';button('Advance one simulated tick').onclick();assert.equal(view.snapshot.state.wait_accumulator,6);blocked=true;view.update();button('Advance one simulated tick').onclick();assert.equal(view.snapshot.state.wait_accumulator,6);blocked=false;input('Hypothetical tick delta').value='bad';button('Advance one simulated tick').onclick();assert.equal(errors.length,1);assert.equal(view.snapshot.state.wait_accumulator,6);live=false;view.update();assert.equal(view.snapshot.state,null);assert.equal(button('Advance one simulated tick').disabled,true);view.dispose();assert.equal(host.children.length,0);
console.log('Wait sandbox: explicit staging/ticks, unknown seed, signed saturation, completion reset, successive waits, zero/negative deltas, exact Back, bounded zero ticks, validation and UI ownership passed');
