import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createScriptFlagSandbox,mountScriptFlagSandbox} from '../editor/script-flag-sandbox.js';
import {createScriptSandboxScenario,replayScriptSandboxScenario} from '../editor/script-sandbox-scenarios.js';
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:webcrypto});
const nop=pc=>({pc,length:1,opcode:0x21,mnemonic:'NOP',target_context:null,operands:{},successors:[{pc:pc+1,condition:'encoded_continuation'}]}),flag={pc:2,length:2,opcode:0x31,mnemonic:'CFLAG_SET',target_context:null,operands:{bit:2,raw_operand:2},successors:[{pc:4,condition:'encoded_continuation'}]},unsupported={pc:4,length:1,opcode:0x22,mnemonic:'EXEC_MOVE',target_context:null,operands:{},successors:[{pc:5,condition:'encoded_continuation'}]},report={status:'decoded_supported_paths',entry_pc:0,instructions:[nop(0),nop(1),flag,unsupported],dialogues:[],stops:[]},words={local:null,global:null,context:null};
const e=createScriptFlagSandbox(report);e.start(0,words);const before=e.snapshot();assert.deepEqual(e.run([0]),before);let stopped=e.run([2]);assert.equal(stopped.state.pc,2);assert.equal(stopped.state.status,'ready');assert.equal(stopped.history.length,2);assert.equal(stopped.state.banks.context.known,0);assert.deepEqual(e.run([2]),stopped);
const context={project_path:'C:/private/project',scene_id:'scene://fixture',script_id:'script://fixture/actors/man-p1/0000',project_source_key:'a'.repeat(64),record_sha256:'b'.repeat(64),representation:'retail_source'};
const scenario=await createScriptSandboxScenario(report,stopped,context);assert.deepEqual(scenario.steps,[{kind:'instruction'},{kind:'instruction'}]);assert.equal(scenario.schema_version,'legaia.script-sandbox-scenario.v1');assert(!Object.hasOwn(scenario,'breakpoints'));assert.deepEqual((await replayScriptSandboxScenario(scenario,report,context)).snapshot(),stopped);
e.step();assert.equal(e.snapshot().state.banks.context.value,4);assert.equal(e.snapshot().state.pc,4);assert.equal(e.run([4]).state.status,'ready');assert.equal(e.step().state.status,'unsupported');assert.deepEqual(e.back().state.banks.context, {value:4,known:4});assert.equal(e.back().state.pc,2);
for(const points of [null,{},[2,2],[3],[-1],[65536],[2.5],['2'],Array(65).fill(0)]){const before=e.snapshot();assert.throws(()=>e.run(points));assert.deepEqual(e.snapshot(),before);}
const loop={...nop(0),length:3,opcode:0x26,mnemonic:'JMP_REL',operands:{delta:-1},successors:[{pc:0,condition:'unconditional'}]},l=createScriptFlagSandbox({...report,instructions:[loop]});l.start(0,words);assert.equal(l.run([0]).history.length,0);l.step();assert.equal(l.run([0]).history.length,1);assert.equal(l.run().state.status,'step_limit');
const wait={pc:0,length:3,opcode:0x4a,mnemonic:'WAIT_FRAMES',target_context:null,operands:{duration_ticks:16,timing_units:'host_frame_delta_ticks',accumulator_width:'signed16'},successors:[{pc:3,condition:'encoded_continuation'}]},waiting=createScriptFlagSandbox({...report,instructions:[wait,{...unsupported,pc:3,successors:[{pc:4,condition:'encoded_continuation'}]}]});waiting.start(0,words,{waitAccumulator:0});assert.equal(waiting.run([0]).history.length,0);waiting.step();assert.equal(waiting.run([0]).state.status,'waiting_ticks');assert.equal(waiting.tick(16).state.pc,3);const waitDone=waiting.snapshot();assert.deepEqual(waiting.run([3]),waitDone);assert.equal(waiting.step().state.status,'unsupported');
const maximum={...report,instructions:Array.from({length:65},(_,pc)=>nop(pc))},m=createScriptFlagSandbox(maximum);m.start(0,words);assert.equal(m.run(Array.from({length:64},(_,i)=>i)).history.length,0);assert.throws(()=>m.run(Array.from({length:65},(_,i)=>i)));
const partial={...report,unvisited_instructions:[nop(6)],unvisited_dialogues:[],unreachable_source_pcs:[6]};const p=createScriptFlagSandbox(partial);p.start(6,words);assert.equal(p.run([6]).history.length,0);assert.equal(p.run([]).state.status,'undecoded');
class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.textContent='';this.value='';}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this[k]=v;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)];globalThis.document={createElement:tag=>new Element(tag)};let selected=2,fresh=true,busy=false;const host=new Element('div'),errors=[],view=mountScriptFlagSandbox(host,{report,selection:()=>selected,current:()=>fresh,busy:()=>busy,selectInstruction:pc=>selected=pc,onError:e=>errors.push(e.message)}),button=text=>tree(host).find(n=>n.tagName==='button'&&n.textContent===text);
button('Set breakpoint at selection').onclick();assert(button('Set breakpoint at selection').disabled);button('Start flag sandbox at entry').onclick();button('Simulate until boundary').onclick();assert.equal(view.snapshot.state.pc,2);assert.equal(view.snapshot.state.banks.context.known,0);assert(tree(host).some(n=>n.textContent.includes('paused before')));button('Simulate one instruction').onclick();assert.equal(view.snapshot.state.pc,4);selected=0;button('Go to sandbox breakpoint 0x0002').onclick();assert.equal(selected,2);assert.equal(view.snapshot.state.pc,4);
const stableJump=button('Go to sandbox breakpoint 0x0002');view.update();assert.equal(button('Go to sandbox breakpoint 0x0002'),stableJump);busy=true;view.update();assert(button('Remove breakpoint at selection').disabled);button('Clear sandbox breakpoints').onclick();assert(tree(host).some(n=>n.textContent.startsWith('1 of 64')));busy=false;button('Remove breakpoint at selection').onclick();assert(tree(host).some(n=>n.textContent.startsWith('0 of 64')));selected=3;button('Set breakpoint at selection').onclick();assert.equal(errors.length,1);selected=0;button('Set breakpoint at selection').onclick();button('Reset flag sandbox').onclick();assert(tree(host).some(n=>n.textContent.startsWith('1 of 64')));fresh=false;view.update();assert.equal(view.snapshot.state,null);assert(tree(host).some(n=>n.textContent.startsWith('0 of 64')));assert(button('Set breakpoint at selection').disabled);view.dispose();assert.equal(host.children.length,0);
selected=0;fresh=true;const cappedHost=new Element('div'),capped=mountScriptFlagSandbox(cappedHost,{report:maximum,selection:()=>selected,current:()=>fresh,busy:()=>false,selectInstruction:()=>{},onError:()=>{}}),capButton=t=>tree(cappedHost).find(n=>n.tagName==='button'&&n.textContent===t);for(selected=0;selected<64;selected++)capButton('Set breakpoint at selection').onclick();capped.update();assert(capButton('Set breakpoint at selection').disabled);capButton('Set breakpoint at selection').onclick();assert(tree(cappedHost).some(n=>n.textContent.startsWith('64 of 64')));assert.equal(tree(cappedHost).filter(n=>n.tagName==='button'&&n.textContent.startsWith('Go to sandbox breakpoint')).length,64);capButton('Clear sandbox breakpoints').onclick();assert(tree(cappedHost).some(n=>n.textContent.startsWith('0 of 64')));capped.dispose();
console.log('Temporary decoded breakpoints stop before effects, preserve exact history/scenario replay, guard malformed bounds/loops/unsupported paths, and support source navigation, busy/stale/reset/disposal.');
