import assert from 'node:assert/strict';
import {decodeActorPresetScene} from '../editor/actor-preset-review.js';
const row=id=>({entity_id:id,asset_id:'old',source_actor_id:id,appearance_authored:false,renderable:true,geometry_key:'old',position:{x:128,y:null,z:256},preview_position:{x:128,y:32,z:256},preview_ground_sample:{y:32,cell_index:0},display_position:{x:128,y:-32,z:256},preview_height_status:'source_surface',model_to_scene:[1,0,0,128,0,-1,0,-32,0,0,1,256,0,0,0,1],authored_position:{},evidence:{position:'imported placement plus authored overrides',height:'source terrain',heading:'unknown',scale:'unknown'}});
const current={schema:'legaia.scene-preview.v1',scene_id:'scene',source_key:'source',coordinate_system:'source',position_to_display:[1],entities:['a','b'].map(row),assets:[{geometry_key:'old',asset_id:'old',preview:{vertices:[[1,2,3]]}}]};
const report={review_key:'review',entity_id:'a',layers:{proposed_position:{x:512,y:null,z:256},proposed_donor:'donor'},after:{Transform:{position:{x:512}}},appearance:{donor_entity_id:'donor',asset_id:'new'}};
const scene=structuredClone(current);scene.representation='authored';scene.source_key='proposal';scene.assets.push({geometry_key:'new',asset_id:'new',preview:{vertices:[[4,5,6]]}});
Object.assign(scene.entities[0],{asset_id:'new',source_actor_id:'donor',appearance_authored:true,geometry_key:'new',position:{x:512,y:null,z:256},preview_position:{x:512,y:64,z:256},preview_ground_sample:{y:64,cell_index:1},display_position:{x:512,y:-64,z:256},model_to_scene:[1,0,0,512,0,-1,0,-64,0,0,1,256,0,0,0,1],authored_position:{x:512}});
const response={schema_version:'legaia.actor-preset-scene.v1',scene_id:'scene',project_source_key:'source',review_key:'review',scene};const before=structuredClone(response);
const decoded=decodeActorPresetScene(response,report,current);decoded.entities[0].position.x=0;assert.deepEqual(response,before);
for(const edit of [r=>r.review_key='stale',r=>r.project_source_key='stale',r=>r.scene.entities[0].position.x=0,r=>r.scene.entities[0].model_to_scene[3]=0,r=>r.scene.entities[0].authored_position.x=0,r=>r.scene.entities[0].preview_ground_sample.y=99,r=>r.scene.entities[0].asset_id='wrong',r=>r.scene.entities[0].source_actor_id='wrong',r=>r.scene.entities[1].position.x=0,r=>r.scene.assets[0].preview.vertices[0][0]=100,r=>r.scene.entities.push(structuredClone(r.scene.entities[0]))]){const copy=structuredClone(response);edit(copy);assert.throws(()=>decodeActorPresetScene(copy,report,current));}
console.log('Combined preset scene: detached placement+donor projection, unknown source height, owner/matrix/authored layer/geometry/source guards passed.');
