import assert from 'node:assert/strict';
import {scriptBranchPage} from '../editor/script-branches.js';
const node=(pc,targets=[])=>({pc,length:1,mnemonic:'FIXTURE',successors:targets.map(target=>typeof target==='number'?{pc:target,condition:'next'}:target)});
const report=instructions=>({status:'partial',instructions,dialogues:[],stops:[],opaque_regions:[]});
const current=report(Array.from({length:70},(_,pc)=>node(pc,pc<69?[pc+1]:[])));
current.instructions[0].successors.push({pc:50,condition:'flag_set'},{pc:900,condition:'unknown'});
current.instructions[2].successors.push({pc:2,condition:'self'});current.stops=[{pc:900,reason:'unsupported opcode'}];
const proposed=structuredClone(current);proposed.instructions[0].successors[1].pc=60;
const before=JSON.stringify([current,proposed]),page=scriptBranchPage(current,proposed);
assert.equal(page.page_count,3);assert.equal(page.total_node_count,70);assert.deepEqual(page.page_pcs,Array.from({length:24},(_,i)=>i));
assert(page.edges.some(e=>e.source===0&&e.target===1&&e.layer==='both'));
assert(page.edges.some(e=>e.source===0&&e.target===50&&e.layer==='current'));
assert(page.edges.some(e=>e.source===0&&e.target===60&&e.layer==='proposed'));
assert.equal(page.nodes.find(n=>n.pc===50).node_page,2);
assert.equal(page.nodes.find(n=>n.pc===900).decoded,false);assert.equal(page.nodes.find(n=>n.pc===900).reason,'unsupported opcode');
assert.equal(page.omitted_edge_count,0);assert(page.edges.some(e=>e.source===2&&e.target===2));
const all=[0,1,2].flatMap(i=>scriptBranchPage(current,proposed,i).page_pcs);assert.deepEqual(all,Array.from({length:70},(_,i)=>i));
assert.equal(scriptBranchPage(current,null,8192).page,2);assert.equal(scriptBranchPage(report([]),null).page_count,1);
const dialogue=report([node(0,[1]),node(5)]);dialogue.dialogues=[{pc:1,length:4,text:'decoded dialogue'}];assert(scriptBranchPage(dialogue,null).edges.some(e=>e.source===1&&e.target===5));
const duplicate=report([node(0,[0,0])]);assert.equal(scriptBranchPage(duplicate,duplicate).edges.length,2);assert(scriptBranchPage(duplicate,duplicate).edges.every(e=>e.layer==='both'));
const dense=report(Array.from({length:24},(_,pc)=>node(pc,Array.from({length:64},(_,i)=>1000+pc*64+i))));
const limited=scriptBranchPage(dense,null);assert.equal(limited.nodes.length,40);assert.equal(limited.omitted_edge_count+limited.edges.length,1536);
for(const bad of [true,-1,0.5,8193])assert.throws(()=>scriptBranchPage(current,null,bad));
for(const value of [{},report([node(0),node(0)]),report([node(0,[65537])])])assert.throws(()=>scriptBranchPage(value,null));
const many=report(Array.from({length:8192},(_,pc)=>node(pc)));assert.equal(scriptBranchPage(many,null,341).page_pcs.length,8);
assert.equal(JSON.stringify([current,proposed]),before);page.nodes[0].mnemonic='changed';page.edges[0].condition='changed';assert.equal(JSON.stringify([current,proposed]),before);
console.log('Whole inspected flow: all-node paging, Current/Proposed exact edge merging, duplicate/loop/dialogue edges, off-page targets, explicit omissions, native bounds and immutable reports passed.');
