import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createScriptFlagSandbox,mountScriptFlagSandbox} from '../editor/script-flag-sandbox.js';
import {createScriptSandboxScenario,replayScriptSandboxScenario} from '../editor/script-sandbox-scenarios.js';
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:webcrypto});
const context={project_path:'C:/private/project',scene_id:'scene://fixture',script_id:'script://fixture/actors/man-p1/0000',project_source_key:'a'.repeat(64),record_sha256:'b'.repeat(64),representation:'retail_source'},words={local:null,global:null,context:null};
const report={status:'decoded_supported_paths',entry_pc:0,instructions:[{pc:0,opcode:0x30,length:2,mnemonic:'GFLAG_TEST',target_context:null,operands:{bit:31,raw_operand:31,can_wait_for_flag:true},successors:[{pc:2,condition:'encoded_continuation'}]},{pc:2,opcode:0x21,length:1,mnemonic:'NOP',target_context:null,operands:{},successors:[{pc:3,condition:'encoded_continuation'}]}],dialogues:[],stops:[]};
const e=createScriptFlagSandbox(report);e.start(0,words);e.step();assert.equal(e.snapshot().state.status,'unknown_flag');const blocked=e.snapshot();e.assumeFlag('global',31,false);assert.equal(e.snapshot().state.pc,0);assert.equal(e.snapshot().state.status,'ready');assert.equal(e.snapshot().state.banks.global.known,2147483648);e.step();assert.equal(e.snapshot().state.status,'flag_wait');e.assumeFlag('global',31,true);assert.equal(e.snapshot().state.pc,0);const assumed=e.snapshot();e.step();assert.equal(e.snapshot().state.pc,2);e.back();assert.deepEqual(e.snapshot(),assumed);e.back();assert.equal(e.snapshot().state.status,'flag_wait');e.back();e.back();assert.deepEqual(e.snapshot(),blocked);
e.assumeFlag('global',31,true);e.assumeFlag('global',31,null);assert.deepEqual(e.snapshot().state.banks.global,{value:0,known:0});e.step();assert.equal(e.snapshot().state.status,'unknown_flag');e.assumeFlag('global',31,true);e.step();const final=e.snapshot(),scenario=await createScriptSandboxScenario(report,final,context);assert.equal(scenario.schema_version,'legaia.script-sandbox-scenario.v2');assert.deepEqual((await replayScriptSandboxScenario(scenario,report,context)).snapshot(),final);
for(const mutate of [s=>s.schema_version='legaia.script-sandbox-scenario.v1',s=>s.steps[1].bit=32,s=>s.steps[1].bank='live',s=>s.steps[1].value=1,s=>s.steps[1].extra=true,s=>s.result.banks.global.value=0]){const bad=structuredClone(scenario);mutate(bad);await assert.rejects(()=>replayScriptSandboxScenario(bad,report,context));}
for(const args of [['local',16,true],['global',-1,true],['global',32,null],['context',1,0],['constructor',1,true],['global',1.5,false]]){const before=e.snapshot();assert.throws(()=>e.assumeFlag(...args));assert.deepEqual(e.snapshot(),before);}
for(const bank of ['local','global','context']){const high=bank==='local'?15:31;e.start(0,words);e.assumeFlag(bank,high,true);assert.equal(e.snapshot().state.banks[bank].value,2**high);assert.equal(e.snapshot().state.banks[bank].known,2**high);e.assumeFlag(bank,high,false);assert.equal(e.snapshot().state.banks[bank].value,0);e.assumeFlag(bank,high,null);assert.equal(e.snapshot().state.banks[bank].known,0);}
e.start(0,words);for(let i=0;i<256;i++)e.assumeFlag('local',0,!!(i%2));assert.equal(e.snapshot().state.status,'step_limit');const capped=e.snapshot();assert.throws(()=>e.assumeFlag('local',0,true));assert.deepEqual(e.snapshot(),capped);e.back();assert.equal(e.snapshot().state.status,'ready');e.reset();assert.throws(()=>e.assumeFlag('local',0,true));
e.start(2,words);e.step();assert.equal(e.snapshot().state.status,'undecoded');assert.throws(()=>e.assumeFlag('local',0,true));
const wait=structuredClone(report);wait.instructions[0]={pc:0,opcode:0x4a,length:3,mnemonic:'WAIT_FRAMES',target_context:null,operands:{duration_ticks:1,timing_units:'host_frame_delta_ticks',accumulator_width:'signed16'},successors:[{pc:3,condition:'encoded_continuation'}]};const w=createScriptFlagSandbox(wait);w.start(0,words,{waitAccumulator:0});w.step();assert.equal(w.snapshot().state.status,'waiting_ticks');assert.throws(()=>w.assumeFlag('local',0,true));
const branch=structuredClone(report);branch.instructions[0]={pc:0,opcode:0x4c,length:5,mnemonic:'FLAG_WORD_BRANCH',target_context:null,operands:{flag_word:'global_story_word',sub_op:0xa2,bit_encoded:31,delta:-1,target:2},successors:[{pc:2,condition:'flag_bit_set'},{pc:5,condition:'flag_bit_clear'}]};const b=createScriptFlagSandbox(branch);b.start(0,words);b.step();assert.equal(b.snapshot().state.status,'unknown_flag');b.assumeFlag('global',31,true);b.step();assert.equal(b.snapshot().state.pc,2);
class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.textContent='';}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this[k]=v;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)];globalThis.document={createElement:tag=>new Element(tag)};const host=new Element('div');let busy=false,live=true;const errors=[],view=mountScriptFlagSandbox(host,{report,selection:()=>0,current:()=>live,busy:()=>busy,selectInstruction:()=>true,onError:e=>errors.push(e.message)}),find=t=>tree(host).find(n=>n.tagName==='button'&&n.textContent===t),input=label=>tree(host).find(n=>n['aria-label']===label),assume=find('Set hypothetical bit');assert.equal(assume.disabled,true);find('Start flag sandbox at selection').onclick();find('Simulate one instruction').onclick();assert.equal(view.snapshot.state.status,'unknown_flag');input('Hypothetical assumption bank').value='global';input('Hypothetical assumption bit').value='31';assume.onclick();assert.equal(view.snapshot.state.pc,0);find('Simulate one instruction').onclick();assert.equal(view.snapshot.state.pc,2);input('Hypothetical assumption bit').value='32';const before=view.snapshot;assume.onclick();assert.deepEqual(view.snapshot,before);assert.equal(errors.length,1);busy=true;view.update();assert.equal(assume.disabled,true);assume.onclick();assert.deepEqual(view.snapshot,before);busy=false;live=false;view.update();assert.equal(view.snapshot.state,null);assert.equal(assume.disabled,true);view.dispose();assert.equal(host.children.length,0);
const pendingHost=new Element('div');let finish;const pending=mountScriptFlagSandbox(pendingHost,{report,getContext:()=>context,requalify:async()=>new Promise(resolve=>finish=resolve),selection:()=>0,current:()=>true,busy:()=>false,selectInstruction:()=>true,onError:e=>{throw e;}}),pendingButton=t=>tree(pendingHost).find(n=>n.tagName==='button'&&n.textContent===t);pendingButton('Start flag sandbox at selection').onclick();const beforeLoad=pending.snapshot,pendingFile=tree(pendingHost).find(n=>n.type==='file');pendingFile.files=[{size:JSON.stringify(scenario).length,text:async()=>JSON.stringify(scenario)}];const loading=pendingFile.onchange();while(!finish)await new Promise(resolve=>setTimeout(resolve,0));assert.equal(pendingButton('Set hypothetical bit').disabled,true);pendingButton('Set hypothetical bit').onclick();assert.deepEqual(pending.snapshot,beforeLoad);finish(true);await loading;assert.deepEqual(pending.snapshot,final);pending.dispose();
console.log('Hypothetical flag assumptions: explicit re-evaluation, all banks and high bits, unknown masks, exact Back, bounded history, v1 refusal/v2 independent replay, invalid/unsupported/pending lifecycle guards passed');
