import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {decodeNpcScriptComparison} from '../editor/npc-script-comparison.js';
const id='authored-actor://11111111-1111-4111-8111-111111111111',owner='scene://town01/actors/man-p1/0012',build='a'.repeat(16),hash='b'.repeat(64),key='c'.repeat(64),input='d'.repeat(64),draft={scene_id:'scene://town01',name:'NPC',donor_entity_id:owner,position:{x:64,z:128}},source={record_index:12,byte_offset:128,byte_length:4},entry={id:build,status:'completed',matches_current_inputs:true,archive_sha256:hash,source_disc_sha256:hash},state={scene:{id:draft.scene_id,entities:[{id:owner,components:{RetailMetadata:{source_record:source}}}]},actor_drafts:{[id]:draft},project_copy_source_key:key,build_review_source_key:input};
const record=(raw,offset,index)=>({raw_hex:raw,script_offset:2,byte_length:4,byte_offset:offset,record_index:index,sha256:createHash('sha256').update(Buffer.from(raw,'hex')).digest('hex')}),retailRecord=record('61626364',128,12),generatedRecord=record('61586364',1000,53),base={schema_version:'legaia.actor-script-inspection.v1',read_only:true,instructions:[],dialogues:[]},retail={schema_version:'legaia.npc-donor-script.v1',project_source_key:key,scene_id:draft.scene_id,entity_id:id,draft,donor_entity_id:owner,donor_source_record:source,representation:'retail_donor_source',generated_code:false,runtime_binding:'not_asserted',gameplay_verified:false,inspection:{...base,semantic_id:'script://town01/actors/man-p1/0012',actor_semantic_id:owner,source_record:source,record:retailRecord}},generated={schema_version:'legaia.npc-build-script.v1',entity_id:id,scene_id:draft.scene_id,project_source_key:key,build_input_key:input,draft,donor_entity_id:owner,representation:'saved_build',generated_code:true,runtime_binding:'not_asserted',gameplay_verified:false,build:{...entry,integrity:'verified',source_disc_integrity:'verified',delivery:'relocated_PROT'},man_source:{payload_sha256:hash,decoded_size:2048},inspection:{...base,semantic_id:'script://generated-npc/'+id.replace('authored-actor://','')+'/'+build,actor_semantic_id:id,source_record:{...generatedRecord,build_id:build,archive_sha256:hash,man_sha256:hash,byte_coordinate_space:'generated_decoded_MAN'},record:generatedRecord}};
const difference={comparison_scope:'same_relative_record_byte_offsets',retail_length:4,generated_length:4,changed_byte_count:1,unchanged_common_byte_count:3,record_bytes_equal:false,script_tail_bytes_equal:true,changes:[{relative_offset:1,retail_byte:98,generated_byte:88,scope:'record_header'}]},report={schema_version:'legaia.npc-script-comparison.v1',project_source_key:key,entity_id:id,scene_id:draft.scene_id,read_only:true,gameplay_verified:false,runtime_binding:'not_asserted',retail,generated,difference,limitations:['Byte comparison only.']};
const decoded=decodeNpcScriptComparison(report,id,state,entry);decoded.difference.changes[0].retail_byte=0;assert.equal(difference.changes[0].retail_byte,98);
for(const change of [r=>r.project_source_key='stale',r=>r.difference.changed_byte_count=0,r=>r.difference.changes[0].generated_byte=99,r=>r.difference.changes[0].scope='script_or_remaining_record_bytes',r=>r.difference.script_tail_bytes_equal=false,r=>r.generated.build.archive_sha256='wrong',r=>r.retail.donor_entity_id='wrong']){const bad=structuredClone(report);change(bad);assert.throws(()=>decodeNpcScriptComparison(bad,id,state,entry));}
console.log('NPC script comparison exact byte rows/counts, separate qualified records, header/tail scope and stale/forged rejection pass.');

const waiting=structuredClone(report),waitingState=structuredClone(state),wait='script://town01/actors/man-p1/0012/wait/0000';waitingState.actor_drafts[id].waits={donor_entity_id:owner,entries:{[wait]:{duration_ticks:11}}};waiting.retail.draft=waitingState.actor_drafts[id];waiting.generated.draft=waitingState.actor_drafts[id];waiting.retail.inspection.record=record('000a0061',128,12);waiting.generated.inspection.record=record('000b0061',1000,53);waiting.difference.changes=[{relative_offset:1,retail_byte:10,generated_byte:11,scope:'record_header'}];waiting.authored_spans=[{category:'own_wait',source_operand_id:wait,relative_offset:1,byte_length:2,before_hex:'0a00',after_hex:'0b00'}];
assert.deepEqual(decodeNpcScriptComparison(waiting,id,waitingState,entry),waiting);
for(const mutate of [v=>v.authored_spans[0].after_hex='0c00',v=>v.authored_spans[0].relative_offset=2,v=>v.authored_spans[0].source_operand_id=wait.replace('0012','0040'),v=>v.authored_spans.push(v.authored_spans[0]),v=>v.authored_spans[0].category='initial_appearance']){const v=structuredClone(waiting);mutate(v);assert.throws(()=>decodeNpcScriptComparison(v,id,waitingState,entry));}
console.log('NPC authored explanations verify exact before/after spans, current wait binding, ownership and nonoverlap independently.');
