import assert from 'node:assert/strict';
import {floorHeights,decodeFloorHeights} from '../editor/floor-heights.js';
const key='a'.repeat(64),scene='scene://fixture',asked=Array(16).fill(0);asked[1]=-64;
const value={schema_version:'legaia.floor-height-review.v1',project_source_key:key,scene_id:scene,source_sha256:key,review_key:'b'.repeat(64),source_record:{disc_sha256:key,payload_sha256:key,source_kind:'descriptor_man',entry_index:2,payload_offset:43,decoded_size:80,encoded_size:32,compression:'lzs',chunk_header_offset:null},retail:Array(16).fill(0),current:Array(16).fill(0),proposed:asked,scope:'MAN-floor-height-table-only',gameplay_verified:false,project_change:true,effective_change_count:1,limitations:[],value:{source_sha256:key,edits:[{tier:1,height:-64}]},audit:[{tier:1,field:'floor_height',decoded_byte_offset:4,byte_length:2,before_value:0,after_value:-64,record_index:0,semantic_id:scene,scope:'MAN-floor-height-table-only'}]};
const decoded=decodeFloorHeights(value,key,scene,asked);decoded.current[0]=1;assert.equal(value.current[0],0);
for(const change of [v=>v.project_source_key='c'.repeat(64),v=>v.proposed[1]=-32,v=>v.current[0]=true,v=>v.source_record.payload_sha256='c'.repeat(64),v=>v.source_record.compression='none',v=>v.source_record.encoded_size=0,v=>v.audit[0].decoded_byte_offset=6,v=>v.audit[0].before_value=12,v=>v.audit[0].byte_length=1,v=>v.audit[0].semantic_id='scene://other',v=>v.effective_change_count=0,v=>v.value.edits[0].tier=2]){const v=structuredClone(value);change(v);assert.throws(()=>decodeFloorHeights(v,key,scene,asked));}
for(const v of [asked.slice(1),[true,...asked.slice(1)],[32768,...asked.slice(1)],[0.5,...asked.slice(1)]])assert.throws(()=>floorHeights(v));
const raw=structuredClone(value);Object.assign(raw.source_record,{source_kind:'raw_streaming_man',compression:'none',chunk_header_offset:0,encoded_size:80});assert.deepEqual(decodeFloorHeights(raw,key,scene,asked),raw);
console.log('Height vector bounds, source identity, exact MAN audit, detached Review and streaming-kind guards passed.');
