import assert from 'node:assert/strict';
import {decodeNpcSystemFlagsSource,decodeNpcSystemFlagsReview} from '../editor/npc-system-flags.js';
const id='authored-actor://fixture',donor='scene://town01/actors/man-p1/0011',key='script://town01/actors/man-p1/0011/system-flag/0016',draft={scene_id:'scene://town01',donor_entity_id:donor,position:{x:128,z:256},name:'NPC'},state={scene:{id:draft.scene_id},actor_drafts:{[id]:draft},project_copy_source_key:'a'.repeat(64)};
const row={semantic_id:key,owner_id:donor,pc:22,mnemonic:'SYSFLAG_TEST',target_context:null,decoded_byte_offset:100,byte_length:2,maximum:4095,values:{index:326},authored_values:null,effective_values:{index:326},source_record_sha256:'b'.repeat(64)};
const source={schema_version:'legaia.npc-system-flags-source.v1',entity_id:id,scene_id:draft.scene_id,project_source_key:state.project_copy_source_key,draft,options:{supported:true,targets:[row]},gameplay_verified:false,runtime_variable_identity:'not_asserted',story_meaning:'not_asserted'};
decodeNpcSystemFlagsSource(source,id,state);
for(const change of [v=>v.options.targets[0].pc=true,v=>v.options.targets[0].byte_length=1,v=>v.options.targets[0].maximum=255,v=>v.options.targets[0].target_context=7,v=>v.options.targets[0].values.index=4096,v=>v.options.targets[0].owner_id='other',v=>v.options.targets.push(row),v=>v.project_source_key='c'.repeat(64)]){const bad=structuredClone(source);change(bad);assert.throws(()=>decodeNpcSystemFlagsSource(bad,id,state));}
const request={entity_id:id,entries:{[key]:{index:4095}}};
const review={schema_version:'legaia.npc-system-flags-review.v1',entity_id:id,project_source_key:state.project_copy_source_key,request,current:draft,proposed:{...draft,system_flags:{donor_entity_id:donor,entries:request.entries}},changes:[{system_flag_id:key,owner_id:donor,pc:22,record_relative_byte_offset:22,mnemonic:'SYSFLAG_TEST',target_context:null,decoded_byte_offset:100,byte_length:2,field:'system_flag_index',source_record_sha256:row.source_record_sha256,source_decoded_man_sha256:'c'.repeat(64),before_index:326,after_index:4095,before_hex:'7146',after_hex:'7fff'}],review_key:'d'.repeat(64),gameplay_verified:false,runtime_variable_identity:'not_asserted',story_meaning:'not_asserted'};
assert.deepEqual(decodeNpcSystemFlagsReview(review,request,source,state),review);
for(const change of [v=>v.changes=[],v=>v.changes[0].after_hex='6fff',v=>v.changes[0].before_hex='7147',v=>v.changes[0].after_index=255,v=>v.changes[0].decoded_byte_offset++,v=>v.changes[0].record_relative_byte_offset++,v=>v.proposed.position.x=192,v=>v.changes[0].target_context=1,v=>v.changes[0].source_record_sha256='e'.repeat(64)]){const bad=structuredClone(review);change(bad);assert.throws(()=>decodeNpcSystemFlagsReview(bad,request,source,state));}
const clear=structuredClone(review);clear.request={entity_id:id,entries:{}};clear.proposed=draft;clear.changes=[];decodeNpcSystemFlagsReview(clear,clear.request,source,state);
for(const index of [true,-1,4096,1.5,'3'])assert.throws(()=>decodeNpcSystemFlagsReview(review,{entity_id:id,entries:{[key]:{index}}},source,state));
console.log('NPC system-selector ownership, bounds, two-byte receipt encoding, clear and stale refusal passed.');
