import assert from 'node:assert/strict';
import {createSceneAnimationRecipe,decodeSceneAnimationRecipe} from '../editor/scene-animation-recipe.js';
import {createSceneAnimationController} from '../editor/scene-animation.js';
const context={projectPath:'C:/private',sceneId:'scene://fixture',mode:'edit',sourceKey:'a'.repeat(64),sceneSourceKey:'b'.repeat(64),representation:'authored',ready:true,canStart:true};
const asset='asset://fixture/models/scene-tmd/0000',actor='scene://fixture/actors/man-p1/0000';
const report={schema_version:'legaia.scene-animation.v1',scene_id:context.sceneId,project_source_key:context.sourceKey,scene_source_key:context.sceneSourceKey,representation:'authored',tracks:[{geometry_key:'geometry-a',asset_id:asset,clip_id:'animation://fixture/scene-anm/0000',pose_kind:'imported_scene_animation_frame0',frame_count:3,vertex_count:1,frames:[[[0,0,0]],[[1,0,0]],[[2,0,0]]]}],instances:[{entity_id:actor,geometry_key:'geometry-a',asset_id:asset,source_actor_id:actor}],unavailable_instances:[],metrics:{animated_instances:1,static_or_unavailable_instances:0,track_count:1,frame_vertex_count:3,max_frame_count:3},limitations:[],project_changed:false,gameplay_verified:false};
const settings=new Map([['geometry-a',{mode:'ping_pong',offset:1}]]),recipe=createSceneAnimationRecipe(report,11,17,settings);
assert.equal(JSON.stringify(recipe).includes('vertices'),false);assert.equal(JSON.stringify(recipe).includes('frames'),false);assert.deepEqual(decodeSceneAnimationRecipe(JSON.parse(JSON.stringify(recipe)),report),recipe);assert.deepEqual(recipe.tracks[0].instances,[{entity_id:actor,source_actor_id:actor}]);
const reordered=structuredClone(recipe);reordered.source=Object.fromEntries(Object.entries(reordered.source).reverse());assert.deepEqual(decodeSceneAnimationRecipe(reordered,report),reordered);
for(const tick of [0,Number.MAX_SAFE_INTEGER])for(const fps of [1,30])for(const mode of ['loop','hold','ping_pong','freeze'])for(const offset of [0,2])assert.equal(createSceneAnimationRecipe(report,tick,fps,new Map([['geometry-a',{mode,offset}]])).tick,tick);
for(const mutate of [r=>r.schema_version='unknown',r=>r.source.scene_id='scene://foreign',r=>r.source.project_source_key='f'.repeat(64),r=>r.source.scene_source_key='f'.repeat(64),r=>r.source.representation='retail',r=>r.tick=-1,r=>r.tick=1.5,r=>r.tick=Number.MAX_SAFE_INTEGER+1,r=>r.preview_fps=31,r=>r.preview_fps=true,r=>r.extra=true,r=>r.tracks=[],r=>r.tracks.push(r.tracks[0]),r=>r.tracks[0].geometry_key='foreign',r=>r.tracks[0].asset_id='foreign',r=>r.tracks[0].clip_id='foreign',r=>r.tracks[0].frame_count=4,r=>r.tracks[0].vertex_count=2,r=>r.tracks[0].pose_kind='inferred',r=>r.tracks[0].instances[0].source_actor_id='foreign',r=>r.tracks[0].offset=3,r=>r.tracks[0].offset=true,r=>r.tracks[0].mode='runtime',r=>r.tracks[0].frames=[],r=>r.unavailable_entity_ids=[actor]]){const r=structuredClone(recipe);mutate(r);assert.throws(()=>decodeSceneAnimationRecipe(r,report));}
assert.throws(()=>createSceneAnimationRecipe(report,0,10,new Map([['foreign',{mode:'loop',offset:0}]])));
class Node{constructor(tag){this.tag=tag;this.children=[];this.attributes={};this.style={};this.dataset={};this.value='';this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this.attributes[k]=v;}remove(){}click(){clicks.push(this);}}
let clicks=[],samples=[],restores=0,ctx=structuredClone(context),busy=false,errors=[],download,raf=0;
globalThis.document={hidden:false,createElement:t=>new Node(t),addEventListener(){},removeEventListener(){}};globalThis.fetch=async()=>({ok:true,text:async()=>JSON.stringify(report)});globalThis.requestAnimationFrame=()=>++raf;globalThis.cancelAnimationFrame=()=>{};URL.createObjectURL=blob=>{download=blob;return 'blob:recipe';};URL.revokeObjectURL=()=>{};
const tree=n=>[n,...n.children.flatMap(tree)],button=(c,name)=>tree(c.element).find(n=>n.dataset.action===name),input=(c,name)=>tree(c.element).find(n=>n.attributes['aria-label']===name);
const open=()=>createSceneAnimationController({getContext:()=>ctx,busy:()=>busy,setBusy:v=>busy=v,onLoad:()=>true,onSample:rows=>{samples.push(rows.map(r=>r.frame_index));return true;},onRestore:()=>restores++,onError:e=>errors.push(e.message)});
let c=open();await c.start();const file=input(c,'Scene animation preview recipe JSON');const load=async raw=>{const text=JSON.stringify(raw);file.files=[{size:text.length,text:async()=>text}];return file.onchange();};
assert.equal(await load(recipe),true);assert.equal(input(c,'Scene animation preview tick').value,'11');assert.equal(input(c,'Scene animation preview fps').value,'17');assert.equal(input(c,'Track preview mode geometry-a').value,'ping_pong');assert.deepEqual(samples.at(-1),[0]);assert.equal(raf,0);
assert.equal(button(c,'save-recipe').onclick(),true);assert.deepEqual(JSON.parse(await download.text()),recipe);assert.equal(clicks[0].download,'fixture-animation-preview.json');
const sampleCount=samples.length;const invalid=structuredClone(recipe);invalid.tracks[0].offset=3;assert.equal(await load(invalid),false);assert.equal(samples.length,sampleCount);assert.equal(input(c,'Scene animation preview tick').value,'11');assert.equal(input(c,'Track preview phase offset geometry-a').value,'1');
file.files=[{size:1048577,text:()=>{throw Error('Oversized file must not read');}}];assert.equal(await file.onchange(),false);assert.equal(samples.length,sampleCount);
let resolve;file.files=[{size:100,text:()=>new Promise(r=>resolve=r)}];const pending=file.onchange();assert(button(c,'save-recipe').disabled);assert(button(c,'play').disabled);assert(input(c,'Track preview mode geometry-a').disabled);assert.equal(button(c,'play').onclick(),false);c.stop();resolve(JSON.stringify(recipe));assert.equal(await pending,false);assert.equal(samples.length,sampleCount);assert.equal(c.active(),false);c.dispose();
ctx=structuredClone(context);c=open();await c.start();const lateFile=input(c,'Scene animation preview recipe JSON');lateFile.files=[{size:100,text:()=>new Promise(r=>resolve=r)}];const late=lateFile.onchange();ctx.sourceKey='f'.repeat(64);c.updateState();resolve(JSON.stringify(recipe));assert.equal(await late,false);assert.equal(c.active(),false);assert.equal(restores,2);c.dispose();
console.log('Preview recipe source/coverage identity, exact schema, safe tick/rate/frame settings, detached metadata, atomic replay, paused save/load, bounds and late-source/Stop refusal passed.');
