import assert from 'node:assert/strict';
import {copiedAnimationAsset} from '../editor/animation-copy-selection.js';
const uuid='12345678-1234-4123-8123-123456789abc',id=`animation://fixture/authored-record/${uuid}`,owner='scene://fixture/actors/man-p1/0001',model='asset://fixture/models/scene-tmd/0001',hash='a'.repeat(64);
const entry={record_id:uuid,entity_id:owner,channel_owner_entity_id:owner,model_source_entity_id:owner,donor_asset_id:model,donor_animation_id:'animation://fixture/scene-anm/0001',record_sha256:hash,donor_record_sha256:hash,source_frame_indices:[1,0],object_count:1};
const row={record_id:uuid,animation_id:id,entity_id:owner,channel_owner_entity_id:owner,model_source_entity_id:owner,donor_asset_id:model,donor_animation_id:entry.donor_animation_id,record_sha256:hash,frame_count:2,object_count:1,active:true,runtime_assigned:false,assigned_actor_ids:[]};
const record={id,data:{semantic_id:id,asset_kind:'animation',scope:'authored-retained',authored_animation_record:true,frame_count:2,bone_count:1,model_asset_id:model,retained_record:row,source_record:{source_kind:'authored_animation_record',record_id:uuid,record_sha256:hash,ledger_sha256:hash,donor_record_sha256:hash,donor_animation_id:row.donor_animation_id}}};
const review={schema_version:'legaia.animation-record-duplicate-review.v1',scene_id:'scene://fixture',record_id:'original',duplicate_entry:entry,project_changed:false,assignments_changed:false,gameplay_verified:false},state={project:{mode:'edit'},scene:{id:'scene://fixture'},scene_preview_source_key:hash,capabilities:{actor_animation_authoring:true}};
assert.deepEqual(copiedAnimationAsset([record],review,state),record);const detached=copiedAnimationAsset([record],review,state);detached.data.retained_record.active=false;assert.equal(record.data.retained_record.active,true);
for(const change of [v=>v.data.retained_record.record_sha256='b'.repeat(64),v=>v.data.retained_record.assigned_actor_ids=[owner],v=>v.data.retained_record.active=false,v=>v.data.source_record.donor_record_sha256='b'.repeat(64),v=>v.data.retained_record.channel_owner_entity_id='scene://fixture/actors/man-p1/0002']){const bad=structuredClone(record);change(bad);assert.throws(()=>copiedAnimationAsset([bad],review,state));}
assert.throws(()=>copiedAnimationAsset([],review,state));assert.throws(()=>copiedAnimationAsset([record,record],review,state));assert.throws(()=>copiedAnimationAsset([record],review,{...state,project:{mode:'live'}}));assert.throws(()=>copiedAnimationAsset([record],{...review,assignments_changed:true},state));
console.log('Copied clip selection binds unique refreshed asset, exact native source/owners/model/counts and active unassigned status; mismatches and Live refuse.');
