import assert from 'node:assert/strict';
import {parseAnimationFrameSequence,decodeAnimationAllocationOptions,decodeAnimationAllocationReview,decodeAnimationAllocationPose,openAnimationAllocationEditor,flattenRetainedSequence} from '../editor/animation-allocation.js';
const entity='scene://town01/actors/man-p1/0011',asset='asset://town01/models/scene-tmd/0001',clip='animation://town01/scene-anm/0000',id='11111111-1111-4111-8111-111111111111';
const initial={projectPath:'C:/private/project',sceneId:'scene://town01',mode:'edit',sourceKey:'f'.repeat(64)};
const options=()=>({schema_version:'legaia.animation-record-allocation-options.v1',entity_id:entity,scene_id:initial.sceneId,project_source_key:initial.sourceKey,donor_animation_id:clip,channel_owner_entity_id:entity,model_source_entity_id:entity,donor_asset_id:asset,donor_frame_count:3,object_count:1,maximum_frame_count:512,remaining_channel_count:4096,remaining_record_count:64,build_available:false,gameplay_verified:false});
function report(request){
  const entry={record_id:id,record_sha256:'c'.repeat(64),entity_id:entity,channel_owner_entity_id:entity,model_source_entity_id:entity,donor_animation_id:clip,donor_asset_id:asset,donor_frame_count:3,object_count:1,source_frame_indices:request.source_frame_indices,edits:request.edits};
  return {schema_version:'legaia.animation-record-allocation-review.v2',entity_id:entity,scene_id:initial.sceneId,project_source_key:initial.sourceKey,donor_animation_id:clip,channel_owner_entity_id:entity,model_source_entity_id:entity,donor_asset_id:asset,review_key:'a'.repeat(64),candidate_bank_sha256:'b'.repeat(64),project_changed:false,gameplay_verified:false,capabilities:{review:true,apply:true,build:false,actor_assignment:false},allocation:{candidate_bank_sha256:'b'.repeat(64),allocated_records:[{record_id:id,frame_count:request.source_frame_indices.length,object_count:1,candidate_record_sha256:'c'.repeat(64)}]},proposed_ledger:{schema_version:'legaia.animation-record-ledger.v1',source_scene_id:initial.sceneId,source_bank_sha256:'d'.repeat(64),revision:1,records:[entry],removed_record_ids:[]},animation_id:'animation://town01/authored-record/'+id};
}
function pose(review){return {schema_version:'legaia.model-preview.v1',semantic_id:asset,report:review,frames:review.proposed_ledger.records[0].source_frame_indices.map((_,index)=>({frame_index:index})),animation:{semantic_id:review.animation_id,entity_id:entity,representation:'allocation_preview',clip_id:'allocation-preview',source_clip_id:clip,frame_count:review.proposed_ledger.records[0].source_frame_indices.length,bone_count:1,association:{runtime_assigned:false},source_record:{record_id:id,record_sha256:'c'.repeat(64),bank_sha256:'b'.repeat(64)}}};}
const request={entity_id:entity,expected_source_key:initial.sourceKey,source_frame_indices:[0,1,2,2,1,0,0],edits:[]};
assert.deepEqual(parseAnimationFrameSequence('0-2, 2-0, 0',3),request.source_frame_indices);
for(const text of ['',',','-1','0.5','0-3','0,','99999999999999999999999','0-2,0-2'])assert.throws(()=>parseAnimationFrameSequence(text,3,5));
assert.throws(()=>parseAnimationFrameSequence('0',3,0));
const opt=decodeAnimationAllocationOptions(options(),entity,initial),review=decodeAnimationAllocationReview(report(request),opt,request);
const source={...report(request).proposed_ledger.records[0],donor_record_sha256:'1'.repeat(64),effective_donor_record_sha256:'2'.repeat(64),donor_edits:[{frame_index:0,object_index:0,translation:{x:123}}],source_frame_indices:[2,0,1,2],edits:[{frame_index:0,object_index:0,translation:{y:234},rotation_psx:{z:32}},{frame_index:3,object_index:0,translation:{z:345}}]};
const retainedOptions={...options(),schema_version:'legaia.animation-record-allocation-options.v2',donor_frame_count:4,source_allocated_entry:source,source_animation_id:'animation://town01/authored-record/'+id};
const retained=decodeAnimationAllocationOptions(retainedOptions,entity,initial);
const captureRequest={...request,source_frame_indices:[3,0,1,0],edits:[{frame_index:1,object_index:0,translation:{y:-123},rotation_psx:{x:64}}]};
const flat=flattenRetainedSequence(source,captureRequest.source_frame_indices,captureRequest.edits);
assert.deepEqual(flat,{source_frame_indices:[2,2,0,2],edits:[{frame_index:0,object_index:0,translation:{z:345}},{frame_index:1,object_index:0,translation:{y:-123},rotation_psx:{z:32,x:64}},{frame_index:3,object_index:0,translation:{y:234},rotation_psx:{z:32}}]});
const newId='22222222-2222-4222-8222-222222222222',capturedReport=report(captureRequest);
Object.assign(capturedReport,{schema_version:'legaia.animation-record-allocation-review.v3',source_allocated_entry:source,source_animation_id:retained.source_animation_id,requested_source_frame_indices:captureRequest.source_frame_indices,requested_edits:captureRequest.edits,animation_id:'animation://town01/authored-record/'+newId});
capturedReport.allocation.allocated_records[0].record_id=newId;
capturedReport.proposed_ledger.records=[source,{...source,...flat,record_id:newId,record_sha256:'c'.repeat(64)}];
capturedReport.proposed_ledger.revision=2;
decodeAnimationAllocationReview(capturedReport,retained,captureRequest);
decodeAnimationAllocationReview(capturedReport,retained,{...captureRequest,source_record_id:id});
assert.throws(()=>decodeAnimationAllocationReview(capturedReport,retained,{...captureRequest,source_record_id:newId}));
for(const change of [v=>v.requested_source_frame_indices=[0],v=>v.source_allocated_entry.edits=[],v=>v.proposed_ledger.records.at(-1).donor_edits=[],v=>v.proposed_ledger.records.at(-1).source_frame_indices=[3,0,1,0],v=>v.source_animation_id=clip]){const value=structuredClone(capturedReport);change(value);assert.throws(()=>decodeAnimationAllocationReview(value,retained,captureRequest));}
for(const change of [v=>v.source_allocated_entry.edits[0].translation.y=2048,v=>v.source_allocated_entry.source_frame_indices=[3],v=>v.donor_frame_count=3,v=>v.source_animation_id=clip]){const value=structuredClone(retainedOptions);change(value);assert.throws(()=>decodeAnimationAllocationOptions(value,entity,initial));}
const deliveredOptions=decodeAnimationAllocationOptions({...options(),build_available:true},entity,initial),deliveredReport=report(request);deliveredReport.capabilities.build=true;decodeAnimationAllocationReview(deliveredReport,deliveredOptions,request);
assert.equal(decodeAnimationAllocationPose(pose(review),review,opt).animation.clip_id,'allocation-preview');
for(const edit of [v=>v.project_source_key='e'.repeat(64),v=>v.capabilities.build=true,v=>v.proposed_ledger.records[0].source_frame_indices=[2],v=>v.allocation.allocated_records[0].object_count=2,v=>v.proposed_ledger.removed_record_ids=[id]]){const value=report(request);edit(value);assert.throws(()=>decodeAnimationAllocationReview(value,opt,request));}
for(const edit of [v=>v.animation.association.runtime_assigned=true,v=>v.animation.source_record.record_sha256='e'.repeat(64),v=>v.frames.pop()]){const value=pose(review);edit(value);assert.throws(()=>decodeAnimationAllocationPose(value,review,opt));}
class Node{constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.attributes={};this.value='';this.textContent='';this.open=false;this.disabled=false;this.hidden=false;}append(...nodes){for(const node of nodes){this.children.push(node);node.parent=this;}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this.attributes[k]=String(v);}showModal(){this.open=true;}close(){this.open=false;this.onclose?.();}remove(){if(this.parent)this.parent.children=this.parent.children.filter(node=>node!==this);}}
const tree=node=>[node,...node.children.flatMap(tree)],action=(control,key)=>tree(control.dialog).find(node=>node.dataset.action===key),input=control=>tree(control.dialog).find(node=>node.attributes['aria-label']==='Source frame sequence');
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const original={document:globalThis.document,fetch:globalThis.fetch};
globalThis.document={body:new Node('body'),createElement:tag=>new Node(tag)};
try{
  let ctx={...initial},busy=false,calls=[],applied=[],returned,hold=null;
  globalThis.fetch=async(path,settings)=>{const body=JSON.parse(settings.body);calls.push({path,body});if(hold&&path===hold.path)return hold.pending.promise;
    let value;if(path.endsWith('-options'))value=options();else if(path.endsWith('-pose-preview'))value=pose(report(body));else if(path.endsWith('-preview'))value=report(body);else value={project:{mode:'edit'}};
    return {ok:true,json:async()=>value};};
  const settings={entityId:entity,getContext:()=>ctx,busy:()=>busy,setBusy:value=>busy=value,onApplied:value=>{assert.equal(busy,false,'Committed Apply releases busy before the asset handoff.');applied.push(value);},onPosePreview:async(data,callbacks)=>{returned=callbacks.returnToEditor;assert.equal(data.animation.source_record.record_id,id);return true;}};
  let control=await openAnimationAllocationEditor(settings);assert.equal(await control.ready,true);assert.equal(busy,false);assert.equal(input(control).value,'0-2');assert.equal(action(control,'apply').disabled,true);
  input(control).value='0-2,2-0,0';input(control).oninput();assert.equal(await action(control,'review').onclick(),true);assert.deepEqual(calls.at(-1).body.source_frame_indices,request.source_frame_indices);assert.equal(action(control,'apply').disabled,false);
  assert.equal(await action(control,'pose').onclick(),true);assert.equal(control.dialog.open,false);assert.equal(busy,false);assert.equal(returned(),true);assert.equal(control.dialog.open,true);control.dialog.onclose();assert.equal(control.dialog.open,true,'queued old close must not destroy reopened review');
  input(control).value='0';input(control).oninput();assert.equal(action(control,'apply').disabled,true);await action(control,'review').onclick();assert.equal(await action(control,'apply').onclick(),true);assert.equal(applied.length,1);assert.equal(control.dialog.open,false);assert.equal(busy,false);
  control=await openAnimationAllocationEditor(settings);await control.ready;hold={path:'/api/animation-record-allocation-preview',pending:deferred()};const late=action(control,'review').onclick();assert.equal(busy,true);control.dispose();hold.pending.resolve({ok:true,json:async()=>report({source_frame_indices:[0,1,2],edits:[]})});assert.equal(await late,false);assert.equal(busy,false);assert.equal(applied.length,1);hold=null;
  control=await openAnimationAllocationEditor(settings);await control.ready;await action(control,'review').onclick();ctx={...ctx,sourceKey:'e'.repeat(64)};control.updateState();assert.equal(action(control,'apply').disabled,true);assert.equal(await action(control,'apply').onclick(),false);control.dispose();
}finally{for(const [key,value] of Object.entries(original)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
console.log('Animation allocation sequence, source/review/pose validation, explicit Apply, stale/late/close guards and retained preview Return passed.');
