import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createControllerBranchWalkthroughLayer as createBranchWalkthroughLayer,scriptFlowReportHash,mountControllerBranchWalkthrough as mountScriptBranchWalkthrough} from '../editor/script-branch-walkthrough.js';
import {createScriptWalkthrough,scriptWalkthroughEvidence} from '../editor/script-walkthrough.js';
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:webcrypto});
const owner='scene://fixture/controllers/man-p1/0000',branch='script://fixture/controllers/man-p1/0000/branch/0000',context={projectPath:'C:/private/project',sceneId:'scene://fixture',mode:'edit',scriptKey:'a'.repeat(64)};
const report={status:'decoded_supported_paths',entry_pc:0,instructions:[{pc:0,length:1,mnemonic:'JUMP',successors:[{pc:1,condition:'unconditional'}]},{pc:1,length:1,mnemonic:'SOURCE_1',successors:[]},{pc:2,length:1,mnemonic:'SOURCE_2',successors:[]}],dialogues:[],stops:[],opaque_regions:[]};
const snapshot={schema_version:'legaia.controller-branches.v1',gameplay_verified:false,current_record_sha256:'e'.repeat(64),owner_id:owner,state_key:context.scriptKey,source_record_sha256:'b'.repeat(64),current_report:report,targets:[{semantic_id:branch}]},review={schema_version:snapshot.schema_version,owner_id:owner,state_key:context.scriptKey,source_record_sha256:snapshot.source_record_sha256,current_record_sha256:snapshot.current_record_sha256,project_changed:false,gameplay_verified:false,review_key:'c'.repeat(64),operand_id:branch,value:{target_pc:2},proposed_report:structuredClone(report)};review.proposed_report.instructions[0].successors[0].pc=2;
const before=JSON.stringify({snapshot,review}),args={snapshot,review,context,projectSourceKey:'d'.repeat(64)};
const c=await createBranchWalkthroughLayer({...args,kind:'current'}),p=await createBranchWalkthroughLayer({...args,kind:'proposed'});
assert.equal(c.context.representation,'authored_current');assert.equal(c.context.flow_proof.review_key,null);assert.equal(p.context.representation,'reviewed_proposed');assert.equal(p.context.flow_proof.review_key,review.review_key);assert.notEqual(c.context.flow_proof.report_sha256,p.context.flow_proof.report_sha256);
const walk=createScriptWalkthrough(p.report);walk.start(0);const trace=walk.step(0);assert.equal(trace.pc,2);const evidence=scriptWalkthroughEvidence(trace,p.context);assert.equal(evidence.schema_version,'legaia.script-source-walkthrough.v2');assert.equal(evidence.source.record_sha256,snapshot.source_record_sha256);assert.equal(evidence.runtime_execution,'not_asserted');
const reordered=Object.fromEntries(Object.entries(report).reverse());assert.equal(await scriptFlowReportHash(reordered),c.context.flow_proof.report_sha256);p.report.instructions[0].successors[0].pc=1;assert.equal(JSON.stringify({snapshot,review}),before);
for(const mutate of [a=>a.kind='retail',a=>a.context.mode='live',a=>a.snapshot.gameplay_verified=true,a=>a.snapshot.current_record_sha256=null,a=>a.projectSourceKey=null,a=>a.snapshot.state_key='f'.repeat(64),a=>a.snapshot.owner_id='scene://elsewhere/controllers/man-p1/0000',a=>a.snapshot.source_record_sha256='bad',a=>a.snapshot.current_report=null,a=>a.review.review_key='bad',a=>a.review.operand_id=branch.slice(0,-4)+'ffff',a=>a.review.value={target_pc:true}]){const bad=structuredClone({...args,kind:'proposed'});mutate(bad);await assert.rejects(()=>createBranchWalkthroughLayer(bad));}
for(const mutate of [v=>v.flow_proof.state_key='bad',v=>v.flow_proof.report_sha256=null,v=>v.flow_proof.review_key=null,v=>v.flow_proof.branch_id='other',v=>v.flow_proof.branch_value={target_pc:-1}]){const bad=structuredClone(evidence.source);mutate(bad);assert.throws(()=>scriptWalkthroughEvidence(trace,bad));}
const currentEvidence=scriptWalkthroughEvidence(trace,c.context);assert.equal(currentEvidence.source.flow_proof.branch_id,null);assert.throws(()=>scriptWalkthroughEvidence(trace,{...c.context,flow_proof:{...c.context.flow_proof,review_key:'f'.repeat(64)}}));
class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.textContent='';this.isConnected=true;}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(){}closest(){return null;}querySelectorAll(tag){return tree(this).filter(n=>n!==this&&n.tagName===tag);}remove(){this.isConnected=false;if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)],timers=new Map();let timer=0,live=true,blocked=false;
globalThis.document={createElement:tag=>new Element(tag)};globalThis.setInterval=fn=>{timers.set(++timer,fn);return timer;};globalThis.clearInterval=id=>timers.delete(id);
const host=new Element('div'),control=mountScriptBranchWalkthrough(host,{owner,getContext:()=>context,getProjectSourceKey:()=>args.projectSourceKey,current:()=>live,busy:()=>blocked,selection:()=>0,selectInstruction:()=>true,request:async()=>{throw Error('No request before explicit download');},decodeSnapshot:v=>v,decodeReview:v=>v});
const button=text=>tree(host).find(n=>n.tagName==='button'&&n.textContent===text);
control.sync(snapshot,null);assert.equal(button('Walk through reviewed Proposed flow').disabled,true);await button('Walk through Current flow').onclick();let current=tree(host).find(n=>n.dataset.scriptWalkthrough==='');assert(current);assert.equal(timers.size,1);control.sync(snapshot,review);assert.equal(tree(host).find(n=>n.dataset.scriptWalkthrough===''),current);
await button('Walk through reviewed Proposed flow').onclick();assert.notEqual(tree(host).find(n=>n.dataset.scriptWalkthrough===''),current);assert.equal(timers.size,1);control.sync(snapshot,null);assert.equal(tree(host).some(n=>n.dataset.scriptWalkthrough===''),false);assert.equal(timers.size,0);
blocked=true;control.sync(snapshot,review);await button('Walk through Current flow').onclick();assert.equal(timers.size,0);blocked=false;await button('Walk through Current flow').onclick();control.sync(structuredClone(snapshot),review);assert.equal(timers.size,0);live=false;control.updateState();assert.equal(button('Walk through Current flow').disabled,true);control.dispose();assert.equal(host.children.length,0);
console.log('Controller authored walkthroughs: canonical report identity, Current/Proposed provenance, exact chosen edge, false-claim refusal, review/refresh withdrawal, busy/lifetime guards and no implicit API requests passed');
