import assert from 'node:assert/strict';
import {decodeNpcEffectColorSource,decodeNpcEffectColorReview} from '../editor/npc-effect-colors.js';
const id='authored-actor://00000000-0000-0000-0000-000000000001',donor='scene://town0b/actors/man-p1/0037',key='script://town0b/actors/man-p1/0037/effect-color/0010',draft={scene_id:'scene://town0b',donor_entity_id:donor,position:{x:0,z:0},name:'NPC'},state={scene:{id:'scene://town0b'},actor_drafts:{[id]:draft},project_copy_source_key:'a'.repeat(64)},values={red:255,green:255,blue:255,intensity:32};
const row={semantic_id:key,owner_id:donor,pc:16,mnemonic:'EFFECT_COLOR_INTENSITY',target_context:null,decoded_byte_offset:400,values,authored_values:null,effective_values:values,source_record_sha256:'b'.repeat(64)},source={schema_version:'legaia.npc-effect-colors-source.v1',entity_id:id,scene_id:draft.scene_id,project_source_key:state.project_copy_source_key,draft,options:{supported:true,targets:[row]},gameplay_verified:false,runtime_effect:'not_asserted',visual_color_space:'not_asserted'};
decodeNpcEffectColorSource(source,id,state);
for(const change of [v=>v.draft.name='other',v=>v.project_source_key='c'.repeat(64),v=>v.options.targets[0].pc=true,v=>v.options.targets[0].values.intensity=32768,v=>v.options.targets[0].owner_id='other',v=>v.options.targets[0].effective_values={...values,red:0},v=>v.options.targets.push(row)]){const v=structuredClone(source);change(v);assert.throws(()=>decodeNpcEffectColorSource(v,id,state));}
const requested={red:12,green:34,blue:56,intensity:-1234},request={entity_id:id,entries:{[key]:requested}},review={schema_version:'legaia.npc-effect-colors-review.v1',entity_id:id,project_source_key:state.project_copy_source_key,request,current:draft,proposed:{...draft,effect_colors:{donor_entity_id:donor,entries:request.entries}},changes:[{effect_color_id:key,owner_id:donor,pc:16,mnemonic:row.mnemonic,target_context:null,decoded_byte_offset:400,byte_length:5,field:'color_intensity',source_record_sha256:row.source_record_sha256,source_decoded_man_sha256:'c'.repeat(64),before_values:values,after_values:requested,before_hex:'ffffff2000',after_hex:'0c22382efb'}],review_key:'d'.repeat(64),gameplay_verified:false,runtime_effect:'not_asserted',visual_color_space:'not_asserted'};
assert.deepEqual(decodeNpcEffectColorReview(review,request,source,state),review);
for(const change of [v=>v.changes[0].decoded_byte_offset++,v=>v.changes[0].byte_length=4,v=>v.changes[0].before_hex='0000000000',v=>v.changes[0].after_hex='0c22382efc',v=>v.changes[0].after_values.red=true,v=>v.changes[0].source_record_sha256='a'.repeat(64),v=>v.changes[0].target_context=1,v=>v.proposed.position.x=1]){const v=structuredClone(review);change(v);assert.throws(()=>decodeNpcEffectColorReview(v,request,source,state));}
const clear=structuredClone(review);clear.request={entity_id:id,entries:{}};clear.proposed=draft;clear.changes=[];decodeNpcEffectColorReview(clear,clear.request,source,state);
assert.throws(()=>decodeNpcEffectColorReview(review,request,source,{...state,project_copy_source_key:'c'.repeat(64)}));
console.log('NPC effect color owner/source qualification, typed bounds, exact five-byte native audit, requested pair layers, clear and stale refusal passed.');
