import assert from 'node:assert/strict';import fs from 'node:fs';
import {renderGaussianEnvelope,renderGaussianEnvelopePitch,directPreviewPitch,previewPitch} from '../editor/audio-native-gaussian.js';
import {decodeNativeLoop,decodeNativePitchLoop} from '../editor/audio-native-loop.js';
import {mountEnvelopeAudition} from '../editor/audio-envelope-audition.js';
assert.deepEqual(directPreviewPitch(0),{pitchRegister:0,effectiveSourceRate:0});assert.deepEqual(directPreviewPitch(4096),{pitchRegister:4096,effectiveSourceRate:44100});assert.equal(directPreviewPitch(16383).effectiveSourceRate,176389.2333984375);
for(const invalid of [-1,16384,true,'4096',1.5,NaN,null])assert.throws(()=>directPreviewPitch(invalid));
const f=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),raw=g=>Uint8Array.from(Buffer.from(g.adpcm.current.adpcm_base64,'base64'));
let frames=0;
for(const row of f.cases){const g=f.groups[row.mode],bytes=Uint8Array.from(Buffer.from(g.adpcm[row.layer].adpcm_base64,'base64')),before=bytes.slice(),result=renderGaussianEnvelopePitch(bytes,row.pitch,15,31,{frameCount:row.frames,keyOffFrame:22050},row.mode),oracle=fs.readFileSync(row.pcm_file),actual=new DataView(result.bytes.buffer),expected=new DataView(oracle.buffer,oracle.byteOffset,oracle.byteLength);assert.equal(result.pitchRegister,row.pitch);assert.equal(result.sourceRate,row.pitch*44100/4096);for(let i=0;i<row.frames;i++)assert.equal(actual.getInt16(i*2,true),Math.floor(expected.getInt16(i*2,true)*result.model.levels[i]/32768),`${row.mode} ${row.layer} pitch ${row.pitch} frame ${i}`);assert.deepEqual(bytes,before);frames+=row.frames;}
for(const mode of ['loop','one-pass'])for(const rate of [11025,22050,32000,44100,48000]){const g=f.groups[mode],direct=renderGaussianEnvelopePitch(raw(g),previewPitch(rate).pitchRegister,15,31,{frameCount:2048,keyOffFrame:1024},mode),preset=renderGaussianEnvelope(raw(g),rate,15,31,{frameCount:2048,keyOffFrame:1024},mode);assert.deepEqual({...direct,sourceRate:rate},preset);}
assert.throws(()=>decodeNativeLoop(raw(f.groups.loop),240002));assert.throws(()=>decodeNativePitchLoop(raw(f.groups.loop),882002));assert.equal(decodeNativePitchLoop(raw(f.groups.loop),882001).bytes.length,1764002);
assert.throws(()=>renderGaussianEnvelopePitch(raw(f.groups.loop),4096,15,31,{},'unknown'));
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.value='';this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(key,value){this.attrs[key]=value;}}
globalThis.document={createElement:tag=>new Element(tag)};const nodes=root=>[root,...root.children.flatMap(nodes)],control=(root,label)=>nodes(root).find(n=>n.attrs['aria-label']===label),button=(root,label)=>nodes(root).find(n=>n.tag==='button'&&n.textContent===label);
const g=f.groups.loop;let fresh=true,stops=0,played=null;const errors=[],request=async(path,init)=>{const body=JSON.parse(init.body),value=path==='/api/audio-sample-authoring'?g.options:path==='/api/audio-sample-adpcm'?g.adpcm[body.layer]:g.pcm[body.layer];return {ok:true,text:async()=>JSON.stringify(value)};};
const audioContext=()=>({destination:{},resume:async()=>{},close:async()=>{},createGain:()=>({gain:{value:0},connect(){},disconnect(){}}),createBuffer(channels,count,rate){played=new Float32Array(count);return {getChannelData:()=>played};},createBufferSource:()=>({connect(){},disconnect(){},start(){},stop(){stops++;}})});
const host=new Element('section'),mounted=mountEnvelopeAudition(host,{bank:g.bank,request,audioContext,fresh:()=>fresh,onError:e=>errors.push(e.message)});mounted.update(g.config);const pitchMode=control(host,'Envelope pitch source'),pitch=control(host,'Envelope SPU pitch register'),interpolation=control(host,'Envelope native interpolation'),mode=control(host,'Envelope sample playback'),rate=control(host,'Envelope sample rate'),load=button(host,'Load envelope sample'),play=button(host,'Play envelope audition'),save=button(host,'Save envelope preview WAV');
assert.equal(pitchMode.value,'rate');assert(pitchMode.disabled);await load.onclick();mode.value='native-loop';mode.onchange();await load.onclick();interpolation.value='gaussian';interpolation.onchange();pitchMode.value='register';pitchMode.onchange();assert(!play.disabled&&!save.disabled);assert(rate.disabled);pitch.value='0';pitch.oninput();await play.onclick();assert(played);pitch.value='16383';pitch.oninput();assert.equal(stops,1);assert(!play.disabled);for(const value of ['','-1','16384','1.5']){pitch.value=value;pitch.oninput();assert(play.disabled&&save.disabled);}
pitch.value='4096';pitch.oninput();await play.onclick();interpolation.value='linear';interpolation.onchange();assert.equal(stops,2);assert.equal(pitchMode.value,'rate');assert(pitchMode.disabled&&pitch.disabled&&play.disabled);
mounted.clear();mounted.update(g.config);assert.equal(pitchMode.value,'rate');assert.equal(pitch.value,'4096');fresh=false;pitch.oninput();assert(host.hidden&&play.disabled);assert.deepEqual(errors,[]);
console.log(JSON.stringify({passed:true,native_oracle_cases:f.cases.length,native_oracle_frames:frames,zero_holds:true,full_register_range:true,five_second_maximum:true,preset_compatibility:true,strict_inputs_and_budget:true,ui_load_guard_mode_stop_reset_stale:true}));
