import assert from 'node:assert/strict';
import {nativeModelFaceAtTriangle,nativeModelFaceTriangles} from '../editor/model-face-picking.js';
import {nativeSceneFaceAtTriangle} from '../editor/model-face-picking.js';
const source={asset_id:'asset://fixture/model/0',objects:[{vertex_count:4,primitives:[{primitive_index:0,corner_count:4},{primitive_index:1,corner_count:3}]},{vertex_count:3,primitives:[{primitive_index:0,corner_count:3}]}]},preview={semantic_id:source.asset_id,coordinate_system:'retail_tmd_object_local',objects:[{object_index:0,vertex_count:4,triangle_start:0,triangle_count:3},{object_index:1,vertex_count:3,triangle_start:3,triangle_count:1}],triangles:[[0,1,2],[1,3,2],[0,1,3],[4,5,6]]};
const before=structuredClone({source,preview});assert.deepEqual(nativeModelFaceAtTriangle(preview,source,0),{object_index:0,primitive_index:0});assert.deepEqual(nativeModelFaceAtTriangle(preview,source,1),{object_index:0,primitive_index:0});assert.deepEqual(nativeModelFaceAtTriangle(preview,source,2),{object_index:0,primitive_index:1});assert.deepEqual(nativeModelFaceAtTriangle(preview,source,3),{object_index:1,primitive_index:0});
for(const i of [-1,4,.5,true,null])assert.throws(()=>nativeModelFaceAtTriangle(preview,source,i));for(const mutate of [p=>p.semantic_id='foreign',p=>p.posed=true,p=>p.objects[1].triangle_start=2,p=>p.objects[0].triangle_count=2,p=>p.triangles.pop(),p=>p.objects[0].vertex_count=5]){const p=structuredClone(preview);mutate(p);assert.throws(()=>nativeModelFaceAtTriangle(p,source,0));}assert.deepEqual({source,preview},before);console.log('Native triangle/quad/shared-object face ownership and stale/posed/partial-layout rejection passed.');

import {selectedTriangleBoundary} from '../editor/scene-renderer.js';
assert.deepEqual(nativeModelFaceTriangles(preview,source,0,0),[0,1]);assert.deepEqual(nativeModelFaceTriangles(preview,source,1,0),[3]);assert.deepEqual(selectedTriangleBoundary(preview.triangles,[0,1]),[[0,1],[2,0],[1,3],[3,2]]);assert.equal(selectedTriangleBoundary(preview.triangles,[3]).length,3);for(const ids of [[],[0,0],[0,1,2],[-1],[4],[true]])assert.throws(()=>selectedTriangleBoundary(preview.triangles,ids));for(const pair of [[-1,0],[0,2],[true,0]])assert.throws(()=>nativeModelFaceTriangles(preview,source,...pair));assert.deepEqual({source,preview},before);console.log('Native face boundary mapping, quad diagonal cancellation and detached bounded edge selection passed.');

const sceneSource=structuredClone(source);sceneSource.objects[0].primitives[0].vertices=[0,1,2,3];sceneSource.objects[0].primitives[1].vertices=[0,1,3];sceneSource.objects[1].primitives[0].vertices=[0,1,2];
const placed=structuredClone(preview);placed.coordinate_system='retail_psx_actor_local_y_down';placed.posed=true;placed.vertices=Array.from({length:7},()=>[30,60,90]);placed.objects[0].vertex_start=0;placed.objects[1].vertex_start=4;
const geometry={asset_id:source.asset_id,geometry_key:'placed',preview:placed},unchanged=structuredClone({geometry,sceneSource});
assert.deepEqual(nativeSceneFaceAtTriangle(geometry,sceneSource,3),{object_index:1,primitive_index:0});
const prefix=structuredClone(geometry);prefix.preview.objects.pop();prefix.preview.vertices.length=4;prefix.preview.triangles.length=3;assert.deepEqual(nativeSceneFaceAtTriangle(prefix,sceneSource,1),{object_index:0,primitive_index:0});
for(const mutate of [g=>g.asset_id='foreign',g=>g.preview.semantic_id='foreign',g=>g.preview.objects[1].vertex_start=3,g=>g.preview.triangles[0][0]=3,g=>g.preview.triangles.pop(),g=>g.preview.vertices.pop(),g=>g.preview.objects[0].triangle_count=2,g=>g.preview.coordinate_system='world']){const g=structuredClone(geometry);mutate(g);assert.throws(()=>nativeSceneFaceAtTriangle(g,sceneSource,0));}
for(const i of [-1,4,.5,true,null])assert.throws(()=>nativeSceneFaceAtTriangle(geometry,sceneSource,i));assert.deepEqual({geometry,sceneSource},unchanged);console.log('Placed posed face ownership, complete object prefixes, exact Current connectivity and detached stale-layout rejection passed.');
