import assert from 'node:assert/strict';
import {decodeAudioWaveform,openAudioWaveform} from '../editor/audio-waveform.js';
const sample={index:0,table_index:1,size_units:2,offset:3104,size_bytes:16,block_aligned:true,source_sha256:'b'.repeat(64)};
const bank={asset_id:'audio://legaia/prot/0877',scene_id:'scene://town01',source_key:'a'.repeat(64),source_record:{entry_sha256:'c'.repeat(64)},reference_commit:'d'.repeat(40),bank_sha256:'e'.repeat(64)};
const report={schema_version:'legaia.audio-waveform-inspection.v1',...bank,sample,read_only:true,project_changed:false,runtime_state:'not_observed',decoder:'psx-spu-adpcm-integer-v1',history:'zero-initialized',source_size_bytes:16,source_sha256:sample.source_sha256,decoded_blocks:1,decoded_frames:28,consumed_bytes:16,remaining_bytes:0,termination:{reason:'encoded-end',byte_offset:0},markers:[{block_index:0,frame_offset:0,flags:1,encoded_shift:0,effective_shift:0}],bins:Array.from({length:28},(_,frame_offset)=>({frame_offset,frame_count:1,minimum:0,maximum:0})),frame_limit:114688,sample_rate:null,limitations:['No rate or pitch is inferred.']};
const detached=decodeAudioWaveform(report,bank,sample);detached.bins[0].minimum=-1;assert.equal(report.bins[0].minimum,0);
for(const change of [r=>r.sample_rate=44100,r=>r.source_sha256='f'.repeat(64),r=>r.bank_sha256='f'.repeat(64),r=>r.decoded_frames++,r=>r.remaining_bytes++,r=>r.termination.reason='source-span-exhausted',r=>r.markers=[],r=>r.markers[0].flags=8,r=>r.markers[0].effective_shift=9,r=>r.bins[0].maximum=-1,r=>r.bins[1].frame_offset=0,r=>r.payload=[]]){const bad=structuredClone(report);change(bad);assert.throws(()=>decodeAudioWaveform(bad,bank,sample));}
class Element{constructor(tag){this.tag=tag;this.style={};this.dataset={};this.children=[];this.listeners={};this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}setAttribute(){}addEventListener(name,fn){this.listeners[name]=fn;}showModal(){}close(){this.listeners.close?.();}remove(){this.removed=true;}getContext(){return {clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}};}}
globalThis.document={body:new Element('body'),createElement:tag=>new Element(tag)};let current={sourceKey:bank.source_key},resolve;
let view=openAudioWaveform({bank,sample,getContext:()=>current,request:async()=>({ok:true,text:async()=>JSON.stringify(report)})});try{await view.ready;assert(view.dialog.children.some(n=>n.textContent==='Source waveform prefix decoded.'));current={sourceKey:'f'.repeat(64)};await new Promise(done=>setTimeout(done,350));assert(view.dialog.children.some(n=>n.textContent.includes('sources changed')));assert(view.dialog.children.find(n=>n.textContent==='Save waveform evidence…').disabled);}finally{view.dispose();}
current={sourceKey:bank.source_key};view=openAudioWaveform({bank,sample,getContext:()=>current,request:()=>new Promise(done=>resolve=done)});view.dispose();resolve({ok:true,text:async()=>JSON.stringify(report)});await view.ready;assert(view.dialog.removed);assert(!view.dialog.children.some(n=>n.textContent==='Source waveform prefix decoded.'));
console.log('Waveform source/prefix/envelope/marker guards, detached metadata, stale withdrawal and late-close ownership passed.');

const emptySample={...sample,size_units:0,size_bytes:0,source_sha256:'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'},emptyReport={...report,sample:emptySample,source_size_bytes:0,source_sha256:emptySample.source_sha256,decoded_blocks:0,decoded_frames:0,consumed_bytes:0,termination:{reason:'source-span-exhausted',byte_offset:0},markers:[],bins:[]};
view=openAudioWaveform({bank,sample:emptySample,getContext:()=>current,request:async()=>({ok:true,text:async()=>JSON.stringify(emptyReport)})});try{await view.ready;assert(view.dialog.children.some(n=>n.textContent==='Source waveform prefix decoded.'));assert(!view.dialog.children.some(n=>n.id==='audio-audition'));}finally{view.dispose();}console.log('Empty source span retains inspection but exposes no audition controls.');
