import assert from 'node:assert/strict';
import {decodeAnimationRecordLibrary,decodeSavedAnimationPose,decodeRecordActivationReview,openAnimationRecordLibrary} from '../editor/animation-record-library.js';
const entity='scene://town01/actors/man-p1/0011',asset='asset://town01/models/scene-tmd/0105',id='11111111-1111-4111-8111-111111111111';
const initial={projectPath:'C:/private/project',sceneId:'scene://town01',sourceKey:'a'.repeat(64),mode:'edit'};
const row=()=>({record_id:id,animation_id:'animation://town01/authored-record/'+id,entity_id:entity,channel_owner_entity_id:entity,model_source_entity_id:entity,donor_asset_id:asset,donor_animation_id:'animation://town01/scene-anm/0012',record_sha256:'b'.repeat(64),frame_count:3,object_count:6,active:true,runtime_assigned:false});
const library=()=>({schema_version:'legaia.animation-record-library.v1',scene_id:initial.sceneId,project_source_key:initial.sourceKey,revision:1,records:[row()],activation_available:true,build_available:false,gameplay_verified:false});
const pose=()=>({schema_version:'legaia.model-preview.v1',semantic_id:asset,frames:[{}, {}, {}],animation:{representation:'allocated_record',clip_id:'allocated-record',semantic_id:row().animation_id,entity_id:entity,frame_count:3,bone_count:6,saved_record:row(),source_record:{record_id:id,record_sha256:row().record_sha256,byte_coordinate_space:'retained_native_animation_record'},association:{runtime_assigned:false}}});
const review=request=>({schema_version:'legaia.animation-record-activation-review.v1',scene_id:initial.sceneId,project_source_key:initial.sourceKey,record_id:id,active:request.active,review_key:'c'.repeat(64),candidate_bank_sha256:'d'.repeat(64),project_changed:false,gameplay_verified:false,proposed_ledger:{schema_version:'legaia.animation-record-ledger.v1',source_scene_id:initial.sceneId,revision:2,records:[row()],removed_record_ids:request.active?[]:[id]}});
decodeAnimationRecordLibrary(library(),initial);decodeSavedAnimationPose(pose(),row());const request={scene_id:initial.sceneId,record_id:id,active:false,expected_source_key:initial.sourceKey};decodeRecordActivationReview(review(request),request,row());
decodeAnimationRecordLibrary({...library(),build_available:true},initial);
for(const edit of [v=>v.project_source_key='0'.repeat(64),v=>v.records.push(row()),v=>v.records[0].runtime_assigned=true,v=>v.records[0].frame_count=513,v=>v.activation_available=false]){const value=library();edit(value);assert.throws(()=>decodeAnimationRecordLibrary(value,initial));}
for(const edit of [v=>v.animation.saved_record.active=false,v=>v.animation.source_record.record_sha256='0'.repeat(64),v=>v.frames.pop()]){const value=pose();edit(value);assert.throws(()=>decodeSavedAnimationPose(value,row()));}
for(const edit of [v=>v.active=true,v=>v.proposed_ledger.removed_record_ids=[],v=>v.proposed_ledger.records[0].record_sha256='0'.repeat(64)]){const value=review(request);edit(value);assert.throws(()=>decodeRecordActivationReview(value,request,row()));}
class Node{constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.attributes={};this.value='';this.open=false;this.disabled=false;}append(...nodes){for(const n of nodes){this.children.push(n);n.parent=this;}}setAttribute(k,v){this.attributes[k]=v;}showModal(){this.open=true;}close(){this.open=false;this.onclose?.();}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}}
const tree=n=>[n,...n.children.flatMap(tree)],action=(c,k)=>tree(c.dialog).find(n=>n.dataset.action===k);
const old={document:globalThis.document,fetch:globalThis.fetch};globalThis.document={body:new Node('body'),createElement:t=>new Node(t)};
try{
  let context={...initial},busy=false,applied=0,returned,calls=[],delay=null;
  globalThis.fetch=async(path,settings)=>{const body=JSON.parse(settings.body);calls.push({path,body});if(delay&&path===delay.path)return delay.promise;return {ok:true,json:async()=>path.endsWith('-library')?library():path.endsWith('-pose')?pose():path.endsWith('-preview')?review(body):{project:{mode:'edit'}}};};
  const settings={entityId:entity,getContext:()=>context,busy:()=>busy,setBusy:v=>busy=v,onApplied:()=>applied++,onPosePreview:async(_,callbacks)=>{returned=callbacks.returnToEditor;return true;}};
  let control=await openAnimationRecordLibrary(settings);await control.ready;assert.equal(action(control,'apply').disabled,true);
  assert.equal(await action(control,'review').onclick(),true);assert.equal(calls.at(-1).body.active,false);assert.equal(action(control,'apply').disabled,false);
  assert.equal(await action(control,'pose').onclick(),true);assert.equal(control.dialog.open,false);assert.equal(returned(),true);control.dialog.onclose();assert.equal(control.dialog.open,true);assert.equal(action(control,'apply').disabled,false);
  assert.equal(await action(control,'apply').onclick(),true);assert.equal(applied,1);assert.equal(busy,false);assert.equal(control.dialog.open,false);
  control=await openAnimationRecordLibrary(settings);await control.ready;await action(control,'review').onclick();context={...context,sourceKey:'0'.repeat(64)};control.updateState();assert.equal(action(control,'apply').disabled,true);assert.equal(await action(control,'apply').onclick(),false);control.dispose();
  context={...initial};control=await openAnimationRecordLibrary(settings);await control.ready;let resolve;delay={path:'/api/animation-record-activation-preview',promise:new Promise(done=>resolve=done)};const late=action(control,'review').onclick();control.dispose();resolve({ok:true,json:async()=>review(request)});assert.equal(await late,false);assert.equal(applied,1);assert.equal(busy,false);
}finally{for(const [k,v] of Object.entries(old)){if(v===undefined)delete globalThis[k];else globalThis[k]=v;}}
console.log('Saved clip library provenance, exact lifecycle review, explicit Apply, retained preview Return and stale/late/close guards passed.');
