import assert from 'node:assert/strict';
import {decodeNpcMovementSource,decodeNpcMovementReview} from '../editor/npc-movement.js';
const id='authored-actor://00000000-0000-4000-8000-000000000001',owner='scene://town01/actors/man-p1/0040',move='script://town01/actors/man-p1/0040/movement/001b',key='a'.repeat(64),draft={scene_id:'scene://town01',donor_entity_id:owner,name:'Resident',position:{x:128,z:256},waits:{donor_entity_id:owner,entries:{'script://town01/actors/man-p1/0040/wait/0065':{duration_ticks:11}}}},state={scene:{id:draft.scene_id},actor_drafts:{[id]:draft},project_copy_source_key:key};
const target={semantic_id:move,owner_id:owner,pc:27,mnemonic:'NPC_RUN',target_context:null,operand_offsets:{x:0,z:1,move_id:3},values:{x:13888,z:5056,move_id:9},authored_values:null,effective_values:{x:13888,z:5056,move_id:9},source_record_sha256:'b'.repeat(64)},source={schema_version:'legaia.npc-movement-source.v1',entity_id:id,scene_id:draft.scene_id,draft,project_source_key:key,options:{supported:true,targets:[target]},gameplay_verified:false,runtime_dispatch:'not_asserted'};
assert.deepEqual(decodeNpcMovementSource(source,id,state),source);
const request={entity_id:id,entries:{[move]:{x:3200}}},review={schema_version:'legaia.npc-movement-review.v1',entity_id:id,project_source_key:key,request,current:draft,proposed:{...draft,movement:{donor_entity_id:owner,entries:request.entries}},review_key:'c'.repeat(64),gameplay_verified:false,runtime_dispatch:'not_asserted'};
assert.deepEqual(decodeNpcMovementReview(review,request,source,state),review);
for(const mutate of [v=>v.project_source_key='d'.repeat(64),v=>v.options.targets[0].owner_id='wrong',v=>v.options.targets[0].effective_values.x=3200,v=>v.options.targets[0].operand_offsets.move_id=2,v=>v.options.targets[0].target_context=256,v=>v.draft.name='Wrong']){const v=structuredClone(source);mutate(v);assert.throws(()=>decodeNpcMovementSource(v,id,state));}
for(const mutate of [v=>v.proposed.position.x++,v=>v.proposed.waits.entries={},v=>v.proposed.donor_entity_id='wrong',v=>v.proposed.movement.entries[move].x=3264]){const v=structuredClone(review);mutate(v);assert.throws(()=>decodeNpcMovementReview(v,request,source,state));}
for(const fields of [{x:32},{x:true},{move_id:256},{y:0},{x:128,depth:0}])assert.throws(()=>decodeNpcMovementReview(review,{entity_id:id,entries:{[move]:fields}},source,state));
console.log('NPC movement source/typed field/offset/dispatch/review guards and retained placement/waits pass.');
