import assert from 'node:assert/strict';
import {decodeNpcAppearanceSource,decodeNpcAppearanceReview,decodeNpcAppearanceScene} from '../editor/npc-appearance.js';
const id='authored-actor://00000000-0000-4000-8000-000000000001',script='scene://town01/actors/man-p1/0012',witness='scene://town01/actors/man-p1/0040',key='a'.repeat(64),draft={scene_id:'scene://town01',donor_entity_id:script,name:'Resident',position:{x:128,z:256},dialogue:{donor_entity_id:script,runs:{'script://town01/actors/man-p1/0012/dialogue/0048/run/0049':'Hello'}}},state={actor_drafts:{[id]:draft},scene:{id:draft.scene_id,entities:[{id:script},{id:witness}]},project_copy_source_key:key};
const source={schema_version:'legaia.npc-appearance-source.v1',entity_id:id,scene_id:draft.scene_id,project_source_key:key,draft,options:{supported:true,source:{decoded_man_sha256:'b'.repeat(64)},options:[{donor_entity_id:witness,asset_id:'asset://town01/models/scene-tmd/0092',animation_id:9,label:'Witness'}]},gameplay_verified:false,runtime_binding:'not_asserted'};
assert.deepEqual(decodeNpcAppearanceSource(source,id,state),source);
const request={entity_id:id,donor_entity_id:witness},review={schema_version:'legaia.npc-appearance-review.v1',entity_id:id,project_source_key:key,request,current:draft,proposed:{...draft,appearance:{script_donor_entity_id:script,donor_entity_id:witness}},review_key:'c'.repeat(64),gameplay_verified:false,runtime_binding:'not_asserted'};
assert.deepEqual(decodeNpcAppearanceReview(review,request,source,state),review);
for(const mutate of [v=>v.project_source_key='d'.repeat(64),v=>v.options.options[0].donor_entity_id='wrong',v=>v.options.options[0].animation_id=0,v=>v.draft.name='Wrong']){const v=structuredClone(source);mutate(v);assert.throws(()=>decodeNpcAppearanceSource(v,id,state));}
for(const mutate of [v=>v.proposed.donor_entity_id=witness,v=>v.proposed.dialogue.runs={},v=>v.proposed.position.x=256,v=>v.proposed.appearance.script_donor_entity_id=witness]){const v=structuredClone(review);mutate(v);assert.throws(()=>decodeNpcAppearanceReview(v,request,source,state));}
const detached=decodeNpcAppearanceReview(review,request,source,state);detached.proposed.appearance.donor_entity_id='Detached';assert.equal(review.proposed.appearance.donor_entity_id,witness);
console.log('NPC appearance source, exact reviewed pair, independent script/text/position and stale/forged rejection pass.');

const row={entity_id:id,kind:'actor_draft',donor_entity_id:script,source_actor_id:script,asset_id:'asset://town01/models/scene-tmd/0105',geometry_key:'old',position:{x:128,z:256},model_reference:{asset_semantic_id:'asset://town01/models/scene-tmd/0105'},renderable:true,evidence:{position:'authored NPC draft',runtime:'not verified',appearance:'retail script donor'}},other={entity_id:script,kind:'actor',renderable:false},base={source_key:'e'.repeat(64),schema:'legaia.scene-preview.v1',scene_id:draft.scene_id,coordinate_system:'native',position_to_display:{scale:1},entities:[row,other],assets:[]};state.scene_preview_source_key=base.source_key;
const target={...row,evidence:{...row.evidence,appearance:'independent appearance witness'},source_actor_id:witness,asset_id:source.options.options[0].asset_id,geometry_key:'new',model_reference:{asset_semantic_id:source.options.options[0].asset_id}},scene={...base,representation:'authored',entities:[target,other],assets:[{geometry_key:'new',asset_id:target.asset_id,preview:{semantic_id:target.asset_id}}]},response={schema_version:'legaia.npc-appearance-scene.v1',review,scene_preview_source_key:base.source_key,scene};
assert.deepEqual(decodeNpcAppearanceScene(response,review,state,base,source),scene);
for(const mutate of [v=>v.scene.entities[0].position.x++,v=>v.scene.entities[0].donor_entity_id=witness,v=>v.scene.entities[1].kind='changed',v=>v.scene.entities[0].asset_id='wrong',v=>v.scene_preview_source_key='f'.repeat(64),v=>v.scene.assets.push({...v.scene.assets[0]})]){const v=structuredClone(response);mutate(v);assert.throws(()=>decodeNpcAppearanceScene(v,review,state,base,source));}
console.log('Detached appearance scene identity, retained placement/script and unrelated geometry guards pass.');
