import assert from 'node:assert/strict';
import {modelMaterialsContext,decodeModelMaterialSource,validateModelMaterialEdits,decodeModelMaterialReview,modelMaterialReportWithoutPreviews,openModelMaterialsEditor} from '../editor/model-materials.js';

const h=c=>c.repeat(64),assetId='asset://town01/models/scene-tmd/0000',context={projectPath:'C:/private/material-project',sceneId:'scene://town01',mode:'edit',sourceKey:h('f')};
const primitive=(index,offset,tpage=0xa061)=>({primitive_index:index,byte_offset:offset,textured:true,clut:0x8403,tpage,page_column:tpage&15,page_row:(tpage>>4)&1,texture_bpp:[4,8,16,null][(tpage>>7)&3],clut_column:3,clut_row:16,source_blend_mode:(tpage>>5)&3});
const untextured=()=>({primitive_index:2,byte_offset:108,textured:false,...Object.fromEntries(['clut','tpage','page_column','page_row','texture_bpp','clut_column','clut_row','source_blend_mode'].map(k=>[k,null]))});
const objects=()=>[{object_index:0,groups:[{group_index:0,byte_offset:40,flags:0x21,mode:0xa0,semi_transparent:false,primitives:[primitive(0,48),primitive(1,72)]},{group_index:1,byte_offset:100,flags:0x18,mode:0xa0,semi_transparent:false,primitives:[untextured()]}]}];
const snapshot=()=>({schema_version:'legaia.model-material-source.v1',asset_id:assetId,scene_id:context.sceneId,source_sha256:h('b'),effective_sha256:h('a'),project_source_key:context.sourceKey,objects:objects(),retail_objects:objects(),limitations:['Fixed source layout only.','Encoded ABR is replaced by caller blend state.']});
const bindingEdit=(index=0,column=2)=>({kind:'primitive',object_index:0,primitive_index:index,values:{page_column:column}}),groupEdit=(index=0)=>({kind:'group',object_index:0,group_index:index,values:{semi_transparent:true}});
const existing={kind:'vertex',object_index:0,vector_index:0,axis:'x',byte_offset:200,before_value:0,after_value:2};
const model=()=>({schema_version:'legaia.model-preview.v1',semantic_id:assetId,coordinate_system:'retail_tmd_object_local',vertices:[[2,0,0],[0,1,0],[0,0,1]],triangles:[[0,1,2],[2,1,0]],triangle_colors:[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]],triangle_uvs:[[[1,1],[2,1],[1,2]],[[1,1],[2,1],[1,2]]],materials:[{textured:true,clut:0x8403,tpage:0xa061,semi_transparent:false}],triangle_materials:[0,0],textures:[{material_index:0,status:'missing',source_ids:[],reason:'No matched texture in source catalog.'}]});
const report=(edits=[bindingEdit()],source=snapshot())=>{const pending=[];for(const edit of edits){const group=source.objects[edit.object_index].groups[edit.kind==='group'?edit.group_index:0];if(edit.kind==='group'){const after=(group.mode&~2)|(edit.values.semi_transparent?2:0);if(after!==group.mode)pending.push({kind:'primitive_group',object_index:0,group_index:group.group_index,field:'gpu_mode',byte_offset:group.byte_offset+7,before_value:group.mode,after_value:after,primitive_indices:group.primitives.map(row=>row.primitive_index)});}else{const row=group.primitives.find(row=>row.primitive_index===edit.primitive_index),after=(row.tpage&~15)|edit.values.page_column;if(after!==row.tpage)pending.push({kind:'primitive',object_index:0,primitive_index:row.primitive_index,group_index:0,field:'tpage',byte_offset:row.byte_offset+10,before_value:row.tpage,after_value:after});}}return {schema_version:'legaia.model-material-review.v1',asset_id:assetId,scene_id:context.sceneId,source_sha256:source.source_sha256,effective_sha256:source.effective_sha256,project_source_key:context.sourceKey,proposed_sha256:pending.length?h('c'):source.effective_sha256,coordinate_changes:[existing,...pending],changes_from_current:pending,review_key:h('d'),project_changed:false,gameplay_verified:false,limitations:['Existing layout, preview blending approximate.'],preview:model(),current_preview:model()};};
const noopEdit={kind:'group',object_index:0,group_index:0,values:{semi_transparent:false}},state=value=>({project:{path:context.projectPath,mode:'edit'},scene:{id:context.sceneId},scene_preview_source_key:h('e'),model_material_report:modelMaterialReportWithoutPreviews(value)});

assert.deepEqual(modelMaterialsContext(context),context);for(const patch of [{mode:'live'},{sourceKey:'stale'},{sceneId:null},{extra:true}])assert.throws(()=>modelMaterialsContext({...context,...patch}));
const source=snapshot(),decoded=decodeModelMaterialSource(source,assetId,context);decoded.objects[0].groups[0].primitives[0].clut=0;assert.equal(source.objects[0].groups[0].primitives[0].clut,0x8403);
for(const mutate of [v=>v.objects[0].groups[0].mode|=2,v=>v.objects[0].groups[0].primitives[0].source_blend_mode=0,v=>v.objects[0].groups[0].primitives[0].byte_offset=40,v=>v.objects[0].groups[0].primitives[1].primitive_index=0,v=>v.project_source_key=h('e'),v=>v.objects[0].groups[0].flags=0x19,v=>v.objects[0].groups[0].primitives[0].tpage^=0x20]){const value=snapshot();mutate(value);assert.throws(()=>decodeModelMaterialSource(value,assetId,context));}
const authored=snapshot();authored.objects[0].groups[0].mode|=2;authored.objects[0].groups[0].semi_transparent=true;authored.objects[0].groups[0].primitives[0]=primitive(0,48,0xa062);assert.equal(decodeModelMaterialSource(authored,assetId,context).objects[0].groups[0].semi_transparent,true);
assert.deepEqual(validateModelMaterialEdits(source,[bindingEdit(),groupEdit(1)]),[bindingEdit(),groupEdit(1)]);assert.throws(()=>validateModelMaterialEdits(source,[bindingEdit(),bindingEdit()]));for(const values of [{tpage:1},{source_blend_mode:1},{page_column:true},{page_row:2},{texture_bpp:3},{clut_row:512},{texture_bpp:16,clut_column:1}])assert.throws(()=>validateModelMaterialEdits(source,[{...bindingEdit(),values}]));assert.throws(()=>validateModelMaterialEdits(source,[bindingEdit(2)]));
const direct=snapshot();direct.objects[0].groups[0].primitives[0]=primitive(0,48,0xa161);direct.retail_objects=structuredClone(direct.objects);assert.equal(validateModelMaterialEdits(direct,[{...bindingEdit(),values:{texture_bpp:4,clut_column:7}}])[0].values.clut_column,7);assert.throws(()=>validateModelMaterialEdits(direct,[{...bindingEdit(),values:{clut_column:7}}]));const reserved=snapshot();reserved.objects[0].groups[0].primitives[0]=primitive(0,48,0xa1e1);reserved.retail_objects=structuredClone(reserved.objects);assert.throws(()=>validateModelMaterialEdits(reserved,[bindingEdit()]));assert.equal(validateModelMaterialEdits(reserved,[{...bindingEdit(),values:{texture_bpp:8}}])[0].values.texture_bpp,8);
const reviewed=decodeModelMaterialReview(report([bindingEdit(),groupEdit()]),source,context,[bindingEdit(),groupEdit()]);assert.deepEqual(reviewed.changes_from_current[1].primitive_indices,[0,1]);reviewed.changes_from_current[1].primitive_indices.pop();assert.deepEqual(report([bindingEdit(),groupEdit()]).changes_from_current[1].primitive_indices,[0,1]);assert.equal(decodeModelMaterialReview(report([noopEdit]),source,context,[noopEdit]).changes_from_current.length,0);
for(const mutate of [v=>v.review_key='bad',v=>v.changes_from_current[0].byte_offset++,v=>v.changes_from_current[0].after_value^=0x20,v=>v.proposed_sha256=h('a'),v=>v.changes_from_current.push({...existing}),v=>v.preview.vertices[0][0]=3,v=>v.preview.triangle_materials[0]=99,v=>v.gameplay_verified=true]){const value=report();mutate(value);assert.throws(()=>decodeModelMaterialReview(value,source,context,[bindingEdit()]));}const wrongMembers=report([groupEdit()]);wrongMembers.changes_from_current[0].primitive_indices=[0];assert.throws(()=>decodeModelMaterialReview(wrongMembers,source,context,[groupEdit()]));

const grown=snapshot();grown.schema_version='legaia.model-material-source.v3';
grown.objects[0].groups[0].primitives=[primitive(0,48),primitive(1,72,0xa069),primitive(2,96)];
grown.objects[0].groups[1].byte_offset=124;grown.objects[0].groups[1].primitives=[{...untextured(),primitive_index:3,byte_offset:132}];
grown.face_mappings=[[{retail_index:0,current_index:0},{retail_index:1,current_index:2},{retail_index:2,current_index:3}]];grown.group_mappings=[[0,1]];
grown.authored_faces=[[{face_id:'face://authored/00000000-0000-4000-8000-000000000001',current_index:1}]];
assert.equal(decodeModelMaterialSource(grown,assetId,context).objects[0].groups[0].primitives.length,3);
for(const mutate of [v=>v.authored_faces[0][0].current_index=2,v=>v.authored_faces[0][0].face_id='face://retail/0',v=>v.authored_faces[0]=[],v=>v.authored_faces[0].push({...v.authored_faces[0][0]}),v=>v.face_mappings[0][1].current_index=1,v=>v.group_mappings[0]=[1,0],v=>v.objects[0].groups[0].primitives[2].tpage^=0x20]){const bad=structuredClone(grown);mutate(bad);assert.throws(()=>decodeModelMaterialSource(bad,assetId,context));}
const grownReport=edits=>{const value=report(edits,grown);value.schema_version='legaia.model-material-review.v2';value.comparison='current_addition_topology';value.coordinate_changes=structuredClone(value.changes_from_current);return value;};
const addedEdits=[bindingEdit(1,3),groupEdit()];decodeModelMaterialReview(grownReport(addedEdits),grown,context,addedEdits);
assert.deepEqual(grownReport(addedEdits).changes_from_current[1].primitive_indices,[0,1,2]);
for(const mutate of [v=>v.comparison='retail_source',v=>v.schema_version='legaia.model-material-review.v1',v=>v.coordinate_changes=[existing],v=>v.changes_from_current[1].primitive_indices.pop()]){const bad=grownReport(addedEdits);mutate(bad);assert.throws(()=>decodeModelMaterialReview(bad,grown,context,addedEdits));}
const addedNoop={kind:'group',object_index:0,group_index:0,values:{semi_transparent:false}};assert.equal(decodeModelMaterialReview(grownReport([addedNoop]),grown,context,[addedNoop]).coordinate_changes.length,0);

class Node {constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.attributes={};this.value='';this.textContent='';this.disabled=false;this.hidden=false;this.open=false;this.checked=false;}append(...nodes){for(const node of nodes){this.children.push(node);node.parent=this;}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this.attributes[k]={value:String(v),toString:()=> '[object Attr]'};}showModal(){this.open=true;}close(){this.open=false;this.onclose?.();}remove(){this.removed=true;if(this.parent)this.parent.children=this.parent.children.filter(node=>node!==this);}}
const tree=node=>[node,...node.children.flatMap(tree)],action=(control,name)=>tree(control.dialog).find(node=>node.dataset.action===name),input=(control,name)=>tree(control.dialog).find(node=>node.attributes['aria-label']?.value===name),hasText=(control,fragment)=>tree(control.dialog).some(node=>node.textContent.includes(fragment)),deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const saved={document:globalThis.document,fetch:globalThis.fetch};globalThis.document={body:new Node('body'),createElement:tag=>new Node(tag)};
try{
  let ctx=structuredClone(context),isBusy=false,control=null,calls=[],queue=[],errors=[],applied=[];
  globalThis.fetch=async(path,options)=>{calls.push({path,body:JSON.parse(options.body),signal:options.signal});const next=queue.shift(),value=next instanceof Promise?await next:next;assert.ok(value,'Queue a source response');return {ok:!value.error,text:async()=>JSON.stringify(value)};};
  const settings={assetId,getContext:()=>ctx,busy:()=>isBusy,setBusy:value=>{isBusy=value;control?.updateState();},onApplied:value=>applied.push(value),onError:value=>errors.push(value)};
  const open=async(extra={},source=snapshot())=>{control=null;queue=[source];control=await openModelMaterialsEditor({...settings,...extra});assert.equal(await control.ready,true);return control;},change=(label,value)=>{const node=input(control,label);node.value=String(value);return node.oninput();},review=async(edits=[bindingEdit()])=>{queue=[report(edits)];assert.equal(await action(control,'review').onclick(),true);};
  await open({initial:{object_index:0,group_index:0,primitive_index:1}},grown);
  assert.equal(hasText(control,'Retail face none (authored)'),true);assert.equal(action(control,'retail').disabled,true);assert.equal(action(control,'retail').onclick(),false);assert.equal(input(control,'Texture page column').value,'9');
  assert.equal(change('Texture page column',3),true);queue=[grownReport([bindingEdit(1,3)])];assert.equal(await action(control,'review').onclick(),true);assert.equal(action(control,'apply').disabled,false);assert.equal(hasText(control,'Current (retained addition topology)'),true);assert.equal(hasText(control,'Current topology \u2192 Proposed'),true);
  assert.equal(action(control,'discard').onclick(),true);assert.equal(input(control,'Texture page column').value,'9');assert.equal(action(control,'apply').disabled,true);
  input(control,'Source primitive').value='2';assert.equal(input(control,'Source primitive').onchange(),true);assert.equal(action(control,'retail').disabled,false);assert.equal(hasText(control,'Retail face 1'),true);assert.equal(action(control,'retail').onclick(),true);control.dispose();
  await open();
  const donorId='asset://global/models/0002',catalog={schema_version:'legaia.model-material-donor-models.v1',scene_id:context.sceneId,project_source_key:context.sourceKey,models:[{asset_id:donorId,label:'Source donor'}],project_changed:false};
  queue=[catalog];assert.equal(await action(control,'donor-browse').onclick(),true);assert.deepEqual(calls.at(-1).body,{source_key:context.sourceKey});
  const donor=snapshot();donor.asset_id=donorId;donor.objects[0].groups[0].primitives[0]=primitive(0,48,0xa069);donor.retail_objects=structuredClone(donor.objects);
  queue=[donor];assert.equal(await action(control,'donor-load').onclick(),true);assert.equal(input(control,'Texture page column').value,'1','Loading donor does not alter draft');input(control,'Packet group semitransparency').checked=true;input(control,'Packet group semitransparency').onchange();assert.equal(action(control,'donor-copy').onclick(),true);assert.equal(input(control,'Texture page column').value,'9');assert.equal(input(control,'Packet group semitransparency').checked,true,'Copy preserves target group draft');assert.equal(action(control,'apply').disabled,true);await review([groupEdit(),bindingEdit(0,9)]);assert.equal(action(control,'apply').disabled,false);assert.equal(action(control,'donor-copy').onclick(),true);assert.equal(action(control,'apply').disabled,true,'A copied binding withdraws a prior review');
  const directDonor=structuredClone(donor);directDonor.objects[0].groups[0].primitives[0]=primitive(0,48,0xa169);directDonor.retail_objects=structuredClone(directDonor.objects);queue=[directDonor];assert.equal(await action(control,'donor-load').onclick(),true);const retainedClut=input(control,'CLUT column').value;assert.equal(action(control,'donor-copy').onclick(),true);assert.equal(input(control,'Texture depth').value,'16');assert.equal(input(control,'CLUT column').value,retainedClut);assert.equal(input(control,'CLUT column').disabled,true);
  const delayed=deferred();queue=[delayed.promise];const late=action(control,'donor-load').onclick();control.dispose();delayed.resolve(donor);assert.equal(await late,false);assert.equal(isBusy,false);assert.equal(applied.length,0);ctx=structuredClone(context);
  await open();queue=[catalog];await action(control,'donor-browse').onclick();queue=[donor];await action(control,'donor-load').onclick();input(control,'Packet group').value='1';input(control,'Packet group').onchange();input(control,'Packet group semitransparency').checked=true;input(control,'Packet group semitransparency').onchange();assert.equal(action(control,'donor-group-copy').disabled,true,'Untextured target group cannot copy bindings');input(control,'Packet group').value='0';input(control,'Packet group').onchange();input(control,'Packet group semitransparency').checked=true;input(control,'Packet group semitransparency').onchange();const copyCalls=calls.length;assert.equal(action(control,'donor-group-copy').onclick(),true);assert.equal(calls.length,copyCalls,'Group copy creates no request');assert.equal(input(control,'Texture page column').value,'9');assert.equal(input(control,'Packet group semitransparency').checked,true);assert.equal(action(control,'apply').disabled,true);await review([groupEdit(),groupEdit(1),bindingEdit(0,9),bindingEdit(1,9)]);assert.equal(action(control,'apply').disabled,false);control.dispose();
  const oversized=snapshot();oversized.objects=[{object_index:0,groups:[{...objects()[0].groups[0],primitives:Array.from({length:257},(_,index)=>primitive(index,48+index*24))}]}];oversized.retail_objects=structuredClone(oversized.objects);await open({},oversized);queue=[catalog];await action(control,'donor-browse').onclick();queue=[donor];await action(control,'donor-load').onclick();assert.equal(action(control,'donor-group-copy').onclick(),false);assert.equal(input(control,'Texture page column').value,'1');assert.equal(hasText(control,'0 pending source entries'),true);assert.equal(action(control,'apply').disabled,true);assert.equal(hasText(control,'256-entry draft budget'),true);control.dispose();
  await open();assert.equal(control.dialog.style.width,'min(540px,94vw)');assert.deepEqual(calls.at(-1).body,{asset_id:assetId});for(const label of ['Texture page column','Texture page row','Texture depth','CLUT column','CLUT row'])assert.equal(tree(control.dialog).some(node=>node.tagName==='th'&&node.textContent===label),true,'Semantic table labels must be strings even when DOM attributes are Attr objects.');assert.equal(hasText(control,'[object Attr]'),false);assert.equal(action(control,'apply').disabled,true);assert.equal(action(control,'model').hidden,true);assert.equal(hasText(control,'all 2 primitives'),true);assert.equal(hasText(control,'caller blend state overrides'),true);assert.equal(change('Texture page column',2),true);await review();assert.deepEqual(calls.at(-1).body,{asset_id:assetId,expected_sha256:h('a'),source_key:h('f'),edits:[bindingEdit()]});assert.equal(action(control,'apply').disabled,false);assert.equal(hasText(control,'Current → Proposed'),true);assert.equal(hasText(control,'unresolved or unavailable'),true);input(control,'Texture page column').value='3';assert.equal(await action(control,'apply').onclick(),false,'Silent input replacement cannot use a prior review.');assert.equal(calls.some(row=>row.path==='/api/model-material-apply'),false);assert.equal(action(control,'discard').onclick(),true);assert.equal(input(control,'Texture page column').value,'1');queue=[report([noopEdit])];assert.equal(await action(control,'review').onclick(),true);assert.equal(action(control,'apply').disabled,true);control.dispose();
  await open();change('Texture page column',2);const semi=input(control,'Packet group semitransparency');semi.checked=true;assert.equal(semi.onchange(),true);input(control,'Source primitive').value='1';assert.equal(input(control,'Source primitive').onchange(),true);assert.equal(input(control,'Texture page column').value,'1');change('Texture page column',3);input(control,'Source primitive').value='0';assert.equal(input(control,'Source primitive').onchange(),true);assert.equal(input(control,'Texture page column').value,'2');assert.equal(input(control,'Packet group semitransparency').checked,true);const batched=[groupEdit(),bindingEdit(),bindingEdit(1,3)];await review(batched);assert.deepEqual(calls.at(-1).body.edits,batched);assert.equal(hasText(control,'3 pending source entries'),true);assert.equal(action(control,'discard').onclick(),true);assert.equal(hasText(control,'1 pending source entries'),true);assert.equal(action(control,'discard-all').onclick(),true);assert.equal(hasText(control,'0 pending source entries'),true);input(control,'Packet group').value='1';assert.equal(input(control,'Packet group').onchange(),true);assert.equal(hasText(control,'untextured'),true);assert.equal(input(control,'Texture page column'),undefined);input(control,'Packet group semitransparency').checked=true;assert.equal(input(control,'Packet group semitransparency').onchange(),true);await review([groupEdit(1)]);assert.deepEqual(calls.at(-1).body.edits,[groupEdit(1)]);control.dispose();
  await open({},direct);assert.equal(input(control,'CLUT column').disabled,true);input(control,'Texture depth').value='4';assert.equal(input(control,'Texture depth').onchange(),true);assert.equal(input(control,'CLUT column').disabled,false);assert.equal(change('CLUT column',9),true);input(control,'Texture depth').value='16';assert.equal(input(control,'Texture depth').onchange(),true);assert.equal(input(control,'CLUT column').disabled,true);assert.equal(change('Texture page column','1.5'),false);assert.equal(action(control,'review').disabled,true);input(control,'Packet group').value='1';assert.equal(input(control,'Packet group').onchange(),false);assert.equal(action(control,'discard').onclick(),true);assert.equal(action(control,'review').disabled,false);control.dispose();
  await open({},authored);assert.equal(action(control,'retail').onclick(),true);assert.equal(input(control,'Texture page column').value,'1');assert.equal(input(control,'Packet group semitransparency').checked,false);assert.equal(hasText(control,'2 pending source entries'),true);control.dispose();

  await open({initial:{object_index:0,group_index:0,primitive_index:1}});assert.equal(input(control,'Source primitive').value,'1');control.dispose();await open({initial:{object_index:0,group_index:1}});assert.equal(input(control,'Packet group').value,'1');assert.equal(input(control,'Source primitive').value,'2');control.dispose();queue=[snapshot()];control=await openModelMaterialsEditor({...settings,initial:{object_index:0,group_index:1,primitive_index:0}});assert.equal(await control.ready,false);assert.equal(action(control,'apply').disabled,true);control.dispose();
  let options,previewRequests=[];await open({onPreview:async(value,opts)=>{options=opts;previewRequests.push(value);assert.equal(control.dialog.open,true);assert.equal(Object.isFrozen(value.preview.materials),true);assert.equal(opts.isCurrent(),true);return {};}});change('Texture page column',2);await review();assert.equal(await action(control,'model').onclick(),true);assert.equal(control.dialog.open,false);assert.equal(control.dialog.dataset.materialInspection,'model');assert.equal(options.returnToEditor(),true);assert.equal(control.dialog.dataset.materialInspection,'false');assert.equal(input(control,'Texture page column').value,'2');assert.equal(action(control,'apply').disabled,false);change('Texture page column',3);assert.equal(options.returnToEditor(),false);assert.equal(control.dialog.removed,true);
  let sceneRequest;await open({canPreviewScene:()=>true,onScenePreview:async(request,value,opts)=>{options=opts;sceneRequest=request;assert.equal(Object.isFrozen(request.edits[0].values),true);assert.equal(Object.isFrozen(value.changes_from_current),true);return {};}});change('Texture page column',2);await review();assert.equal(await action(control,'scene').onclick(),true);assert.equal(control.dialog.dataset.sceneInspection,'true');assert.deepEqual(sceneRequest,{asset_id:assetId,expected_sha256:h('a'),source_key:h('f'),edits:[bindingEdit()],review_key:h('d')});assert.equal(options.returnToEditor(),true);assert.equal(control.dialog.dataset.sceneInspection,'false');control.dispose();
  const sceneLate=deferred();await open({canPreviewScene:()=>true,onScenePreview:async(_request,_value,opts)=>{options=opts;return sceneLate.promise;}});change('Texture page column',2);await review();const handoff=action(control,'scene').onclick();control.dispose();assert.equal(options.signal.aborted,true);assert.equal(options.isCurrent(),false);sceneLate.resolve({});assert.equal(await handoff,false);assert.equal(isBusy,false);

  await open();change('Texture page column',2);const stale=deferred();queue=[stale.promise];const reading=action(control,'review').onclick(),signal=calls.at(-1).signal;ctx={...ctx,sourceKey:h('e')};control.updateState();assert.equal(signal.aborted,true);assert.equal(isBusy,false);isBusy=true;stale.resolve(report());assert.equal(await reading,false);assert.equal(isBusy,true,'Late requests cannot release newer busy ownership.');isBusy=false;ctx=structuredClone(context);control.updateState();assert.equal(action(control,'review').disabled,true);control.dispose();
  for(const mutate of [value=>value.project.path='C:/other',value=>value.scene.id='scene://other',value=>value.model_material_report.review_key=h('e')]){await open();change('Texture page column',2);await review();const value=state(report());mutate(value);queue=[value];assert.equal(await action(control,'apply').onclick(),false);assert.equal(action(control,'apply').disabled,true);assert.equal(applied.length,0);control.dispose();}
  await open({onApplied:value=>{applied.push(value);ctx={...ctx,sourceKey:h('e')};control.updateState();}});change('Texture page column',2);await review();const applyingLate=deferred();queue=[applyingLate.promise];const applying=action(control,'apply').onclick();assert.equal(action(control,'close').disabled,true);assert.equal(action(control,'close').onclick(),false);let prevented=false;control.dialog.oncancel({preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(await action(control,'apply').onclick(),false);assert.deepEqual(calls.at(-1).body,{asset_id:assetId,expected_sha256:h('a'),source_key:h('f'),edits:[bindingEdit()],review_key:h('d')});applyingLate.resolve(state(report()));assert.equal(await applying,true);assert.equal(applied.length,1);assert.equal(control.dialog.removed,true);assert.equal(isBusy,false);ctx=structuredClone(context);
  await open();change('Texture page column',2);const closedLate=deferred();queue=[closedLate.promise];const waiting=action(control,'review').onclick(),closedSignal=calls.at(-1).signal,errorCount=errors.length;control.dialog.close();closedLate.resolve({error:'Late closed error'});assert.equal(await waiting,false);assert.equal(closedSignal.aborted,true);assert.equal(errors.length,errorCount);assert.equal(isBusy,false);
}finally{for(const [key,value] of Object.entries(saved)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
console.log('Model material source/mask/domain and shared group qualification; batched drafts, Review/no-op/reset, immutable model/scene Return, exact Apply state and stale/abort/busy lifecycle passed.');

const dropped=snapshot();dropped.schema_version='legaia.model-material-source.v2';
dropped.objects[0].groups=[{...structuredClone(dropped.retail_objects[0].groups[1]),group_index:0,byte_offset:40,primitives:[{...untextured(),primitive_index:0,byte_offset:48}]}];
dropped.face_mappings=[[{retail_index:0,current_index:null},{retail_index:1,current_index:null},{retail_index:2,current_index:0}]];dropped.group_mappings=[[1]];
assert.equal(decodeModelMaterialSource(dropped,assetId,context).group_mappings[0][0],1);
for(const mutate of [v=>v.group_mappings=[[0]],v=>v.face_mappings[0][2].current_index=1,v=>v.objects[0].groups[0].flags=0x19]){const bad=structuredClone(dropped);mutate(bad);assert.throws(()=>decodeModelMaterialSource(bad,assetId,context));}
const compactReview=report([groupEdit()],dropped);compactReview.coordinate_changes=[{kind:'primitive_removal',object_index:0,primitive_index:0},{kind:'primitive_removal',object_index:0,primitive_index:1},{...compactReview.changes_from_current[0],group_index:1,byte_offset:107,primitive_indices:[2]}];
decodeModelMaterialReview(compactReview,dropped,context,[groupEdit()]);compactReview.coordinate_changes[0].primitive_index=2;assert.throws(()=>decodeModelMaterialReview(compactReview,dropped,context,[groupEdit()]));
console.log('Retained material group/face mapping and actual Retail removal audit guards passed.');
