import assert from 'node:assert/strict';
import {decodeControllerFiveWordSnapshot,decodeControllerFiveWordReview,mountControllerFiveWords} from '../editor/controller-five-words.js';
const owner='scene://fixture/controllers/man-p1/0000',id='script://fixture/controllers/man-p1/0000/five-word/0005',context={projectPath:'C:/private',sceneId:'scene://fixture',mode:'edit',scriptKey:'a'.repeat(64)};
const values=value=>({signed_words:[-32768,32767,0,-1,value]});
const report=value=>({status:'decoded_supported_paths',instructions:[{pc:5,length:12,byte_offset:105,mnemonic:'FIVE_WORD_HELPER_REQUEST',raw_hex:'43110080ff7f0000ffff'+(value&65535).toString(16).padStart(4,'0').match(/../g).reverse().join(''),target_context:null,operands:{sub_op:0x11,...values(value),helper:'0x801F8D4C',runtime_binding:'helper_owned_state_unresolved',parameter_semantics:'runtime_word_meanings_unresolved',runtime_effect:'not_evaluated'},successors:[{pc:17,condition:'encoded_continuation'}]},{pc:17,length:3,byte_offset:117,mnemonic:'JMP_REL',raw_hex:'26f3ff',target_context:null,operands:{},successors:[{pc:5,condition:'unconditional'}]}],dialogues:[],stops:[],opaque_regions:[],unvisited_instructions:[],unvisited_dialogues:[]});
const snapshot=()=>({schema_version:'legaia.controller-five-words.v1',owner_id:owner,state_key:context.scriptKey,source_record_sha256:'b'.repeat(64),current_record_sha256:'b'.repeat(64),source:{owner_id:owner,record_kind:'man_partition_1_scene_controller',runtime_execution:'not_asserted'},source_report:report(5),current_report:report(5),targets:[{semantic_id:id,owner_id:owner,pc:5,mnemonic:'FIVE_WORD_HELPER_REQUEST',sub_op:0x11,target_context:null,decoded_byte_offset:107,source_record_sha256:'b'.repeat(64),values:values(5),current_values:values(5),authored_values:null}],supported:true,reason:null,limitations:[],gameplay_verified:false});
const proposal=()=>({...snapshot(),operand_id:id,value:values(6),proposed_record_sha256:'c'.repeat(64),review_key:'d'.repeat(64),proposed_report:report(6),changed_decoded_byte_offsets:[115],no_op:false,native_bytes_changed:true,project_changed:false});
assert.equal(decodeControllerFiveWordSnapshot(snapshot(),owner,context).targets.length,1);assert.equal(decodeControllerFiveWordReview(proposal(),snapshot(),id,values(6)).operand_id,id);
for(const change of [r=>r.owner_id='scene://foreign/controllers/man-p1/0000',r=>r.targets[0].owner_id='scene://foreign/controllers/man-p1/0000',r=>r.targets[0].values.signed_words[0]=32768,r=>r.schema_version='actor',r=>r.state_key='f'.repeat(64),r=>r.gameplay_verified=true,r=>r.source.runtime_execution='observed',r=>r.targets.push(r.targets[0]),r=>r.targets[0].decoded_byte_offset++,r=>r.targets[0].current_values.signed_words[2]=7,r=>r.current_report.instructions[0].raw_hex='4ce60080ff7f0500ff',r=>r.targets=[],r=>r.current_report.instructions[0].raw_hex='4c910080ff7f0500',r=>r.targets[0].values.signed_words[0]=-32769,r=>r.current_report.instructions[0].operands.runtime_binding=42,r=>r.source_report.instructions[0].operands.parameter_semantics='none',r=>r.current_report.instructions[0].operands.helper='0x801F8D50']){const r=snapshot();change(r);assert.throws(()=>decodeControllerFiveWordSnapshot(r,owner,context));}
for(const change of [r=>r.project_changed=true,r=>r.value.signed_words[2]=8,r=>r.changed_decoded_byte_offsets=[105],r=>r.changed_decoded_byte_offsets=[115,115],r=>r.proposed_report.instructions[1].raw_hex='26ffff',r=>r.proposed_report.instructions[0].successors[0].pc=12,r=>r.proposed_record_sha256=r.current_record_sha256,r=>r.proposed_report.instructions[0].operands.signed_words[2]=7]){const r=proposal();change(r);assert.throws(()=>decodeControllerFiveWordReview(r,snapshot(),id,values(6)));}
const retained=snapshot();retained.current_report.unvisited_instructions=[retained.current_report.instructions.shift()];assert.equal(decodeControllerFiveWordSnapshot(retained,owner,context).targets.length,1);
const extended=snapshot();extended.targets[0].target_context=7;extended.targets[0].decoded_byte_offset=108;
for(const report of [extended.source_report,extended.current_report]){const n=report.instructions[0];n.target_context=7;n.length=13;n.raw_hex='c307'+n.raw_hex.slice(2);n.successors[0].pc=18;const jump=report.instructions[1];jump.pc=18;jump.byte_offset=118;jump.raw_hex='26f2ff';}
assert.equal(decodeControllerFiveWordSnapshot(extended,owner,context).targets[0].values.signed_words[0],-32768);
class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.value='';}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(name,value){this[name]=value;}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}}
globalThis.document={createElement:tag=>new Node(tag)};let queue=[],ctx=structuredClone(context),busy=false,commands=[],reopened=[];
globalThis.fetch=async()=>({ok:true,json:async()=>await queue.shift()});
const tree=n=>[n,...n.children.flatMap(tree)],button=(h,id)=>tree(h).find(n=>n.dataset.controllerFiveWordAction===id),input=h=>tree(h).filter(n=>n.tag==='input').at(-1);
const settings={owner,getContext:()=>ctx,busy:()=>busy,setBusy:v=>busy=v,api:async(route,body)=>{assert.equal(busy,false);commands.push(body);return true;},reopen:pc=>reopened.push(pc)};
async function mount(extra={},initial=snapshot()){ctx=structuredClone(context);const host=new Node();queue=[initial];const controls=mountControllerFiveWords(host,{...settings,...extra});assert(await controls.ready);return {host,controls};}
let {host,controls}=await mount();assert.equal(tree(host).filter(n=>n.tag==='input').length,5);assert(tree(host).some(n=>n.textContent==='Retail: -32768, 32767, 0, -1, 5 \u00b7 Current: -32768, 32767, 0, -1, 5 \u00b7 Authored: None'));assert(tree(host).some(n=>n.textContent==='Controller Five-Word Requests'));input(host).value='6';input(host).oninput();queue=[proposal()];assert(await button(host,'review').onclick());assert.equal(commands.length,0);assert.equal(tree(host).find(n=>'controllerOperandProposed' in n.dataset).hidden,false);assert(!button(host,'apply').disabled);input(host).value='32768';input(host).oninput();assert(button(host,'apply').disabled);assert(button(host,'review').disabled);assert.equal(tree(host).find(n=>'controllerOperandProposed' in n.dataset).hidden,true);
button(host,'discard').onclick();input(host).value='6';input(host).oninput();queue=[proposal()];await button(host,'review').onclick();assert(await button(host,'apply').onclick());assert.equal(commands[0].type,'set_controller_five_word');assert.deepEqual(commands[0].value,values(6));assert.deepEqual(reopened,[5]);controls.dispose();
({host,controls}=await mount({api:async()=>false}));input(host).value='6';input(host).oninput();queue=[proposal()];await button(host,'review').onclick();assert.equal(await button(host,'apply').onclick(),false);assert(button(host,'apply').disabled);controls.dispose();
({host,controls}=await mount());input(host).value='6';input(host).oninput();let resolve;queue=[new Promise(r=>resolve=r)];const late=button(host,'review').onclick();ctx.scriptKey='f'.repeat(64);controls.updateState();resolve(proposal());assert.equal(await late,false);assert(button(host,'apply').disabled);assert.equal(busy,false);controls.dispose();
const authored=snapshot();authored.current_record_sha256='c'.repeat(64);authored.current_report=report(6);authored.targets[0].current_values=values(6);authored.targets[0].authored_values=values(6);
({host,controls}=await mount({},authored));queue=[{...proposal(),value:null,current_record_sha256:authored.current_record_sha256,current_report:authored.current_report,proposed_record_sha256:'b'.repeat(64),proposed_report:report(5)}];
assert(await button(host,'reset').onclick());assert.equal(input(host).value,'5');assert(!button(host,'apply').disabled);assert(await button(host,'apply').onclick());assert.equal(commands.at(-1).value,null);controls.dispose();
console.log('Controller five-word source/Review qualification, retained boundaries, bounded drafts, typed Apply, failed Apply withdrawal and stale-response rejection passed.');
