import assert from 'node:assert/strict';
import {controllerResetEntries,decodeControllerComponentReset,mountControllerComponentReset} from '../editor/controller-component-reset.js';
import {CONTROLLER_SNAPSHOT_SCHEMAS} from '../editor/controller-workspace-snapshot.js';
const owner='scene://fixture/controllers/man-p1/0000',entry=owner.replace('scene://','script://')+'/operand/0005',hash='a'.repeat(64),other='b'.repeat(64);
for(const [component,schema_version] of Object.entries(CONTROLLER_SNAPSHOT_SCHEMAS)){
 const snapshot={schema_version,owner_id:owner,state_key:hash,source_record_sha256:hash,current_record_sha256:other,source_report:{source:true},current_report:{current:true},targets:[{semantic_id:entry,[component==='ControllerBranches'?'authored_value':'authored_values']:{value:7}},{semantic_id:'unmodified',authored_values:null}]};
 const proof={schema_version:'legaia.controller-component-reset.v1',owner_id:owner,component,state_key:hash,source_record_sha256:hash,current_record_sha256:other,proposed_record_sha256:hash,review_key:other,project_changed:false,gameplay_verified:false,authored:{source_record_sha256:hash,entries:{[entry]:{value:7}}},proposed:{},removed_operand_ids:[entry],removed_operand_count:1,changed_decoded_byte_offsets:[62,63],native_bytes_changed:true,source_report:{source:true},current_report:{current:true}};
 assert.deepEqual(controllerResetEntries(snapshot),proof.authored.entries);
 const result=decodeControllerComponentReset(proof,snapshot,component);result.authored.entries[entry].value=9;assert.equal(proof.authored.entries[entry].value,7);
 for(const change of [{state_key:other},{owner_id:'foreign'},{component:'Transform'},{removed_operand_count:2},{removed_operand_ids:[]},{proposed:{[component]:{}}},{authored:{...proof.authored,entries:{}}},{current_report:{}},{source_report:{}},{changed_decoded_byte_offsets:[63,62]},{native_bytes_changed:false},{gameplay_verified:true},{review_key:null}])assert.throws(()=>decodeControllerComponentReset({...proof,...change},snapshot,component));
 assert.throws(()=>decodeControllerComponentReset(proof,{...snapshot,targets:[]},component));
 const noBytes={...proof,current_record_sha256:hash,changed_decoded_byte_offsets:[],native_bytes_changed:false};assert.equal(decodeControllerComponentReset(noBytes,{...snapshot,current_record_sha256:hash},component).native_bytes_changed,false);
}
console.log('All thirteen component reset Reviews preserve source binding, authored entries, detached evidence and explicit byte changes.');
class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.value='';}append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n);if(this.tag==='select'&&!this.value)this.value=n.value;}}prepend(n){n.parent=this;this.children.unshift(n);}setAttribute(name,value){this[name]=value;}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}}
globalThis.document={createElement:tag=>new Node(tag)};
const component='ControllerPartySelectors',snapshot={schema_version:CONTROLLER_SNAPSHOT_SCHEMAS[component],owner_id:owner,state_key:hash,source_record_sha256:hash,current_record_sha256:other,source_report:{},current_report:{},targets:[{semantic_id:entry,authored_values:{value:7}}]};
const proof={schema_version:'legaia.controller-component-reset.v1',owner_id:owner,component,state_key:hash,source_record_sha256:hash,current_record_sha256:other,proposed_record_sha256:hash,review_key:other,project_changed:false,gameplay_verified:false,authored:{source_record_sha256:hash,entries:{[entry]:{value:7}}},proposed:{},removed_operand_ids:[entry],removed_operand_count:1,changed_decoded_byte_offsets:[62],native_bytes_changed:true,source_report:{},current_report:{}};
let key=hash,busy=false,reply=proof,commands=[],opened=0;
globalThis.fetch=async()=>({ok:true,json:async()=>await reply});
const tree=n=>[n,...n.children.flatMap(tree)],button=(host,text)=>tree(host).find(n=>n.tag==='button'&&n.textContent===text);
function mount(api=async(route,command)=>{assert.equal(busy,false);commands.push(command);return true;}){key=hash;const host=new Node('host'),control=mountControllerComponentReset(host,{families:{[component]:snapshot},owner,getKey:()=>key,current:()=>true,busy:()=>busy,setBusy:v=>busy=v,api,reopen:()=>opened++});return {host,control};}
let {host,control}=mount();await button(host,'Review component reset').onclick();assert.equal(commands.length,0);assert.equal(busy,false);assert(!button(host,'Reset reviewed controller component').disabled);button(host,'Discard component reset').onclick();assert(button(host,'Reset reviewed controller component').disabled);await button(host,'Review component reset').onclick();await button(host,'Reset reviewed controller component').onclick();assert.equal(commands[0].type,'reset_controller_component');assert.equal(opened,1);control.dispose();
({host,control}=mount(async()=>false));await button(host,'Review component reset').onclick();await button(host,'Reset reviewed controller component').onclick();assert(button(host,'Reset reviewed controller component').disabled);control.dispose();
({host,control}=mount());let resolve;reply=new Promise(r=>resolve=r);const late=button(host,'Review component reset').onclick();key=other;control.updateState();resolve(proof);await late;assert(button(host,'Reset reviewed controller component').disabled);assert.equal(busy,false);control.dispose();
({host,control}=mount());reply=new Promise(r=>resolve=r);const disposed=button(host,'Review component reset').onclick();control.dispose();resolve(proof);await disposed;assert.equal(host.children.length,0);assert.equal(busy,false);
console.log('Review is read-only; Apply uses shared mutation locking; discard, failed Apply, stale replies and disposed controls withdraw proofs.');
