import fs from 'node:fs';
import assert from 'node:assert/strict';
import {decodeNativeSample,decodeNativeLoop} from '../editor/audio-native-loop.js';
import {mountEnvelopeAudition} from '../editor/audio-envelope-audition.js';
if(process.argv.length<4)throw Error('Provide freshly qualified allocated sample cases and widget fixtures.');
const cases=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),f=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));let refusals=0;
for(const c of cases.cases){
 const o=c.options,sample=cases.bank.samples[c.sample_index],selection=c.layer==='retail'?{row:sample,position:o.current_sample_entry_byte_offset-o.current_sample.offset+sample.offset,entryHash:cases.bank.source_record.entry_sha256,entryBytes:cases.bank.source_record.entry_size_bytes}:{row:o.current_sample,position:o.current_sample_entry_byte_offset,entryHash:o.current_entry_sha256,entryBytes:o.current_entry_size_bytes};
 const pcm=Uint8Array.from(Buffer.from(c.pcm.pcm_base64,'base64')),raw=await decodeNativeSample(c.adpcm,cases.context,cases.bank,sample,c.layer,c.pcm.sample_sha256,o.current_entry_sha256,c.pcm.waveform,pcm,c.mode,selection);
 if(c.mode==='loop')assert.deepEqual(decodeNativeLoop(raw,1000).bytes,Uint8Array.from(Buffer.from(c.oracle_pcm_base64,'base64')));
 for(const [field,value] of [['sample_entry_byte_offset',0],['entry_size_bytes',1],['entry_sha256','0'.repeat(64)],['adpcm_base64','AA==']]){await assert.rejects(()=>decodeNativeSample({...c.adpcm,[field]:value},cases.context,cases.bank,sample,c.layer,c.pcm.sample_sha256,o.current_entry_sha256,c.pcm.waveform,pcm,c.mode,selection));refusals++;}
}
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.value='';this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(key,value){this.attrs[key]=value;}}
globalThis.document={createElement:tag=>new Element(tag)};const nodes=root=>[root,...root.children.flatMap(nodes)],button=(host,title)=>nodes(host).find(n=>n.tag==='button'&&n.textContent===title),control=(host,title)=>nodes(host).find(n=>n.attrs['aria-label']===title);
let fresh=true,held=null,started=0,stopped=0,closed=0;const errors=[],calls=[];
const request=async(path,init)=>{const body=JSON.parse(init.body);calls.push({path,body});if(held)return new Promise(resolve=>held.resolve=resolve);const value=path==='/api/audio-allocation-authoring'?f.options:path==='/api/audio-sample-adpcm'?f.adpcm[body.layer]:f.pcm[body.layer];return {ok:true,text:async()=>JSON.stringify(value)};};
const audioContext=()=>({destination:{},resume:async()=>{},close:async()=>closed++,createGain:()=>({gain:{value:0},connect(){},disconnect(){}}),createBuffer:(_channels,length)=>({getChannelData:()=>new Float32Array(length)}),createBufferSource:()=>({connect(){},disconnect(){},start(){started++;},stop(){stopped++;}})});
const host=new Element('section'),view=mountEnvelopeAudition(host,{bank:f.bank,fresh:()=>fresh,request,audioContext,onError:e=>errors.push(e.message)});view.update(f.config);const layer=control(host,'Envelope audition layer'),rate=control(host,'Envelope sample rate'),playback=control(host,'Envelope sample playback'),load=button(host,'Load envelope sample'),play=button(host,'Play envelope audition');layer.value='Current';layer.onchange();await load.onclick();assert(play.disabled);rate.value='44100';rate.onchange();assert(!play.disabled);await play.onclick();assert.equal(started,1);playback.value='native-one-pass';playback.onchange();await load.onclick();await play.onclick();assert.equal(started,2);assert.equal(errors.length,0);assert(calls.some(c=>c.path==='/api/audio-allocation-authoring'));assert(calls.some(c=>c.path==='/api/audio-allocation-preview'));assert(calls.some(c=>c.path==='/api/audio-sample-adpcm'));assert(!calls.some(c=>c.path==='/api/audio-sample-authoring'));
view.clear();assert(closed);assert(stopped);view.update(f.config);held={};const pending=load.onclick();view.clear();held.resolve({ok:true,text:async()=>JSON.stringify(f.options)});await pending;assert(play.disabled);fresh=false;view.refresh();assert(play.disabled);
console.log(JSON.stringify({allocated_native_layer_cases:cases.cases.length,forged_layout_raw_refusals:refusals,current_pcm_native_audition:true,explicit_rate_stale_disposal_guards:true}));
