import assert from 'node:assert/strict';import fs from 'node:fs';
import {decodeNativeLoop,renderNativeEnvelope,decodeNativeSample,nativeLoopQualified} from '../editor/audio-native-loop.js';
import {renderEnvelopePcm,mountEnvelopeAudition} from '../editor/audio-envelope-audition.js';
const block=(header,flags,data=0)=>Uint8Array.from([header,flags,...Array(14).fill(data)]),raw=Uint8Array.from([...block(0,0,0x11),...block(0x10,4),...block(0x10,3)]),before=raw.slice();
const decoded=decodeNativeLoop(raw,200),read=(bytes,i)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getInt16(i*2,true);
assert.equal(decoded.sourceFrames,84);assert.deepEqual(decoded.loop,{startFrame:28,endFrame:84});assert.equal(read(decoded.bytes,28),3840);assert(read(decoded.bytes,84)<read(decoded.bytes,28));assert.deepEqual(raw,before);
assert.equal(decodeNativeLoop(raw,1).wraps,0);assert.equal(decodeNativeLoop(raw,84).wraps,1);assert.equal(decodeNativeLoop(raw,85).wraps,1);
const native=renderNativeEnvelope(raw,44100,15,31,{frameCount:200,keyOffFrame:180}),pcm=renderEnvelopePcm(decodeNativeLoop(raw,84).bytes,44100,15,31,{frameCount:200,keyOffFrame:180},decoded.loop);
assert.notDeepEqual(native.bytes,pcm.bytes);assert.deepEqual(native.bytes.slice(0,168),pcm.bytes.slice(0,168));
for(const invalid of [block(0x0d,7),block(0x50,7),block(0,8),block(0,3),block(0,4),block(0,1),new Uint8Array(65537)])assert.throws(()=>decodeNativeLoop(invalid,10));
for(const frames of [0,240002,true,1.5])assert.throws(()=>decodeNativeLoop(raw,frames));assert.equal(decodeNativeLoop(raw,240001).bytes.length,480002);
assert.throws(()=>renderNativeEnvelope(raw,44101,15,31));assert.equal(renderNativeEnvelope(raw,48000,15,31,{frameCount:220500,keyOffFrame:200000}).bytes.length,441000);
const file=process.argv[2];if(!file)throw Error('Supply fresh native ADPCM fixtures and compiled runtime oracle output.');const f=JSON.parse(fs.readFileSync(file,'utf8'));
for(const row of f.oracleCases){const bytes=Uint8Array.from(Buffer.from(row.adpcm_base64,'base64')),actual=decodeNativeLoop(bytes,row.frames).bytes,expected=Uint8Array.from(Buffer.from(row.pcm_base64,'base64'));assert.deepEqual(actual,expected,row.name);}
for(const layer of ['retail','current']){const source=f.pcm[layer],bytes=Uint8Array.from(Buffer.from(source.pcm_base64,'base64')),sha=source.sample_sha256,verified=await decodeNativeSample(f.adpcm[layer],f.config.context,f.bank,f.bank.samples[f.sampleIndex],layer,sha,f.config.currentEntryHash,source.waveform,bytes);assert.equal(verified.length,source.waveform.source_size_bytes);assert(nativeLoopQualified(source.waveform));
 for(const mutate of [v=>v.layer='live',v=>v.current_entry_sha256='f'.repeat(64),v=>v.sample_sha256='f'.repeat(64),v=>v.adpcm_base64='AA==',v=>v.waveform.decoded_frames++,v=>v.extra=true]){const bad=structuredClone(f.adpcm[layer]);mutate(bad);await assert.rejects(()=>decodeNativeSample(bad,f.config.context,f.bank,f.bank.samples[f.sampleIndex],layer,sha,f.config.currentEntryHash,source.waveform,bytes));}}
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.value='';this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(key,value){this.attrs[key]=value;}}
globalThis.document={createElement:tag=>new Element(tag)};const nodes=root=>[root,...root.children.flatMap(nodes)],button=(host,title)=>nodes(host).find(n=>n.tag==='button'&&n.textContent===title),control=(host,title)=>nodes(host).find(n=>n.attrs['aria-label']===title);
let held=null,fresh=true;const calls=[],errors=[],request=async(path,init)=>{const body=JSON.parse(init.body);calls.push({path,body});if(held&&path==='/api/audio-sample-adpcm')return new Promise(resolve=>held.resolve=resolve);const value=path==='/api/audio-sample-authoring'?f.options:path==='/api/audio-sample-adpcm'?f.adpcm[body.layer]:f.pcm[body.layer];return {ok:true,text:async()=>JSON.stringify(value)};};
const host=new Element('section'),view=mountEnvelopeAudition(host,{bank:f.bank,request,fresh:()=>fresh,onError:error=>errors.push(error.message)});view.update(f.config);
const load=button(host,'Load envelope sample'),play=button(host,'Play envelope audition'),rate=control(host,'Envelope sample rate'),mode=control(host,'Envelope sample playback'),layer=control(host,'Envelope audition layer');await load.onclick();assert(!mode.children[2].disabled);rate.value='44100';mode.value='native-loop';mode.onchange();assert(play.disabled&&!load.disabled);await load.onclick();assert(!play.disabled&&load.disabled);assert.equal(calls.at(-1).path,'/api/audio-sample-adpcm');
layer.value='Current';layer.onchange();assert.equal(mode.value,'one-pass');await load.onclick();mode.value='native-loop';mode.onchange();await load.onclick();assert(!play.disabled);const count=calls.length;layer.value='Reviewed Proposed';layer.onchange();assert.equal(mode.value,'native-loop');assert(load.disabled&&!play.disabled);assert.equal(calls.length,count);view.clear();
view.update(f.config);await load.onclick();rate.value='44100';mode.value='native-loop';mode.onchange();held={};const pending=load.onclick();view.clear();held.resolve({ok:true,text:async()=>JSON.stringify(f.adpcm.retail)});await pending;assert(host.hidden&&play.disabled);held=null;view.update(f.config);await load.onclick();fresh=false;mode.value='native-loop';mode.onchange();assert(host.hidden&&play.disabled);assert.deepEqual(errors,[]);
console.log('Continuous history, native-vs-PCM distinction, compiled runtime oracle cases, source/hash contracts, layer cache ownership and stale/late native withdrawal passed.');
