import assert from 'node:assert/strict';
import {decodeDonorGroupProposal} from '../editor/draft-donor-group.js';
const ids=['authored-actor://00000000-0000-4000-8000-000000000001','authored-actor://00000000-0000-4000-8000-000000000002'],donor='scene://fixture/actors/man-p1/0002',old='scene://fixture/actors/man-p1/0001',model='asset://fixture/models/scene-tmd/0002',oldModel='asset://fixture/models/scene-tmd/0001',source={record_index:2},reference={asset_semantic_id:model},drafts=Object.fromEntries(ids.map(id=>[id,{scene_id:'scene://fixture',donor_entity_id:old,name:id,position:{x:512,z:512}}]));
const state={scene:{id:'scene://fixture',entities:[{id:donor}]},actor_drafts:drafts,project_copy_source_key:'a'.repeat(64),scene_preview_source_key:'b'.repeat(64)},request={entity_ids:ids,donor_entity_id:donor};
const entity=id=>({entity_id:id,kind:'actor_draft',name:id,donor_entity_id:old,source_actor_id:old,source_record:{record_index:1},model_reference:{asset_semantic_id:oldModel},asset_id:oldModel,geometry_key:'old',renderable:true,authored_position:{x:512,z:512},model_to_scene:[1,0,0,512,0,1,0,0,0,0,1,512,0,0,0,1]});
const base={source_key:'b'.repeat(64),scene_id:'scene://fixture',position_to_display:[],entities:ids.map(entity),assets:[{geometry_key:'old',asset_id:oldModel,preview:{semantic_id:oldModel}}]},scene={...structuredClone(base),schema:'legaia.scene-preview.v1',representation:'authored',entities:base.entities.map(e=>({...e,donor_entity_id:donor,source_actor_id:donor,source_record:source,model_reference:reference,asset_id:model,geometry_key:'new'})),assets:[...base.assets,{geometry_key:'new',asset_id:model,preview:{semantic_id:model}}]},report={schema_version:'legaia.draft-donor-group-review.v1',project_source_key:state.project_copy_source_key,scene_preview_source_key:state.scene_preview_source_key,scene_id:state.scene.id,request,donor:{semantic_id:donor,source_record:source,model_reference:reference},targets:ids.map(id=>({entity_id:id,current:drafts[id],proposed:{...drafts[id],donor_entity_id:donor}})),changed_count:2,review_key:'c'.repeat(64),gameplay_verified:false},value={schema_version:'legaia.draft-donor-group-proposal.v1',review:report,scene};
const accepted=decodeDonorGroupProposal(value,request,state,base);accepted.review.targets[0].current.name='changed';assert.equal(drafts[ids[0]].name,ids[0]);
for(const change of [v=>v.review.project_source_key='stale',v=>v.review.targets[0].proposed.position.x=576,v=>v.scene.entities[0].model_reference.asset_semantic_id=oldModel,v=>v.scene.entities[0].source_record={record_index:99},v=>v.scene.entities[0].model_to_scene[3]=576,v=>v.scene.assets[1].preview.semantic_id=oldModel,v=>v.scene.assets.push({geometry_key:'unrelated'}),v=>v.review.changed_count=1]){const bad=structuredClone(value);change(bad);assert.throws(()=>decodeDonorGroupProposal(bad,request,state,base));}
console.log('NPC donor group exact source/membership, detached proposals, held placement, native model binding and forged scene rejection pass.');
