import assert from 'node:assert/strict';
import {decodeModelAllocation,openModelAllocation} from '../editor/model-allocation.js';
const key='a'.repeat(64),asset='asset://fixture/model/0';
const allocation={schema_version:'legaia.model-allocation.v1',source_sha256:key,byte_length:100,tail_policy:'Uninterpreted trailing bytes are not authorized allocation space.',objects:[{object_index:0,primitive_count:1,groups:[{group_index:0,byte_offset:40,byte_length:32,primitive_count:1,packet_stride:12,first_primitive_index:0}],primitive_stream:{byte_offset:40,byte_limit:76,terminator_offset:72,encoded_byte_length:36,uninterpreted_tail_bytes:0},vectors:[{kind:'vertex',byte_offset:76,byte_length:24,count:3}]}]};
const report={schema_version:'legaia.model-allocation-source.v1',asset_id:asset,project_source_key:key,source_sha256:key,effective_sha256:key,retail:structuredClone(allocation),current:structuredClone(allocation),project_changed:false,gameplay_verified:false};
const original=JSON.stringify(report);decodeModelAllocation(report,asset,key).current.objects[0].groups.pop();assert.equal(JSON.stringify(report),original);
for(const edit of [r=>r.asset_id='other',r=>r.project_source_key='bad',r=>r.gameplay_verified=true,r=>r.project_changed=true,r=>r.current.source_sha256='b'.repeat(64),r=>r.current.byte_length=10,r=>r.current.objects[0].primitive_count=2,r=>r.current.objects[0].primitive_stream.encoded_byte_length=32,r=>r.current.objects[0].primitive_stream.uninterpreted_tail_bytes=1,r=>r.current.objects[0].groups[0].first_primitive_index=1,r=>r.current.objects[0].groups[0].packet_stride=13,r=>r.current.objects[0].groups[0].byte_offset=44,r=>r.current.objects[0].vectors[0].byte_offset=72,r=>r.current.objects[0].vectors.push(structuredClone(r.current.objects[0].vectors[0]))]){const bad=structuredClone(report);edit(bad);assert.throws(()=>decodeModelAllocation(bad,asset,key));}
const grown=structuredClone(report);grown.current.byte_length=112;grown.current.objects[0].vectors[0].byte_offset=88;grown.current.objects[0].primitive_stream.byte_limit=88;grown.current.objects[0].primitive_stream.uninterpreted_tail_bytes=12;assert.equal(decodeModelAllocation(grown,asset,key).current.byte_length,112);
class Element{constructor(tag){this.tagName=tag;this.children=[];this.nodes=new Map();this.listeners=new Map();this.value='current';this.textContent='';}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}querySelector(key){if(!this.nodes.has(key))this.nodes.set(key,new Element(key));return this.nodes.get(key);}addEventListener(name,fn){this.listeners.set(name,fn);}showModal(){this.open=true;}close(){this.open=false;this.listeners.get('close')?.();}remove(){this.removed=true;}}
const body=new Element('body');globalThis.document={body,createElement:tag=>new Element(tag)};let context={sourceKey:key,mode:'edit',assetId:asset},isBusy=false,calls=[],errors=[];
const options={assetId:asset,getContext:()=>context,busy:()=>isBusy,setBusy:value=>{isBusy=value;calls.push(value);},onError:e=>errors.push(e)};
globalThis.fetch=async(url,args)=>{assert.equal(url,'/api/model-allocation-source');assert.deepEqual(JSON.parse(args.body),{asset_id:asset,source_key:key});return {ok:true,json:async()=>structuredClone(report)}};
let tool=await openModelAllocation(options);assert.deepEqual(calls,[true,false]);assert.equal(isBusy,false);tool.dialog.querySelector('[aria-label="Allocation layer"]').value='retail';tool.dialog.querySelector('[aria-label="Allocation layer"]').onchange();assert.equal(tool.dialog.querySelector('[role="status"]').textContent,'1 stored primitives · 1 groups · 100 model bytes');tool.dispose();assert.equal(tool.dialog.removed,true);
let resolve;globalThis.fetch=()=>new Promise(r=>resolve=r);calls=[];const pending=openModelAllocation(options);const dialog=body.children.at(-1);dialog.close();assert.deepEqual(calls,[true,false]);resolve({ok:true,json:async()=>structuredClone(report)});assert.equal(await pending,null);assert.equal(errors.length,0);
calls=[];context={...context,mode:'edit'};const stale=openModelAllocation(options);context={...context,sourceKey:'b'.repeat(64)};resolve({ok:true,json:async()=>structuredClone(report)});assert.equal(await stale,null);assert.deepEqual(calls,[true,false]);assert.equal(body.children.at(-1).removed,true);
isBusy=true;assert.equal(await openModelAllocation(options),null);isBusy=false;context={...context,sourceKey:key};globalThis.fetch=async()=>({ok:true,json:async()=>({...report,asset_id:'wrong'})});tool=await openModelAllocation(options);assert.equal(errors.length,1);assert.equal(tool.dialog.querySelector('[aria-label="Allocation object"]').disabled,true);tool.dispose();
console.log('Allocation metadata ownership, detached layers, growth extents, source binding, close/stale/late/error/busy guards pass');
