import assert from 'node:assert/strict';
import {modelPreviewFrame} from '../editor/model-preview-frame.js';
const current={vertices:[[0,0,0],[100,0,0],[0,100,0],[99999,-99999,99999]],triangles:[[0,1,2]]};
const proposed={vertices:[[1000,0,0],[1002,0,0],[1000,2,0],[-99999,99999,-99999]],triangles:[[0,1,2]]};
const before=structuredClone({current,proposed});
const shared=modelPreviewFrame(current,proposed);
assert.deepEqual(shared.bounds,{min:[0,0,0],max:[1002,100,0]});
assert.deepEqual(modelPreviewFrame(current,proposed,'current'),shared);
const visible=modelPreviewFrame(current,proposed,'proposed','visible');
assert.deepEqual(visible.bounds,{min:[1000,0,0],max:[1002,2,0]});
assert.deepEqual(visible.center,[1001,1,0]);assert.equal(visible.radius,Math.sqrt(2));
assert.deepEqual(modelPreviewFrame(current,proposed,'current','visible').bounds,{min:[0,0,0],max:[100,100,0]});
assert.deepEqual(modelPreviewFrame(current,proposed,'proposed','stored').bounds,{min:[-99999,0,-99999],max:[1002,99999,0]});
const empty={vertices:[[100,200,300]],triangles:[]};
assert.equal(modelPreviewFrame(empty,empty).empty,true);
assert.deepEqual(modelPreviewFrame(empty,proposed).bounds,visible.bounds);
assert.equal(modelPreviewFrame(empty,empty,'current','stored').empty,false);
for(const bad of [{vertices:[[NaN,0,0]],triangles:[[0,0,0]]},{...current,triangles:[[0,1,4]]},{...current,triangles:[[0,1]]},{...current,triangles:[[0,1,true]]},{...current,vertices:Array(100001)}])assert.throws(()=>modelPreviewFrame(bad,proposed));
assert.throws(()=>modelPreviewFrame(current,proposed,'other'));assert.throws(()=>modelPreviewFrame(current,proposed,'current','other'));
assert.deepEqual({current,proposed},before);
console.log('Visible, shared and stored model framing; retired rows, empty geometry, malformed references and immutable source previews passed.');
