import assert from 'node:assert/strict';import fs from 'node:fs';
import {directVoiceVolume,renderStaticStereo} from '../editor/audio-static-stereo.js';
import {encodeEnvelopeWav,mountEnvelopeAudition} from '../editor/audio-envelope-audition.js';
const pcm=values=>{const bytes=new Uint8Array(values.length*2),view=new DataView(bytes.buffer);values.forEach((v,i)=>view.setInt16(i*2,v,true));return bytes;},words=bytes=>Array.from({length:bytes.length/2},(_,i)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getInt16(i*2,true));
const values=[-32768,-3,-1,0,1,3,32767],input=pcm(values),before=input.slice();assert.deepEqual([0,8192,16383,16384,24576,32767].map(directVoiceVolume),[0,16384,32766,-32768,-16384,-2]);
const result=renderStaticStereo(input,8192,24576);assert.deepEqual(words(result.bytes),[-16384,16384,-2,1,-1,0,0,0,0,-1,1,-2,16383,-16384]);assert.deepEqual(input,before);assert.deepEqual(words(renderStaticStereo(pcm([-32768,32767]),16384,16384).bytes),[32767,32767,-32767,-32767]);
assert.deepEqual(words(renderStaticStereo(input,0,0).bytes),new Array(values.length*2).fill(0));const backing=new Uint8Array(input.length+8);backing.set(input,4);assert.deepEqual(renderStaticStereo(backing.subarray(4,-4),8192,24576).bytes,result.bytes);
for(const value of [-1,32768,65535,1.5,true,NaN])assert.throws(()=>directVoiceVolume(value));for(const value of [new Uint8Array(),new Uint8Array(3),new Uint8Array(441002)])assert.throws(()=>renderStaticStereo(value,0,0));
const wav=encodeEnvelopeWav(result.bytes,2),header=new DataView(wav.buffer);assert.equal(header.getUint16(22,true),2);assert.equal(header.getUint32(28,true),176400);assert.equal(header.getUint16(32,true),4);assert.equal(header.getUint32(40,true),result.bytes.length);assert.deepEqual(wav.slice(44),result.bytes);assert.equal(encodeEnvelopeWav(new Uint8Array(882000),2).length,882044);for(const [b,c] of [[new Uint8Array(6),2],[new Uint8Array(882004),2],[input,0],[input,true]])assert.throws(()=>encodeEnvelopeWav(b,c));
const oracle=process.argv[2];if(oracle){const native=fs.readFileSync(oracle),samples=[-32768,-32767,-3,-1,0,1,3,32766,32767];assert.equal(native.length,32768*samples.length*4);let at=0;for(let raw=0;raw<32768;raw++){const bytes=renderStaticStereo(pcm(samples),raw,(raw+16384)&32767).bytes;assert.deepEqual(Buffer.from(bytes),native.subarray(at,at+bytes.length));at+=bytes.length;}console.log('All 32768 direct registers ×9 signed samples ×2 channels match compiled runtime arithmetic.');}
const fixture=process.argv[3];if(fixture){
 class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.value='';this.textContent='';this.checked=false;}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(k,v){this.attrs[k]=v;}}
 globalThis.document={createElement:tag=>new Element(tag)};const nodes=root=>[root,...root.children.flatMap(nodes)],control=(root,label)=>nodes(root).find(n=>n.attrs['aria-label']===label),button=(root,label)=>nodes(root).find(n=>n.tag==='button'&&n.textContent===label),g=JSON.parse(fs.readFileSync(fixture,'utf8')).groups.loop;let fresh=true,stops=0,played=null;const errors=[];
 const request=async(path,init)=>{const body=JSON.parse(init.body),value=path==='/api/audio-sample-authoring'?g.options:g.pcm[body.layer];return {ok:true,text:async()=>JSON.stringify(value)};};
 const audioContext=()=>({destination:{},resume:async()=>{},close:async()=>{},createGain:()=>({gain:{value:0},connect(){},disconnect(){}}),createBuffer(channels,count,rate){played={channels,count,rate,data:Array.from({length:channels},()=>new Float32Array(count))};return {getChannelData:i=>played.data[i]};},createBufferSource:()=>({connect(){},disconnect(){},start(){},stop(){stops++;}})});
 const host=new Element('section'),mounted=mountEnvelopeAudition(host,{bank:g.bank,request,audioContext,fresh:()=>fresh,onError:e=>errors.push(e.message)});mounted.update(g.config);const stereo=control(host,'Static stereo voice gains'),left=control(host,'Static voice left register'),right=control(host,'Static voice right register'),rate=control(host,'Envelope sample rate'),play=button(host,'Play envelope audition'),save=button(host,'Save envelope preview WAV');
 assert(!stereo.checked&&left.disabled&&right.disabled);await button(host,'Load envelope sample').onclick();rate.value='44100';rate.onchange();await play.onclick();assert.equal(played.channels,1);stereo.checked=true;stereo.onchange();assert.equal(stops,1);left.value='8192';right.value='24576';left.oninput();await play.onclick();assert.equal(played.channels,2);assert.equal(played.data[0].length,played.data[1].length);right.value='0';right.oninput();assert.equal(stops,2);
 for(const value of ['',-1,32768,1.5]){left.value=String(value);left.oninput();assert(play.disabled&&save.disabled);}left.value='8192';left.oninput();assert(!play.disabled);stereo.checked=false;stereo.onchange();assert(left.disabled&&right.disabled);mounted.update({...g.config,tone:{page:1,index:1}});assert(!stereo.checked);assert.equal(left.value,'16383');assert.equal(right.value,'16383');fresh=false;await play.onclick();assert(host.hidden);assert(play.disabled&&save.disabled);assert.deepEqual(errors,[]);mounted.clear();console.log('Stereo playback, input refusal, gain-change stop, mono default/reset and stale disposal passed.');
}
console.log('Signed register phase, floor rounding, saturation, immutable input, offset views and stereo WAV bounds passed.');
