import assert from 'node:assert/strict';
import fs from 'node:fs';
import {decodeModelTextureAssignmentReview,modelTextureAssignmentDrafts} from '../editor/model-primitives.js';
const f=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),before=structuredClone(f);
const check=(r=f.report,source=f.source,material=f.material_source,context=f.context,faces=f.faces,materials=f.materials)=>decodeModelTextureAssignmentReview(r,source,material,context,faces,materials);
const r=check();assert.deepEqual(r,f.report);r.limitations.push('Detached');assert.deepEqual(f,before);
for(const edit of [r=>r.scene_id='scene://foreign',r=>r.project_source_key='0'.repeat(64),r=>r.gameplay_verified=true,r=>r.project_changed=true,r=>r.material_edit_count++,r=>r.primitive_edit_count++,r=>r.changes_from_current.pop(),r=>r.face_changes_from_current[0].after_value^=1,r=>r.material_changes_from_current[0].after_value^=1,r=>r.face_candidate_sha256=r.effective_sha256,r=>r.material_candidate_sha256=r.effective_sha256,r=>r.proposed_sha256=r.face_candidate_sha256,r=>r.comparison='unqualified',r=>r.extra=true]){const changed=structuredClone(f.report);edit(changed);assert.throws(()=>check(changed));}
const wrong=structuredClone(f.material_source);wrong.effective_sha256='0'.repeat(64);assert.throws(()=>check(f.report,f.source,wrong));
const face=f.source.objects[0].primitives.find(p=>p.uvs!==null),choice={asset_id:'texture://fixture/5/raw/0',effective_sha256:'a'.repeat(64),project_source_key:f.context.sourceKey,values:{texture_bpp:16,page_column:5,page_row:1}};
const one=modelTextureAssignmentDrafts(f.source,0,face.primitive_index,'primitive',null,choice);assert.equal(one.length,1);assert.deepEqual(one[0].values,choice.values);one[0].values.page_column=1;assert.equal(choice.values.page_column,5);
const group=modelTextureAssignmentDrafts(f.source,0,face.primitive_index,'group',null,choice);assert.equal(group.length,f.source.objects[0].primitives.filter(p=>p.group_index===face.group_index&&p.uvs!==null).length);
const selection={asset_id:f.source.asset_id,effective_sha256:f.source.effective_sha256,project_source_key:f.context.sourceKey,can_stage:true,faces:group.map(p=>({object_index:p.object_index,primitive_index:p.primitive_index}))};assert.equal(modelTextureAssignmentDrafts(f.source,0,face.primitive_index,'glb',selection,choice).length,group.length);
assert.throws(()=>modelTextureAssignmentDrafts(f.source,0,face.primitive_index,'glb',{...selection,effective_sha256:'0'.repeat(64)},choice));assert.throws(()=>modelTextureAssignmentDrafts(f.source,0,face.primitive_index,'glb',{...selection,faces:[selection.faces[0],selection.faces[0]]},choice));assert.throws(()=>modelTextureAssignmentDrafts(f.source,0,face.primitive_index,'primitive',null,{...choice,project_source_key:'0'.repeat(64)}));
console.log('Combined native audit union, intermediate/final hashes, stale Current ownership, topology comparison, detached scoped page drafts and explicit GLB/group/face targeting passed.');
